"""Minimal BV/Koszul-Tate closure attempt for the anchor-scale A-door.

This module is intentionally finite-fiber and conservative.  It checks whether
the A-door vector-spinor declaration admits the algebraic BV/KT closure one
would expect after projecting the gauge differential into the gamma-traceless
constraint surface.  It does not claim a source-derived Noether differential.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[3]
TESTS = ROOT / "tests"
if str(TESTS) not in sys.path:
    sys.path.insert(0, str(TESTS))

import gu_bridge  # noqa: E402


ANCHOR_BARE_COMMUTATOR = 58.7215
ANCHOR_C2 = 155.3625
TOL = 1.0e-8


class MinimalBvKtVerdict(str, Enum):
    """Outcome labels for the bounded closure attempt."""

    FINITE_FIBER_CLOSES_SOURCE_NOETHER_BLOCKED = (
        "finite_fiber_closes_source_noether_blocked"
    )
    FAILS = "fails"


@dataclass(frozen=True)
class MinimalBvKtReport:
    """Machine-checkable report for the minimal BV/KT closure attempt."""

    verdict: MinimalBvKtVerdict
    raw_noether_norm: float
    raw_noether_rank: int
    projected_noether_norm: float
    projected_gauge_rank: int
    kt_cross_norm: float
    escape_norm: float
    escape_kt_exact_residual: float
    bare_commutator_norm: float
    c2_norm: float
    null_tau_trace_rank: int
    bare_commutator_anchor_preserved: bool
    source_derived_noether_differential: bool
    next_progress_point: str

    @property
    def finite_fiber_closes(self) -> bool:
        return (
            self.projected_noether_norm < TOL
            and self.kt_cross_norm < TOL
            and self.projected_gauge_rank > 0
            and self.escape_kt_exact_residual < TOL
        )

    @property
    def raw_map_is_second_class(self) -> bool:
        return self.raw_noether_norm > 1.0 and self.raw_noether_rank == 128


def _rank(matrix: np.ndarray, tol: float = 1.0e-8) -> int:
    return int(np.linalg.matrix_rank(matrix, tol=tol))


def _vector_spinor_injection(direction: np.ndarray, spin_dim: int) -> np.ndarray:
    """Return spinor -> vector-spinor injection psi |-> direction tensor psi."""

    vector_dim = int(direction.shape[0])
    injection = np.zeros((vector_dim * spin_dim, spin_dim), dtype=complex)
    for vector_index, coeff in enumerate(direction):
        start = vector_index * spin_dim
        injection[start : start + spin_dim, :] = coeff * np.eye(spin_dim)
    return injection


def run_minimal_bv_kt_closure(xi: np.ndarray | None = None) -> MinimalBvKtReport:
    """Run the finite-fiber BV/KT closure attempt.

    The raw gauge differential is the ordinary scalar-spinor shift
    ``d_A psi = xi tensor psi``.  The projected map
    ``A = Pi_kerGamma d_A`` is the smallest algebraic repair that makes the
    Noether identity ``Gamma A = 0`` true on the full vector-spinor carrier.
    That repair is useful as a closure witness, but it is not a source-derived
    differential.
    """

    _basis, gamma_trace, pi_rs, mass_operator = gu_bridge.constraint_objects()
    spin_dim = gu_bridge.DIM
    vector_dim = gu_bridge.N

    if xi is None:
        xi = np.asarray(gu_bridge.XI, dtype=complex)
    else:
        xi = np.asarray(xi, dtype=complex)
    if xi.shape != (vector_dim,):
        raise ValueError(f"xi must have shape ({vector_dim},), got {xi.shape}")

    raw_gauge = _vector_spinor_injection(xi, spin_dim)
    projected_gauge = pi_rs @ raw_gauge

    raw_noether = gamma_trace @ raw_gauge
    projected_noether = gamma_trace @ projected_gauge

    # The KT differential for the constraint is generated by Gamma^dagger Gamma.
    # We avoid materializing the 1792 x 1792 map; its action on A factors this way.
    gamma_dagger = gamma_trace.conj().T
    kt_cross = gamma_dagger @ projected_noether

    escape = (np.eye(pi_rs.shape[0], dtype=complex) - pi_rs) @ mass_operator @ pi_rs
    gamma_gamma_dagger = gamma_trace @ gamma_dagger
    escape_potential = np.linalg.solve(gamma_gamma_dagger, gamma_trace @ escape)
    escape_residual = gamma_dagger @ escape_potential - escape

    c2_operator = gamma_trace @ mass_operator @ pi_rs
    bare_commutator = pi_rs @ mass_operator - mass_operator @ pi_rs

    null_direction = np.zeros(vector_dim, dtype=complex)
    null_direction[0] = 1.0
    null_direction[9] = 1.0
    null_tau_trace_rank = _rank(
        gamma_trace @ _vector_spinor_injection(null_direction, spin_dim)
    )

    raw_norm = float(np.linalg.norm(raw_noether))
    raw_rank = _rank(raw_noether)
    projected_norm = float(np.linalg.norm(projected_noether))
    projected_rank = _rank(projected_gauge)
    kt_cross_norm = float(np.linalg.norm(kt_cross))
    escape_norm = float(np.linalg.norm(escape))
    escape_kt_exact_residual = float(np.linalg.norm(escape_residual))
    bare_commutator_norm = float(np.linalg.norm(bare_commutator))
    c2_norm = float(np.linalg.norm(c2_operator))

    finite_fiber_closes = (
        projected_norm < TOL
        and kt_cross_norm < TOL
        and projected_rank > 0
        and escape_kt_exact_residual < TOL
    )
    raw_second_class = raw_norm > 1.0 and raw_rank == spin_dim
    anchor_metrics_preserved = (
        abs(bare_commutator_norm - ANCHOR_BARE_COMMUTATOR) < 1.0e-4
        and
        abs(c2_norm - ANCHOR_C2) < 1.0e-4
    )

    if finite_fiber_closes and raw_second_class and anchor_metrics_preserved:
        verdict = MinimalBvKtVerdict.FINITE_FIBER_CLOSES_SOURCE_NOETHER_BLOCKED
    else:
        verdict = MinimalBvKtVerdict.FAILS

    return MinimalBvKtReport(
        verdict=verdict,
        raw_noether_norm=raw_norm,
        raw_noether_rank=raw_rank,
        projected_noether_norm=projected_norm,
        projected_gauge_rank=projected_rank,
        kt_cross_norm=kt_cross_norm,
        escape_norm=escape_norm,
        escape_kt_exact_residual=escape_kt_exact_residual,
        bare_commutator_norm=bare_commutator_norm,
        c2_norm=c2_norm,
        null_tau_trace_rank=null_tau_trace_rank,
        bare_commutator_anchor_preserved=anchor_metrics_preserved,
        source_derived_noether_differential=False,
        next_progress_point="SOURCE-NOETHER-TAU-CARRIER",
    )


if __name__ == "__main__":
    report = run_minimal_bv_kt_closure()
    print(report)
