#!/usr/bin/env python3
"""Where a base-sign resolver can and cannot live: a wholesale exclusion.

VERDICT on pass: GROUP-AND-METRIC-CRITERIA-EXCLUDED__CLIFFORD-SPINOR-CRITERIA-REMAIN

THE QUESTION.  On 2026-08-08 the fibre trace sign was shown to be selected by an
authorial criterion -- requiring the fibre isometry group's maximal compact to be
Pati-Salam Spin(6) x Spin(4) picks (6,4) over (7,3)
(tests/pati_salam_selects_the_fibre_trace_sign.py).  The symmetric question is
whether the BASE sign admits an analogous criterion.  It does not admit a
group-theoretic one, and this certificate says exactly why and exactly how far
the exclusion reaches.

A PROPOSAL THIS CORRECTS.  The exclusion was first stated in chat as "no
base-intrinsic criterion can distinguish the horns."  THAT IS FALSE, and the
computation below shows it: the Clifford algebras differ at base level.  The
correct, narrower statement is the one certified here.

WHAT IS INVISIBLE TO THE BASE SIGN.

  * THE ISOMETRY GROUP.  L^T g L = g  <=>  L^T (-g) L = -g.  The condition is
    literally the same equation, so O(3,1) and O(1,3) are THE SAME SET OF
    MATRICES.  Checked on 400 sampled group elements: agreement 400/400.
  * THE MAXIMAL COMPACT.  SO(3)xSO(1) and SO(1)xSO(3), both dimension 3.
    Identical -- so the Pati-Salam style move that WORKED on the fibre cannot
    even be posed on the base.
  * THE LEVI-CIVITA CONNECTION, hence geodesics, curvature and parallel
    transport (residual 0.00e+00, tests/signature_fork_equivariance_defect.py).
  * THE CAUSAL CONE, which is one set under either labelling (same file).

WHAT IS VISIBLE TO IT.

  * THE CLIFFORD ALGEBRA.  Cl(3,1) = M(4,R) is real; Cl(1,3) = M(2,H) is
    quaternionic.  p-q mod 8 is 2 versus 6.  These are not real-isomorphic.
  * Hence spinor reality, Majorana availability, and every downstream
    reality-type statement.

WHY THE ASYMMETRY, in one line.  The isometry group depends on which
transformations PRESERVE the form; the Clifford algebra depends on the form's
actual SIGN, because it is generated by v^2 = g(v,v).  Flipping g flips every
generator's square and therefore the algebra, while leaving the preservation
condition untouched.

THE EXCLUSION, and it is wholesale rather than candidate-by-candidate.

  ANY resolver for the base sign built from the isometry group, the maximal
  compact, the Levi-Civita connection, geodesics, curvature, or the causal
  structure is DEAD BEFORE IT IS WRITTEN.  These objects provably cannot see the
  distinction.  A resolver must reach the Clifford/spinor layer.

WHAT THIS EXPLAINS IN RETROSPECT, which is the reason it is worth certifying.

  * The Pati-Salam criterion worked on the FIBRE because SO(7,3) and SO(6,4) are
    genuinely different groups (maximal compacts of dimension 24 vs 21).  It
    cannot work on the BASE because the two groups coincide.
  * The "declared-base route" (filed and falsified 2026-08-08) was a source-
    reading argument about the base label; nothing in it reached the spinor
    layer.
  * The Majorana-Weyl candidate WAS in the right class -- MW is a spinor-reality
    criterion.  It was falsified on 2026-08-08 for an unrelated reason: the
    reality requirement was not independently established.  Being in the right
    class is necessary, not sufficient.

SCOPE.  This does not resolve SIGNATURE-AMBIENT and does not weaken the
2026-08-08 hostile review.  It maps where a resolver may live.
"""

from __future__ import annotations

import unittest

import numpy as np
import scipy.linalg as sla

TOL = 1e-9
G_PLUS = np.diag([1.0, 1.0, 1.0, -1.0])
G_MINUS = -G_PLUS

ABS_TABLE = {0: "M(R)", 1: "M(R)+M(R)", 2: "M(R)", 3: "M(C)",
             4: "M(H)", 5: "M(H)+M(H)", 6: "M(H)", 7: "M(C)"}


def clifford_class(p: int, q: int) -> str:
    return ABS_TABLE[(p - q) % 8]


def so_dim(n: int) -> int:
    return n * (n - 1) // 2


def preserves(l: np.ndarray, q: np.ndarray) -> bool:
    return bool(np.allclose(l.T @ q @ l, q, atol=1e-8))


class BaseSignVisibility(unittest.TestCase):

    def test_1_the_isometry_group_cannot_see_the_base_sign(self) -> None:
        rng = np.random.default_rng(3)
        gi = np.linalg.inv(G_PLUS)
        agree = 0
        trials = 400
        for _ in range(trials):
            a = rng.normal(size=(4, 4))
            x = (a - G_PLUS @ a.T @ gi) / 2          # an so(3,1) element
            l = sla.expm(x)
            if preserves(l, G_PLUS) == preserves(l, G_MINUS):
                agree += 1
        print("\n[1] does 'preserves g' coincide with 'preserves -g'?")
        print(f"    agreement on {agree}/{trials} sampled group elements")
        print("    reason: L^T g L = g  <=>  L^T(-g)L = -g -- the SAME equation.")
        self.assertEqual(trials, agree,
                         "O(3,1) and O(1,3) must be the same set of matrices")

    def test_2_the_maximal_compact_cannot_either_but_the_fibres_could(self) -> None:
        base_plus = so_dim(3) + so_dim(1)
        base_minus = so_dim(1) + so_dim(3)
        print("\n[2] maximal compact subgroups")
        print(f"    SO(3,1) -> SO(3)xSO(1), dim {base_plus}")
        print(f"    SO(1,3) -> SO(1)xSO(3), dim {base_minus}   IDENTICAL")
        self.assertEqual(base_plus, base_minus)
        fib_raw = so_dim(7) + so_dim(3)
        fib_rev = so_dim(6) + so_dim(4)
        print(f"    contrast the FIBRE, where the criterion worked:")
        print(f"      SO(7,3) -> dim {fib_raw}   vs   SO(6,4) -> dim {fib_rev}   DIFFERENT")
        self.assertNotEqual(fib_raw, fib_rev,
                            "the fibre criterion must be able to discriminate")
        print("    => the Pati-Salam move cannot even be POSED on the base.")

    def test_3_but_the_clifford_algebra_can(self) -> None:
        print("\n[3] the Clifford algebras")
        for p, q in [(3, 1), (1, 3)]:
            print(f"    Cl({p},{q}): p-q mod 8 = {(p-q) % 8} -> {clifford_class(p, q)}")
        self.assertEqual("M(R)", clifford_class(3, 1))
        self.assertEqual("M(H)", clifford_class(1, 3))
        self.assertNotEqual(clifford_class(3, 1), clifford_class(1, 3))
        print("    NOT real-isomorphic. The base sign IS visible here.")
        print("\n    WHY THE ASYMMETRY: the isometry group depends on which maps")
        print("    PRESERVE the form; the Clifford algebra depends on the form's")
        print("    SIGN, since it is generated by v^2 = g(v,v). Flipping g flips")
        print("    every generator's square while leaving preservation untouched.")

    def test_4_the_wholesale_exclusion(self) -> None:
        print("\n[4] the exclusion")
        print("    DEAD BEFORE WRITTEN -- any base-sign resolver built from:")
        for item in ("the isometry group", "the maximal compact",
                     "the Levi-Civita connection", "geodesics / curvature",
                     "parallel transport", "the causal structure"):
            print(f"      * {item}")
        print("    These provably cannot see the distinction.")
        print("\n    STILL AVAILABLE -- the Clifford/spinor layer:")
        print("      * spinor reality type, Majorana availability, mod-8 class")
        print("\n    Retrospect: the declared-base route never reached the spinor")
        print("    layer. The Majorana-Weyl candidate DID -- it was in the right")
        print("    class and failed for an unrelated reason (its reality")
        print("    requirement was not independently established). Right class is")
        print("    NECESSARY, not sufficient.")
        print("\n    SCOPE: this resolves nothing and weakens no review. It maps")
        print("    where a resolver may live.")
        print("\nVERDICT: GROUP-AND-METRIC-CRITERIA-EXCLUDED"
              "__CLIFFORD-SPINOR-CRITERIA-REMAIN")
        self.assertTrue(True)


if __name__ == "__main__":
    unittest.main(verbosity=2)
