#!/usr/bin/env python3
"""Audit the typed VZ Q-block and Schur-symbol algebra.

This is a finite formal-algebra check, not a Clifford representation proof.  It
works in the quotient generated by one symbol G with relation G^2 = q and
tracks the rational coefficients used in the typed-spine VZ derivation.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
import argparse
import json
import sys
import unittest


@dataclass(frozen=True)
class GQuotient:
    """Element of Q(q)[G] / (G^2 - q), allowing Laurent powers of q."""

    terms: tuple[tuple[int, int, Fraction], ...] = ()

    @staticmethod
    def zero() -> "GQuotient":
        return GQuotient(())

    @staticmethod
    def one() -> "GQuotient":
        return GQuotient(((0, 0, Fraction(1)),))

    @staticmethod
    def g(coeff: Fraction = Fraction(1), q_power: int = 0) -> "GQuotient":
        return GQuotient(((1, q_power, coeff),))._normalized()

    def _normalized(self) -> "GQuotient":
        merged: dict[tuple[int, int], Fraction] = {}
        for g_power, q_power, coeff in self.terms:
            if coeff == 0:
                continue
            q_shift, g_parity = divmod(g_power, 2)
            key = (g_parity, q_power + q_shift)
            merged[key] = merged.get(key, Fraction(0)) + coeff
        return GQuotient(
            tuple(
                (g_power, q_power, coeff)
                for (g_power, q_power), coeff in sorted(merged.items())
                if coeff != 0
            )
        )

    def __add__(self, other: "GQuotient") -> "GQuotient":
        return GQuotient(self.terms + other.terms)._normalized()

    def __neg__(self) -> "GQuotient":
        return GQuotient(tuple((g, q, -c) for g, q, c in self.terms))

    def __sub__(self, other: "GQuotient") -> "GQuotient":
        return self + (-other)

    def __mul__(self, other: "GQuotient") -> "GQuotient":
        products: list[tuple[int, int, Fraction]] = []
        for g1, q1, c1 in self.terms:
            for g2, q2, c2 in other.terms:
                products.append((g1 + g2, q1 + q2, c1 * c2))
        return GQuotient(tuple(products))._normalized()

    def __bool__(self) -> bool:
        return bool(self.terms)

    def to_jsonable(self) -> list[dict[str, object]]:
        return [
            {"g_power": g, "q_power": q, "coefficient": f"{c}"}
            for g, q, c in self.terms
        ]


Matrix2 = tuple[tuple[GQuotient, GQuotient], tuple[GQuotient, GQuotient]]


def matrix_mul(left: Matrix2, right: Matrix2) -> Matrix2:
    out: list[list[GQuotient]] = [[GQuotient.zero(), GQuotient.zero()], [GQuotient.zero(), GQuotient.zero()]]
    for i in range(2):
        for j in range(2):
            value = GQuotient.zero()
            for k in range(2):
                value = value + left[i][k] * right[k][j]
            out[i][j] = value
    return ((out[0][0], out[0][1]), (out[1][0], out[1][1]))


def identity2() -> Matrix2:
    z = GQuotient.zero()
    o = GQuotient.one()
    return ((o, z), (z, o))


def embedded_e_block(n: int = 14, lambda_d: Fraction = Fraction(1)) -> Matrix2:
    a = Fraction(1, n)
    b = lambda_d * Fraction(2 * (n - 1), n * n)
    z = GQuotient.zero()
    return ((z, GQuotient.g(a)), (GQuotient.g(a), GQuotient.g(b)))


def embedded_e_inverse(n: int = 14, lambda_d: Fraction = Fraction(1)) -> Matrix2:
    z = GQuotient.zero()
    return (
        (GQuotient.g(-2 * lambda_d * (n - 1), -1), GQuotient.g(Fraction(n), -1)),
        (GQuotient.g(Fraction(n), -1), z),
    )


def trace_coordinate_e_block(n: int = 14, lambda_d: Fraction = Fraction(1)) -> Matrix2:
    z = GQuotient.zero()
    return (
        (z, GQuotient.g(Fraction(1, n))),
        (GQuotient.g(), GQuotient.g(lambda_d * Fraction(2 * (n - 1), n))),
    )


def trace_coordinate_e_inverse(n: int = 14, lambda_d: Fraction = Fraction(1)) -> Matrix2:
    z = GQuotient.zero()
    return (
        (GQuotient.g(-2 * lambda_d * (n - 1), -1), GQuotient.g(Fraction(1), -1)),
        (GQuotient.g(Fraction(n), -1), z),
    )


def q_block_coefficients(n: int = 14, lambda_d: Fraction = Fraction(1)) -> dict[str, Fraction]:
    return {
        "scalar_to_trace_embedded": Fraction(1, n),
        "trace_to_scalar": Fraction(1, n),
        "trace_to_trace_coordinate": lambda_d * Fraction(2 * (n - 1), n),
        "trace_to_trace_embedded": lambda_d * Fraction(2 * (n - 1), n * n),
    }


def schur_symbol_coefficients(n: int = 14, lambda_d: Fraction = Fraction(1)) -> dict[str, Fraction]:
    """Return coefficients in S_R psi_A.

    The convention is:
      S_R psi_A = lambda_d * (
          -G psi_A + xi_coeff * xi_A G chi / q + gamma_coeff * gamma_A chi
      )
    where chi = i_xi psi and Gamma psi = 0.
    """

    return {
        "overall_lambda": lambda_d,
        "minus_g_psi": -lambda_d,
        "xi_g_chi_over_q": lambda_d * Fraction(n + 2),
        "gamma_chi": -lambda_d,
    }


class TypedSymbolGateTests(unittest.TestCase):
    def assertMatrixEqual(self, left: Matrix2, right: Matrix2) -> None:  # noqa: N802
        self.assertEqual(left, right)

    def test_q_block_coefficients_for_typed_spine(self) -> None:
        coeffs = q_block_coefficients()
        self.assertEqual(coeffs["scalar_to_trace_embedded"], Fraction(1, 14))
        self.assertEqual(coeffs["trace_to_scalar"], Fraction(1, 14))
        self.assertEqual(coeffs["trace_to_trace_coordinate"], Fraction(13, 7))
        self.assertEqual(coeffs["trace_to_trace_embedded"], Fraction(13, 98))

    def test_embedded_e_inverse_is_two_sided(self) -> None:
        e_block = embedded_e_block()
        inverse = embedded_e_inverse()
        self.assertMatrixEqual(matrix_mul(e_block, inverse), identity2())
        self.assertMatrixEqual(matrix_mul(inverse, e_block), identity2())

    def test_trace_coordinate_e_inverse_is_two_sided(self) -> None:
        e_block = trace_coordinate_e_block()
        inverse = trace_coordinate_e_inverse()
        self.assertMatrixEqual(matrix_mul(e_block, inverse), identity2())
        self.assertMatrixEqual(matrix_mul(inverse, e_block), identity2())

    def test_schur_symbol_coefficients_for_typed_spine(self) -> None:
        coeffs = schur_symbol_coefficients()
        self.assertEqual(coeffs["overall_lambda"], Fraction(1))
        self.assertEqual(coeffs["minus_g_psi"], Fraction(-1))
        self.assertEqual(coeffs["xi_g_chi_over_q"], Fraction(16))
        self.assertEqual(coeffs["gamma_chi"], Fraction(-1))

    def test_phi_d_zero_collapses_effective_spin_three_halves_symbol(self) -> None:
        coeffs = schur_symbol_coefficients(lambda_d=Fraction(0))
        self.assertEqual(coeffs["overall_lambda"], Fraction(0))
        self.assertEqual(coeffs["minus_g_psi"], Fraction(0))
        self.assertEqual(coeffs["xi_g_chi_over_q"], Fraction(0))
        self.assertEqual(coeffs["gamma_chi"], Fraction(0))

        e_block = embedded_e_block(lambda_d=Fraction(0))
        inverse = embedded_e_inverse(lambda_d=Fraction(0))
        self.assertMatrixEqual(matrix_mul(e_block, inverse), identity2())
        self.assertMatrixEqual(matrix_mul(inverse, e_block), identity2())


def summary() -> dict[str, object]:
    coeffs = q_block_coefficients()
    schur = schur_symbol_coefficients()
    return {
        "dimension": 14,
        "relation": "G^2 = q",
        "typed_lambda_d": "1",
        "q_block_coefficients": {key: str(value) for key, value in coeffs.items()},
        "schur_symbol_coefficients": {key: str(value) for key, value in schur.items()},
        "lambda_zero_warning": (
            "E remains invertible off q=0, but the effective spin-3/2 Schur symbol "
            "has zero principal part."
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="Print coefficient summary as JSON.")
    args, remaining = parser.parse_known_args(argv)

    if args.json:
        print(json.dumps(summary(), indent=2, sort_keys=True))

    suite = unittest.defaultTestLoader.loadTestsFromTestCase(TypedSymbolGateTests)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
