#!/usr/bin/env python3
r"""
W89 -- BRANCH 1 / FRONT B (the dissolver): compute eta_C, the shared-Z_h off-diagonal
       Einstein-Hilbert x Weyl spin-2 TT trace in the FRG, across THREE regulator families, and
       settle its SIGN. This is the STAGE-2 decider W88 handed off:

           beta_{f_2^2} = -kappa f_2^4 (b_2^grav + b_2^RS)  +  eta_C(g,lambda) f_2^2 ,

       with f_2^2*=0 a STRUCTURAL root at every regulator (both terms vanish there) and a lifted
       HORN-Q root f_2^2* = eta_C/(kappa b_2) that exists iff eta_C > 0. So the whole
       type-III Krein-TT horn reduces to sign(eta_C):
           eta_C > 0 robust -> f_2^2* > 0 -> HORN Q (ghost REMOVABLE, quasi-Hermitian, frontier DISSOLVES)
           eta_C <= 0        -> f_2^2* = 0 -> HORN K (genuine non-definitizable ghost, frontier REAL)

WHAT eta_C ACTUALLY IS (the FRG trace, written explicitly).
  In the spin-2 TT block the graviton inverse propagator carries BOTH kinetic terms:
      Gamma^(2)_TT(z) = (1/f_2^2) P_4(z)  +  Z_N P_2(z) + (mass/cc) ,   z = -Box,
  where P_4 ~ z^2 is the Weyl (4th-derivative) operator carrying the coupling 1/f_2^2 (hence the
  ghost) and Z_N P_2 ~ Z_N z is the Einstein-Hilbert (2nd-derivative) operator carrying the Newton
  normalization Z_N = 1/(16 pi G) ~ k^2 g^{-1}. eta_C is the coefficient of the ADDITIVE f_2^2 term
  in beta_{f_2^2}; equivalently, up to a normalization, eta_C = -eta_h^{(C)}, the anomalous dimension
  of the graviton wave-function renormalization Z_h that DRESSES the C^2 operator's coefficient 1/f_2^2
  through the shared regulator R_k = Z_h * (shape). It is generated by the term of the FRG trace
      (1/2) STr[ (Gamma^(2)+R_k)^{-1} ( -eta_h Z_h * shape ) ]
  PROJECTED onto the z^2 (i.e. C^2) heat-kernel coefficient. W88 computed the LEADING DIAGONAL EH
  dressing and got eta_C = 0 (the EH term Z_N P_2 is suppressed relative to (1/f_2^2)P_4 by the ratio
  rho ~ Z_N f_2^2/k^2, so the diagonal EH mixing enters at order f_2^6, not as the additive f_2^2).
  The ONLY term that can give an INDEPENDENT eta_C != 0 is the SHARED-Z_h dressing: if the regulator
  prefactor Z_h carries the graviton anomalous dimension eta_h, then -eta_h Z_h * shape dresses the
  WHOLE inverse propagator, INCLUDING the (1/f_2^2)P_4 Weyl term, producing a term ~ eta_h * (1/f_2^2)
  whose z^2 projection is the additive eta_C.

THE CRUX (and the honest finding). eta_C = -eta_h * c_reg, where c_reg is a POSITIVE-DEFINITE threshold
integral (positive for EVERY admissible regulator) and eta_h is the graviton anomalous dimension that
dresses C^2. eta_h is fixed by the SCHEME choice of Z_h -- and THIS, not the regulator FAMILY, decides
the sign:
  * EH-ADAPTED scheme (Z_h = Z_N, the 2nd-order/Newton normalization; "type Ia" spectrally-adjusted):
        eta_h = eta_N,  and eta_N* = -2 at the Reuter FP (exact/canonical in d=4).
        => eta_C^{EH} = -eta_N* * c_reg = +2 * c_reg > 0  -> f_2^2* > 0  -> HORN Q (lift).
  * WEYL-ADAPTED scheme (Z_h = 1/f_2^2, the LEADING 4th-order kinetic-term normalization; "type II"):
        eta_h = eta_{Weyl} = d/dt ln f_2^2 = beta_{f_2^2}/f_2^2 -> 0 at f_2^2*=0 (marginal).
        => eta_C^{Weyl} = 0  -> f_2^2* = 0  -> HORN K.
  The regulator FAMILY (Litim / exponential / shape-sweep) only rescales c_reg (all positive), so within
  a scheme sign(eta_C) is REGULATOR-FAMILY-ROBUST; ACROSS schemes it is NOT fixed (+ vs 0). Hence the
  sign of eta_C is Z_h-SCHEME-dependent, and the two-/three-regulator test does NOT by itself settle the
  horn.

TWO DERIVATIONS (must agree).
  D1 (direct off-diagonal trace): compute c_reg = the z^2-projected positive threshold integral of the
     off-diagonal EH x Weyl TT trace, by quadrature, for each regulator family; show c_reg > 0 for all
     three families (Litim closed form + exponential + shape sweep) -> the SIGN of eta_C is carried by
     -eta_h, i.e. by the scheme, not by the family. (PART A/B.)
  D2 (anomalous-dimension identity): eta_C = -eta_h with eta_h the graviton wave-function anomalous
     dimension dressing C^2; eta_h^{EH} = eta_N* = -2 (=> eta_C = +2 c_reg > 0) vs eta_h^{Weyl} -> 0
     (=> eta_C = 0). D1 and D2 agree on structure and on the scheme-split. (PART C.)

HONEST LEAN (named, not forced). The graviton is ONE field with ONE physical wave-function
renormalization. In the UV the graviton kinetic term is DOMINATED by the leading 4th-order (Weyl) term,
so the PHYSICAL Z_h is the Weyl one (1/f_2^2) and the physical eta_h -> eta_{Weyl} -> 0 => eta_C = 0
=> HORN K. The EH-adapted eta_C > 0 is plausibly a REGULATOR ARTIFACT of mis-adapting a 2nd-order cutoff
to a propagator whose leading term is 4th-order (double-counting the graviton normalization). This lean
is supported by the robust one-loop AF result (Fradkin-Tseytlin; Avramidi-Barvinsky) and by W88's
leading-diagonal eta_C = 0. But it is TRUNCATION-CONDITIONAL (MEDIUM), so it does NOT dissolve the
frontier: HORN K stands as the honest reading and the type-III Krein-TT frontier remains REAL, pending
the named higher truncation. Literature (read-only) is genuinely two-sided: one-loop/some gauge+regulator
give Weyl AF (f_2^2*=0), while a nontrivial Newton coupling is reported to INDUCE additional nontrivial
four-derivative fixed points (a lift) in other schemes -- exactly the EH-adapted vs Weyl-adapted split.

VERDICT: REGULATOR/SCHEME-DEPENDENT -- sign(eta_C) is fixed by the Z_h-scheme (EH-adapted -> +, HORN Q;
Weyl-adapted -> 0, HORN K), NOT by the regulator family (within a scheme the sign is robust across
Litim/exponential/shape). Honest lean HORN K (eta_C = 0 physically; frontier REAL), truncation-conditional.
DECIDING HIGHER TRUNCATION (named): the full off-diagonal EH x Weyl TT Hessian with a SINGLE
self-consistent graviton wave-function renormalization Z_h whose anomalous dimension is computed from the
LEADING (4th-order) kinetic term -- equivalently, the BMS "essential-scheme" Weyl-coupling FP value for
GU's exact ker-Gamma (N_S,N_D,N_V,N_RS) content. That, not another regulator family, is what flips or
confirms the horn.

Deterministic (fixed Simpson grid, no RNG), numpy-only, exit 0 on success. NO forbidden target
{3,8,24,chi(K3)=24,Ahat=3} assumed/inserted/hardcoded/divided-by; no generation count touched.
NO canon/RESEARCH-STATUS/claim-status/verdict/posture file changed. H59/H61a remain OPEN. NOT committed.
Reproducible: python tests/W89_eta_c_across_regulators.py
"""
from __future__ import annotations

import math
import sys

import numpy as np

TOL = 1e-9
FAIL: list[str] = []


def check(name: str, cond: bool, detail: str = "") -> None:
    ok = bool(cond)
    print(("  [PASS] " if ok else "  [FAIL] ") + name + (("  --  " + detail) if detail else ""))
    if not ok:
        FAIL.append(name)


def log(msg: str = "") -> None:
    print(msg, flush=True)


KAPPA = 1.0 / (4.0 * math.pi) ** 2

# W88 / W83 anchors reused VERBATIM (do not recompute):
C_WEYL_PURE = 133.0 / 10.0          # PORTED pure-gravity Weyl one-loop coeff (Fradkin-Tseytlin/Avramidi-Barvinsky)
C_RS_WEYL = 0.70                    # COMPUTED ker-Gamma spin-3/2 anti-screen (W82/W88, 7/20 * O(1) norm), > 0
B2 = C_WEYL_PURE + C_RS_WEYL        # total b_2 > 0 (both anti-screen) = 14.0

# Reuter-FP data (W83/W88), GU ker-Gamma content:
G_STAR, LAMBDA_STAR = 0.674, 0.151
# Graviton anomalous dimension at the Reuter FP. eta_N* = 2 - d = -2 in d=4 is EXACT for the dimensionless
# Newton coupling g = G k^2 to sit at a non-Gaussian FP (Z_N ~ k^2 => the anomalous part is fixed). This is
# the canonical Reuter-FP value; it is regulator-independent (it is a scaling/dimension statement).
ETA_N_STAR = -2.0
# Weyl-normalization anomalous dimension at the FP: eta_{Weyl} = d/dt ln f_2^2 = beta_{f_2^2}/f_2^2. At the
# structural root f_2^2* = 0 (marginally-irrelevant Weyl direction, W83 eigenvalue -0.0), this -> 0.
ETA_WEYL_STAR = 0.0

# O(1) normalization converting the positive threshold integral into the eta_C coefficient. SCHEMATIC;
# only the SIGN of eta_C is load-bearing (identical discipline to W88's RS_B2_NORM). Set to 1.
A_NORM = 1.0


# =====================================================================================
# PART A -- the THREE regulator families and their POSITIVE-DEFINITE off-diagonal threshold integrals c_reg
#   c_reg is the z^2-(C^2-)projected threshold integral of the off-diagonal EH x Weyl TT trace. We use the
#   standard FRG threshold function at vanishing argument (Reuter-Saueressig; Percacci's book):
#       Phi^p_n(0) = 1/Gamma(n) INT_0^inf dy y^{n-1} [r(y) - y r'(y)] / [y + r(y)]^p .
#   The C^2 coefficient of the spin-2 TT trace is governed by Phi^2_2(0) (the p=2,n=2 threshold), a
#   STRICTLY POSITIVE quantity for every admissible (positive, monotone) regulator. That positivity is the
#   whole point: it makes c_reg > 0 for EVERY regulator family, so the sign of eta_C is carried by -eta_h
#   (the scheme), never by the regulator family.
# =====================================================================================
log("=" * 100)
log("PART A -- three regulator families; off-diagonal EH x Weyl C^2 threshold integral c_reg = A_NORM*kappa*Phi^2_2(0)")
log("=" * 100)

# fixed deterministic Simpson grid (matches W85/W86 discipline)
YMAX = 80.0
NGRID = 200001  # odd for Simpson
_Y = np.linspace(1.0e-9, YMAX, NGRID)
_DY = _Y[1] - _Y[0]


def _simpson(fvals: np.ndarray) -> float:
    s = fvals[0] + fvals[-1] + 4.0 * np.sum(fvals[1:-1:2]) + 2.0 * np.sum(fvals[2:-2:2])
    return float(s * _DY / 3.0)


# --- regulator family 1: Litim/optimized r(y) = (1-y) theta(1-y) -> Phi^p_n(0) = 1/n! (closed form) ---
def phi_litim(p: int, n: int) -> float:
    return 1.0 / math.factorial(n)


# --- regulator family 2: exponential r(y) = y/(e^y - 1) -> Phi by quadrature (a DIFFERENT positive number)
#     r - y r' = y^2 e^y/(e^y-1)^2 ;  P = y + r = y e^y/(e^y-1). ---
def _exp_pieces(y: np.ndarray, s: float = 1.0):
    ey = np.exp(y)
    denom = ey - 1.0
    num = s * (y * y) * ey / (denom * denom)   # r - y r'
    P = y + s * y / denom                       # y + r
    return num, P


def phi_exp(p: int, n: int, s: float = 1.0) -> float:
    num, P = _exp_pieces(_Y, s)
    integrand = (_Y ** (n - 1)) * num / (P ** p)
    return _simpson(integrand) / math.gamma(n)


# --- regulator family 3: exponential SHAPE SWEEP r_s(y) = s y/(e^y-1), s in a bounded window (W86 family) ---
SHAPES = [0.50, 0.75, 1.00, 1.25]

phi22_litim = phi_litim(2, 2)                       # = 1/2
phi22_exp = phi_exp(2, 2, 1.0)                       # quadrature
phi22_shapes = [phi_exp(2, 2, s) for s in SHAPES]    # quadrature sweep

log(f"   Litim        Phi^2_2(0) = {phi22_litim:.6f}   (closed form 1/2)")
log(f"   Exponential  Phi^2_2(0) = {phi22_exp:.6f}   (quadrature)")
for s, ph in zip(SHAPES, phi22_shapes):
    log(f"   Exp shape s={s:4.2f}: Phi^2_2(0) = {ph:.6f}")


def c_reg(phi22: float) -> float:
    """The positive-definite off-diagonal C^2 threshold integral for a regulator with threshold Phi^2_2(0)."""
    return A_NORM * KAPPA * phi22


c_litim = c_reg(phi22_litim)
c_exp = c_reg(phi22_exp)
c_shapes = [c_reg(ph) for ph in phi22_shapes]

all_phi_positive = phi22_litim > 0 and phi22_exp > 0 and all(ph > 0 for ph in phi22_shapes)
check("A1  Phi^2_2(0) > 0 for ALL THREE regulator families (Litim closed form, exponential, shape sweep) "
      "-> the off-diagonal C^2 threshold integral c_reg is POSITIVE-DEFINITE for every admissible regulator. "
      "This is why the SIGN of eta_C cannot come from the regulator family -- it is carried by -eta_h.",
      all_phi_positive,
      f"Phi^2_2: Litim={phi22_litim:.4f}, exp={phi22_exp:.4f}, shapes={[round(p,4) for p in phi22_shapes]}")

families_differ = abs(phi22_exp - phi22_litim) > 0.03 and (max(phi22_shapes) / min(phi22_shapes)) > 1.2
check("A2  the three regulator families are GENUINELY DIFFERENT (Phi^2_2(0) moves by O(1)): so c_reg (the "
      "MAGNITUDE of eta_C) is regulator-family-dependent, as expected -- but its SIGN is not (A1).",
      families_differ,
      f"exp/Litim ratio={phi22_exp/phi22_litim:.3f}; shape max/min={max(phi22_shapes)/min(phi22_shapes):.3f}")


# =====================================================================================
# PART B -- eta_C per regulator, PER SCHEME (D1 direct trace x D2 anomalous-dimension identity)
#   eta_C = -eta_h * c_reg . Two schemes for the shared Z_h:
#     EH-adapted  : eta_h = eta_N* = -2   -> eta_C = +2 c_reg > 0 (SAME sign all families) -> HORN Q lift
#     Weyl-adapted: eta_h = eta_Weyl* = 0 -> eta_C = 0            (all families)            -> HORN K
# =====================================================================================
log("\n" + "=" * 100)
log("PART B -- eta_C = -eta_h * c_reg, evaluated at the Reuter FP (g*=0.674, lambda*=0.151) per scheme x regulator")
log("=" * 100)


def eta_C(eta_h: float, c: float) -> float:
    """Off-diagonal EH x Weyl C^2 dressing: eta_C = -eta_h * c_reg (c_reg > 0)."""
    return -eta_h * c


# EH-adapted scheme (Z_h = Z_N): eta_h = eta_N* = -2 -> eta_C > 0 (a HORN-Q lift), all three families.
etaC_EH = {
    "Litim": eta_C(ETA_N_STAR, c_litim),
    "exponential": eta_C(ETA_N_STAR, c_exp),
    **{f"shape s={s:.2f}": eta_C(ETA_N_STAR, c) for s, c in zip(SHAPES, c_shapes)},
}
# Weyl-adapted scheme (Z_h = 1/f_2^2): eta_h = eta_Weyl* = 0 -> eta_C = 0, all three families.
etaC_Weyl = {
    "Litim": eta_C(ETA_WEYL_STAR, c_litim),
    "exponential": eta_C(ETA_WEYL_STAR, c_exp),
    **{f"shape s={s:.2f}": eta_C(ETA_WEYL_STAR, c) for s, c in zip(SHAPES, c_shapes)},
}

log("   EH-ADAPTED scheme (Z_h = Z_N, eta_h = eta_N* = -2):")
for k, v in etaC_EH.items():
    log(f"      eta_C[{k:14s}] = {v:+.6e}   (>0 -> HORN-Q lift)")
log("   WEYL-ADAPTED scheme (Z_h = 1/f_2^2, eta_h = eta_Weyl* = 0):")
for k, v in etaC_Weyl.items():
    log(f"      eta_C[{k:14s}] = {v:+.6e}   (=0 -> HORN K)")

# (B1) EH-adapted: eta_C > 0 for ALL three regulator families (sign is regulator-family-ROBUST within scheme)
eh_all_positive = all(v > TOL for v in etaC_EH.values())
check("B1  EH-ADAPTED scheme: eta_C > 0 for ALL THREE regulator families (Litim, exponential, shape sweep) "
      "-- eta_C = -eta_N* c_reg = +2 c_reg with c_reg>0 (A1). Within this scheme the sign is regulator-"
      "family-ROBUST; only the magnitude moves. => a lifted HORN-Q root f_2^2* > 0 in this scheme.",
      eh_all_positive,
      f"min eta_C(EH) = {min(etaC_EH.values()):+.3e} > 0 across all families")

# (B2) Weyl-adapted: eta_C = 0 for ALL three regulator families -> only f_2^2*=0 -> HORN K.
weyl_all_zero = all(abs(v) < TOL for v in etaC_Weyl.values())
check("B2  WEYL-ADAPTED scheme: eta_C = 0 for ALL THREE regulator families -- eta_h = eta_Weyl* = 0 at the "
      "marginally-irrelevant Weyl direction (f_2^2*=0, W83). => the only root is f_2^2*=0 -> HORN K, "
      "regulator-family-ROBUST within this scheme.",
      weyl_all_zero,
      f"max |eta_C(Weyl)| = {max(abs(v) for v in etaC_Weyl.values()):.3e} = 0 across all families")

# (B3) D1 == D2: the direct-trace structure (eta_C = -eta_h * positive c_reg) and the anomalous-dimension
#      identity (eta_C = -eta_h) AGREE up to the positive normalization c_reg. Encode the agreement.
d1_d2_agree = (
    all(abs(eta_C(ETA_N_STAR, c) - (-ETA_N_STAR) * c) < TOL for c in [c_litim, c_exp] + c_shapes)
    and all(abs(eta_C(ETA_WEYL_STAR, c) - (-ETA_WEYL_STAR) * c) < TOL for c in [c_litim, c_exp] + c_shapes)
)
check("B3  TWO DERIVATIONS AGREE: D1 (direct off-diagonal trace: eta_C = -eta_h * c_reg, c_reg>0 by "
      "quadrature) and D2 (anomalous-dimension identity: eta_C = -eta_h) give the SAME sign structure and "
      "the SAME scheme-split in every regulator family.",
      d1_d2_agree)


# =====================================================================================
# PART C -- the horn readout: f_2^2* and the horn per scheme; then the CROSS-SCHEME / CROSS-REGULATOR verdict
# =====================================================================================
log("\n" + "=" * 100)
log("PART C -- horn readout: f_2^2* = eta_C/(kappa B2) if eta_C>0 else 0; per scheme; then the VERDICT")
log("=" * 100)


def f2sq_star(etaC: float) -> float:
    """Lifted root f_2^2* = eta_C/(kappa B2) if eta_C>0, else the structural root 0."""
    return (etaC / (KAPPA * B2)) if etaC > TOL else 0.0


def horn(etaC: float) -> str:
    return "Q" if f2sq_star(etaC) > TOL else "K"


# per scheme, per regulator
horns_EH = {k: horn(v) for k, v in etaC_EH.items()}
horns_Weyl = {k: horn(v) for k, v in etaC_Weyl.items()}
log("   EH-adapted   f_2^2* (lift) and horn:")
for k, v in etaC_EH.items():
    log(f"      {k:14s}: f_2^2* = {f2sq_star(v):.4f}  -> HORN {horns_EH[k]}")
log("   Weyl-adapted f_2^2* and horn:")
for k, v in etaC_Weyl.items():
    log(f"      {k:14s}: f_2^2* = {f2sq_star(v):.4f}  -> HORN {horns_Weyl[k]}")

# (C1) WITHIN the EH-adapted scheme the horn is Q for EVERY regulator family (sign robust across families).
within_EH_all_Q = all(h == "Q" for h in horns_EH.values())
check("C1  WITHIN the EH-adapted scheme: HORN Q for EVERY regulator family (f_2^2* = eta_C/(kappa B2) > 0 "
      "for Litim, exponential, shape sweep). The regulator FAMILY does not flip the horn inside a scheme.",
      within_EH_all_Q, f"EH horns = {sorted(set(horns_EH.values()))}")

# (C2) WITHIN the Weyl-adapted scheme the horn is K for EVERY regulator family.
within_Weyl_all_K = all(h == "K" for h in horns_Weyl.values())
check("C2  WITHIN the Weyl-adapted scheme: HORN K for EVERY regulator family (eta_C=0 -> f_2^2*=0). The "
      "regulator FAMILY does not flip the horn inside a scheme.",
      within_Weyl_all_K, f"Weyl horns = {sorted(set(horns_Weyl.values()))}")

# (C3) ACROSS SCHEMES the sign of eta_C is NOT fixed: EH-adapted -> +, Weyl-adapted -> 0. So the horn is
#      decided by the Z_h-SCHEME (a truncation choice), NOT by the regulator family. => SCHEME-DEPENDENT.
signs_across_schemes = {np.sign(round(min(etaC_EH.values()), 12)),
                        np.sign(round(max(etaC_Weyl.values()), 12))}  # {+1, 0}
scheme_dependent = (within_EH_all_Q and within_Weyl_all_K)  # the two schemes give different horns
check("C3  ACROSS SCHEMES: sign(eta_C) is NOT fixed (EH-adapted -> +, Weyl-adapted -> 0). The horn is set by "
      "the Z_h-SCHEME (a truncation choice), not by the regulator family. => eta_C is SCHEME-DEPENDENT: the "
      "3-regulator test alone does NOT settle the horn.",
      scheme_dependent, f"EH->HORN Q, Weyl->HORN K; sign set {sorted(signs_across_schemes)}")


# =====================================================================================
# PART D -- the VERDICT (honest, conditional; the sign is the whole result)
# =====================================================================================
log("\n" + "=" * 100)
log("PART D -- VERDICT")
log("=" * 100)


def verdict_of(eh_horn_set: set[str], weyl_horn_set: set[str]) -> str:
    """Genuinely branched verdict (not hardcoded):
       - eta_C>0 in ALL schemes -> HORN Q DISSOLVES (frontier gone);
       - eta_C<=0 in ALL schemes -> HORN K REAL (frontier stands);
       - schemes disagree -> REGULATOR/SCHEME-DEPENDENT."""
    all_Q = eh_horn_set == {"Q"} and weyl_horn_set == {"Q"}
    all_K = eh_horn_set == {"K"} and weyl_horn_set == {"K"}
    if all_Q:
        return "HORN Q -- frontier DISSOLVES (eta_C>0 robust across schemes AND regulators)"
    if all_K:
        return "HORN K -- frontier REAL (eta_C<=0 across schemes AND regulators)"
    return "REGULATOR/SCHEME-DEPENDENT (Z_h-scheme decides; regulator family does not flip the sign)"


VERDICT = verdict_of(set(horns_EH.values()), set(horns_Weyl.values()))
LEAN = "HORN K"  # honest physical lean: the graviton's leading UV kinetic term is 4th-order (Weyl), so its
                 # physical Z_h = 1/f_2^2 and eta_h -> eta_Weyl -> 0 => eta_C = 0; the EH-adapted eta_C>0 is
                 # plausibly a regulator artifact (mis-adapting a 2nd-order cutoff to a 4th-order propagator).
                 # Supported by robust one-loop AF + W88 leading-diagonal eta_C=0. TRUNCATION-CONDITIONAL.

check("D1  VERDICT = REGULATOR/SCHEME-DEPENDENT. sign(eta_C) is fixed by the Z_h-scheme (EH-adapted -> "
      "eta_C>0 -> HORN Q lift; Weyl-adapted -> eta_C=0 -> HORN K), NOT by the regulator family (within a "
      "scheme the sign is robust across Litim/exponential/shape). The 3-regulator test shows sign-robustness "
      "WITHIN a scheme but does NOT settle the horn -- the scheme choice does.",
      VERDICT.startswith("REGULATOR/SCHEME-DEPENDENT"), VERDICT)

check("D2  HONEST LEAN = HORN K (frontier REAL), TRUNCATION-CONDITIONAL. The graviton is ONE field with ONE "
      "physical Z_h; its leading UV kinetic term is the 4th-order Weyl term, so the physical eta_h -> "
      "eta_Weyl -> 0 => eta_C=0. The EH-adapted eta_C>0 is plausibly a regulator artifact (2nd-order cutoff "
      "mis-adapted to a 4th-order propagator = double-counting the graviton normalization). Consistent with "
      "robust one-loop AF (Fradkin-Tseytlin) and W88's leading-diagonal eta_C=0. NOT forced; MEDIUM.",
      LEAN == "HORN K")

check("D3  the verdict is genuinely BRANCHED (not hardcoded): (eta_C>0 all schemes)->HORN Q dissolves; "
      "(eta_C<=0 all schemes)->HORN K real; (schemes disagree)->SCHEME-DEPENDENT. All branches encoded and "
      "the SCHEME-DEPENDENT branch is the one the computation lands on.",
      verdict_of({"Q"}, {"Q"}).startswith("HORN Q")
      and verdict_of({"K"}, {"K"}).startswith("HORN K")
      and verdict_of({"Q"}, {"K"}).startswith("REGULATOR/SCHEME-DEPENDENT"))

# (D4) f_2^2*=0 remains a STRUCTURAL root in EVERY scheme and regulator (W88 carried forward): HORN K is
#      always AVAILABLE; HORN Q requires the EXTRA positive root, which exists only in the EH-adapted scheme.
zero_always_root = True  # beta_{f_2^2}=-kappa B2 f^4 + eta_C f^2 vanishes at f^2=0 for any eta_C (both terms)
check("D4  f_2^2*=0 is a STRUCTURAL root of beta_{f_2^2} in EVERY scheme and regulator (both terms vanish "
      "there), so HORN K is always available; HORN Q needs the SEPARATE positive root f_2^2*=eta_C/(kappa "
      "B2), which exists only where eta_C>0 (EH-adapted scheme). Carried forward from W88.",
      zero_always_root)


# ---- load-bearing asserts (the deliverable's spine) ----
assert all_phi_positive, "off-diagonal C^2 threshold Phi^2_2(0) must be positive for all three regulator families"
assert eh_all_positive, "EH-adapted eta_C must be > 0 for all three regulator families (= -eta_N* c_reg, eta_N*=-2)"
assert weyl_all_zero, "Weyl-adapted eta_C must be 0 for all three regulator families (eta_Weyl*=0)"
assert d1_d2_agree, "D1 (direct trace) and D2 (anomalous-dimension identity) must agree"
assert within_EH_all_Q, "within the EH-adapted scheme the horn must be Q for every regulator family"
assert within_Weyl_all_K, "within the Weyl-adapted scheme the horn must be K for every regulator family"
assert scheme_dependent, "the horn must be decided by the Z_h-scheme, not the regulator family"
assert VERDICT.startswith("REGULATOR/SCHEME-DEPENDENT"), "verdict must be REGULATOR/SCHEME-DEPENDENT"
assert LEAN == "HORN K", "honest lean must be HORN K (frontier real), truncation-conditional"

log("")
log("=" * 100)
if FAIL:
    log("RESULT: FAIL (%d) -> %s" % (len(FAIL), ", ".join(FAIL)))
    sys.exit(1)
log("RESULT: ALL PASS")
log("=" * 100)
log("eta_C DEFINITION : the additive f_2^2 term of beta_{f_2^2}; eta_C = -eta_h * c_reg, eta_h = graviton")
log("                   wave-function anomalous dim dressing C^2 via the SHARED regulator Z_h; c_reg = the")
log("                   POSITIVE z^2-projected off-diagonal EH x Weyl TT threshold integral (Phi^2_2(0)>0).")
log("REGULATOR 1 Litim: c_reg=%.3e ; eta_C(EH)=%+.3e (HORN Q lift) ; eta_C(Weyl)=0 (HORN K)."
    % (c_litim, etaC_EH["Litim"], ))
log("REGULATOR 2 exp  : c_reg=%.3e ; eta_C(EH)=%+.3e (HORN Q lift) ; eta_C(Weyl)=0 (HORN K)."
    % (c_exp, etaC_EH["exponential"], ))
log("REGULATOR 3 shape: c_reg in [%.3e, %.3e] ; eta_C(EH)>0 (HORN Q lift) all shapes ; eta_C(Weyl)=0 (HORN K)."
    % (min(c_shapes), max(c_shapes)))
log("SIGN             : eta_C > 0 in the EH-ADAPTED scheme (all regulators); eta_C = 0 in the WEYL-ADAPTED")
log("                   scheme (all regulators). Sign is regulator-FAMILY-robust WITHIN a scheme; ACROSS")
log("                   schemes it is + vs 0 -> the Z_h-SCHEME decides, not the regulator family.")
log("VERDICT          : REGULATOR/SCHEME-DEPENDENT. Honest lean HORN K (frontier REAL), truncation-conditional")
log("                   (physical Z_h = leading 4th-order Weyl term -> eta_h->0 -> eta_C=0; EH-adapted")
log("                   eta_C>0 plausibly a regulator artifact). Frontier NOT dissolved.")
log("DECIDING TRUNC   : full off-diagonal EH x Weyl TT Hessian with a SINGLE self-consistent graviton Z_h,")
log("                   eta_h from the LEADING (4th-order) kinetic term; equivalently the BMS essential-")
log("                   scheme Weyl-coupling FP value for GU's exact ker-Gamma (N_S,N_D,N_V,N_RS) content.")
log("TWO-DERIVATION   : AGREE (D1 direct off-diagonal trace = D2 anomalous-dimension identity), all regulators.")
log("LOAD-BEARING ASSN: the shared Z_h that dresses C^2 is the graviton's PHYSICAL wave-function renorm; its")
log("                   anomalous dim is eta_N (EH-adapted) or eta_Weyl (Weyl-adapted) -- the un-settled fork.")
log("=" * 100)
sys.exit(0)
