#!/usr/bin/env python3
"""F5 SIGNED FRACTION -- the 0.5975 DERIVED: k_sigma as an exact closed-form
functional of xi's plane content against the canonical Krein cut.

CHANNEL: S_IG/B.5 construction frontier follow-up (the named leftover of the
         master-identity derivation: derive the F5 signed fraction).
DESIGN:  explorations/f5-signed-fraction-2026-07-20.md
EXTENDS: tests/channel-swings/master_identity_mechanism_probe.py (A closed form)
         tests/channel-swings/f5_shadow_c2_flip_probe.py (the discovery: 14421)
         tests/channel-swings/sig_b5_habitat_probe.py (K_S conventions)
STATUS:  exploration tier; the algebra is UNCONDITIONAL (pure Clifford/Krein
         linear algebra on the verified rep); the SECTOR reading of the cut
         inherits the standing boundary-adapter axiom exactly as in the F5
         shadow. No claim, canon, or public-posture movement.

WHAT IS PROVED (paper-grade symbolic derivation, every step machine-
corroborated below). Setup as in the master-identity probe: verified Cl(9,5)
gammas e_a (eta = diag(+1 x9, -1 x5)), n = 14, DIM = 128, xi REAL,
c = c(xi), D = c, X = Gamma M_D Pi_RS, A = X X^+ = (4(n-1)/n)|xi|^2_E I
- (4/n) B with B = xi ^ (eta xi) = -2 c_s c_t (mixed bivector), K_S =
e_0...e_8. Split xi = xi_s + xi_t (space/time), P = |xi_s|^2, T = |xi_t|^2,
s = P + T, q = P - T = <xi, xi>_eta, and let w = c_s c_t / sqrt(PT) (the
unit mixed involution of xi's own plane pair, w^2 = I, B = -2 sqrt(PT) w),
and alpha = artanh(sqrt(T/P)) the RAPIDITY of xi w.r.t. the K_S space/time
split (defined for spacelike xi, q > 0).

  Step 1 (commutant).   Ku := K_S c_s / sqrt(P) commutes with D, and the
                        commutant of D inside the algebra generated by
                        {c_s, c_t, K_S} is the Klein four-group algebra
                        span{I, d, Ku, E^} with d = D/sqrt(q),
                        E^ = d Ku = K_S (sqrt(P) + sqrt(T) w)/sqrt(q):
                        d^2 = Ku^2 = E^2 = I, d Ku = E^ (all commuting).
  Step 2 (Gram).        The compressed Krein Gram on the D-eigenspaces is
                        ch_+- K_S ch_+- = +-(sqrt(P/q)) Ku|_{E_+-}: the
                        Gram-sign splitting used by the F2/F5 canonical-cut
                        construction IS the Ku eigensplitting. Hence
                        V_+ = {E^ = +1}, V_- = {E^ = -1}, and
                            S := Q_+ - Q_- = E^ = K_S e^{alpha w}
                               = K_S (2P I - B) / (2 sqrt(Pq)).
                        The canonical cut is K_S hyperbolically rotated
                        toward xi by exactly the rapidity alpha; the F2
                        "definiteness margin" is sech(alpha) = sqrt(q/P).
                        UNIQUENESS: S is the only Krein-cut symmetry in
                        alg{D, K_S} (sector-value argument in the design
                        doc); K_S S = e^{alpha w} > 0.
  Step 3 (functional).  k_sigma = Re tr(X^+ K_S Q_sigma X) = Re tr(K_S
                        Q_sigma A); tr(K_S A) = 0 gives k_sigma =
                        (sigma/2) tr(e^{alpha w} A), and with the closed
                        form of A (only scalar-scalar and w-w terms
                        survive the trace):
                          k_sigma = sigma (2 DIM / n) sqrt(P/q) ((n-1)s + 2T)
                                  = sigma (128/7) sqrt(P/q) (13P + 15T)
                                  = sigma (C2^2/2) [cosh(alpha)
                                       + tanh(2 alpha) sinh(alpha)/(n-1)].
  The fraction.         f := k_+/C2^2 = (13 + 15 rho) / (26 (1+rho)
                        sqrt(1-rho)), rho = T/P in [0,1) -- scale-free,
                        depending ONLY on xi's plane content; equivalently
                        f = (1/2)[cosh(alpha) + tanh(2 alpha) sinh(alpha)/13].
  Exact value.          Frozen XI: P = 809/20, T = 258/25, q = 3013/100:
                          k_+ = (435616/35) sqrt(4045/3013) = 14421.00328...
                          f   = (68065/132002) sqrt(4045/3013) = 0.5974520...
                        -- the F5 shadow's 0.5975 is an exact ALGEBRAIC
                        (irrational) number, now derived, not measured.
  Decomposition.        k_+ = (C2^2/2) cosh(alpha)            [scalar channel]
                            + (2 DIM/n) sqrt(PT/q) 2 sqrt(T)... = (256/7)
                              sqrt(PT) sinh(alpha)            [B channel]
                        = 13983.70 + 437.30 at frozen XI: the scalar part
                        does NOT cancel per-sector (tr K_S Q_sigma =
                        sigma 64 cosh(alpha) != 0) -- it cancels only in the
                        zero-sum k_+ + k_-. The B-coupling weight is
                        1/(n-1) = 1/13 (ratio of the grade-2 to grade-0
                        contraction coefficients (4/n)/(4(n-1)/n)).
  Scope.                Domain of the canonical cut: EXACTLY {q > 0}. For
                        timelike xi the D-eigenspaces are K-neutral, for
                        null xi Ker D = Range D is K-neutral: no maximal
                        K-definite D-invariant subspace exists either way.
                        On the domain f is strictly increasing in rho with
                        range [1/2, infinity): floor f = 1/2 attained
                        exactly at pure-space xi (where S = K_S and B = 0),
                        divergence at the null cone. f > 1 is reached
                        (rho = 0.98 gives f = 3.80): the Krein-signed
                        reading is NOT a proportion of C2^2.
  Cut-dependence.       The zero-sum k_+ + k_- = 0 holds for EVERY Krein
                        splitting (master identity). The VALUE of |k| does
                        not: a deformed cut that satisfies every
                        admissibility property (K-sa idempotent
                        complementary half-rank, D-invariant, K-definite
                        ranges, magnitude-blind) but is not Gram-spectral
                        gives a different |k|; the naive K_S eigencut (not
                        D-invariant) gives exactly f = 1/2. The 0.5975 is a
                        property of the CANONICAL cut, which is the unique
                        admissible cut with S in alg{D, K_S}.

CONSTRUCTIONS USED (GEOMETER-VS-PHYSICS-OBJECTS discipline): all objects
PROGRAM-NATIVE: the verified Cl(9,5)=M(64,H) rep, C2 as the native
obstruction NORM (never an index), the Krein-native canonical cut of the
F2/F5 probes (the standard positive-Hilbert cut carries no sector datum --
recorded there). No positivity assumption: the derivation uses only the
Krein form and the rep's adjoint structure; the one positivity statement
(K_S S > 0) is DERIVED, not assumed.

NONCLAIMS. Nothing here runs the N2-grade F5 test, builds S_IG, or reads
the bit's value; the sector interpretation of the cut stays conditional on
the standing boundary-adapter axiom; no claim/canon/posture movement.
Deterministic; numpy only; seeded 20260720.
"""
from __future__ import annotations

import os
import sys
from fractions import Fraction

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "generation-sector"))
sys.path.insert(0, os.path.join(HERE, ".."))
import gen_sector_bridge as gb  # noqa: E402
import oq_rk1_cl95_explicit_rep as cl95  # noqa: E402

N_DIRS, DIM = 14, 128
ETA = np.array([1.0] * 9 + [-1.0] * 5)
RNG = np.random.default_rng(20260720)

RESULTS = []


def check(tag, name, ok, detail=""):
    RESULTS.append((tag, name, bool(ok)))
    line = f"[{tag}] {'PASS' if ok else 'FAIL'}  {name}"
    if detail:
        line += f"   ({detail})"
    print(line)
    return ok


def rel(x, ref):
    return float(np.linalg.norm(x)) / max(float(np.linalg.norm(ref)), 1e-300)


# --- the actual W229 objects --------------------------------------------------
e = gb.gammas()
K_S = e[0].copy()
for a in range(1, 9):
    K_S = K_S @ e[a]
I128 = np.eye(DIM, dtype=complex)
XI = np.real(np.asarray(gb.XI)).astype(float)
U_h = e[0] @ e[9]
Uh_inv = np.linalg.inv(U_h)

Gamma = np.hstack(e)
Pi_RS = (np.eye(N_DIRS * DIM, dtype=complex)
         - Gamma.conj().T @ np.linalg.inv(Gamma @ Gamma.conj().T) @ Gamma)


def cvec(v):
    return sum(v[a] * e[a] for a in range(N_DIRS))


def rot(n, a, b, th):
    A = np.eye(n)
    A[a, a] = np.cos(th)
    A[b, b] = np.cos(th)
    A[a, b] = -np.sin(th)
    A[b, a] = np.sin(th)
    return A


def qform(v):
    return float(v @ (ETA * v))


def parts(v):
    vs = np.array(v, dtype=float)
    vt = vs.copy()
    vs[9:] = 0.0
    vt[:9] = 0.0
    return vs, vt, float(vs @ vs), float(vt @ vt)


def X_of(v):
    c = cvec(v)
    return np.hstack([e[a] @ c for a in range(N_DIRS)]) @ Pi_RS


# --- generic Krein-cut machinery (identical construction to the F5 probe,
#     dimension-agnostic so the Cl(5,3) control can reuse it) -----------------
def half_basis(ch):
    Uu, _s, _v = np.linalg.svd(ch)
    return Uu[:, :ch.shape[0] // 2]


def gram_parts(Bc, K):
    Gm = Bc.conj().T @ K @ Bc
    Gm = 0.5 * (Gm + Gm.conj().T)
    w, S = np.linalg.eigh(Gm)
    return Bc @ S[:, w > 0], Bc @ S[:, w < 0]


def kproj(Xc, K):
    M = Xc.conj().T @ K @ Xc
    return Xc @ np.linalg.solve(M, Xc.conj().T @ K)


def krein_cuts(D, q, K, Iden):
    chp = 0.5 * (Iden + D / np.sqrt(q))
    chm = Iden - chp
    p_pos, p_neg = gram_parts(half_basis(chp), K)
    m_pos, m_neg = gram_parts(half_basis(chm), K)
    return (kproj(np.hstack([p_pos, m_pos]), K),
            kproj(np.hstack([p_neg, m_neg]), K))


def k_read(Q, A, K):
    return float(np.trace(K @ Q @ A).real)


def k_formula(P, T, n, dim):
    q = P - T
    return (2.0 * dim / n) * np.sqrt(P / q) * ((n - 1.0) * (P + T) + 2.0 * T)


# --- [T] setup ----------------------------------------------------------------
X = X_of(XI)
A = X @ X.conj().T
C2 = float(np.linalg.norm(X))
bare_e, bare_G, bare_Pi, bare_MD = gb.constraint_objects()
bare = float(np.linalg.norm(bare_Pi @ bare_MD - bare_MD @ bare_Pi))
xs, xt, P0, T0 = parts(XI)
q0 = qform(XI)
s0 = P0 + T0
B = cvec(XI) @ cvec(XI).conj().T - s0 * I128        # = xi ^ (eta xi)
A_closed = (26.0 / 7.0) * s0 * I128 - (2.0 / 7.0) * B
check("T", "anchors + master closed form reproduce: bare 58.7215, "
           "C2 155.3625, A = (26/7)|xi|^2_E I - (2/7) B machine-exactly "
           "(B = c c^+ - |xi|^2_E I = -2 c_s c_t, the mixed bivector)",
      abs(bare - 58.7215) < 1e-2 and abs(C2 - 155.3625) < 1e-2
      and rel(A_closed - A, A) < 1e-12
      and rel(B + 2.0 * cvec(xs) @ cvec(xt), B) < 1e-12,
      f"bare {bare:.4f}, C2 {C2:.4f}, closed-form rel-res "
      f"{rel(A_closed - A, A):.1e}")

D0 = cvec(XI)
Qp, Qm = krein_cuts(D0, q0, K_S, I128)
k_p, k_m = k_read(Qp, A, K_S), k_read(Qm, A, K_S)
k_p_direct = float(np.trace(X.conj().T @ K_S @ Qp @ X).real)
check("T", "the F5-shadow discovery reproduces on the canonical cut: "
           "k_sigma = sigma * 14421.0033, zero-sum, |k|/C2^2 = 0.5975; "
           "the A-based readout tr(K Q A) equals the direct "
           "tr(X^+ K Q X) exactly",
      abs(k_p - 14421.0033) < 1e-2 and abs(k_p + k_m) < 1e-6 * abs(k_p)
      and abs(k_p_direct - k_p) < 1e-6 * abs(k_p)
      and abs(k_p / C2 ** 2 - 0.5975) < 1e-3,
      f"k_+ = {k_p:.4f}, k_- = {k_m:.4f}, f = {k_p / C2 ** 2:.6f}")


# =============================================================================
# Part A -- the derivation: commutant, compressed Gram, cut closed form
# =============================================================================
d = D0 / np.sqrt(q0)
Ku = K_S @ cvec(xs) / np.sqrt(P0)
w_biv = cvec(xs) @ cvec(xt) / np.sqrt(P0 * T0)
Ehat = d @ Ku
alpha = float(np.arctanh(np.sqrt(T0 / P0)))
Ehat_closed = K_S @ (2.0 * P0 * I128 - B) / (2.0 * np.sqrt(P0 * q0))
Ehat_exp = K_S @ (np.cosh(alpha) * I128 + np.sinh(alpha) * w_biv)
klein = max(rel(d @ d - I128, I128), rel(Ku @ Ku - I128, I128),
            rel(Ehat @ Ehat - I128, I128), rel(d @ Ku - Ku @ d, Ku),
            rel(D0 @ Ku - Ku @ D0, D0 @ Ku))
check("E", "STEP 1 (commutant): Ku = K_S c_s/sqrt(P) COMMUTES with D, and "
           "{I, d, Ku, E^ = d Ku} is a Klein four-group of commuting "
           "involutions -- the commutant of D in alg{c_s, c_t, K_S}; "
           "closed forms E^ = K_S(2P I - B)/(2 sqrt(Pq)) = K_S e^{alpha w} "
           "with tanh(alpha) = sqrt(T/P) (rapidity of xi vs the K_S split)",
      klein < 1e-12 and rel(Ehat - Ehat_closed, Ehat) < 1e-12
      and rel(Ehat - Ehat_exp, Ehat) < 1e-12,
      f"alpha = {alpha:.6f}, worst rel-res {klein:.1e}")

chp = 0.5 * (I128 + d)
chm = I128 - chp
gram_p = chp @ K_S @ chp - (np.sqrt(P0 / q0) / 2.0) * (Ehat + Ku)
gram_m = chm @ K_S @ chm - (np.sqrt(P0 / q0) / 2.0) * (Ehat - Ku)
check("E", "STEP 2 (compressed Gram): ch_+- K_S ch_+- = "
           "(sqrt(P/q)/2)(E^ +- Ku) = +-sqrt(P/q) Ku on E_+-(D): the "
           "Gram-sign splitting of the canonical-cut construction IS the "
           "Ku eigensplitting, so V_+ = {E^=+1}, V_- = {E^=-1}",
      rel(gram_p, K_S) < 1e-12 and rel(gram_m, K_S) < 1e-12,
      f"rel-res {max(rel(gram_p, K_S), rel(gram_m, K_S)):.1e}")

S_can = Qp - Qm
KS_eigs = np.linalg.eigvalsh(0.5 * (K_S @ S_can + (K_S @ S_can).conj().T))
check("E", "STEP 2b (cut identification): the machine-built canonical cut "
           "IS the closed form: Q_+- = (I +- E^)/2 machine-exactly; "
           "K_S S = e^{alpha w} > 0 with eigenvalues e^{+-alpha} -- the "
           "F2 probe's 'definiteness margin' is sech(alpha) = sqrt(q/P)",
      rel(Qp - 0.5 * (I128 + Ehat), Qp) < 1e-9
      and rel(Qm - 0.5 * (I128 - Ehat), Qm) < 1e-9
      and float(np.min(KS_eigs)) > 0
      and abs(float(np.min(KS_eigs)) - np.exp(-alpha)) < 1e-9
      and abs(float(np.max(KS_eigs)) - np.exp(alpha)) < 1e-9,
      f"Q_+ rel-res {rel(Qp - 0.5 * (I128 + Ehat), Qp):.1e}; "
      f"spec(K_S S) = [e^-a, e^+a] = [{np.exp(-alpha):.4f}, "
      f"{np.exp(alpha):.4f}], margin sech(a) = {1.0 / np.cosh(alpha):.4f}")

k_fun = k_formula(P0, T0, N_DIRS, DIM)
k_rapid = (C2 ** 2 / 2.0) * (np.cosh(alpha)
                             + np.tanh(2.0 * alpha) * np.sinh(alpha) / 13.0)
check("E", "STEP 3 (THE FUNCTIONAL): k_sigma = sigma (128/7) sqrt(P/q) "
           "(13P + 15T) = sigma (C2^2/2)[cosh(a) + tanh(2a) sinh(a)/13] "
           "-- machine k on the canonical cut matches the closed form to "
           "machine precision",
      abs(k_p - k_fun) < 1e-9 * k_p and abs(k_p - k_rapid) < 1e-9 * k_p,
      f"machine {k_p:.6f} vs formula {k_fun:.6f} vs rapidity form "
      f"{k_rapid:.6f}")

# exact rational/algebraic value at the frozen XI
P_ex, T_ex = Fraction(809, 20), Fraction(258, 25)
q_ex, s_ex = P_ex - T_ex, P_ex + T_ex
k_ex_coeff = Fraction(128, 7) * (13 * P_ex + 15 * T_ex)      # rational
rad = P_ex / q_ex                                             # = 4045/3013
k_exact = float(k_ex_coeff) * np.sqrt(float(rad))
f_coeff = k_ex_coeff / (Fraction(3328, 7) * s_ex)
f_exact = float(f_coeff) * np.sqrt(float(rad))
check("E", "EXACT VALUE: with P = 809/20, T = 258/25 (exact), k_+ = "
           "(435616/35) sqrt(4045/3013) = 14421.0032799... and f = "
           "(68065/132002) sqrt(4045/3013) = 0.5974520211... -- the F5 "
           "shadow's 0.5975 is an exact algebraic (irrational) number, "
           "derived not measured",
      abs(P0 - float(P_ex)) < 1e-12 and abs(T0 - float(T_ex)) < 1e-12
      and k_ex_coeff == Fraction(435616, 35)
      and rad == Fraction(4045, 3013)
      and f_coeff == Fraction(68065, 132002)
      and abs(k_p - k_exact) < 1e-8 * k_p
      and abs(k_p / C2 ** 2 - f_exact) < 1e-10,
      f"k_exact = {k_exact:.10f}, machine {k_p:.10f}; "
      f"f_exact = {f_exact:.10f}")

k_scalar = (26.0 / 7.0) * s0 * float(np.trace(K_S @ Qp).real)
k_bchan = -(2.0 / 7.0) * float(np.trace(K_S @ Qp @ B).real)
trKQ = float(np.trace(K_S @ Qp).real)
check("E", "DECOMPOSITION (the guessed shape corrected): k_+ = "
           "(26/7)s tr(K Q_+) - (2/7) tr(K Q_+ B) = (C2^2/2)cosh(a) + "
           "(256/7)sqrt(PT) sinh(a): the SCALAR channel does NOT cancel "
           "per-sector (tr K_S Q_sigma = sigma 64 cosh(a) != 0), only in "
           "the zero sum; the B channel carries weight 1/(n-1) = 1/13 of "
           "the scalar (grade-2/grade-0 contraction ratio)",
      abs(k_scalar + k_bchan - k_p) < 1e-8 * k_p
      and abs(trKQ - 64.0 * np.cosh(alpha)) < 1e-8
      and abs(k_scalar - (C2 ** 2 / 2.0) * np.cosh(alpha)) < 1e-8 * k_p
      and abs(k_bchan - (256.0 / 7.0) * np.sqrt(P0 * T0)
              * np.sinh(alpha)) < 1e-8 * k_p,
      f"scalar {k_scalar:.4f} (f-share {k_scalar / C2 ** 2:.4f}) + "
      f"B {k_bchan:.4f} (f-share {k_bchan / C2 ** 2:.4f}) = {k_p:.4f}; "
      f"tr K Q_+ = {trKQ:.4f} = 64 cosh(a)")


# =============================================================================
# Part B -- scope: all spacelike xi; floor, divergence, monotonicity
# =============================================================================
def machine_k(v):
    Xv = X_of(v)
    Av = Xv @ Xv.conj().T
    Qpv, _ = krein_cuts(cvec(v), qform(v), K_S, I128)
    return k_read(Qpv, Av, K_S), float(np.linalg.norm(Xv)) ** 2


sweep_ok, sweep_lines = True, []
for label, v in [("generic spacelike", None), ("space-heavy rho=0.05", 0.05),
                 ("moderate rho=0.55", 0.55), ("near-null rho=0.98", 0.98)]:
    if v is None:
        vv = RNG.standard_normal(N_DIRS)
        _, _, Pv, Tv = parts(vv)
        if Pv <= Tv:                       # ensure spacelike
            vv[9:] *= 0.5 * np.sqrt(Pv / Tv)
    else:
        vv = RNG.standard_normal(N_DIRS)
        _, _, Pv, Tv = parts(vv)
        vv[9:] *= np.sqrt(v * Pv / Tv)
    _, _, Pv, Tv = parts(vv)
    km, c2m = machine_k(vv)
    kf = k_formula(Pv, Tv, N_DIRS, DIM)
    fm = km / c2m
    sweep_lines.append(f"      {label:22s} rho = {Tv / Pv:.4f}  f = {fm:.6f}"
                       f"  formula-res {abs(km - kf) / km:.1e}")
    if abs(km - kf) > 1e-7 * km:
        sweep_ok = False
    if v == 0.98 and fm < 1.0:
        sweep_ok = False
v_scaled = 1e3 * XI
km_s, c2m_s = machine_k(v_scaled)
scale_ok = abs(km_s / c2m_s - k_p / C2 ** 2) < 1e-9
for line in sweep_lines:
    print(line)
rho_grid = np.linspace(0.0, 0.95, 96)
f_grid = (13.0 + 15.0 * rho_grid) / (26.0 * (1.0 + rho_grid)
                                     * np.sqrt(1.0 - rho_grid))
check("E", "SCOPE (all spacelike xi): the functional matches machine k for "
           "every seeded spacelike draw (generic, rho = 0.05 / 0.55 / "
           "0.98); f is scale-invariant (xi -> 1000 xi unchanged), depends "
           "only on rho = T/P, is strictly increasing on the sampled grid "
           "with f(0) = 1/2, and EXCEEDS 1 near the null cone (rho = 0.98 "
           "gives f = 3.80): |k|/C2^2 is a rapidity-weighted Krein "
           "reading, NOT a proportion of the obstruction content -- the "
           "frozen XI's 0.5975 is one point on this curve, in no way "
           "special",
      sweep_ok and scale_ok and bool(np.all(np.diff(f_grid) > 0))
      and abs(f_grid[0] - 0.5) < 1e-15,
      f"scaled-xi f = {km_s / c2m_s:.6f}; grid monotone, f(0) = 1/2")

v_space = np.zeros(N_DIRS)
v_space[:9] = RNG.standard_normal(9)
Qps, Qms = krein_cuts(cvec(v_space), qform(v_space), K_S, I128)
Xsp = X_of(v_space)
Asp = Xsp @ Xsp.conj().T
f_space = k_read(Qps, Asp, K_S) / float(np.linalg.norm(Xsp)) ** 2
check("E", "FLOOR: for pure-space xi the canonical cut degenerates to the "
           "K_S eigencut itself (Q_+ = (I + K_S)/2 machine-exactly, since "
           "alpha = 0, B = 0) and f = 1/2 EXACTLY -- the universal floor: "
           "any Krein-definite half of a pure-scalar density reads half "
           "the trace",
      rel(Qps - 0.5 * (I128 + K_S), Qps) < 1e-9
      and abs(f_space - 0.5) < 1e-12,
      f"f(pure space) = {f_space:.14f}")

D1 = cvec(rot(N_DIRS, 0, 9, np.pi) @ XI)
Qp1, _ = krein_cuts(D1, qform(rot(N_DIRS, 0, 9, np.pi) @ XI), K_S, I128)
S_transported = Uh_inv @ (2.0 * Qp1 - I128) @ U_h
check("E", "DECK (closed form of the holonomy tie): transporting the "
           "canonical cut once around the mixed loop sends S = +E^ to -E^ "
           "(machine), so k flips sign exactly -- the F5 shadow's "
           "holonomy-tied sign flip, now read off the derived S",
      rel(S_transported + Ehat, Ehat) < 1e-9,
      f"rel-res {rel(S_transported + Ehat, Ehat):.1e}")


# =============================================================================
# Part C -- controls: cut-dependence, domain boundary, generality
# =============================================================================
# C.1: a DEFORMED admissible cut -- every admissibility property, different k
chp0 = 0.5 * (I128 + d)
p_pos, p_neg = gram_parts(half_basis(chp0), K_S)
m_pos, m_neg = gram_parts(half_basis(I128 - chp0), K_S)
x = p_pos[:, [0]]
y = p_neg[:, [0]]
x = x / np.sqrt(float((x.conj().T @ K_S @ x)[0, 0].real))
y = y / np.sqrt(-float((y.conj().T @ K_S @ y)[0, 0].real))
bta = 0.7
xp = np.cosh(bta) * x + np.sinh(bta) * y
V_def = np.hstack([xp, p_pos[:, 1:], m_pos])
Q_def = kproj(V_def, K_S)
S_def = 2.0 * Q_def - I128
props = (rel(Q_def @ Q_def - Q_def, Q_def) < 1e-9
         and rel(K_S @ Q_def.conj().T @ K_S - Q_def, Q_def) < 1e-9
         and abs(float(np.trace(Q_def).real) - 64.0) < 1e-8
         and rel(Q_def @ D0 - D0 @ Q_def, D0 @ Q_def) < 1e-9)
gram_def = V_def.conj().T @ K_S @ V_def
gram_def = 0.5 * (gram_def + gram_def.conj().T)
pos_def = float(np.min(np.linalg.eigvalsh(gram_def))) > 1e-10
r1 = float(np.linalg.norm(Q_def @ X))
r2 = float(np.linalg.norm((I128 - Q_def) @ X))
k_def = k_read(Q_def, A, K_S)
k_def_c = k_read(I128 - Q_def, A, K_S)
M4 = np.stack([I128.ravel(), d.ravel(), Ku.ravel(), Ehat.ravel()], axis=1)
res_can = np.linalg.lstsq(M4, S_can.ravel(), rcond=None)[1]
res_def = np.linalg.lstsq(M4, S_def.ravel(), rcond=None)[1]
res_can = float(np.sqrt(res_can[0])) / float(np.linalg.norm(S_can))
res_def = float(np.sqrt(res_def[0])) / float(np.linalg.norm(S_def))
check("F", "CUT-DEPENDENCE (the fraction is a property of the CUT): a "
           "Gram-boosted cut satisfying EVERY admissibility property "
           "(K-sa idempotent complementary half-rank, D-invariant, "
           "K-definite range, magnitude-blind, zero-sum) gives a "
           "DIFFERENT |k| -- so |k|/C2^2 is not invariant across the "
           "admissible family; the canonical cut is the unique admissible "
           "cut whose symmetry lies in alg{D, K_S} (canonical residual "
           "~0, deformed residual O(1))",
      props and pos_def and abs(r1 - r2) < 1e-8 * C2
      and abs(k_def + k_def_c) < 1e-6 * abs(k_def)
      and abs(k_def - k_p) > 1.0
      and res_can < 1e-9 and res_def > 1e-2,
      f"k_deformed = {k_def:.4f} vs canonical {k_p:.4f} "
      f"(shift {k_def - k_p:+.4f}); zero-sum holds; "
      f"algebra residuals: canonical {res_can:.1e}, deformed {res_def:.2f}")

Q_KS = 0.5 * (I128 + K_S)
f_KS = k_read(Q_KS, A, K_S) / C2 ** 2
check("F", "the naive K_S eigencut (a Krein splitting, NOT D-invariant) "
           "reads exactly f = 1/2 -- the floor, with ZERO B-coupling: "
           "tr(K_S Q A) = tr(A)/2. Everything above 1/2 in the canonical "
           "0.5975 is the cut's D-compatibility tilt (cosh a - 1)/2 = "
           "0.0793 plus the B channel 0.0181",
      abs(f_KS - 0.5) < 1e-12,
      f"f(K_S cut) = {f_KS:.14f}")

# C.2: domain boundary -- timelike and null xi admit NO canonical cut
v_time = RNG.standard_normal(N_DIRS)
_, _, Pt, Tt = parts(v_time)
v_time[9:] *= np.sqrt(2.0 * Pt / Tt)               # rho = 2 -> q < 0
_, _, Pt, Tt = parts(v_time)
lam = np.sqrt(Tt - Pt)
Dt = cvec(v_time)
_u, sv, vh = np.linalg.svd(Dt - 1j * lam * I128)
ker_t = vh[64:].conj().T                            # eigenspace for +i lam
gram_t = ker_t.conj().T @ K_S @ ker_t
v_null = RNG.standard_normal(N_DIRS)
_, _, Pn, Tn = parts(v_null)
v_null[9:] *= np.sqrt(Pn / Tn)                      # q = 0 exactly (float)
Dn = cvec(v_null)
_u, svn, vhn = np.linalg.svd(Dn)
ker_n = vhn[64:].conj().T                           # Ker D (= Range D)
gram_n = ker_n.conj().T @ K_S @ ker_n
check("F", "DOMAIN BOUNDARY: for timelike xi (q<0) the D-eigenspaces "
           "(eigenvalues +-i sqrt(-q)) are K-NEUTRAL (compressed Gram = "
           "0), and for null xi (q=0) Ker D = Range D is K-neutral (D^2 "
           "= 0) -- either way NO maximal K-definite D-invariant subspace "
           "exists, so the canonical cut and the fraction are defined "
           "EXACTLY on {q > 0}, where f ranges over [1/2, infinity) "
           "(divergence at the null cone = the Gram margin sech(a) -> 0)",
      sv[63] > 1e-3 and sv[64] < 1e-8 * sv[0]
      and float(np.linalg.norm(gram_t)) < 1e-8
      and svn[63] > 1e-3 and svn[64] < 1e-8 * svn[0]
      and float(np.linalg.norm(gram_n)) < 1e-8
      and rel(Dn @ Dn, Dn @ Dn.conj().T) < 1e-12,
      f"||Gram(timelike eigenspace)|| = {float(np.linalg.norm(gram_t)):.1e}, "
      f"||Gram(null kernel)|| = {float(np.linalg.norm(gram_n)):.1e}")

# C.3: generality control -- Cl(5,3): same functional, weight 1/(n-1) = 1/7
n8, dim8 = 8, 16
G8 = cl95.jordan_wigner_gammas(4)
eta8 = np.array([1.0] * 5 + [-1.0] * 3)
f8 = [G8[a] if eta8[a] > 0 else 1j * G8[a] for a in range(n8)]
K8 = f8[0] @ f8[1] @ f8[2] @ f8[3] @ f8[4]
I16 = np.eye(dim8, dtype=complex)
Gamma8 = np.hstack(f8)
Pi8 = (np.eye(n8 * dim8, dtype=complex)
       - Gamma8.conj().T @ np.linalg.inv(Gamma8 @ Gamma8.conj().T) @ Gamma8)
v8 = RNG.standard_normal(n8)
P8r = float(v8[:5] @ v8[:5])
T8r = float(v8[5:] @ v8[5:])
v8[5:] *= np.sqrt(0.4 * P8r / T8r)                  # rho = 0.4, spacelike
P8 = float(v8[:5] @ v8[:5])
T8 = float(v8[5:] @ v8[5:])
c8 = sum(v8[a] * f8[a] for a in range(n8))
X8 = np.hstack([f8[a] @ c8 for a in range(n8)]) @ Pi8
A8 = X8 @ X8.conj().T
Qp8, _ = krein_cuts(c8, P8 - T8, K8, I16)
k8 = float(np.trace(K8 @ Qp8 @ A8).real)
k8_f = k_formula(P8, T8, n8, dim8)
a8 = float(np.arctanh(np.sqrt(T8 / P8)))
f8_rapid = 0.5 * (np.cosh(a8) + np.tanh(2.0 * a8) * np.sinh(a8) / (n8 - 1.0))
check("F", "GENERALITY CONTROL (the 1/13 is 1/(n-1)): the SAME functional "
           "holds verbatim in Cl(5,3) at n = 8, DIM = 16: k = (2 DIM/n) "
           "sqrt(P/q)((n-1)s + 2T), f = (1/2)[cosh a + tanh(2a) sinh(a)/"
           "(n-1)] with weight 1/7 -- the B-coupling weight is the "
           "grade-2/grade-0 contraction ratio, pure combinatorics, not "
           "signature-(9,5) magic",
      abs(k8 - k8_f) < 1e-8 * abs(k8)
      and abs(k8 / float(np.linalg.norm(X8)) ** 2 - f8_rapid) < 1e-10,
      f"machine {k8:.6f} vs formula {k8_f:.6f}; f = "
      f"{k8 / float(np.linalg.norm(X8)) ** 2:.6f}")


# --- headline -----------------------------------------------------------------
nE = sum(1 for tag, _n, ok in RESULTS if tag == "E")
nF = sum(1 for tag, _n, ok in RESULTS if tag == "F")
nT = sum(1 for tag, _n, ok in RESULTS if tag == "T")
all_ok = all(ok for _t, _n, ok in RESULTS)
print()
print("SIGNED-FRACTION VERDICT: DERIVED (paper grade, machine-corroborated "
      "stepwise). The canonical Krein cut is S = K_S e^{alpha w} -- K_S "
      "boosted toward xi by the rapidity alpha = artanh(sqrt(T/P)) -- and "
      "the signed accounting is k_sigma = sigma (C2^2/2)[cosh a + tanh(2a) "
      "sinh(a)/13]: exact algebraic value (435616/35) sqrt(4045/3013) = "
      "14421.0033 at the frozen XI, fraction (68065/132002) sqrt(4045/3013) "
      "= 0.5974520. Scope: all spacelike xi (domain exactly q > 0), floor "
      "1/2 at pure space, unbounded at the null cone, frozen XI not "
      "special. The magnitude is cut-specific (canonical = unique cut in "
      "alg{D, K_S}); the zero-sum sign structure is cut-generic.")
print(f"HEADLINE: {nE} [E] + {nF} [F] = {nE + nF}   (setup [T] = {nT} "
      f"excluded)   {'ALL PASS' if all_ok else 'FAILURES PRESENT'}")
sys.exit(0 if all_ok else 1)
