#!/usr/bin/env python3
"""K1034: action-derived closed flows must descend and preserve the pairing."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "lab/process/k1034-k1033-action-generator-compatibility.json"


def mm(a, b):
    return [[sum(a[i][k] * b[k][j] for k in range(len(b))) for j in range(len(b[0]))] for i in range(len(a))]


def add(a, b):
    return [[a[i][j] + b[i][j] for j in range(len(a[0]))] for i in range(len(a))]


def transpose(a):
    return [list(row) for row in zip(*a)]


def build():
    m = [[1, 0, 0], [0, 2, 0], [0, 0, 0]]
    k = [[0, -2, 0], [1, 0, 0], [0, 0, 0]]
    bad = [[1, 0, 0], [0, 0, 0], [0, 0, 0]]
    good_defect = add(mm(transpose(k), m), mm(m, k))
    bad_defect = add(mm(transpose(bad), m), mm(m, bad))
    return {
        "schema_version": "1.0",
        "result_id": "K1034-K1033-ACTION-GENERATOR-COMPATIBILITY",
        "status": "working_draft_verified",
        "created": "2026-10-04",
        "closed_flow_theorem": {
            "radical_invariance": "K(ker M) subset ker M",
            "pairing_preservation": "K^*M+MK=0",
            "consequence": "exp(tK) descends to an isometry of the positive quotient",
            "local_consequence": "a local quotient unitary gives the K1033 nonselective remote-marginal identity",
        },
        "exact_control": {"M": m, "good_K": k, "good_defect": good_defect, "bad_K": bad, "bad_defect": bad_defect},
        "open_flow_boundary": "dissipative dephasing is not generated by a finite closed M-skew flow alone; its completely positive noise/environment/reset data remain separate owned inputs",
        "source_scope": {
            "SC-ACT-01": "ASSERTS a classical first-order action, not this selected positive quantum generator",
            "SC-ACT-02": "ASSERTS its stated field equation, not a CPTP apparatus evolution",
        },
        "claim_ceiling": "exact finite-dimensional compatibility criterion; no GU generator or dissipative resource derived",
        "ownership": {"gu_generator_selected": False, "gu_open_system_resource_selected": False},
        "target_claim": "NONE-NOT-A-KILL",
    }


def validate(d):
    t = d["closed_flow_theorem"]
    assert t["radical_invariance"] == "K(ker M) subset ker M"
    assert t["pairing_preservation"] == "K^*M+MK=0"
    assert "isometry" in t["consequence"] and "remote-marginal" in t["local_consequence"]
    c = d["exact_control"]
    assert c["good_defect"] == [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
    assert c["bad_defect"] == [[2, 0, 0], [0, 0, 0], [0, 0, 0]]
    assert "not generated" in d["open_flow_boundary"] and "environment/reset" in d["open_flow_boundary"]
    assert d["source_scope"]["SC-ACT-01"].startswith("ASSERTS")
    assert d["source_scope"]["SC-ACT-02"].startswith("ASSERTS")
    assert "no GU generator" in d["claim_ceiling"]
    assert all(value is False for value in d["ownership"].values())
    assert d["target_claim"] == "NONE-NOT-A-KILL"


if __name__ == "__main__":
    data = build()
    validate(data)
    OUTPUT.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    print("K1034 controls: 12/12")
