#!/usr/bin/env python3
"""Reconcile K1193--K1195 with the stronger K542--K545 lineage."""
from __future__ import annotations
import argparse,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k1198-order-ten-projective-lineage-reconciliation.json"
def load(n:str)->dict[str,Any]:return json.loads((ROOT/"lab/process"/n).read_text())
def build()->dict[str,Any]:
 a=load("k1193-order-ten-normal-projective-atlas.json");b=load("k1194-order-ten-projective-measure-and-boundary-routing.json");c=load("k1195-order-ten-anisotropic-projective-controls.json");q=load("k542-order-ten-normal-projective-partition.json");p=load("k543-order-ten-positive-width-projective-pilots.json");z=load("k544-order-ten-zero-strip-angular-majorants.json");o=load("k545-order-ten-global-face-neighborhood-ownership.json")
 shared={"zero_masks":(a["fixed_control"]["unique_zero_masks"],q["fixed_control"]["unique_zero_masks"]),"charts":(a["fixed_control"]["unique_maximum_charts"],q["fixed_control"]["unique_maximum_charts"]),"program_chart_uses":(a["fixed_control"]["program_chart_uses"],q["fixed_control"]["program_chart_uses"]),"coordinate_boundaries":(b["fixed_control"]["unique_oriented_coordinate_boundaries"],q["fixed_control"]["unique_oriented_coordinate_boundaries"]),"boundary_uses":(b["fixed_control"]["program_oriented_coordinate_boundary_uses"],q["fixed_control"]["program_oriented_coordinate_boundary_uses"]),"lower_strata":(b["fixed_control"]["compactly_represented_nonempty_lower_strata"],q["fixed_control"]["compactly_represented_nonempty_lower_strata"])}
 return {"schema_version":"1.0","result_id":"K1198-ORDER-TEN-PROJECTIVE-LINEAGE-RECONCILIATION","created":"2026-10-06","classification":"INTERNAL_STRUCTURAL_ONLY","direction":"observed_to_native","fixed_control":{"predecessor_manifests":["lab/process/k1193-order-ten-normal-projective-atlas.json","lab/process/k1194-order-ten-projective-measure-and-boundary-routing.json","lab/process/k1195-order-ten-anisotropic-projective-controls.json","lab/process/k542-order-ten-normal-projective-partition.json","lab/process/k543-order-ten-positive-width-projective-pilots.json","lab/process/k544-order-ten-zero-strip-angular-majorants.json","lab/process/k545-order-ten-global-face-neighborhood-ownership.json"],"shared_census":shared},"lineage_reconciliation":{"all_shared_censuses_equal":all(x==y for x,y in shared.values()),"K542_already_compiles_exact_partition_measure_and_boundary_routing":q["decision"]["exact_normal_projective_coordinate_partition_complete"] and q["decision"]["exact_angular_measure_compiled"] and q["decision"]["compact_boundary_routing_compiled"],"K543_executes_positive_width_projective_controls":p["decision"]["positive_width_projective_pilot_interface_executed"],"K544_supplies_zero_strip_angular_majorants":z["decision"]["one_sided_zero_strip_angular_mass_majorants_complete"],"K545_supplies_global_disjoint_ownership":o["decision"]["disjoint_global_face_neighborhood_owner_rule_complete"],"K1193_K1195_are_confirmatory_not_frontier_openers":True},"decision":{"projective_lineage_reconciled":True,"factorized_evaluator_is_not_the_current_order_ten_wake":True,"uniform_integrand_boundary_chain_continues_at_K546":True,"next_exact_input":"Replay K546--K553, which already resolves the determinant-preserving boundary envelope through complete integral enclosure."},"release_test":{"all_shared_censuses_equal":all(x==y for x,y in shared.values()),"exactly_16_projective_pilots":p["fixed_control"]["executed_interval_controls"]==16,"exactly_8388606_owned_subsets":o["fixed_control"]["exhausted_low_coordinate_subsets"]==8388606,"stronger_lineage_retained":True,"integrand_boundary_not_credited_to_K544":not z["decision"]["zero_inclusive_integrand_weighted_boundary_majorants_complete"],"complete_integral_not_overclaimed":True,"protected_status_unchanged":True},"claim_ceiling":"Exact reconciliation of K1193--K1195 with K542--K545. The new artifacts reproduce the same 121 masks, 1,022 charts, 6,337 program-chart uses, 21,624 oriented boundaries and 94,463,974 compact lower strata, while the earlier lineage already adds positive-width projective controls, zero-strip angular majorants and exhaustive disjoint owner routing. This is lineage and frontier correction, not a new physical result."}
def validate_payload(p:dict[str,Any])->None:
 if not all(p["release_test"].values()):raise AssertionError("K1198 reconciliation failed")
 if not all(p["lineage_reconciliation"].values()):raise AssertionError("K1198 lineage invariant failed")
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");x=a.parse_args();p=build();validate_payload(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if x.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
