#!/usr/bin/env python3
"""Restore the live branch frontier after downstream lineage reconciliation."""
from __future__ import annotations
import argparse,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k1205-live-frontier-restoration.json"
NOTICE="GU-COMPARATOR-ROUTING — scope before inference. This artifact contains or borders a conventional particle-physics comparator. Any result about a standard Higgs/VEV, ordinary family index or net chirality, SO(10) `126` Majorana mechanism, anomaly selector, VEV-only breaking or familiar vector-mass route binds only that named model. It is not evidence for or against Weinstein's source-native mechanism without an explicit typed bridge. Read `lab/methods/source-native-comparator-routing.md` and follow its source-native pointers before reusing this result."
def load(n:str)->dict[str,Any]:return json.loads((ROOT/"lab/process"/n).read_text())
def build()->dict[str,Any]:
 a=load("k1201-order-ten-to-q12-lineage-replay.json");b=load("k1202-complete-m-dual-consumer-boundary.json");c=load("k1203-high-order-conditional-route-disposition.json");d=load("k1204-k500-current-custody-route-disposition.json");k1190=load("k1190-i1b-enlarged-gauge-boundary.json")
 return {"schema_version":"1.0","result_id":"K1205-LIVE-FRONTIER-RESTORATION","created":"2026-10-06","status":"working_draft_verified","classification":"INTERNAL_STRUCTURAL_ONLY","direction":"observed_to_native","target_claim":"NONE-NOT-A-KILL","gu_comparator_routing":NOTICE,"scope":"Branch-relative restoration after correcting K1200's regression from the later K568--K798 evidence back to K553.","gu_typed_objects":{"result":"frontier restoration MAP-TYPE=typed route reconciliation","primary":"post-K1190 source-action enlarged-gauge/KT/BFV question","conditional_alternative":"K218/K152 only with a named consuming margin and tighter complete bounds","revival_alternative":"K500 only with genuinely new same-domain A and B data"},"fixed_control":{"reconciliation_packets":[a["result_id"],b["result_id"],c["result_id"],d["result_id"]],"Q12_entries":a["fixed_control"]["self_and_cross_entries"],"K577_groups":c["fixed_control"]["high_order_groups"],"K582_targets_met":c["fixed_control"]["targets_met"],"K1190_next_condition":k1190["next_condition"]},"frontier":{"post_K553_join_open":False,"complete_M_dual_residual_open":False,"K152_shifted_form_residual_open":True,"K218_route_current_attempt_satisfies_consumer":False,"K500_current_custody_assembly_open":False,"K500_future_native_construction_open":True,"primary_source_action_frontier_open":True,"primary_next_condition":k1190["next_condition"]},"decision":{"K1200_post_K553_wake_superseded":True,"K1191_K1200_evidence_retained":True,"K568_K798_evidence_retained":True,"primary_frontier_restored_to_post_K1190":True,"protected_status_moves":False},"release_test":{"all_four_reconciliation_packets_pass":all(all(x["release_test"].values()) for x in (a,b,c,d)),"post_K553_not_reopened":a["decision"]["post_K553_join_already_completed_by_K569"],"M_dual_complete":b["decision"]["complete_base_M_dual_residual_is_not_open"],"K152_still_open":b["decision"]["useful_K152_consumer_margin_remains_open"],"K218_current_attempt_not_promoted":not c["decision"]["current_K582_attempt_satisfies_consumer"],"K500_repeat_not_promoted":d["decision"]["repeat_current_custody_assembly_rejected"],"source_frontier_present":bool(k1190["next_condition"]),"protected_disposition_preserved":k1190["protected_disposition"]=="SC-ACT-01/02/06 remain ASSERTS; SC-META-53 remains UNCERTAIN; LT-SM8/LT-GR6b/RA-F1/AC-F1 remain NEEDS","protected_status_unchanged":True},"source_and_ledger_effect":"none","claim_ceiling":"Branch-relative frontier correction only. The post-K553 join and complete M-dual residual are not open. K152 remains open, K218 requires a named consumer and tighter bounds, K500 requires genuinely new native A/B data, and the live primary question remains K1190's source-owned enlarged gauge/KT/BFV or changed-parent packet. No protected verdict moves."}
def validate_payload(p:dict[str,Any])->None:
 if not all(p["release_test"].values()):raise AssertionError("K1205 frontier restoration failed")
 f=p["frontier"]
 if f["post_K553_join_open"] or f["complete_M_dual_residual_open"] or not f["K152_shifted_form_residual_open"] or f["K500_current_custody_assembly_open"]:raise AssertionError("K1205 frontier polarity changed")
 if not f["primary_source_action_frontier_open"] or p["decision"]["protected_status_moves"]:raise AssertionError("K1205 protected frontier changed")
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");x=a.parse_args();p=build();validate_payload(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if x.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
