#!/usr/bin/env python3
"""Dispose the current K576--K582 conditional high-order route exactly."""
from __future__ import annotations
import argparse,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k1203-high-order-conditional-route-disposition.json"
NOTICE="GU-COMPARATOR-ROUTING — scope before inference. This artifact contains or borders a conventional particle-physics comparator. Any result about a standard Higgs/VEV, ordinary family index or net chirality, SO(10) `126` Majorana mechanism, anomaly selector, VEV-only breaking or familiar vector-mass route binds only that named model. It is not evidence for or against Weinstein's source-native mechanism without an explicit typed bridge. Read `lab/methods/source-native-comparator-routing.md` and follow its source-native pointers before reusing this result."
def load(n:str)->dict[str,Any]:return json.loads((ROOT/"lab/process"/n).read_text())
def build()->dict[str,Any]:
 k577=load("k577-k152-high-order-coherent-group-target-atlas.json");k579=load("k579-k577-order-eight-group-complete-uppers.json");k582=load("k582-k579-group-rank-adaptive-complete-uppers.json")
 return {"schema_version":"1.0","result_id":"K1203-HIGH-ORDER-CONDITIONAL-ROUTE-DISPOSITION","created":"2026-10-06","status":"working_draft_verified","classification":"INTERNAL_STRUCTURAL_ONLY","direction":"observed_to_native","target_claim":"NONE-NOT-A-KILL","gu_comparator_routing":NOTICE,"scope":"Branch-relative disposition of the current K576/K577 K152 high-order consumer route after K579 and K582's complete order-eight attempts.","gu_typed_objects":{"result":"conditional route disposition MAP-TYPE=frontier audit","consumer":"K573/K576 projection_sine=1/2","certificate_family":"K577 groupwise sufficient complete-integral uppers","current_attempt":"K579/K582 order-eight complete noncompact group uppers"},"fixed_control":{"high_order_groups":k577["fixed_control"]["coherent_groups"],"high_order_orders":k577["fixed_control"]["orders"],"order_eight_groups":k582["fixed_control"]["groups"],"groups_improved":k582["decision"]["groups_strictly_improved_over_K579"],"groups_unchanged":k582["decision"]["groups_unchanged_from_K579"],"targets_met":k582["decision"]["K577_targets_met"],"targets_failed":k582["decision"]["K577_targets_failed"]},"route":{"all_128_targets_defined":k577["decision"]["all_high_order_coherent_groups_have_exact_sufficient_targets"],"K579_complete_order_eight_uppers":k579["decision"]["all_order_eight_groups_have_complete_noncompact_upper"],"K582_complete_uppers_preserved":k582["decision"]["all_complete_noncompact_group_uppers_preserved"],"K582_improves_13_groups":k582["decision"]["groups_strictly_improved_over_K579"]==13,"K582_meets_no_K577_targets":k582["decision"]["K577_targets_met"]==0,"current_route_emits_K152":k582["decision"]["native_K152_interval_emitted"]},"decision":{"K218_K152_route_globally_killed":False,"current_K582_attempt_satisfies_consumer":False,"new_high_order_work_requires_named_consuming_margin":True,"if_reopened_next_exact_input":k582["decision"]["next_exact_input"],"protected_status_moves":False},"release_test":{"exactly_128_high_order_groups":k577["fixed_control"]["coherent_groups"]==128,"exactly_23_order_eight_groups":k582["fixed_control"]["groups"]==23,"all_23_have_complete_uppers":k579["decision"]["all_order_eight_groups_have_complete_noncompact_upper"],"thirteen_improved":k582["decision"]["groups_strictly_improved_over_K579"]==13,"ten_unchanged":k582["decision"]["groups_unchanged_from_K579"]==10,"zero_targets_met":k582["decision"]["K577_targets_met"]==0,"twenty_three_targets_failed":k582["decision"]["K577_targets_failed"]==23,"K152_not_overclaimed":not k582["decision"]["native_K152_interval_emitted"],"protected_status_unchanged":True},"source_and_ledger_effect":"none","claim_ceiling":"Exact current-route disposition. K577's targets remain valid and K582 improves thirteen complete order-eight group uppers, but all twenty-three remain above target. The broader K218/K152 route is not killed; it requires a named consuming margin and tighter descriptor/face-specific bounds before resumption."}
def validate_payload(p:dict[str,Any])->None:
 if not all(p["release_test"].values()):raise AssertionError("K1203 route disposition failed")
 if p["decision"]["K218_K152_route_globally_killed"] or p["decision"]["current_K582_attempt_satisfies_consumer"] or p["decision"]["protected_status_moves"]:raise AssertionError("K1203 overclaim")
 if p["route"]["current_route_emits_K152"]:raise AssertionError("K1203 invented K152")
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");x=a.parse_args();p=build();validate_payload(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if x.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
