#!/usr/bin/env python3
"""Restore the branch-relative frontier after the order-ten reconciliation."""
from __future__ import annotations
import argparse,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k1200-order-ten-frontier-restoration.json"
def load(n:str)->dict[str,Any]:return json.loads((ROOT/"lab/process"/n).read_text())
def build()->dict[str,Any]:
 a,b,c,d=load("k1196-order-ten-program-lineage-reconciliation.json"),load("k1197-order-ten-face-execution-coverage-replay.json"),load("k1198-order-ten-projective-lineage-reconciliation.json"),load("k1199-order-ten-completion-chain-replay.json")
 return {"schema_version":"1.0","result_id":"K1200-ORDER-TEN-FRONTIER-RESTORATION","created":"2026-10-06","classification":"INTERNAL_STRUCTURAL_ONLY","direction":"observed_to_native","fixed_control":{"predecessor_manifests":["lab/process/k1196-order-ten-program-lineage-reconciliation.json","lab/process/k1197-order-ten-face-execution-coverage-replay.json","lab/process/k1198-order-ten-projective-lineage-reconciliation.json","lab/process/k1199-order-ten-completion-chain-replay.json"],"reconciled_programs":a["fixed_control"]["new_face_programs"],"executed_positive_width_cells":b["fixed_control"]["total_cells"],"projective_masks":c["fixed_control"]["shared_census"]["zero_masks"][0],"completion_chain_length":d["fixed_control"]["chain_length"]},"frontier":{"K1191_host_cost_observation_retained":True,"K1191_host_cost_observation_does_not_erase_K488_or_K508_K553":True,"order_ten_face_execution_open":False,"order_ten_projective_partition_open":False,"order_ten_boundary_envelope_open":False,"order_ten_complete_conditional_integral_enclosure_open":False,"order_ten_sign_open":True,"complete_base_action_column_open":True,"R_ref_residual_open":True,"native_K152_interval_open":True,"restored_next_exact_input":d["decision"]["next_exact_input"]},"decision":{"current_state_requires_correction":True,"factorized_or_cached_group_evaluator_removed_as_current_wake":True,"K553_post_integral_frontier_restored":True,"protected_status_moves":False},"release_test":{"all_four_reconciliation_packets_pass":all([a["decision"]["K487_and_K415_scientific_program_lineages_reconciled"],b["decision"]["all_936_reachable_face_programs_have_positive_width_execution_evidence"],c["decision"]["projective_lineage_reconciled"],d["decision"]["order_ten_numerical_projective_route_is_complete_to_conditional_integral_enclosure"]]),"host_cost_observation_preserved":True,"historical_completion_preserved":True,"current_wake_is_post_K553":d["decision"]["next_exact_input"].startswith("combine the complete order-eight"),"sign_still_open":not d["decision"]["order_ten_sign_decided"],"action_column_still_open":not d["decision"]["action_column_emitted"],"R_ref_still_open":not d["decision"]["R_ref_residual_emitted"],"K152_still_open":not d["decision"]["native_K152_interval_emitted"],"protected_status_unchanged":True},"claim_ceiling":"Branch-relative frontier reconciliation. K1191's measured cost remains valid for its attempted implementation, but it does not reopen the already completed K488 and K508--K553 evidence chain. The order-ten conditional integral enclosure is closed; sign, the complete base action column, R_ref and K152 remain open. No source, ledger, canon, paper, public or physical verdict changes."}
def validate_payload(p:dict[str,Any])->None:
 if not all(p["release_test"].values()):raise AssertionError("K1200 frontier restoration failed")
 if p["decision"]["protected_status_moves"]:raise AssertionError("K1200 moved protected status")
 f=p["frontier"]
 if f["order_ten_complete_conditional_integral_enclosure_open"] or not f["native_K152_interval_open"]:raise AssertionError("K1200 frontier polarity changed")
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");x=a.parse_args();p=build();validate_payload(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if x.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
