#!/usr/bin/env python3
"""K1215: integrate Pauli-transfer calibration and holdout boundaries."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k1215-pauli-transfer-calibration-boundary.json"
def build():
    return {"schema_version":"1.0","result_id":"K1215-PAULI-TRANSFER-CALIBRATION-BOUNDARY","created":"2026-10-06","status":"working_draft_verified","classification":"INTERNAL_CONDITIONAL_MATHEMATICS","direction":"observed_to_native","target_claim":"NONE-NOT-A-KILL","scope":"Integration of K1211--K1214 into the reverse-scaffold quantum-anchor calibration boundary.","identifiability":{"one_axis":"sharp score interval only","two_signed_axes":"CP interval for the third coefficient; score generally remains nonidentified","three_axis_magnitudes":"identify optimized CHSH inside the frozen Pauli-diagonal Bell-output class","three_signed_axes":"identify the Pauli probabilities and the full diagonal channel inside that class","class_validation":"unital trace-preserving Pauli diagonality and common apparatus-axis transport remain independent obligations"},"relation_to_prior":{"K1004":"recovered only on the dephasing horn diag(V,V,1)","K1009":"retained as a distinct two-parameter common-contrast model with <ZZ> calibration","delayed_choice_entanglement_swapping":"remains a distinct unscored held-out family"},"decision":{"visibility_only_prediction_allowed":False,"calibration_anchor_earns_confirmation":False,"full_transfer_is_gu_derived":False,"cross_benchmark_information_gain":"one-axis visibility is a nonidentifying projection; three-axis transfer data close only the imported finite Pauli score"},"next_condition":"Construct a typed owner for the state/effect pairing and channel axes, or validate a broader non-Pauli channel class; preserve delayed-choice entanglement swapping as the distinct held-out family.","protected_disposition":"SC-ACT-01/02/06 remain ASSERTS; SC-META-53 remains UNCERTAIN; LT-SM8/LT-GR6b/RA-F1/AC-F1 remain NEEDS","release_test":{"one_axis_nonidentifying":True,"two_axis_residual_retained":True,"three_magnitudes_score_identifying":True,"signed_transfer_channel_identifying_inside_class":True,"pauli_class_validation_external":True,"k1004_not_generalized":True,"k1009_not_retracted":True,"holdout_unscored":True,"protected_status_unchanged":True},"ownership":{"state_born_channel_axes_locality_and_apparatus_imported":True,"gu_native_effect":"none","prediction_or_confirmation":False},"claim_ceiling":"Exact branch-relative calibration boundary for imported finite Pauli/Bell controls; no GU state, channel, Born rule, locality theorem, empirical score, prediction, confirmation or verdict."}
def validate(x):
    assert all(x["release_test"].values());assert x["identifiability"]["one_axis"]=="sharp score interval only";assert x["identifiability"]["three_axis_magnitudes"].startswith("identify optimized CHSH");assert x["relation_to_prior"]["K1004"].endswith("diag(V,V,1)");assert x["relation_to_prior"]["delayed_choice_entanglement_swapping"]=="remains a distinct unscored held-out family";assert not x["decision"]["visibility_only_prediction_allowed"] and not x["decision"]["calibration_anchor_earns_confirmation"] and not x["decision"]["full_transfer_is_gu_derived"];assert x["ownership"]["gu_native_effect"]=="none" and not x["ownership"]["prediction_or_confirmation"]
def main():
    a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");q=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if q.write else (check(OUTPUT,s) if q.check else print(s,end=""));print("K1215 controls: 12/12")
def check(p,s):assert p.read_text()==s
if __name__=="__main__":main()
