#!/usr/bin/env python3
"""Integrate the custody, rank, control and functional results into the live wake."""
from __future__ import annotations
import argparse,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k1210-source-action-frontier-refinement.json"
def load(n:str)->dict[str,Any]:return json.loads((ROOT/"lab/process"/n).read_text())
def build()->dict[str,Any]:
    a=load("k1206-current-gauge-bfv-custody-ceiling.json");b=load("k1207-changed-parent-rank-budget.json");c=load("k1208-stratumwise-projector-parent-control.json");d=load("k1209-projector-parent-functional-boundary.json");e=load("k1205-live-frontier-restoration.json")
    next_condition="serialize one source-selected/action-owned alternative Shiab or changed-parent stationary two-jet and recompute H, J and d together across every causal stratum, then pass K1145/K1150; otherwise supply a genuinely new source-owned map"
    release={"known_gauge_bfv_candidates_do_not_pay_debt":not a["decision"]["ordinary_known_gauge_enlargement_closes_joint_kernel"],"global_changed_parent_budget_is_98308_98311":b["exact_control"]["minimum_correction_restriction_ranks"]==[98308,98308,98311],"rank8191_not_reused_as_global_cost":not b["decision"]["k1189_rank8191_is_full_native_parent_cost"],"pointwise_control_is_not_native_parent":not c["decision"]["native_changed_parent_constructed"],"literal_projector_fails_cross_null":not d["decision"]["literal_projector_is_continuous_cross_null_family"],"literal_projector_fails_nonzero_cohomology":not d["decision"]["control_passes_nonzero_cohomology_gate"],"alternative_parent_requires_joint_H_J_d_recomputation":True,"K218_revival_predicate_retained":not e["frontier"]["K218_route_current_attempt_satisfies_consumer"],"K500_revival_predicate_retained":e["frontier"]["K500_future_native_construction_open"],"protected_status_unchanged":True}
    return {"schema_version":"1.0","result_id":"K1210-SOURCE-ACTION-FRONTIER-REFINEMENT","created":"2026-10-06","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"NONE-NOT-A-KILL","scope":"Branch-relative integration of K1206--K1209 into the post-K1190 source-action frontier.","gu_typed_objects":{"current_parent":"selected K132 H,J,d packet","excluded_control":"reverse-selected S=B*B+P_W","next_parent_class":"source-selected alternative Shiab or changed-parent stationary two-jet","target":"ROUTE-TYPE=jointly recomputed source-action H/J/d frontier"},"fixed_control":{"packet_ids":[a["result_id"],b["result_id"],c["result_id"],d["result_id"]],"known_overgrant_residuals":a["exact_control"]["residual_after_full_u_and_rank98_overgrant"],"minimum_changed_parent_restriction_ranks":b["exact_control"]["minimum_correction_restriction_ranks"],"projector_rank_jump":d["exact_control"]["rank_jump"],"projector_failed_functional_gates":d["exact_control"]["failed_gate_count"]},"frontier":{"current_known_gauge_route_complete":False,"literal_projector_parent_route_open":False,"alternative_shiab_changed_parent_route_open":True,"new_source_owned_map_route_open":True,"K218_requires_named_consumer_and_tighter_bounds":True,"K500_requires_new_same_domain_A_and_B":True,"next_condition":next_condition},"decision":{"mix_new_J_with_selected_H_allowed":False,"alternative_parent_must_recompute_H_J_d_together":True,"conditional_control_promoted_to_source_owner":False,"SC_ACT_06_proved_or_refuted":False,"protected_status_moves":False},"release_test":release,"source_and_ledger_effect":"none","next_condition":next_condition,"protected_disposition":"SC-ACT-01/02/06 remain ASSERTS; SC-META-53 remains UNCERTAIN; LT-SM8/LT-GR6b/RA-F1/AC-F1 remain NEEDS","claim_ceiling":"Exact current-frontier refinement only. Known candidates and the literal projector control are closed at their stated interfaces; future source-owned changed parents or maps remain open."}
def validate_payload(p:dict[str,Any])->None:
    if not all(p["release_test"].values()):raise AssertionError("K1210 release test failed")
    f=p["frontier"];d=p["decision"]
    if f["literal_projector_parent_route_open"] or not f["alternative_shiab_changed_parent_route_open"] or not f["new_source_owned_map_route_open"]:raise AssertionError("K1210 frontier changed")
    if d["mix_new_J_with_selected_H_allowed"] or d["conditional_control_promoted_to_source_owner"] or d["protected_status_moves"]:raise AssertionError("K1210 custody or protected overclaim")
def main()->int:
    a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");x=a.parse_args();p=build();validate_payload(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if x.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
