#!/usr/bin/env python3
"""Hostile mutations for K1496."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1496-finite-cutoff-krylov-endpoint.json').read_text())
def valid(d):
 a,q=d['finite_cutoff_endpoint'],d['decision'];return all([d['claim_id']=='K1496','(phi_N(x)^2-3C_N)^2' in a['square_completion'],'sqrt(3C_N)' in a['exact_essential_infimum'],'ess inf X_N=-L_N' in a['exact_essential_infimum'],'Hardy criterion' in a['hardy_determinacy'],'E exp(c_N sqrt(Z_N))<infinity' in a['hardy_determinacy'],'decreasing to ess inf X_N' in a['tower_limit'],'Theta(N^(3/2))' in a['endpoint_scale'],'does not prove that c_d is unbounded' in a['noncommuting_limits'],q['exact_fixed_cutoff_multiplication_infimum']=='-6C_N^2/sigma_N',q['fixed_cutoff_polynomial_tower_reaches_infimum'],q['fixed_cutoff_endpoint_order']=='N^(3/2)',not q['degree_and_cutoff_limits_interchanged'],not q['degree_dependent_free_cost_controlled_uniformly'],not q['ground_energy_asymptotic_determined'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('square',lambda d:d['finite_cutoff_endpoint'].update(square_completion='none')),('support',lambda d:d['finite_cutoff_endpoint'].update(exact_essential_infimum='unknown')),('Hardy',lambda d:d['finite_cutoff_endpoint'].update(hardy_determinacy='unknown')),('tower',lambda d:d['finite_cutoff_endpoint'].update(tower_limit='unknown')),('scale',lambda d:d['finite_cutoff_endpoint'].update(endpoint_scale='unknown')),('fence',lambda d:d['finite_cutoff_endpoint'].update(noncommuting_limits='limits commute')),('inf',lambda d:d['decision'].update(exact_fixed_cutoff_multiplication_infimum='0')),('tower decision',lambda d:d['decision'].update(fixed_cutoff_polynomial_tower_reaches_infimum=False)),('scale decision',lambda d:d['decision'].update(fixed_cutoff_endpoint_order='N')),('interchange',lambda d:d['decision'].update(degree_and_cutoff_limits_interchanged=True)),('uniform cost',lambda d:d['decision'].update(degree_dependent_free_cost_controlled_uniformly=True)),('ground',lambda d:d['decision'].update(ground_energy_asymptotic_determined=True)),('protected',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
