#!/usr/bin/env python3
"""Hostile mutations for K1495."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1495-fixed-degree-variational-hierarchy.json').read_text())
def valid(d):
 a,q=d['variational_hierarchy'],d['decision'];return all([d['claim_id']=='K1495','strictly increasing' in a['coefficients'],'-c_d+o(1)' in a['multiplication_bottom'],'O_d(N)' in a['free_cost'],'6gC_N^2-c_d g sigma_N+O_d(N)' in a['ground_energy_upper'],'requires a_N<=' in a['necessary_recentering'],'->-infinity' in a['explicit_divergent_window'],q['strictly_increasing_fixed_degree_coefficients'],q['arbitrary_fixed_degree_variational_upper_bound'],q['arbitrary_fixed_degree_recentering_necessity'],not q['every_finite_degree_is_terminal'],not q['coefficient_sequence_unbounded'],not q['matching_ground_energy_lower_bound_proved'],not q['mosco_recovery_proved'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('strict prose',lambda d:d['variational_hierarchy'].update(coefficients='flat')),('bottom',lambda d:d['variational_hierarchy'].update(multiplication_bottom='unknown')),('free',lambda d:d['variational_hierarchy'].update(free_cost='unknown')),('energy',lambda d:d['variational_hierarchy'].update(ground_energy_upper='unknown')),('recenter',lambda d:d['variational_hierarchy'].update(necessary_recentering='unknown')),('window',lambda d:d['variational_hierarchy'].update(explicit_divergent_window='bounded')),('strict decision',lambda d:d['decision'].update(strictly_increasing_fixed_degree_coefficients=False)),('variational',lambda d:d['decision'].update(arbitrary_fixed_degree_variational_upper_bound=False)),('recenter decision',lambda d:d['decision'].update(arbitrary_fixed_degree_recentering_necessity=False)),('terminal',lambda d:d['decision'].update(every_finite_degree_is_terminal=True)),('unbounded',lambda d:d['decision'].update(coefficient_sequence_unbounded=True)),('lower',lambda d:d['decision'].update(matching_ground_energy_lower_bound_proved=True)),('Mosco',lambda d:d['decision'].update(mosco_recovery_proved=True)),('protected',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
