#!/usr/bin/env python3
"""Hostile mutations for K1498."""
import copy, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1498-fourth-chaos-contraction-decay.json').read_text())
def valid(d):
 a,q=d['contraction_power_count'],d['decision'];return all([d['claim_id']=='K1498',a['contraction_orders']==[1,2,3],a['vertices']==4,a['edges']==8,a['loop_rank']==5,a['full_superficial_degree']==7,a['proper_two_vertex_degrees']==[-1,1,3],a['proper_three_vertex_degree_upper']==2,'N^7' in a['graph_sum_upper'],'N^10' in a['variance_square_order'],'N^-3' in a['normalized_contraction_upper'],q['all_nontrivial_contractions_vanish'],q['fixed_chaos_fourth_moment_criterion_ready'],not q['growing_polynomial_degree_controlled'],not q['ground_energy_lower_bound_proved'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('orders',lambda d:d['contraction_power_count'].update(contraction_orders=[1,2])),('vertices',lambda d:d['contraction_power_count'].update(vertices=3)),('edges',lambda d:d['contraction_power_count'].update(edges=7)),('loops',lambda d:d['contraction_power_count'].update(loop_rank=4)),('degree',lambda d:d['contraction_power_count'].update(full_superficial_degree=8)),('pair degrees',lambda d:d['contraction_power_count'].update(proper_two_vertex_degrees=[-1,1,4])),('triple degree',lambda d:d['contraction_power_count'].update(proper_three_vertex_degree_upper=3)),('graph scale',lambda d:d['contraction_power_count'].update(graph_sum_upper='unknown')),('variance',lambda d:d['contraction_power_count'].update(variance_square_order='unknown')),('decay',lambda d:d['contraction_power_count'].update(normalized_contraction_upper='unknown')),('deny vanish',lambda d:d['decision'].update(all_nontrivial_contractions_vanish=False)),('deny criterion',lambda d:d['decision'].update(fixed_chaos_fourth_moment_criterion_ready=False)),('claim degree',lambda d:d['decision'].update(growing_polynomial_degree_controlled=True)),('claim lower',lambda d:d['decision'].update(ground_energy_lower_bound_proved=True)),('move status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
