#!/usr/bin/env python3
"""Hostile mutations for K1497."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1497-polynomial-krylov-admission.json').read_text())
def valid(d):
 c,q=d['bridge_census'],d['decision'];return all([d['claim_id']=='K1497',c['row_count']==c['satisfied_count']+c['conditional_count']+c['excluded_count']+c['missing_count'],c['row_count']==187,c['satisfied_count']==117,c['conditional_count']==10,c['excluded_count']==56,c['missing_count']==4,len(c['new_satisfied_rows'])==6,len(c['new_excluded_rows'])==2,len(c['missing_rows'])==4,q['all_fixed_polynomial_degrees_controlled'],q['strict_fixed_degree_variational_hierarchy_proved'],q['finite_cutoff_full_tower_endpoint_proved'],not q['fixed_degree_coefficient_sequence_unbounded'],not q['many_chaos_ground_energy_lower_bound_constructed'],not q['ground_energy_recentered_limit_constructed'],not q['full_spacetime_pde_repair_constructed'],not q['source_selected_reduction_constructed'],not q['k1145_k1150_candidate_counts_move'],not q['protected_status_change'],'SOURCE_REGISTER_UNCHANGED' in d['source_and_ledger_effect']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('rows',lambda d:d['bridge_census'].update(row_count=186)),('satisfied',lambda d:d['bridge_census'].update(satisfied_count=116)),('conditional',lambda d:d['bridge_census'].update(conditional_count=11)),('excluded',lambda d:d['bridge_census'].update(excluded_count=55)),('missing',lambda d:d['bridge_census'].update(missing_count=5)),('new satisfied',lambda d:d['bridge_census'].update(new_satisfied_rows=[])),('new excluded',lambda d:d['bridge_census'].update(new_excluded_rows=[])),('missing list',lambda d:d['bridge_census'].update(missing_rows=[])),('fixed degrees',lambda d:d['decision'].update(all_fixed_polynomial_degrees_controlled=False)),('hierarchy',lambda d:d['decision'].update(strict_fixed_degree_variational_hierarchy_proved=False)),('endpoint',lambda d:d['decision'].update(finite_cutoff_full_tower_endpoint_proved=False)),('unbounded',lambda d:d['decision'].update(fixed_degree_coefficient_sequence_unbounded=True)),('lower',lambda d:d['decision'].update(many_chaos_ground_energy_lower_bound_constructed=True)),('limit',lambda d:d['decision'].update(ground_energy_recentered_limit_constructed=True)),('PDE',lambda d:d['decision'].update(full_spacetime_pde_repair_constructed=True)),('source',lambda d:d['decision'].update(source_selected_reduction_constructed=True)),('counts',lambda d:d['decision'].update(k1145_k1150_candidate_counts_move=True)),('protected',lambda d:d['decision'].update(protected_status_change=True)),('source effect',lambda d:d.update(source_and_ledger_effect='changed'))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
