#!/usr/bin/env python3
"""Hostile mutations for K1501."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1501-superlinear-variational-recentering.json').read_text())
def valid(d):
 a,q=d['superlinear_boundary'],d['decision'];return all([d['claim_id']=='K1501','fixed d' in a['degree_choice'],'-(A+1)' in a['multiplication_trial'],'O_d(N)=o(sigma_N)' in a['free_cost'],'every fixed A>0' in a['arbitrary_fixed_coefficient'],'+infinity' in a['ratio_limit'],'requires' in a['necessary_recentering'],'O(sigma_N)' in a['excluded_window'],'-infinity' in a['mosco_boundary'],'harmonic BRST vacuum' in a['brst_transfer'],q['negative_correction_super_sigma'],q['every_order_sigma_recentering_excluded'],q['fixed_gaussian_mosco_weak_liminf_excluded_in_that_window'],q['harmonic_brst_boundary_transferred'],not q['quantitative_divergence_rate_proved'],not q['cutoff_dependent_degree_constructed'],not q['matching_ground_energy_lower_bound_proved'],not q['ground_energy_recentering_excluded'],not q['mosco_recovery_proved'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('degree',lambda d:d['superlinear_boundary'].update(degree_choice='d(N)')),('gain',lambda d:d['superlinear_boundary'].update(multiplication_trial='unknown')),('cost',lambda d:d['superlinear_boundary'].update(free_cost='unknown')),('A',lambda d:d['superlinear_boundary'].update(arbitrary_fixed_coefficient='unknown')),('ratio',lambda d:d['superlinear_boundary'].update(ratio_limit='bounded')),('recenter',lambda d:d['superlinear_boundary'].update(necessary_recentering='unknown')),('window',lambda d:d['superlinear_boundary'].update(excluded_window='unknown')),('Mosco',lambda d:d['superlinear_boundary'].update(mosco_boundary='unknown')),('BRST',lambda d:d['superlinear_boundary'].update(brst_transfer='unknown')),('deny super',lambda d:d['decision'].update(negative_correction_super_sigma=False)),('deny window',lambda d:d['decision'].update(every_order_sigma_recentering_excluded=False)),('deny Mosco',lambda d:d['decision'].update(fixed_gaussian_mosco_weak_liminf_excluded_in_that_window=False)),('deny BRST',lambda d:d['decision'].update(harmonic_brst_boundary_transferred=False)),('claim rate',lambda d:d['decision'].update(quantitative_divergence_rate_proved=True)),('claim dN',lambda d:d['decision'].update(cutoff_dependent_degree_constructed=True)),('claim lower',lambda d:d['decision'].update(matching_ground_energy_lower_bound_proved=True)),('exclude ground',lambda d:d['decision'].update(ground_energy_recentering_excluded=True)),('claim recovery',lambda d:d['decision'].update(mosco_recovery_proved=True)),('move status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
