#!/usr/bin/env python3
"""Hostile mutations for K1506."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1506-growing-rate-recentering.json').read_text())
def valid(d):
 r,m,q=d['recentering_boundary'],d['mosco_transfer'],d['decision'];return all([d['claim_id']=='K1506','sqrt(log N/log log N)' in r['necessary_scale'],'=o(' in r['excluded_window'],'c-epsilon' in r['quantitative_failure'],'-infinity' in r['quantitative_failure'],'weakly convergent subsequences' in m['weak_compactness'],'may be zero' in m['weak_limit'],'-infinity' in m['failure'],'semibounded' in m['failure'],'K1471' in m['brst'],'harmonic compression' in m['brst'],q['growing_rate_recentering_necessity_proved'],q['fixed_gaussian_mosco_weak_liminf_window_excluded'],q['harmonic_brst_window_excluded'],not q['nonzero_weak_limit_proved'],not q['mosco_recovery_proved'],not q['ground_energy_recentered_limit_proved'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('rate',lambda d:d['recentering_boundary'].update(necessary_scale='sigma only')),('window',lambda d:d['recentering_boundary'].update(excluded_window='none')),('epsilon',lambda d:d['recentering_boundary'].update(quantitative_failure='bounded')),('compactness',lambda d:d['mosco_transfer'].update(weak_compactness='none')),('zero',lambda d:d['mosco_transfer'].update(weak_limit='nonzero required')),('failure',lambda d:d['mosco_transfer'].update(failure='unknown')),('BRST',lambda d:d['mosco_transfer'].update(brst='none')),('deny necessity',lambda d:d['decision'].update(growing_rate_recentering_necessity_proved=False)),('deny Mosco',lambda d:d['decision'].update(fixed_gaussian_mosco_weak_liminf_window_excluded=False)),('deny BRST',lambda d:d['decision'].update(harmonic_brst_window_excluded=False)),('claim nonzero',lambda d:d['decision'].update(nonzero_weak_limit_proved=True)),('claim recovery',lambda d:d['decision'].update(mosco_recovery_proved=True)),('claim limit',lambda d:d['decision'].update(ground_energy_recentered_limit_proved=True)),('move status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
