#!/usr/bin/env python3
"""Hostile mutations for K1500."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1500-hermite-jacobi-limit.json').read_text())
def valid(d):
 a,q=d['hermite_jacobi_limit'],d['decision'];return all([d['claim_id']=='K1500','fixed before N' in a['fixed_degree'],'2d' in a['moment_matrix'],'positive definite' in a['positive_definiteness'],'continuous' in a['coefficient_continuity'],'J_(d,N)->J_d^G' in a['jacobi_limit'],'sqrt(j+1)' in a['hermite_recurrence'],'-c_d^G' in a['limiting_bottom'],'sqrt(d)' in a['two_coordinate_bound'],q['every_fixed_jacobi_compression_converges'],q['limiting_orthogonal_polynomials_are_hermite'],q['fixed_degree_coefficient_sequence_unbounded'],not q['simultaneous_degree_cutoff_rate_proved'],not q['fixed_cutoff_endpoint_replaced'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('order',lambda d:d['hermite_jacobi_limit'].update(fixed_degree='d(N)')),('moments',lambda d:d['hermite_jacobi_limit'].update(moment_matrix='unknown')),('positive',lambda d:d['hermite_jacobi_limit'].update(positive_definiteness='unknown')),('continuity',lambda d:d['hermite_jacobi_limit'].update(coefficient_continuity='unknown')),('Jacobi',lambda d:d['hermite_jacobi_limit'].update(jacobi_limit='unknown')),('recurrence',lambda d:d['hermite_jacobi_limit'].update(hermite_recurrence='unknown')),('bottom',lambda d:d['hermite_jacobi_limit'].update(limiting_bottom='unknown')),('bound',lambda d:d['hermite_jacobi_limit'].update(two_coordinate_bound='unknown')),('deny compression',lambda d:d['decision'].update(every_fixed_jacobi_compression_converges=False)),('deny Hermite',lambda d:d['decision'].update(limiting_orthogonal_polynomials_are_hermite=False)),('deny unbounded',lambda d:d['decision'].update(fixed_degree_coefficient_sequence_unbounded=False)),('claim rate',lambda d:d['decision'].update(simultaneous_degree_cutoff_rate_proved=True)),('replace endpoint',lambda d:d['decision'].update(fixed_cutoff_endpoint_replaced=True)),('move status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
