#!/usr/bin/env python3
"""Hostile mutations for K1507."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1507-growing-krylov-admission.json').read_text())
def valid(d):
 c,q=d['bridge_census'],d['decision'];return all([d['claim_id']=='K1507',c['row_count']==c['satisfied_count']+c['conditional_count']+c['excluded_count']+c['missing_count'],c['row_count']==204,c['satisfied_count']==129,c['conditional_count']==10,c['excluded_count']==61,c['missing_count']==4,len(c['new_satisfied_rows'])==6,len(c['new_excluded_rows'])==2,len(c['missing_rows'])==4,q['growing_moment_window_proved'],q['cutoff_dependent_degree_constructed'],q['explicit_divergent_variational_rate_proved'],q['growing_rate_recentering_window_excluded'],not q['optimal_degree_or_rate_proved'],not q['many_chaos_ground_energy_lower_bound_constructed'],not q['ground_energy_recentered_limit_constructed'],not q['full_spacetime_pde_repair_constructed'],not q['source_selected_reduction_constructed'],not q['k1145_k1150_candidate_counts_move'],not q['protected_status_change'],'SOURCE_REGISTER_UNCHANGED' in d['source_and_ledger_effect']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('rows',lambda d:d['bridge_census'].update(row_count=203)),('satisfied',lambda d:d['bridge_census'].update(satisfied_count=128)),('conditional',lambda d:d['bridge_census'].update(conditional_count=9)),('excluded',lambda d:d['bridge_census'].update(excluded_count=60)),('missing',lambda d:d['bridge_census'].update(missing_count=3)),('new satisfied',lambda d:d['bridge_census'].update(new_satisfied_rows=[])),('new excluded',lambda d:d['bridge_census'].update(new_excluded_rows=[])),('missing rows',lambda d:d['bridge_census'].update(missing_rows=[])),('deny moment',lambda d:d['decision'].update(growing_moment_window_proved=False)),('deny dN',lambda d:d['decision'].update(cutoff_dependent_degree_constructed=False)),('deny rate',lambda d:d['decision'].update(explicit_divergent_variational_rate_proved=False)),('deny recenter',lambda d:d['decision'].update(growing_rate_recentering_window_excluded=False)),('claim optimal',lambda d:d['decision'].update(optimal_degree_or_rate_proved=True)),('claim lower',lambda d:d['decision'].update(many_chaos_ground_energy_lower_bound_constructed=True)),('claim limit',lambda d:d['decision'].update(ground_energy_recentered_limit_constructed=True)),('claim PDE',lambda d:d['decision'].update(full_spacetime_pde_repair_constructed=True)),('claim source',lambda d:d['decision'].update(source_selected_reduction_constructed=True)),('move counts',lambda d:d['decision'].update(k1145_k1150_candidate_counts_move=True)),('move status',lambda d:d['decision'].update(protected_status_change=True)),('move ledger',lambda d:d.update(source_and_ledger_effect='changed'))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
