#!/usr/bin/env python3
"""Hostile mutations for K1511."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1511-sqrt-log-recentering-boundary.json').read_text())
def valid(d):
 r,q=d['recentering_boundary'],d['decision'];return all([d['claim_id']=='K1511','liminf' in r['necessary_scale'],'>=sqrt(3)' in r['necessary_scale'],'limsup' in r['excluded_window'],'<sqrt(3)' in r['excluded_window'],'unit ball' in r['weak_compactness'],'may be zero' in r['weak_compactness'],'Mosco liminf' in r['mosco_failure'],'harmonic BRST vacuum' in r['brst_transfer'],q['sqrt_log_recentering_necessity_proved'],q['fixed_gaussian_mosco_weak_liminf_window_excluded'],q['harmonic_brst_window_excluded'],not q['ground_energy_recentered_limit_constructed'],not q['mosco_recovery_proved'],not q['changed_representation_excluded'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('necessary',lambda d:d['recentering_boundary'].update(necessary_scale='none')),('constant',lambda d:d['recentering_boundary'].update(necessary_scale='liminf>=0')),('window',lambda d:d['recentering_boundary'].update(excluded_window='none')),('window constant',lambda d:d['recentering_boundary'].update(excluded_window='limsup<4')),('compactness',lambda d:d['recentering_boundary'].update(weak_compactness='unknown')),('zero',lambda d:d['recentering_boundary'].update(weak_compactness='unit ball')),('Mosco',lambda d:d['recentering_boundary'].update(mosco_failure='unknown')),('BRST',lambda d:d['recentering_boundary'].update(brst_transfer='unknown')),('deny',lambda d:d['decision'].update(sqrt_log_recentering_necessity_proved=False)),('claim limit',lambda d:d['decision'].update(ground_energy_recentered_limit_constructed=True)),('claim recovery',lambda d:d['decision'].update(mosco_recovery_proved=True)),('close changed rep',lambda d:d['decision'].update(changed_representation_excluded=True)),('status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
