#!/usr/bin/env python3
"""Hostile mutations for K1515."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1515-weighted-malliavin-tilt-cost.json').read_text())
def valid(d):
 c,q=d['weighted_cost'],d['decision'];return all([d['claim_id']=='K1515','D u_N(X_N)' in c['chain_rule'],'-(R_N/2)u_N' in c['chain_rule'],'chi\u0027(x/R_N)' in c['chain_rule'],'at least R_N/2' in c['cutoff_boundary'],'exponentially negligible' in c['cutoff_boundary'],'p_N=1+R_N^(-2)' in c['holder_pair'],'q_N=p_N/(p_N-1)=R_N^2+1' in c['holder_pair'],'Hilbert-valued third chaos' in c['gradient_chaos'],'=4' in c['gradient_chaos'],'(2q_N-1)^3' in c['hypercontractivity'],'O(R_N^6)' in c['hypercontractivity'],'=O(R_N^6)' in c['weighted_gradient'],'=O(R_N^8)' in c['normalized_malliavin_cost'],'omega_max(N)=O(N)' in c['free_form_cost'],'O(N R_N^8)' in c['free_form_cost'],'N^(1/14)/(1+log N)' in c['dominance'],'N^(-1)' in c['dominance'],q['weighted_malliavin_cost_proved'],q['free_cost_lower_order_than_interaction_gain'],not q['pointwise_gradient_bound_claimed'],not q['sharp_weighted_cost_exponent_claimed'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('chain',lambda d:d['weighted_cost'].update(chain_rule='unknown')),('boundary',lambda d:d['weighted_cost'].update(cutoff_boundary='uncontrolled')),('p',lambda d:d['weighted_cost'].update(holder_pair='p=2')),('q',lambda d:d['weighted_cost'].update(holder_pair='p_N=1+R_N^(-2)')),('chaos',lambda d:d['weighted_cost'].update(gradient_chaos='untyped')),('mean',lambda d:d['weighted_cost'].update(gradient_chaos='Hilbert-valued third chaos')),('hypercontractivity',lambda d:d['weighted_cost'].update(hypercontractivity='unknown')),('weighted',lambda d:d['weighted_cost'].update(weighted_gradient='exponential')),('Malliavin',lambda d:d['weighted_cost'].update(normalized_malliavin_cost='unknown')),('free',lambda d:d['weighted_cost'].update(free_form_cost='unknown')),('dominance',lambda d:d['weighted_cost'].update(dominance='none')),('deny cost',lambda d:d['decision'].update(weighted_malliavin_cost_proved=False)),('deny lower',lambda d:d['decision'].update(free_cost_lower_order_than_interaction_gain=False)),('claim pointwise',lambda d:d['decision'].update(pointwise_gradient_bound_claimed=True)),('claim sharp',lambda d:d['decision'].update(sharp_weighted_cost_exponent_claimed=True)),('status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
