#!/usr/bin/env python3
"""Hostile mutations for K1516."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1516-polynomial-wick-recentering-boundary.json').read_text())
def valid(d):
 b,q=d['variational_boundary'],d['decision'];return all([d['claim_id']=='K1516','N^(1/14)/(1+log N)' in b['selected_radius'],'-(1-o(1))g sigma_N R_N' in b['energy_upper_bound'],'beta<1/14' in b['power_family'],'A>0' in b['power_family'],'liminf' in b['necessary_recentering'],'>=1' in b['necessary_recentering'],'limsup' in b['excluded_window'],'<1' in b['excluded_window'],'fixed Gaussian unit ball' in b['mosco_failure'],'may be zero' in b['mosco_failure'],'harmonic BRST vacuum' in b['brst_transfer'],q['polynomial_variational_descent_proved'],q['sqrt_log_boundary_superseded'],q['polynomial_recentering_necessity_proved'],q['fixed_gaussian_mosco_window_excluded'],q['harmonic_brst_window_excluded'],not q['one_fourteenth_endpoint_or_optimal_scale_proved'],not q['matching_many_chaos_lower_bound_proved'],not q['ground_energy_recentered_limit_constructed'],not q['mosco_recovery_proved'],not q['changed_representation_excluded'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('radius',lambda d:d['variational_boundary'].update(selected_radius='N')),('energy',lambda d:d['variational_boundary'].update(energy_upper_bound='unknown')),('beta',lambda d:d['variational_boundary'].update(power_family='beta=1/14')),('coefficient',lambda d:d['variational_boundary'].update(power_family='beta<1/14')),('necessary',lambda d:d['variational_boundary'].update(necessary_recentering='none')),('excluded',lambda d:d['variational_boundary'].update(excluded_window='none')),('Mosco',lambda d:d['variational_boundary'].update(mosco_failure='strong convergence')),('BRST',lambda d:d['variational_boundary'].update(brst_transfer='unknown')),('deny descent',lambda d:d['decision'].update(polynomial_variational_descent_proved=False)),('deny superseded',lambda d:d['decision'].update(sqrt_log_boundary_superseded=False)),('deny recenter',lambda d:d['decision'].update(polynomial_recentering_necessity_proved=False)),('claim endpoint',lambda d:d['decision'].update(one_fourteenth_endpoint_or_optimal_scale_proved=True)),('claim lower',lambda d:d['decision'].update(matching_many_chaos_lower_bound_proved=True)),('claim limit',lambda d:d['decision'].update(ground_energy_recentered_limit_constructed=True)),('claim recovery',lambda d:d['decision'].update(mosco_recovery_proved=True)),('close changed rep',lambda d:d['decision'].update(changed_representation_excluded=True)),('status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
