#!/usr/bin/env python3
"""Hostile mutations for K1512."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1512-total-variation-bump-admission.json').read_text())
def valid(d):
 c,q=d['bridge_census'],d['decision'];return all([d['claim_id']=='K1512',c['row_count']==sum(c[x] for x in ('satisfied_count','conditional_count','excluded_count','missing_count')),c['row_count']==212,c['satisfied_count']==135,c['conditional_count']==10,c['excluded_count']==63,c['missing_count']==4,len(c['new_satisfied_rows'])==6,len(c['new_excluded_rows'])==2,len(c['missing_rows'])==4,q['total_variation_rate_proved'],q['rare_bump_transferred'],q['sqrt_log_variational_rate_proved'],q['sqrt_log_recentering_window_excluded'],not q['optimal_rate_or_constant_proved'],not q['many_chaos_ground_energy_lower_bound_constructed'],not q['ground_energy_recentered_limit_constructed'],not q['full_spacetime_pde_repair_constructed'],not q['source_selected_reduction_constructed'],not q['k1145_k1150_candidate_counts_move'],not q['protected_status_change'],'SOURCE_REGISTER_UNCHANGED' in d['source_and_ledger_effect']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('rows',lambda d:d['bridge_census'].update(row_count=211)),('satisfied',lambda d:d['bridge_census'].update(satisfied_count=134)),('conditional',lambda d:d['bridge_census'].update(conditional_count=11)),('excluded',lambda d:d['bridge_census'].update(excluded_count=62)),('missing',lambda d:d['bridge_census'].update(missing_count=5)),('new satisfied',lambda d:d['bridge_census'].update(new_satisfied_rows=[])),('new excluded',lambda d:d['bridge_census'].update(new_excluded_rows=[])),('missing rows',lambda d:d['bridge_census'].update(missing_rows=[])),('deny TV',lambda d:d['decision'].update(total_variation_rate_proved=False)),('deny bump',lambda d:d['decision'].update(rare_bump_transferred=False)),('deny rate',lambda d:d['decision'].update(sqrt_log_variational_rate_proved=False)),('claim optimal',lambda d:d['decision'].update(optimal_rate_or_constant_proved=True)),('claim lower',lambda d:d['decision'].update(many_chaos_ground_energy_lower_bound_constructed=True)),('claim limit',lambda d:d['decision'].update(ground_energy_recentered_limit_constructed=True)),('claim PDE',lambda d:d['decision'].update(full_spacetime_pde_repair_constructed=True)),('claim source',lambda d:d['decision'].update(source_selected_reduction_constructed=True)),('move counts',lambda d:d['decision'].update(k1145_k1150_candidate_counts_move=True)),('move status',lambda d:d['decision'].update(protected_status_change=True)),('move source',lambda d:d.update(source_and_ledger_effect='changed'))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
