#!/usr/bin/env python3
"""Hostile mutations for K1514."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1514-truncated-exponential-tilt-transfer.json').read_text())
def valid(d):
 t,q=d['tilt_trial'],d['decision'];return all([d['claim_id']=='K1514','smooth chi' in t['profile'],'[-3/2,-1/2]' in t['profile'],'[-2,0]' in t['profile'],'exp(-R_N x/2-R_N^2/4)' in t['profile'],'N(-R_N,1)' in t['gaussian_identity'],'Integration by parts' in t['stieltjes_transfer'],'P(X_N<=-z)' in t['stieltjes_transfer'],'1+o(1)' in t['cutoff_norm'],'-(1+o(1))R_N' in t['multiplication_quotient'],'p_N=1+R_N^(-2)' in t['near_one_holder_moment'],'=O(1)' in t['near_one_holder_moment'],q['truncated_exponential_tilt_transferred'],q['negative_polynomial_multiplication_quotient_proved'],q['near_one_holder_norm_controlled'],not q['untruncated_laplace_transform_transferred'],not q['density_ratio_or_pointwise_likelihood_proved'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('smoothness',lambda d:d['tilt_trial'].update(profile='indicator')),('plateau',lambda d:d['tilt_trial'].update(profile='smooth chi support [-2,0] exp(-R_N x/2-R_N^2/4)')),('support',lambda d:d['tilt_trial'].update(profile='smooth chi [-3/2,-1/2] exp(-R_N x/2-R_N^2/4)')),('tilt',lambda d:d['tilt_trial'].update(profile='smooth chi [-3/2,-1/2] [-2,0]')),('likelihood',lambda d:d['tilt_trial'].update(gaussian_identity='unknown')),('transfer',lambda d:d['tilt_trial'].update(stieltjes_transfer='density convergence')),('norm',lambda d:d['tilt_trial'].update(cutoff_norm='unknown')),('quotient',lambda d:d['tilt_trial'].update(multiplication_quotient='fixed')),('holder exponent',lambda d:d['tilt_trial'].update(near_one_holder_moment='p=2')),('holder bound',lambda d:d['tilt_trial'].update(near_one_holder_moment='p_N=1+R_N^(-2), divergent')),('deny tilt',lambda d:d['decision'].update(truncated_exponential_tilt_transferred=False)),('deny quotient',lambda d:d['decision'].update(negative_polynomial_multiplication_quotient_proved=False)),('deny holder',lambda d:d['decision'].update(near_one_holder_norm_controlled=False)),('claim untruncated',lambda d:d['decision'].update(untruncated_laplace_transform_transferred=True)),('claim density',lambda d:d['decision'].update(density_ratio_or_pointwise_likelihood_proved=True)),('status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
