#!/usr/bin/env python3
"""Hostile mutations for K1513."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=json.loads((ROOT/'lab/process/k1513-fourth-chaos-moderate-deviation-window.json').read_text())
def valid(d):
 t,s,q=d['literature_theorem'],d['selected_scale'],d['decision'];return all([d['claim_id']=='K1513','Theorem 5(i)' in t['citation'],'10.1016/j.jfa.2016.01.002' in t['citation'],'sqrt(4!) g_N' in t['normalization'],'||h_N||=1' in t['normalization'],'1<=r<=3' in t['contraction_modulus'],'N^(-3/2)' in t['contraction_modulus'],'3/7' in t['graph_exponent'],'N^(9/14)' in t['deviation_parameter'],'P(X_N<=-z)' in t['tail_ratio'],'1+z^3' in t['tail_ratio'],'R_N=o(Delta_N^(1/9))' in t['uniform_window'],'N^(1/14)/(1+log N)' in s['radius'],'beta<1/14' in s['power_family'],q['relative_left_tail_window_proved'],q['polynomial_moderate_deviation_radius_available'],not q['density_ratio_or_local_limit_proved'],not q['endpoint_one_fourteenth_optimal'],not q['protected_status_change']])
mut=[('claim',lambda d:d.update(claim_id='bad')),('citation',lambda d:d['literature_theorem'].update(citation='unknown')),('normalization',lambda d:d['literature_theorem'].update(normalization='raw')),('contractions',lambda d:d['literature_theorem'].update(contraction_modulus='unknown')),('alpha',lambda d:d['literature_theorem'].update(graph_exponent='1')),('Delta',lambda d:d['literature_theorem'].update(deviation_parameter='logarithmic')),('tail side',lambda d:d['literature_theorem'].update(tail_ratio='right only')),('tail error',lambda d:d['literature_theorem'].update(tail_ratio='P(X_N<=-z)')),('window',lambda d:d['literature_theorem'].update(uniform_window='endpoint')),('radius',lambda d:d['selected_scale'].update(radius='N')),('family',lambda d:d['selected_scale'].update(power_family='beta=1')),('deny tail',lambda d:d['decision'].update(relative_left_tail_window_proved=False)),('deny polynomial',lambda d:d['decision'].update(polynomial_moderate_deviation_radius_available=False)),('claim density',lambda d:d['decision'].update(density_ratio_or_local_limit_proved=True)),('claim endpoint',lambda d:d['decision'].update(endpoint_one_fourteenth_optimal=True)),('status',lambda d:d['decision'].update(protected_status_change=True))]
for i,(label,f) in enumerate(mut,1):x=copy.deepcopy(D);f(x);assert not valid(x),label;print(f'PASS {i:02d}: rejected {label}')
print(f'RESULT: PASS {len(mut)}/{len(mut)}')
