#!/usr/bin/env python3
"""Independent controls and hostile mutations for K418."""

from __future__ import annotations

import argparse
import copy
import importlib.util
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOLVER = Path(__file__).with_name("k418_k77_observer_stabilizer_intersection_obstruction.py")
MANIFEST = ROOT / "lab/process/k418-k77-observer-stabilizer-intersection-obstruction.json"


def load_solver():
    spec = importlib.util.spec_from_file_location("k418_solver", SOLVER)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load K418 solver")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


K418 = load_solver()


def checks(data: dict) -> list[tuple[str, bool]]:
    result = K418.demo()
    intersection = result["intersection"]
    branching = result["spin2_branching"]
    observed = data.get("observer_stabilizer_intersection", {})
    manifest_branching = data.get("spin2_branching", {})
    decision = data.get("decision", {})
    boundaries = data.get("boundaries", {})
    return [
        ("schema", result["schema_version"] == "1.0" and data.get("schema_version") == "1.0"),
        ("classification", data.get("classification") == "BRIDGE_OR_SEMANTIC_BOUNDARY"),
        ("direction", data.get("direction") == "observed_to_native"),
        ("observer axes", result["observer"]["adapted_lorentz_axes"] == [0, 7, 8, 9]),
        ("observer generators", result["observer"]["spatial_rotation_generators"] == [[7, 8], [7, 9], [8, 9]]),
        ("stabilizer dimension", result["frozen_stabilizer"]["generator_count"] == 21),
        ("common generator", intersection["generators"] == [[7, 9]]),
        ("intersection dimension", intersection["dimension"] == 1 and observed.get("dimension") == 1),
        ("not diagonal SU2", intersection["equals_k416_all_factor_diagonal_su2"] is False),
        ("manifest group", observed.get("group") == "Spin(2) generated by the (7,9) plane rotation"),
        ("source branching", branching["source"] == {"real_trivial": 56, "real_weight_2_plane": 7}),
        ("target branching", branching["target"] == {"real_weight_1_plane": 64}),
        ("source dimension", branching["source_dimension"] == 70 and manifest_branching.get("source_dimension") == 70),
        ("target dimension", branching["target_dimension"] == 128 and manifest_branching.get("target_dimension") == 128),
        ("no common irreps", branching["common_irreducibles"] == []),
        ("Hom zero", branching["equivariant_hom_rank"] == 0 and manifest_branching.get("Hom_rank") == 0),
        ("no observer repair", decision.get("observer_selected_common_symmetry_repairs_k416_route") is False),
        ("frozen obstruction", decision.get("tested_full_spinor_trace_map_obstructed_at_frozen_background") is True),
        ("principal fence", boundaries.get("observer_selection_global_or_action_owned") is False),
        ("quotient fence", boundaries.get("quotient_or_target_differential_tested") is False),
        ("Green fence", boundaries.get("green_domain_solved") is False),
        ("ledger fence", boundaries.get("source_ledger_canon_paper_public_or_physical_effect") is False),
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    data = json.loads(MANIFEST.read_text())
    baseline = checks(data)
    failed = [name for name, ok in baseline if not ok]
    if failed:
        print(f"FAIL baseline {len(baseline)-len(failed)}/{len(baseline)}: {failed}")
        return 1
    if not args.selftest:
        print(f"PASS {len(baseline)}/{len(baseline)} K418 controls")
        return 0
    mutations = [
        lambda d: d.__setitem__("classification", "SOURCE_NATIVE"),
        lambda d: d.__setitem__("direction", "native_to_observed"),
        lambda d: d["observer_stabilizer_intersection"].__setitem__("dimension", 3),
        lambda d: d["observer_stabilizer_intersection"].__setitem__("group", "diagonal SU(2)"),
        lambda d: d["spin2_branching"].__setitem__("source_dimension", 69),
        lambda d: d["spin2_branching"].__setitem__("target_dimension", 127),
        lambda d: d["spin2_branching"].__setitem__("Hom_rank", 1),
        lambda d: d["decision"].__setitem__("observer_selected_common_symmetry_repairs_k416_route", True),
        lambda d: d["decision"].__setitem__("tested_full_spinor_trace_map_obstructed_at_frozen_background", False),
        lambda d: d["boundaries"].__setitem__("observer_selection_global_or_action_owned", True),
        lambda d: d["boundaries"].__setitem__("quotient_or_target_differential_tested", True),
        lambda d: d["boundaries"].__setitem__("green_domain_solved", True),
        lambda d: d["boundaries"].__setitem__("source_ledger_canon_paper_public_or_physical_effect", True),
    ]
    caught = 0
    for mutate in mutations:
        trial = copy.deepcopy(data)
        mutate(trial)
        caught += int(any(not ok for _, ok in checks(trial)))
    if caught != len(mutations):
        print(f"FAIL hostile selftest caught {caught}/{len(mutations)}")
        return 1
    print(f"PASS hostile selftest caught {caught}/{len(mutations)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
