#!/usr/bin/env python3
"""K421 central-character obstruction for quotient and Green repairs."""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path
from typing import Any


K420_PATH = Path(__file__).with_name("k420_k77_coordinate_orbit_observer_stabilizer_census.py")


def load_k420():
    spec = importlib.util.spec_from_file_location("k420_for_k421", K420_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load K420")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


K420 = load_k420()


def demo() -> dict[str, Any]:
    census = K420.demo()["census"]
    source_character = 1
    target_character = -1
    characteristic = 0
    intertwiner_scalar_equation = target_character - source_character
    hom_zero = intertwiner_scalar_equation != 0 and characteristic != 2
    return {
        "schema_version": "1.0",
        "classification": "BRIDGE_OR_SEMANTIC_BOUNDARY",
        "direction": "observed_to_native",
        "scope": {
            "coordinate_backgrounds": census["nontrivial_common_symmetry_backgrounds"],
            "common_groups": ["Spin(2)", "Spin(3)"],
            "source": "frozen rank-70 orbit source generated by vectors and trivial modules",
            "target": "tested full real K77 spinor and equivariant complexes built only from it",
        },
        "central_character_argument": {
            "source_character": source_character,
            "target_character": target_character,
            "intertwiner_equation": "F z_source = z_target F",
            "reduced_scalar_equation": "F = -F",
            "field_characteristic": characteristic,
            "equivariant_hom_zero": hom_zero,
        },
        "exact_functors": {
            "equivariant_kernel_preserves_target_character": True,
            "equivariant_image_preserves_target_character": True,
            "equivariant_quotient_preserves_target_character": True,
            "equivariant_cohomology_preserves_target_character": True,
            "green_compatible_maps_subset_of_equivariant_maps": True,
        },
        "decision": {
            "same_target_equivariant_differential_repairs_map": False,
            "same_target_equivariant_quotient_repairs_map": False,
            "green_pairing_or_adjointness_repairs_map": False,
            "nonzero_repair_requires": [
                "a target complex with an even-central-character cohomology summand",
                "or symmetry breaking that removes the retained common central element",
                "or a non-equivariant construction with separately justified action ownership",
            ],
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--demo", action="store_true")
    args = parser.parse_args()
    if not args.demo:
        parser.error("use --demo")
    print(json.dumps(demo(), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
