#!/usr/bin/env python3
"""K492 exhaustive M-orthogonal contrast basis on a Neumann cyclic slice."""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path
from typing import Any, Sequence


ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/"lab/process/k492-k162-cyclic-m-orthogonal-basis.json"


class CertificateError(ValueError): pass
def q(x:Any)->Fraction:
    try: return x if isinstance(x,Fraction) else Fraction(x)
    except Exception as exc: raise CertificateError("invalid rational") from exc
def qstr(x:Fraction)->str: return str(x.numerator) if x.denominator==1 else f"{x.numerator}/{x.denominator}"


def tail(values:Sequence[Fraction])->list[Fraction]:
    out=[Fraction() for _ in values]; s=Fraction()
    for i in range(len(values)-1,-1,-1): s+=values[i]; out[i]=s
    return out


def matmul(a,b): return [[sum((a[i][k]*b[k][j] for k in range(len(b))),Fraction()) for j in range(len(b[0]))] for i in range(len(a))]
def transpose(a): return [list(r) for r in zip(*a)]


def contrast_certificate(masses:Sequence[Any])->dict[str,Any]:
    a=list(map(q,masses))
    if len(a)<2 or a[0]!=1 or any(x<=0 for x in a): raise CertificateError("positive normalized masses of length at least two required")
    b=tail(a); n=len(a)
    gram=[[b[max(i,j)] for j in range(n)] for i in range(n)]
    # columns are e0 followed by u_j=e_(j-1)-(B_(j-1)/B_j)e_j.
    cols=[[Fraction() for _ in range(n)] for _ in range(n)]
    cols[0][0]=1
    for j in range(1,n): cols[j-1][j]=1; cols[j][j]=-b[j-1]/b[j]
    transformed=matmul(transpose(cols),matmul(gram,cols))
    expected=[b[0]]+[a[j-1]*b[j-1]/b[j] for j in range(1,n)]
    diagonal=all(transformed[i][j]==(expected[i] if i==j else 0) for i in range(n) for j in range(n))
    return {
        "word_masses":list(map(qstr,a)), "tail_masses":list(map(qstr,b)),
        "basis":["e0"]+[f"e{j-1}-({qstr(b[j-1]/b[j])})e{j}" for j in range(1,n)],
        "transformed_gram":[[qstr(x) for x in r] for r in transformed],
        "expected_norms":list(map(qstr,expected)), "diagonal_verified":diagonal,
        "k489_relation":f"u1=-({qstr(b[0]/b[1])})*[e1-({qstr(b[1]/b[0])})e0]",
        "complement_dimension":n-1,
    }


def build()->dict[str,Any]:
    control=contrast_certificate([1,Fraction(1,4),Fraction(1,16),Fraction(1,64)])
    return {
      "schema_version":"1.0","result_id":"K492-K162-CYCLIC-M-ORTHOGONAL-BASIS","created":"2026-09-25",
      "status":"working_draft_verified","classification":"INTERNAL_STRUCTURAL_ONLY","direction":"observed_to_native","target_claim":"NONE-NOT-A-KILL",
      "scope":"The complete Neumann cyclic closure generated by one K162 zero-bath seed; vectors outside that cyclic closure are excluded.",
      "gu_typed_objects":{"result":"weighted Neumann contrast basis MAP-TYPE=projection","carrier":"closure span{G^n phi}","pairing":"M=S* S","target":"cyclic part of the K473 trial complement"},
      "exact_theorem":{
        "tails":"B_j=sum_(n>=j)a_n","basis":"u_j=e_(j-1)-(B_(j-1)/B_j)e_j, j>=1",
        "physical_image":"S u_j=v_(j-1)-(a_(j-1)/B_j)sum_(n>=j)v_n",
        "orthogonality":"<e0,M u_j>=0 and <u_j,M u_k>=0 for j!=k",
        "norm":"<u_j,M u_j>=a_(j-1)B_(j-1)/B_j",
        "finite_exhaustiveness":"{u_1,...,u_N} is a basis of e0^perp_M in span{e0,...,eN}",
        "infinite_exhaustiveness":"finite-support limits make {u_j:j>=1} total in the cyclic e0^perp_M closure",
        "k489":"K489 t=e1-(B1/B0)e0=-(B1/B0)u1",
      },
      "exact_control":control,
      "decision":{"one_corrected_line_extended_to_exhaustive_cyclic_basis":True,"complete_K162_complement_constructed":False,"next_exact_input":"Evaluate the combined form matrix on these contrasts and separately bound the M-orthogonal noncyclic K162 remainder."},
      "source_and_ledger_effect":"none",
      "claim_ceiling":"Exact exhaustive M-orthogonal basis for one native Neumann cyclic closure. It is not the complete K162 charge-sector complement and supplies no combined floor, K473 beta, K152 interval or physical conclusion."
    }


def main()->int:
    p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--demo",action="store_true");a=p.parse_args();d=build()
    if a.write: OUTPUT.write_text(json.dumps(d,indent=2,sort_keys=True)+"\n")
    if a.demo or not a.write: print(json.dumps(d,indent=2,sort_keys=True))
    return 0
if __name__=="__main__": raise SystemExit(main())
