#!/usr/bin/env python3
"""K610 closure of the available K590-by-K438 factorwise carrier algebra."""

from __future__ import annotations

import argparse
import json
from itertools import product
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "lab/process/k610-k77-factorwise-algebra-selector-obstruction.json"


def strict(path: str) -> dict[str, Any]:
    return json.loads((ROOT / path).read_text())


def exact_control(block_ranks: list[int]) -> dict[str, Any]:
    ranks = sorted({sum(rank for keep, rank in zip(mask, block_ranks) if keep) for mask in product((0, 1), repeat=len(block_ranks))})
    nonzero = [rank for rank in ranks if rank]
    base_ranks = [1, 2, 3]
    factorwise_ranks = sorted({base * carrier for base in base_ranks for carrier in nonzero})
    return {
        "spectral_subset_ranks": ranks,
        "minimum_nonzero_carrier_rank": min(nonzero),
        "toy_base_ranks": base_ranks,
        "toy_factorwise_nonzero_ranks": factorwise_ranks,
        "minimum_nonzero_factorwise_rank": min(factorwise_ranks),
        "rank_one_absent": 1 not in factorwise_ranks,
    }


def build() -> dict[str, Any]:
    k590 = strict("lab/process/k590-k77-corrected-carrier-completion-squares.json")
    k607 = strict("lab/process/k607-k77-action-symbol-stabilizer-refinement.json")
    block_ranks = k607["actual_action_symbol_replay"]["spectral_multiplicities"]
    control = exact_control(block_ranks)
    return {
        "schema_version": "1.0",
        "result_id": "K610-K77-FACTORWISE-ALGEBRA-SELECTOR-OBSTRUCTION",
        "created": "2026-09-28",
        "status": "working_draft_verified",
        "classification": "BRIDGE_OR_SEMANTIC_BOUNDARY",
        "direction": "observed_to_native",
        "target_claim": "NONE-NOT-A-KILL",
        "scope": "Closure of all carrier-factorwise maps generated by K590's base arrows, K438's action symbol A, K439's projector, adjoints, sums, compositions and base-only contractions.",
        "gu_typed_objects": {
            "base_complex": "K589/K590's exact H^21 to Q^91 to M^70 coefficient complex",
            "carrier_algebra": "R[A] on K438's rank-512 corrected carrier, including K439 Pi as a cubic polynomial",
            "allowed_operations": "finite sums, compositions, adjoints, tensoring with base maps and contractions confined to base factors",
            "result": "factorwise-algebra no-selector theorem MAP-TYPE=tensor-rank obstruction",
            "target": "K598's action-owned initial carrier vector, covector, Riesz return or rank-one packet",
        },
        "closure_theorem": {
            "carrier_closure": "Every carrier factor produced by the allowed operations remains p(A) in the four-idempotent algebra R[A].",
            "factorwise_closure": "Every surviving map is a finite sum of base maps tensor p(A); base-only contraction cannot create a carrier vector or covector.",
            "spectral_block_ranks": block_ranks,
            "possible_carrier_idempotent_ranks": control["spectral_subset_ranks"],
            "minimum_nonzero_carrier_idempotent_rank": control["minimum_nonzero_carrier_rank"],
            "rank_product_rule": "rank(B tensor p(A))=rank(B) rank(p(A)), so every nonzero simple factorwise term has rank at least 64.",
            "global_sign_rule": "The central -I_E fixes A, Pi, pairing and every p(A), while reversing vectors and covectors; hence no nonzero natural carrier vector or covector is selected.",
            "rank_one_packet_in_factorwise_closure": False,
            "nonfactorized_escape": "A genuinely field-dependent or inhomogeneous field-to-carrier/Riesz datum need not lie in this algebra and is not excluded.",
        },
        "K590_K607_reconciliation": {
            "K590_factorized_exact_complex_retracted": False,
            "K607_action_symbol_result_retracted": False,
            "full_available_factorwise_algebra_tested": True,
            "K598_actual_action_owned_packet_constructed": False,
            "base_homology_dimensions": k590["factorized_completion"]["homology_dimensions"],
        },
        "exact_controls": control,
        "decision": {
            "factorwise_algebra_selects_carrier_vector_or_covector": False,
            "factorwise_algebra_selects_rank_one_packet": False,
            "K598_released": False,
            "selected_source_action_rejected": False,
            "nonfactorized_action_data_remain_live": True,
            "next_exact_input": "Supply a named action-owned inhomogeneous field-to-carrier injection and its K441-compatible Riesz return, then apply K596/K598 and test total nilpotence/properness.",
        },
        "source_and_ledger_effect": "none",
        "claim_ceiling": "Exact closure obstruction for the currently available factorwise K590-by-K438 algebra. It excludes no genuinely nonfactorized inhomogeneous action datum and moves no full nonlinear BV/KT, source, ledger, canon, paper, public, novelty, prediction, confirmation or physical conclusion.",
    }


def validate(payload: dict[str, Any]) -> None:
    theorem, rec, control, decision = payload["closure_theorem"], payload["K590_K607_reconciliation"], payload["exact_controls"], payload["decision"]
    assert theorem["spectral_block_ranks"] == [192, 192, 64, 64]
    assert theorem["minimum_nonzero_carrier_idempotent_rank"] == 64 and not theorem["rank_one_packet_in_factorwise_closure"]
    assert rec["full_available_factorwise_algebra_tested"] and not rec["K590_factorized_exact_complex_retracted"] and not rec["K607_action_symbol_result_retracted"]
    assert control["minimum_nonzero_carrier_rank"] == 64 and control["minimum_nonzero_factorwise_rank"] == 64 and control["rank_one_absent"]
    assert not decision["factorwise_algebra_selects_carrier_vector_or_covector"] and not decision["factorwise_algebra_selects_rank_one_packet"] and not decision["K598_released"]
    assert not decision["selected_source_action_rejected"] and decision["nonfactorized_action_data_remain_live"]


def main() -> int:
    parser = argparse.ArgumentParser(); parser.add_argument("--write", action="store_true"); args = parser.parse_args()
    payload = build(); validate(payload); rendered = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.write: OUTPUT.write_text(rendered)
    else: print(rendered, end="")
    return 0


if __name__ == "__main__": raise SystemExit(main())
