#!/usr/bin/env sage-python
"""K619 common K438 action module generated by the K614 and K617 seeds."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from sage.all import block_matrix

from k435_k77_full_h640_observed_map import PRIMES
from k617_k77_moving_varpi_corrected_carrier_descent import build_prime_packet


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "lab/process/k619-k77-zero-form-moving-graph-common-action-module.json"


def strict(relative: str) -> dict:
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


def joined_rank(field, columns) -> int:
    return int(block_matrix(field, 1, len(columns), [columns], sparse=True).rank())


def build_prime_module(prime: int, keep_matrices: bool = False) -> dict:
    packet = build_prime_packet(prime, keep_matrices=True)
    field = packet["field"]
    action = packet["compressed"]["compressed"]
    graph = packet["corrected_graph"]
    zero_seed = packet["zero_seed"]
    graph_powers = []
    zero_powers = []
    graph_current = graph
    zero_current = zero_seed
    rows = []
    for depth in range(1, 6):
        graph_powers.append(graph_current)
        zero_powers.append(zero_current)
        graph_rank = joined_rank(field, graph_powers)
        zero_rank = joined_rank(field, zero_powers)
        joined = joined_rank(field, graph_powers + zero_powers)
        rows.append({
            "depth": depth,
            "graph_hull_rank": graph_rank,
            "zero_form_hull_rank": zero_rank,
            "joined_hull_rank": joined,
            "intersection_rank": graph_rank + zero_rank - joined,
        })
        graph_current = action * graph_current
        zero_current = action * zero_current

    final_graph = block_matrix(field, 1, len(graph_powers), [graph_powers], sparse=True)
    final_zero = block_matrix(field, 1, len(zero_powers), [zero_powers], sparse=True)
    checks = {
        "seeds_are_disjoint": rows[0] == {
            "depth": 1,
            "graph_hull_rank": 128,
            "zero_form_hull_rank": 128,
            "joined_hull_rank": 256,
            "intersection_rank": 0,
        },
        "first_action_extensions_intersect_in_rank_128": rows[1]["intersection_rank"] == 128,
        "both_filtrations_reach_rank_384_at_depth_3": (
            rows[2]["graph_hull_rank"] == rows[2]["zero_form_hull_rank"] == 384
        ),
        "depth_3_hulls_are_equal": rows[2]["joined_hull_rank"] == 384,
        "both_filtrations_stabilize": all(
            row["graph_hull_rank"] == row["zero_form_hull_rank"] == 384
            and row["joined_hull_rank"] == row["intersection_rank"] == 384
            for row in rows[2:]
        ),
    }
    if not all(checks.values()):
        raise AssertionError({"prime": prime, "rows": rows, "checks": checks})
    public = {"prime": prime, "filtration_rows": rows, "checks": checks}
    if keep_matrices:
        public.update({
            "field": field,
            "action": action,
            "graph": graph,
            "zero_seed": zero_seed,
            "common_graph_hull": final_graph,
            "common_zero_hull": final_zero,
            "compressed": packet["compressed"],
            "split": packet["split"],
        })
    return public


def build() -> dict:
    k614 = strict("lab/process/k614-k77-zero-form-corrected-carrier-injection.json")
    k615 = strict("lab/process/k615-k77-zero-form-stationarity-obstruction.json")
    k617 = strict("lab/process/k617-k77-moving-varpi-corrected-carrier-descent.json")
    k618 = strict("lab/process/k618-k77-moving-varpi-corrected-action-hull.json")
    southeast = strict("lab/process/selected-k77-unrestricted-southeast-bv-kernel.json")
    coupled_bv = strict("lab/process/selected-k77-coupled-gauge-noether-bv.json")
    assert k614["injection_theorem"]["canonical_zero_form_inclusion_rank"] == 128
    assert k615["fibrewise_stationarity_theorem"]["kernel_dimension"] == 0
    assert k617["descent_theorem"]["corrected_graph_intersection_K614_zero_seed_rank"] == 0
    assert k618["action_hull_theorem"]["minimal_action_hull_rank"] == 384
    assert southeast["full_field_ordinary_gauge_bv"].startswith("OPEN_DISTINCT")
    assert coupled_bv["minimal_brst"]["nilpotent_on_every_declared_field"]

    packets = [build_prime_module(prime) for prime in PRIMES]
    assert packets[0]["filtration_rows"] == packets[1]["filtration_rows"]
    rows = packets[0]["filtration_rows"]
    return {
        "schema_version": "1.0",
        "result_id": "K619-K77-ZERO-FORM-MOVING-GRAPH-COMMON-ACTION-MODULE",
        "created": "2026-09-29",
        "status": "working_draft_verified",
        "classification": "BRIDGE_OR_SEMANTIC_BOUNDARY",
        "direction": "observed_to_native",
        "target_claim": "NONE-NOT-A-KILL",
        "scope": "Exact comparison of the K438 Krylov filtrations generated by K614's source-owned zero-form injection and K617's historically constructed moving-varpi corrected graph inside the same rank-512 corrected carrier.",
        "gu_comparator_routing": "GU-COMPARATOR-ROUTING — scope before inference. This artifact contains or borders a conventional particle-physics comparator. Any result about a standard Higgs/VEV, ordinary family index or net chirality, SO(10) `126` Majorana mechanism, anomaly selector, VEV-only breaking or familiar vector-mass route binds only that named model. It is not evidence for or against Weinstein's source-native mechanism without an explicit typed bridge. Read `lab/methods/source-native-comparator-routing.md` and follow its source-native pointers before reusing this result.",
        "gu_typed_objects": {
            "action": "K438 compressed frozen normal symbol A on the corrected rank-512 carrier",
            "source_owned_seed": "K614 canonical zero-form injection J0: Omega0(S)_128 -> E",
            "historical_seed": "K617 common corrected image X of the two displayed-southeast-zero moving-varpi Pin graphs",
            "filtrations": "span{J0,A J0,...} and span{X,A X,...} as image subspaces of E",
            "result": "common corrected action-module theorem MAP-TYPE=Krylov-subspace comparison",
            "target": "ownership of a stationary background, seed adapter, and mixed-Hessian bilinear coupling",
        },
        "cross_characteristic_packets": packets,
        "filtration_fingerprint": rows,
        "common_module_theorem": {
            "seed_ranks": {"zero_form": 128, "moving_graph": 128},
            "seed_intersection_rank": 0,
            "depth_2_hull_ranks": {"zero_form": 256, "moving_graph": 256},
            "depth_2_intersection_rank": 128,
            "depth_3_hull_ranks": {"zero_form": 384, "moving_graph": 384},
            "depth_3_join_rank": 384,
            "depth_3_intersection_rank": 384,
            "minimal_common_action_module_rank": 384,
            "filtrations_equal_from_depth_3": True,
            "corrected_carrier_complement_rank": 128,
        },
        "ownership_reconciliation": {
            "source_owns_zero_form_field_space": True,
            "source_selects_nonzero_zero_form_background": False,
            "historical_moving_graph_is_source_selected": False,
            "equality_of_generated_subspaces_identifies_seed_maps": False,
            "common_module_is_stationary_solution_space": False,
            "common_module_supplies_mixed_hessian_coupling": False,
            "unrestricted_southeast_route_already_completed": True,
            "local_full_field_ordinary_gauge_bv_already_completed": True,
        },
        "decision": {
            "K614_zero_form_injection_retracted": False,
            "K615_stationarity_obstruction_retracted": False,
            "K617_nontrivial_descent_retracted": False,
            "K618_action_hull_retracted": False,
            "two_disjoint_seeds_generate_same_A_module": True,
            "selected_source_action_rejected": False,
            "actual_K596_K598_packet_released": False,
            "next_exact_input": "Test whether the four-root K438 functional calculus can project onto the common rank-384 module or map J0 to X. Equality of orbit spans alone does not provide either selection or transport.",
        },
        "ledger_no_change_reason": "The exact result compares two existing conditional corrected-carrier constructions below action-owned stationary, BV-reduced, or observable altitude. SC-ACT-01/02 and SC-CHI-01/51 keep their source polarity and every v0.263 ledger row keeps its verdict, reason, distance, trigger, and evidence.",
        "source_and_ledger_effect": "none",
        "preflight_bookend": {
            "route_comparison": "Before constructing new moving nonlinear data, compare the already-owned source zero-form and historical moving-graph seeds under the same exact corrected action.",
            "retrieval_collision_result": "The unrestricted southeast and local full-field ordinary-gauge BV successors named by K618 already exist as v0.163--v0.165; no predecessor compares the K614 and K617 Krylov filtrations.",
            "strongest_alternative": "A genuine moving mixed Hessian and common BV/Green domain would address action ownership directly, but those coefficients and a nonzero stationary background are not currently serialized.",
        },
        "postflight_bookend": {
            "strongest_overclaim": "Calling equality of generated subspaces equality of seed maps, a source-selected background, or an action-owned bilinear coupling.",
            "strongest_contrary_construction": "The two seed images are disjoint at depth one despite producing the same rank-384 module at depth three.",
            "weakest_reproducibility_seam": "The equality is certified by mutual inclusion through equal ranks at two good characteristics; no characteristic-zero seed isomorphism is claimed.",
        },
        "claim_ceiling": "Exact cross-characteristic action-module comparison: K614's source-owned zero-form seed and K617's historically constructed moving-graph seed are disjoint rank-128 subspaces, their depth-two K438 hulls intersect in rank 128, and their depth-three Krylov hulls are the same rank-384 subspace of the corrected rank-512 carrier. This equality does not identify the seed maps, select a nonzero stationary background, own a mixed-Hessian coupling, release K596/K598, or move source, ledger, canon, paper, public, novelty, prediction, confirmation, or physical conclusions.",
    }


def validate(payload: dict) -> None:
    theorem = payload["common_module_theorem"]
    ownership = payload["ownership_reconciliation"]
    decision = payload["decision"]
    assert len(payload["cross_characteristic_packets"]) == 2
    assert theorem["seed_intersection_rank"] == 0
    assert theorem["depth_2_intersection_rank"] == 128
    assert theorem["depth_3_join_rank"] == theorem["depth_3_intersection_rank"] == 384
    assert theorem["filtrations_equal_from_depth_3"]
    assert theorem["corrected_carrier_complement_rank"] == 128
    assert not ownership["equality_of_generated_subspaces_identifies_seed_maps"]
    assert not ownership["common_module_supplies_mixed_hessian_coupling"]
    assert decision["two_disjoint_seeds_generate_same_A_module"]
    assert not decision["actual_K596_K598_packet_released"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    payload = build()
    validate(payload)
    rendered = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
