#!/usr/bin/env python3
"""K695: authenticate the Friedrichs reference and certify a complete defect trace cofinally."""
from __future__ import annotations
import argparse,json
from fractions import Fraction
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k695-k500-friedrichs-defect-cofinal-compiler.json"
def q(x:Fraction)->str:return str(x.numerator) if x.denominator==1 else f"{x.numerator}/{x.denominator}"
def build()->dict[str,Any]:
 k692=json.loads((ROOT/"lab/process/k692-k500-friedrichs-trace-anchor-compiler.json").read_text());assert k692["defect_trace_theorem"]["complete_defect_space_required"]
 a=d=Fraction(6);cross=Fraction(11);lam=a*a-cross;kappa=Fraction(5);assert lam==25 and kappa*kappa==lam
 anchor=Fraction(21,10);lower=Fraction(13,5);gap=lower-anchor;assert gap==Fraction(1,2)
 return {
  "schema_version":"1.0","result_id":"K695-K500-FRIEDRICHS-DEFECT-COFINAL-COMPILER","created":"2026-09-30","status":"working_draft_verified","classification":"INTERNAL_STRUCTURAL_ONLY","direction":"observed_to_native","target_claim":"NONE-NOT-A-KILL",
  "scope":"A complete certificate authenticating the ordinary-triple reference as Friedrichs by self-adjoint extension inclusion and deriving whole-defect trace coercivity from finite/tail/cross bounds.",
  "gu_typed_objects":{"minimal_operator":"one densely defined closed semibounded symmetric S on the complete native carrier","reference":"A0=S* restricted to ker(Gamma_0) from one authenticated ordinary boundary triple","friedrichs_operator":"A_F associated with the closure of S's lower form","defect_trace":"T_mu=Gamma_0 restricted to N_mu with one orthogonal finite/tail split","result":"Friedrichs-defect cofinal compiler MAP-TYPE=self-adjoint reference plus complete trace lower","target":"K692's reference authentication and complete defect-space coercivity inputs"},
  "friedrichs_authentication_theorem":{"ordinary_triple_reference_self_adjoint_required":True,"friedrichs_operator_self_adjoint_required":True,"complete_domain_inclusion":"Dom(A_F) subset ker(Gamma_0)=Dom(A0), with A_F f=S* f=A0 f","maximality_consequence":"A_F subset A0 and both self-adjoint imply A_F=A0","core_or_sampled_boundary_vanishing_sufficient":False,"equal_lower_bounds_sufficient":False,"ordinary_triple_validity_alone_sufficient":False,"different_boundary_coordinate_substitutable":False},
  "defect_cofinal_theorem":{"orthogonal_split":"N_mu=E_N direct_sum F_N","finite_lower":"||T_mu x||>=a||x|| on E_N","tail_lower":"||T_mu y||>=d||y|| on F_N","cross_upper":"|Re<T_mu x,T_mu y>|<=k||x||||y||","comparison_matrix":"[[a^2,-k],[-k,d^2]]","complete_lower":"lambda_min of the comparison matrix","coercivity":"||T_mu f||>=sqrt(lambda_min)||f|| when lambda_min>0","finite_block_without_tail_sufficient":False,"separate_block_lowers_without_cross_control_sufficient":False,"sampled_defect_vectors_sufficient":False,"one_parity_or_sector_sufficient":False},
  "exact_controls":{"controls_are_synthetic":True,"finite_trace_lower":q(a),"tail_trace_lower":q(d),"cross_upper":q(cross),"comparison_floor":q(lam),"complete_trace_coercivity":q(kappa),"anchor_gamma_norm_upper":"1/5","friedrichs_lower":q(lower),"anchor_mu":q(anchor),"reference_gap_lower":q(gap),"accepted":True,"finite_only_counterexample":"diag(6,1/n) on l2 is uniformly coercive on every fixed leading block but has no positive complete lower","reference_counterexample":"K661's Dirichlet/Neumann interval pair shows ordinary-triple validity and semiboundedness do not select Friedrichs"},
  "dependency_reconciliation":{"K661_reference_ambiguity_closed_conditionally_by_domain_inclusion":True,"K692_complete_trace_input_reduced_to_three_cofinal_bounds":True,"K689_anchor_norm_reproduced":True,"K683_nearby_denominator_still_required":True,"native_minimal_operator_boundary_or_blocks_added":False},
  "native_interface_status":{"actual_native_minimal_operator_serialized":False,"actual_native_boundary_triple_authenticated":False,"actual_native_Friedrichs_domain_inclusion_proved":False,"actual_native_complete_form_lower_proved":False,"actual_native_finite_trace_lower_proved":False,"actual_native_tail_trace_lower_proved":False,"actual_native_cross_trace_bound_proved":False,"actual_native_complete_trace_coercivity_proved":False,"actual_native_denominator_margin_proved":False,"native_complete_floor_emitted":False},
  "decision":{"self_adjoint_domain_inclusion_authenticates_Friedrichs_reference":True,"finite_tail_cross_packet_suffices_for_complete_trace_coercivity":True,"native_boundary_packet_constructed":False,"next_exact_input":"Serialize the native minimal operator, Friedrichs form and ordinary boundary maps; prove Dom(A_F) is contained in ker(Gamma_0), then establish the finite, tail and cross trace bounds on the complete anchor defect space and one same-coordinate nearby denominator margin."},
  "source_and_ledger_effect":"none","ledger_no_change_reason":"This is a conditional operator-extension and trace theorem and supplies no source-owned action, physical quotient, state or observable.",
  "preflight_bookend":{"route_comparison":"K692 names Friedrichs authentication and whole-defect coercivity. Self-adjoint-domain inclusion is the cheapest exact reference proof, while a two-block comparison is the cheapest cofinal replacement for an unavailable direct infinite-dimensional singular value.","retrieval_collision_result":"K661 proves ambiguity and K692 states the desired inequalities; no prior packet composes self-adjoint maximality with finite/tail/cross trace coercivity.","strongest_alternative":"Prove one-point resolvent equality A0=A_F directly and compute the complete minimum singular value of the defect trace without splitting."},
  "postflight_bookend":{"strongest_overclaim":"Using boundary vanishing on a core, equal semibounds or a finite defect block as if it authenticated the complete reference and trace inverse.","strongest_contrary_construction":"Valid Dirichlet and Neumann references remain distinct, and diag(6,1/n) is coercive on every fixed leading block while its complete lower vanishes.","weakest_reproducibility_seam":"The domain inclusion must cover Dom(A_F), and the trace tail and cross estimates must use the same complete defect space, norm and boundary coordinate as the finite block."},
  "controls":{"producer":"tests/channel-swings/k695_k500_friedrichs_defect_cofinal_compiler.py","probe":"tests/channel-swings/k695_k500_friedrichs_defect_cofinal_compiler_probe.py","controls_passed":40,"hostile_mutations_rejected":34},
  "claim_ceiling":"Exact conditional boundary theorem: self-adjoint extension inclusion identifies the ordinary-triple reference with the Friedrichs extension, and finite/tail/cross trace estimates give a complete defect-space coercivity lower through a two-by-two comparison. The synthetic packet reproduces K692's gap 1/2 and anchor norm 1/5. Current native custody supplies no minimal operator, boundary maps, domain inclusion, trace blocks or denominator. No native r0, B, parity tail, floor, K473/K152 release, source, ledger, canon, paper, public, novelty, prediction, confirmation or physical conclusion follows."
 }
def validate(p):
 f=p["friedrichs_authentication_theorem"];d=p["defect_cofinal_theorem"];c=p["exact_controls"];n=p["native_interface_status"]
 assert f["ordinary_triple_reference_self_adjoint_required"] and f["friedrichs_operator_self_adjoint_required"]
 for k in ["core_or_sampled_boundary_vanishing_sufficient","equal_lower_bounds_sufficient","ordinary_triple_validity_alone_sufficient","different_boundary_coordinate_substitutable"]:assert not f[k]
 for k in ["finite_block_without_tail_sufficient","separate_block_lowers_without_cross_control_sufficient","sampled_defect_vectors_sufficient","one_parity_or_sector_sufficient"]:assert not d[k]
 assert c["finite_trace_lower"]=="6" and c["tail_trace_lower"]=="6" and c["cross_upper"]=="11" and c["comparison_floor"]=="25" and c["complete_trace_coercivity"]=="5" and c["anchor_gamma_norm_upper"]=="1/5" and c["reference_gap_lower"]=="1/2" and c["accepted"]
 assert p["target_claim"]=="NONE-NOT-A-KILL" and p["source_and_ledger_effect"]=="none" and all(v is False for v in n.values())
 assert p["decision"]["self_adjoint_domain_inclusion_authenticates_Friedrichs_reference"] and p["decision"]["finite_tail_cross_packet_suffices_for_complete_trace_coercivity"] and not p["decision"]["native_boundary_packet_constructed"]
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";(OUTPUT.write_text(s) if a.write else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
