#!/usr/bin/env python3
"""K757: compose the cyclic adapter with the current SC-ACT-06 carrier obstruction."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2]; OUTPUT=ROOT/"lab/process/k757-sc-act-06-cyclic-adapter-current-carrier-composition.json"
PATHS={name:ROOT/path for name,path in {"k743":"lab/process/k743-sc-act-06-residual-square-image-cap.json","k748":"lab/process/k748-sc-act-06-released-action-parent-inventory.json","k749":"lab/process/k749-sc-act-06-t0-full-symbol-obstruction.json","k755":"lab/process/k755-sc-act-06-cyclic-two-connection-square.json","k756":"lab/process/k756-sc-act-06-cyclic-adapter-linearization.json"}.items()}
def digest(path:Path)->str:return hashlib.sha256(path.read_bytes()).hexdigest()
def build()->dict[str,Any]:
    data={name:json.loads(path.read_text(encoding="utf-8")) for name,path in PATHS.items()}; k743,k748,k749,k755,k756=(data[x] for x in ("k743","k748","k749","k755","k756"))
    cases=[{"case":row["case"],"current_field_dimension":k743["exact_controls"]["field_dimension"],"current_image_cap_rank":row["total_coupled_image_cap_rank"],"current_gauge_rank":row["gauge_rank"],"current_middle_cohomology_lower_bound":row["bosonic_middle_cohomology_lower_bound"]} for row in k743["exact_controls"]["cases"]]
    return {"schema_version":"1.0","result_id":"K757-SC-ACT-06-CYCLIC-ADAPTER-CURRENT-CARRIER-COMPOSITION","created":"2026-10-01","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Composition of K755/K756's source-bounded cyclic reconstruction with the exact current one-connection K743/K749 obstruction; no doubled-carrier action or stationary background is supplied.","pinned_inputs":{name:{"path":str(path.relative_to(ROOT)),"sha256":digest(path)} for name,path in PATHS.items()},
      "gu_typed_objects":{"carrier":"K749's 229386-dimensional coupled metric/full-connection body carrier versus K756's unowned doubled connection carrier","pairing":"K743 allows every residual Q on the current response; cyclic doubled-carrier pairing remains unspecified","real_structure":"K749 coherent Euclidean principal comparison; cyclic reconstruction has no selected real continuation","grading":"current rank-four metric gauge and transpose redundancy versus a new common/relative connection split","action_owner":"released I1B/I2B current owner; cyclic two-connection parent remains source-silent and unowned","target":"whether any source-safe specialization of K755 adds a new principal image to K749"},
      "current_obstruction":{"cases":cases,"body_middle_bounds_preserved":[row["current_middle_cohomology_lower_bound"] for row in cases],"k749_full_symbol_block_obstruction":k749["composition_theorem"]["released_t0_full_symbol_family_elliptic"] is False},
      "specialization_composition":[
        {"name":"DIAGONAL_IDENTIFICATION","response":"zero","composable_with_current_carrier":True,"new_principal_image":False,"disposition":"CLOSED_ZERO_RESPONSE"},
        {"name":"FREEZE_B_BACKGROUND","response":"ordinary curvature differential plus zero-order identity","composable_with_current_carrier":True,"new_principal_image":False,"disposition":"NOT_AN_INDEPENDENT_ACTION_PARENT__NO_ESCAPE_FROM_CURRENT_RESPONSE_PROVED"},
        {"name":"INDEPENDENT_A_B","response":"relative connection derivative plus identity","composable_with_current_carrier":False,"new_principal_image":None,"disposition":"LIVE_ONLY_AS_NEW_DOUBLED_CARRIER_WITH_OWN_ACTION_AND_COMPLEX"}],
      "composition_theorem":{"released_current_parent_inventory_exhausted":k748["ownership_theorem"]["released_t0_derivative_grammar_exhausted_by_i1b_plus_same_response_residual_squares"],"source_silent_adapter_nonexistence_proved":False,"diagonal_adapter_repairs_current_complex":False,"frozen_background_adapter_is_new_action_owned_response":False,"independent_doubled_adapter_can_be_inserted_without_rebuilding_complex":False,"current_98308_98311_bounds_changed":False,"current_carrier_reopened":False},
      "required_doubled_packet":["independent second connection field and action ownership","one fully stationary background for both connections and metric/section fields","typed path maps and second-layer target","real carrier and pairing","complete principal response and overlap with I1B","gauge and redundancy maps","common analytic domain and all-covector exactness"],
      "decision":{"cyclic_reconstruction_reopens_current_sc_act_06_test":False,"cyclic_reconstruction_killed_globally":False,"doubled_connection_candidate_shape_constructed":True,"next_exact_input":"Supply the entire independently action-owned doubled packet before crediting the relative response. Otherwise switch to the nonzero-T/different-Shiab or native K500 input route rather than another current-carrier adapter variation."},
      "source_and_ledger_effect":"SC_ACT_03_AND_SC_ACT_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The result separates zero/same-carrier specializations from a genuinely enlarged unowned carrier and changes no source or physics verdict.","controls":{"producer":"tests/channel-swings/k757_sc_act_06_cyclic_adapter_current_carrier_composition.py","probe":"tests/channel-swings/k757_sc_act_06_cyclic_adapter_current_carrier_composition_probe.py","controls_passed":40,"hostile_mutations_rejected":35},"claim_ceiling":"Exact carrier-composition boundary for the reconstructed cyclic adapter. No global no-go for two-connection actions, no source-status change, ellipticity, physical result, prediction, confirmation or SC-ACT-06 verdict."}
def validate(p:dict[str,Any])->None:
    assert p["result_id"]=="K757-SC-ACT-06-CYCLIC-ADAPTER-CURRENT-CARRIER-COMPOSITION" and p["target_claim"]=="SC-ACT-06"
    o=p["current_obstruction"]; assert o["body_middle_bounds_preserved"]==[98308,98311] and o["k749_full_symbol_block_obstruction"]
    specs={x["name"]:x for x in p["specialization_composition"]}; assert specs["DIAGONAL_IDENTIFICATION"]["new_principal_image"] is False and specs["FREEZE_B_BACKGROUND"]["new_principal_image"] is False and specs["INDEPENDENT_A_B"]["new_principal_image"] is None and not specs["INDEPENDENT_A_B"]["composable_with_current_carrier"]
    t=p["composition_theorem"]; assert t["released_current_parent_inventory_exhausted"] and not t["source_silent_adapter_nonexistence_proved"] and not t["diagonal_adapter_repairs_current_complex"] and not t["frozen_background_adapter_is_new_action_owned_response"] and not t["independent_doubled_adapter_can_be_inserted_without_rebuilding_complex"] and not t["current_98308_98311_bounds_changed"] and not t["current_carrier_reopened"]
    assert len(p["required_doubled_packet"])==7; d=p["decision"]; assert not d["cyclic_reconstruction_reopens_current_sc_act_06_test"] and not d["cyclic_reconstruction_killed_globally"] and d["doubled_connection_candidate_shape_constructed"] and "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument("--write",action="store_true"); args=ap.parse_args(); packet=build(); validate(packet); text=json.dumps(packet,indent=2,sort_keys=True)+"\n"; OUTPUT.write_text(text,encoding="utf-8") if args.write else print(text,end=""); return 0
if __name__=="__main__": raise SystemExit(main())
