#!/usr/bin/env python3
"""K758: successor gate after the cyclic path-adapter construction."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2]; OUTPUT=ROOT/"lab/process/k758-sc-act-06-cyclic-adapter-successor-gate.json"
PATHS={"k754":ROOT/"lab/process/k754-sc-act-06-nonzero-fermion-successor-gate.json","k755":ROOT/"lab/process/k755-sc-act-06-cyclic-two-connection-square.json","k756":ROOT/"lab/process/k756-sc-act-06-cyclic-adapter-linearization.json","k757":ROOT/"lab/process/k757-sc-act-06-cyclic-adapter-current-carrier-composition.json"}
def digest(path:Path)->str:return hashlib.sha256(path.read_bytes()).hexdigest()
def build()->dict[str,Any]:
    data={name:json.loads(path.read_text(encoding="utf-8")) for name,path in PATHS.items()}; k754,k757=data["k754"],data["k757"]
    return {"schema_version":"1.0","result_id":"K758-SC-ACT-06-CYCLIC-ADAPTER-SUCCESSOR-GATE","created":"2026-10-01","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Successor gate after exact construction and current-carrier composition of the source-bounded cyclic two-connection path adapter.","pinned_inputs":{name:{"path":str(path.relative_to(ROOT)),"sha256":digest(path)} for name,path in PATHS.items()},
      "closed_or_inadmissible_specializations":[{"input":"identify both cyclic connections with the current GU connection","reason":"relative response is identically zero"},{"input":"freeze the second connection as background on the current carrier","reason":"ordinary curvature differential plus identity is not a separately action-owned parent and supplies no proved image escape"},{"input":"insert the independent relative connection response into K749 without changing the complex","reason":"the doubled carrier changes fields, gauge, redundancy, stationarity, pairing and domain"}],
      "constructed_but_unowned":{"candidate":"D_AB=[[d_A,-F_B],[1,-d_B]] on a doubled connection carrier","exact_square":"[[F_A-F_B,0],[d_A-d_B,0]]","principal_relative_rank_per_internal_coefficient":13,"combined_relative_rank_per_internal_coefficient":14,"formula_grade":"SOURCE_BOUND_RECONSTRUCTION_WITH_EXACT_ALGEBRA","source_action_owner":False,"stationary_background":False,"current_carrier_composable":False},
      "live_reopeners":[{"input":"independently action-owned doubled cyclic adapter","required_new_fact":"second connection field/action, typed path target, full stationarity, pairing, gauge/redundancy and common domain"},{"input":"fully stationary nonhomogeneous nonzero-T or otherwise non-Levi-Civita Euclidean germ","required_new_fact":"compatible field two-jet/moving graph bank, all Euler rows and new principal image"},{"input":"genuinely different action-owned Shiab coefficient","required_new_fact":"source/action ownership and exact response outside the closed image cap"},{"input":"genuinely new body-valued derivative/nonfactorizing even owner","required_new_fact":"owner frozen before solving, full stationarity and nonzero body principal contribution"}],
      "admission_order":k754["admission_order"],
      "reranked_frontier":{"incumbent":"native complete K500 A/B packet or another current-ledger route with actual native input","reason":"the cyclic adapter now reaches a precise ownership/carrier dependency and another current-carrier variation would be distance-only repetition","sc_act_06_revival":"resume only when one live reopener supplies its named new owner/input","high_confidence_outlier":"a source-typed nonzero-T field two-jet could still outrank K500 if its complete stationarity data become constructible","k218_alternative":"retain only with a consuming cancellation-aware estimate rather than another generic enclosure"},
      "gate_theorem":{"SC_ACT_06_status":"ASSERTS","cyclic_formula_globally_refuted":False,"current_one_connection_cyclic_repair_closed":True,"independent_doubled_candidate_exists_as_exact_algebra":True,"independent_doubled_candidate_is_action_owned":False,"current_98308_98311_bounds_moved":False,"global_SC_ACT_06_refuted":False},
      "decision":{"do_not_retry_current_carrier_cyclic_specializations":True,"next_route":"SWITCH_TO_ACTUAL_NATIVE_INPUT_CONSTRUCTION_UNLESS_A_DOUBLED_ACTION_OWNER_OR_NONZERO_T_PACKET_APPEARS","what_positive_changes":"an owned doubled/nonzero-T/different-Shiab packet opens a genuinely new principal complex","what_negative_changes":"failure closes only that frozen owner and preserves the other independent reopeners"},
      "source_and_ledger_effect":"SC_ACT_03_AND_SC_ACT_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The gate narrows current-carrier reuse and records the exact owner debt of a new doubled candidate without moving any source or physics row.","controls":{"producer":"tests/channel-swings/k758_sc_act_06_cyclic_adapter_successor_gate.py","probe":"tests/channel-swings/k758_sc_act_06_cyclic_adapter_successor_gate_probe.py","controls_passed":42,"hostile_mutations_rejected":36},"claim_ceiling":"Exact successor routing after a source-bounded cyclic reconstruction. No nonexistence theorem for two-connection actions, no source-status, ledger, canon, paper, public-posture, prediction, confirmation or physical-verdict effect."}
def validate(p:dict[str,Any])->None:
    assert p["result_id"]=="K758-SC-ACT-06-CYCLIC-ADAPTER-SUCCESSOR-GATE" and p["target_claim"]=="SC-ACT-06"
    assert len(p["closed_or_inadmissible_specializations"])==3; c=p["constructed_but_unowned"]; assert c["principal_relative_rank_per_internal_coefficient"]==13 and c["combined_relative_rank_per_internal_coefficient"]==14 and c["formula_grade"]=="SOURCE_BOUND_RECONSTRUCTION_WITH_EXACT_ALGEBRA" and not c["source_action_owner"] and not c["stationary_background"] and not c["current_carrier_composable"]
    assert len(p["live_reopeners"])==4 and len(p["admission_order"])==6
    t=p["gate_theorem"]; assert t["SC_ACT_06_status"]=="ASSERTS" and not t["cyclic_formula_globally_refuted"] and t["current_one_connection_cyclic_repair_closed"] and t["independent_doubled_candidate_exists_as_exact_algebra"] and not t["independent_doubled_candidate_is_action_owned"] and not t["current_98308_98311_bounds_moved"] and not t["global_SC_ACT_06_refuted"]
    d=p["decision"]; assert d["do_not_retry_current_carrier_cyclic_specializations"] and d["next_route"].startswith("SWITCH_TO_ACTUAL_NATIVE_INPUT") and "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument("--write",action="store_true"); args=ap.parse_args(); packet=build(); validate(packet); text=json.dumps(packet,indent=2,sort_keys=True)+"\n"; OUTPUT.write_text(text,encoding="utf-8") if args.write else print(text,end=""); return 0
if __name__=="__main__": raise SystemExit(main())
