#!/usr/bin/env python3
"""K770: route SC-ACT-06 after the high-rank curvature-square comparator."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2]; OUTPUT=ROOT/"lab/process/k770-sc-act-06-curvature-square-successor-gate.json"
PATHS={"k766":ROOT/"lab/process/k766-sc-act-06-derivative-even-successor-gate.json","k767":ROOT/"lab/process/k767-sc-act-06-curvature-square-control.json","k768":ROOT/"lab/process/k768-sc-act-06-curvature-square-rank-boundary.json","k769":ROOT/"lab/process/k769-sc-act-06-curvature-square-cohomology-bound.json","k716":ROOT/"lab/process/k716-sc-act-06-compact-reduction-selection-boundary.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
    return {"schema_version":"1.0","result_id":"K770-SC-ACT-06-CURVATURE-SQUARE-SUCCESSOR-GATE","created":"2026-10-01","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Successor routing after K767--K769 test the natural full-connection curvature-square comparator under native and positive Cartan pairings.","pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for n,p in PATHS.items()},"closed_classes":[{"class":"pure full-connection curvature-square comparator with native (13,1) adjoint on the frozen K749 germ","reason":"At a native-null nonzero covector its Hessian rank is only 16384, so K763 leaves at least 81927 middle classes."},{"class":"identifying pure ||F_A||^2 with the source-owned I2B residual action","reason":"SC-ACT-04 owns ||Upsilon||^2 and the evidence contract requires an explicit residual/action derivative owner; matching derivative order or Yang-Mills language is insufficient."}],"surviving_branches":[{"input":"positive Cartan-reduction curvature comparator","required_new_fact":"background/source ownership of one reduction, exact combined I1B image placement, total-action gauge/redundancy maps and all-covector exactness; rank-threshold clearance alone is insufficient"},{"input":"fully stationary changed or nonzero-T source-typed germ","required_new_fact":"new action-owned principal image and complete coupled symbol complex"},{"input":"independent source/action parent or different Shiab response","required_new_fact":"exact owner, maps, pairing, common domain and stationarity"},{"input":"complete native K500 A/B packet","required_new_fact":"native remainder and boundary maps plus complete A and parity-cofinal B certificates"}],"decision":{"do_not_retry_native_pairing_curvature_square_comparator":True,"do_not_promote_positive_rank_clearance_to_exactness":True,"do_not_promote_comparator_to_source_I2B":True,"positive_reduction_branch_mathematically_open_but_unowned":True,"SC_ACT_06_status":"ASSERTS","global_SC_ACT_06_refuted":False},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The native comparator is excluded, while its positive repair changes the pairing/reduction ownership and still lacks the complete source-owned symbol complex.","controls":{"producer":"tests/channel-swings/k770_sc_act_06_curvature_square_successor_gate.py","probe":"tests/channel-swings/k770_sc_act_06_curvature_square_successor_gate_probe.py","controls_passed":42,"hostile_mutations_rejected":36},"claim_ceiling":"Exact successor gate for the pure curvature-square comparator. It closes the native-pairing version and preserves a positive-reduction version only as an unowned threshold survivor. No source action identification, complete exactness, global SC-ACT-06 result, or physical conclusion."}
def validate(p:dict[str,Any])->None:
    assert p["result_id"].startswith("K770-") and p["status"]=="working_draft_verified" and p["classification"]=="SOURCE_NATIVE_ROUTE" and p["target_claim"]=="SC-ACT-06"
    assert len(p["closed_classes"])==2 and "81927" in p["closed_classes"][0]["reason"] and "||Upsilon||^2" in p["closed_classes"][1]["reason"]
    assert len(p["surviving_branches"])==4
    d=p["decision"]; assert d["do_not_retry_native_pairing_curvature_square_comparator"] and d["do_not_promote_positive_rank_clearance_to_exactness"] and d["do_not_promote_comparator_to_source_I2B"] and d["positive_reduction_branch_mathematically_open_but_unowned"] and d["SC_ACT_06_status"]=="ASSERTS" and not d["global_SC_ACT_06_refuted"]
    assert "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument("--write",action="store_true"); args=ap.parse_args(); p=build(); validate(p); s=json.dumps(p,indent=2,sort_keys=True)+"\n"; OUTPUT.write_text(s) if args.write else print(s,end=""); return 0
if __name__=="__main__": raise SystemExit(main())
