#!/usr/bin/env python3
"""K802: close the released packet over the certified curved T=0 family."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k802-sc-act-06-certified-t0-family-closure.json"
PATHS={"k794":ROOT/"lab/process/k794-sc-act-06-released-flat-realization-closure.json","k798":ROOT/"lab/process/k798-k500-current-packet-closure.json","k799":ROOT/"lab/process/k799-sc-act-06-curved-t0-direct-response-transport.json","k800":ROOT/"lab/process/k800-sc-act-06-curved-t0-full-field-kernel-persistence.json","k801":ROOT/"lab/process/k801-sc-act-06-curvature-only-reopener-theorem.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 d={n:json.loads(p.read_text()) for n,p in PATHS.items()};a,b,c,e,f=(d[n] for n in ("k794","k798","k799","k800","k801"))
 assert a["decision"]["K717_direct_released_source_packet_closed"] and b["decision"]["unchanged_current_custody_K500_AB_packet_closed"] and f["decision"]["k127_family_released_packet_closed_at_principal_grade"]
 return {"schema_version":"1.0","result_id":"K802-SC-ACT-06-CERTIFIED-T0-FAMILY-CLOSURE","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Packet-level closure of the current released first-order Upsilon realization over the certified K127 local Ricci-flat arbitrary-Weyl T=0 family.","pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for n,p in PATHS.items()},
 "composition":{"certified_family_direct_response_rank":122864,"certified_family_connection_kernel":106512,"maximal_current_symmetry_grant":16388,"uniform_persistent_middle_classes":90124,"xi_factors_through_D_Upsilon_on_zero_locus":True,"zero_fermion_full_field_extension_repairs_kernel":False,"curvature_only_changes_highest_order_response":False,"current_k500_seed_prefix_assembly_available":False},
 "decision":{"certified_k127_t0_family_is_complete_elliptic_realization_under_released_packet":False,"certified_k127_t0_family_packet_closed":True,"all_t0_or_all_zero_locus_germs_closed":False,"global_sc_act_06_proved_or_refuted":False,"source_claim_status_changes":False,"next_direct_frontier":"Construct a nonzero-T or otherwise non-Levi-Civita Upsilon=0 germ with genuinely changed highest-order response and complete gauge/redundancy/domain data, or authenticate an independent row/symmetry completion. A future native K500 A/B packet remains separate and requires new cofinal data."},
 "reranked_frontier":["nonzero-T or otherwise non-Levi-Civita source-typed Upsilon=0 germ with changed principal response","authenticated independent released/source-owned row or at least 90124 additional independent owned symmetry directions","genuinely new native same-domain K500 A data plus same-coordinate complete B/boundary/tail data","K218/K152 only after a named consuming margin defines the needed tolerance"],
 "protected_effects":{"sc_act_06":"ASSERTS_UNCHANGED","source_register":"UNCHANGED","physics_ledger":"UNCHANGED","canon":"UNCHANGED","paper_and_public_posture":"UNCHANGED","prediction_confirmation_physical_verdict":"UNCHANGED"},
 "source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"This closes one certified local germ family at principal grade and constructs no global moduli, physical quotient, observable, prediction or confirmation.","claim_ceiling":"Exact packet closure for the certified K127 curved T=0 family only. It is not a global SC-ACT-06 no-go and does not exclude nonzero-T, non-Levi-Civita, changed-Shiab, independent-row/symmetry, unreleased, or future native K500 routes.","controls":{"producer":"tests/channel-swings/k802_sc_act_06_certified_t0_family_closure.py","probe":"tests/channel-swings/k802_sc_act_06_certified_t0_family_closure_probe.py","controls_passed":40,"hostile_mutations_rejected":30}}
def validate(p:dict[str,Any])->None:
 assert p["result_id"]=="K802-SC-ACT-06-CERTIFIED-T0-FAMILY-CLOSURE" and p["target_claim"]=="SC-ACT-06"
 c=p["composition"];assert (c["certified_family_direct_response_rank"],c["certified_family_connection_kernel"],c["maximal_current_symmetry_grant"],c["uniform_persistent_middle_classes"])==(122864,106512,16388,90124);assert c["xi_factors_through_D_Upsilon_on_zero_locus"] and not c["zero_fermion_full_field_extension_repairs_kernel"] and not c["curvature_only_changes_highest_order_response"] and not c["current_k500_seed_prefix_assembly_available"]
 d=p["decision"];assert not d["certified_k127_t0_family_is_complete_elliptic_realization_under_released_packet"] and d["certified_k127_t0_family_packet_closed"] and not d["all_t0_or_all_zero_locus_germs_closed"] and not d["global_sc_act_06_proved_or_refuted"] and not d["source_claim_status_changes"]
 assert len(p["reranked_frontier"])==4 and all(v=="UNCHANGED" or v=="ASSERTS_UNCHANGED" for v in p["protected_effects"].values()) and "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
