#!/usr/bin/env python3
"""K806: close nonzero T alone as a principal reopener."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k806-sc-act-06-nonzero-t-alone-closure.json"
PATHS={"k798":ROOT/"lab/process/k798-k500-current-packet-closure.json","k802":ROOT/"lab/process/k802-sc-act-06-certified-t0-family-closure.json","k803":ROOT/"lab/process/k803-sc-act-06-nonzero-t-principal-invariance.json","k804":ROOT/"lab/process/k804-sc-act-06-fixed-structure-full-field-kernel.json","k805":ROOT/"lab/process/k805-sc-act-06-fixed-structure-symmetry-threshold.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 d={n:json.loads(p.read_text()) for n,p in PATHS.items()};assert not d["k803"]["decision"]["fixed_structure_nonzero_T_is_new_principal_germ"] and not d["k805"]["decision"]["current_grant_closes_fixed_structure_packet"]
 return {"schema_version":"1.0","result_id":"K806-SC-ACT-06-NONZERO-T-ALONE-CLOSURE","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Closure of nonzero background T alone, with unchanged released first-order principal structure, as a repair of the current SC-ACT-06 packet.","gu_typed_objects":{"carrier":"fixed-principal-structure nonzero-T connection tangent and its full-field embedding","pairing":"principal response, embedded kernel, and authenticated symmetry quotient considered in sequence","real_structure":"real U(64,64) coefficient dimensions inherited from K803-K805","grading":"connection principal symbol through full-field middle cohomology","action_owner":"released Upsilon equation and current owned symmetry grant only","target":"whether changing T alone reopens the certified SC-ACT-06 packet"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for n,p in PATHS.items()},
 "composition":{"nonzero_T_alone_changes_principal_response":False,"fixed_structure_connection_rank":122864,"fixed_structure_connection_kernel":106512,"full_field_embedded_kernel":106512,"maximal_current_grant":16388,"persistent_classes_under_current_grant":90124,"released_independent_row_beyond_Upsilon_available":False,"current_k500_native_packet_available":False},
 "decision":{"nonzero_T_alone_reopens_certified_packet":False,"all_nonzero_T_or_non_levi_civita_zero_locus_germs_closed":False,"moving_principal_geometry_closed":False,"future_owned_symmetry_or_independent_row_closed":False,"global_sc_act_06_proved_or_refuted":False,"source_claim_status_changes":False,"next_direct_frontier":"Construct a source-typed zero-locus germ whose moving metric/epsilon/Shiab/Hodge principal coefficients actually differ, authenticate an independent first-order row, or supply enough owned symmetry to cover the 106512-dimensional kernel. Future native K500 remains separate and needs new A/B data."},
 "reranked_frontier":["moving metric/epsilon/Shiab/Hodge zero-locus germ with genuinely changed principal coefficients and complete stationarity/gauge/domain packet","authenticated independent released/source-owned first-order row acting on the embedded kernel","owned symmetry image spanning 106512 kernel directions or at least 90124 beyond the current grant","genuinely new native same-domain K500 A data plus same-coordinate complete B/boundary/tail data","K218/K152 only after a named consuming margin"],
 "protected_effects":{"sc_act_06":"ASSERTS_UNCHANGED","source_register":"UNCHANGED","physics_ledger":"UNCHANGED","canon":"UNCHANGED","paper_and_public_posture":"UNCHANGED","prediction_confirmation_physical_verdict":"UNCHANGED"},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The result narrows one principal reopener and constructs no stationary nonzero-T germ, physical quotient, observable, prediction or confirmation.","claim_ceiling":"Exact closure of nonzero T alone under unchanged released principal structure. It is not a global nonzero-T/non-Levi-Civita classification or SC-ACT-06 no-go.","controls":{"producer":"tests/channel-swings/k806_sc_act_06_nonzero_t_alone_closure.py","probe":"tests/channel-swings/k806_sc_act_06_nonzero_t_alone_closure_probe.py","controls_passed":40,"hostile_mutations_rejected":30}}
def validate(p:dict[str,Any])->None:
 assert p["result_id"]=="K806-SC-ACT-06-NONZERO-T-ALONE-CLOSURE" and p["target_claim"]=="SC-ACT-06";c=p["composition"]
 assert not c["nonzero_T_alone_changes_principal_response"] and (c["fixed_structure_connection_rank"],c["fixed_structure_connection_kernel"],c["full_field_embedded_kernel"],c["maximal_current_grant"],c["persistent_classes_under_current_grant"])==(122864,106512,106512,16388,90124) and not c["released_independent_row_beyond_Upsilon_available"] and not c["current_k500_native_packet_available"]
 d=p["decision"]
 for k in ("nonzero_T_alone_reopens_certified_packet","all_nonzero_T_or_non_levi_civita_zero_locus_germs_closed","moving_principal_geometry_closed","future_owned_symmetry_or_independent_row_closed","global_sc_act_06_proved_or_refuted","source_claim_status_changes"):assert not d[k]
 assert len(p["reranked_frontier"])==5 and all(v in ("UNCHANGED","ASSERTS_UNCHANGED") for v in p["protected_effects"].values()) and "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
