#!/usr/bin/env python3
"""K808: transport the fixed pure-connection kernel through the full-field packet."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k808-sc-act-06-comoving-full-field-kernel.json"
PATHS={"k792":ROOT/"lab/process/k792-sc-act-06-redundant-prolongation-kernel-theorem.json","k804":ROOT/"lab/process/k804-sc-act-06-fixed-structure-full-field-kernel.json","k807":ROOT/"lab/process/k807-sc-act-06-comoving-principal-conjugacy.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 d={n:json.loads(p.read_text()) for n,p in PATHS.items()};assert d["k807"]["orbit_consequence"]["transported_kernel_dimension"]==106512
 return {"schema_version":"1.0","result_id":"K808-SC-ACT-06-COMOVING-FULL-FIELD-KERNEL","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Transport of the K804 pure-connection kernel embedding through a regular natural full-field frame map at a zero-fermion Upsilon=0 germ.","gu_typed_objects":{"carrier":"released zero-fermion full-field tangent with transported pure-connection subspace","pairing":"principal field-equation symbol and redundant Xi row","real_structure":"transported real full-field frame compatible with K807","grading":"pure connection tangent embedded into the full bosonic-plus-fermionic packet","action_owner":"released Upsilon row, redundant Xi prolongation and displayed zero-fermion diagonal","target":"whether natural full-field frame transport removes the connection kernel"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for n,p in PATHS.items()},"extension_theorem":{"full_field_frame_map_invertible":True,"pure_connection_subspace_intertwined":True,"xi_row_factors_through_transported_D_Upsilon":True,"zero_fermion_diagonal_remains_separate":True,"extra_transported_field_columns_delete_pure_connection_kernel":False,"embedded_reference_kernel_dimension":106512,"embedded_transported_kernel_dimension":106512,"genuine_mixed_principal_blocks_covered":False},"decision":{"comoving_full_field_packet_middle_exact_before_symmetry":False,"all_moving_full_field_germs_classified":False,"global_sc_act_06_proved_or_refuted":False,"next_exact_input":"Test the transported kernel against owned symmetry, or construct genuinely new mixed principal blocks on a complete stationary germ."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"This is a functorial kernel embedding, not a new physical quotient, domain, prediction or confirmation.","claim_ceiling":"Exact regular co-moving full-field kernel transport only; genuine mixed blocks and arbitrary moving germs remain open.","controls":{"producer":"tests/channel-swings/k808_sc_act_06_comoving_full_field_kernel.py","probe":"tests/channel-swings/k808_sc_act_06_comoving_full_field_kernel_probe.py","controls_passed":40,"hostile_mutations_rejected":30}}
def validate(p:dict[str,Any])->None:
 assert p["result_id"]=="K808-SC-ACT-06-COMOVING-FULL-FIELD-KERNEL" and p["target_claim"]=="SC-ACT-06";e=p["extension_theorem"]
 for k in ("full_field_frame_map_invertible","pure_connection_subspace_intertwined","xi_row_factors_through_transported_D_Upsilon","zero_fermion_diagonal_remains_separate"):assert e[k]
 assert not e["extra_transported_field_columns_delete_pure_connection_kernel"] and not e["genuine_mixed_principal_blocks_covered"] and (e["embedded_reference_kernel_dimension"],e["embedded_transported_kernel_dimension"])==(106512,106512)
 d=p["decision"];assert not d["comoving_full_field_packet_middle_exact_before_symmetry"] and not d["all_moving_full_field_germs_classified"] and not d["global_sc_act_06_proved_or_refuted"] and "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
