#!/usr/bin/env python3
"""K809: simultaneous frame transport preserves the current symmetry quotient."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k809-sc-act-06-comoving-symmetry-quotient.json"
PATHS={"k805":ROOT/"lab/process/k805-sc-act-06-fixed-structure-symmetry-threshold.json","k807":ROOT/"lab/process/k807-sc-act-06-comoving-principal-conjugacy.json","k808":ROOT/"lab/process/k808-sc-act-06-comoving-full-field-kernel.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 d={n:json.loads(p.read_text()) for n,p in PATHS.items()};k=d["k805"]["threshold_theorem"];assert k["persistent_middle_classes_under_current_grant"]==90124
 return {"schema_version":"1.0","result_id":"K809-SC-ACT-06-COMOVING-SYMMETRY-QUOTIENT","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Simultaneous regular frame transport of the K808 embedded kernel and the current authenticated internal-plus-diffeomorphism grant.","gu_typed_objects":{"carrier":"transported K808 pure-connection kernel inside the released full-field packet","pairing":"middle quotient by the simultaneously transported current symmetry image","real_structure":"real associated-bundle transport inherited from K807","grading":"principal middle term modulo authenticated infinitesimal symmetry directions","action_owner":"current source-owned grant only; the q-lambda candidate is not promoted to total gauge","target":"whether a basis change creates new owned symmetry or shrinks the quotient"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for n,p in PATHS.items()},"quotient_transport":{"kernel_frame_map_invertible":True,"symmetry_frame_map_invertible":True,"same_domain_intertwiner_used":True,"reference_kernel_dimension":106512,"transported_kernel_dimension":106512,"reference_current_grant_rank":16388,"transported_current_grant_rank":16388,"reference_persistent_classes":90124,"transported_persistent_classes":90124,"basis_motion_creates_owned_symmetry":False,"candidate_internal_map_promoted_to_gauge":False},"decision":{"current_transported_grant_closes_packet":False,"future_background_dependent_symmetry_closed":False,"global_sc_act_06_proved_or_refuted":False,"next_exact_input":"Supply new source-owned symmetry directions, a new independent row, or genuine relative principal motion; simultaneous frame transport preserves the quotient."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"This is quotient invariance under an isomorphism, not ownership of new gauge data or a physical quotient.","claim_ceiling":"Exact current-grant quotient transport only; future owned symmetries and arbitrary backgrounds remain open.","controls":{"producer":"tests/channel-swings/k809_sc_act_06_comoving_symmetry_quotient.py","probe":"tests/channel-swings/k809_sc_act_06_comoving_symmetry_quotient_probe.py","controls_passed":36,"hostile_mutations_rejected":28}}
def validate(p:dict[str,Any])->None:
 assert p["result_id"]=="K809-SC-ACT-06-COMOVING-SYMMETRY-QUOTIENT" and p["target_claim"]=="SC-ACT-06";q=p["quotient_transport"]
 for k in ("kernel_frame_map_invertible","symmetry_frame_map_invertible","same_domain_intertwiner_used"):assert q[k]
 assert (q["reference_kernel_dimension"],q["transported_kernel_dimension"],q["reference_current_grant_rank"],q["transported_current_grant_rank"],q["reference_persistent_classes"],q["transported_persistent_classes"])==(106512,106512,16388,16388,90124,90124)
 assert not q["basis_motion_creates_owned_symmetry"] and not q["candidate_internal_map_promoted_to_gauge"]
 d=p["decision"];assert not d["current_transported_grant_closes_packet"] and not d["future_background_dependent_symmetry_closed"] and not d["global_sc_act_06_proved_or_refuted"] and "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
