#!/usr/bin/env python3
"""K817: finite-parameter Schur-complement gate after transverse rank."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k817-sc-act-06-finite-parameter-schur-gate.json"
PATHS={"k812":ROOT/"lab/process/k812-sc-act-06-relative-transverse-block.json","k816":ROOT/"lab/process/k816-sc-act-06-response-symmetry-overlap.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 return {"schema_version":"1.0","result_id":"K817-SC-ACT-06-FINITE-PARAMETER-SCHUR-GATE","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Finite-dimensional square-response control separating an invertible transverse derivative from finite-parameter persistence.","gu_typed_objects":{"carrier":"complement plus kernel decomposition of a square finite symbol response","pairing":"none; block decomposition and determinant/Schur complement","real_structure":"real analytic one-parameter matrix family","grading":"old image/complement block plus kernel-to-cokernel block","action_owner":"generic control theorem; application to GU requires the complete source-owned quotient complex","target":"whether first-order transverse lifting opens a punctured finite-parameter response"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for n,p in PATHS.items()},"schur_theorem":{"decomposition":"X=X1+K and Y=im(J0)+Q","invertible_old_block":"A(0):X1->im(J0)","effective_block":"S(t)=D(t)-C(t)A(t)^-1B(t)","first_term":"S(t)=t tau+O(t^2)","invertible_tau_implies_punctured_local_invertibility":True,"deficient_tau_implies_no_finite_parameter_repair":False,"single_parameter_rank_threshold_is_sufficient_for_complex":False,"requires_square_quotient_block":True},"exact_controls":{"opening_family":{"matrices":"diag(1,t,2t)","tau":"diag(1,2)","tau_rank":2,"determinant":"2*t^2","invertible_for_nonzero_t":True},"absorbed_family":{"matrices":"[[1,t,0],[0,0,0],[0,0,0]]","tau_rank":0,"rank_for_nonzero_t":1,"opens":False},"higher_order_family":{"matrices":"diag(1,t,t^2)","tau_rank":1,"determinant":"t^3","invertible_for_nonzero_t":True,"shows_deficient_tau_is_inconclusive":True}},"decision":{"gu_square_quotient_complex_constructed":False,"finite_parameter_gu_ellipticity_proved":False,"deficient_first_derivative_closes_higher_order_repairs":False,"global_sc_act_06_proved_or_refuted":False,"next_exact_input":"After a source family passes K815 and K816, build its actual quotient block, control the Schur remainder uniformly, and prove the complete finite-parameter complex on the common domain."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"This generic persistence theorem is not yet applied to a source-owned GU quotient complex.","claim_ceiling":"Generic finite-dimensional punctured-family control only; no GU quotient construction, ellipticity or global conclusion.","controls":{"producer":"tests/channel-swings/k817_sc_act_06_finite_parameter_schur_gate.py","probe":"tests/channel-swings/k817_sc_act_06_finite_parameter_schur_gate_probe.py","controls_passed":36,"hostile_mutations_rejected":28}}
def validate(p:dict[str,Any])->None:
 t,c,d=p["schur_theorem"],p["exact_controls"],p["decision"]
 assert t["invertible_tau_implies_punctured_local_invertibility"] and t["requires_square_quotient_block"]
 assert not t["deficient_tau_implies_no_finite_parameter_repair"] and not t["single_parameter_rank_threshold_is_sufficient_for_complex"]
 assert c["opening_family"]=={"matrices":"diag(1,t,2t)","tau":"diag(1,2)","tau_rank":2,"determinant":"2*t^2","invertible_for_nonzero_t":True}
 assert c["absorbed_family"]["tau_rank"]==0 and c["absorbed_family"]["rank_for_nonzero_t"]==1 and not c["absorbed_family"]["opens"]
 assert c["higher_order_family"]["tau_rank"]==1 and c["higher_order_family"]["determinant"]=="t^3" and c["higher_order_family"]["invertible_for_nonzero_t"] and c["higher_order_family"]["shows_deficient_tau_is_inconclusive"]
 assert not any(d[k] for k in ("gu_square_quotient_complex_constructed","finite_parameter_gu_ellipticity_proved","deficient_first_derivative_closes_higher_order_repairs","global_sc_act_06_proved_or_refuted"))
 assert p["target_claim"]=="SC-ACT-06" and "UNCHANGED" in p["source_and_ledger_effect"]
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else print(s,end="");return 0
if __name__=="__main__":raise SystemExit(main())
