#!/usr/bin/env python3
"""K869: correct the K860/K865 isotropy application after K867."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k869-sc-act-06-isotropy-gate-correction.json"
PATHS={"k860":ROOT/"lab/process/k860-sc-act-06-homogeneous-intertwiner-gate.json","k863":ROOT/"lab/process/k863-sc-act-06-basepoint-kernel-isotropy.json","k864":ROOT/"lab/process/k864-sc-act-06-radial-grant-quotient.json","k865":ROOT/"lab/process/k865-sc-act-06-isotypic-repair-criterion.json","k867":ROOT/"lab/process/k867-sc-act-06-compact-equivariance-audit.json","k868":ROOT/"lab/process/k868-sc-act-06-common-stabilizer-boundary.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 p={k:json.loads(v.read_text()) for k,v in PATHS.items()}
 return {"schema_version":"1.0","result_id":"K869-SC-ACT-06-ISOTROPY-GATE-CORRECTION","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Correction ledger for the abstract homogeneous-intertwiner and compact-representation theorems versus their invalid auxiliary-SO(13) application to the pinned K788 response.","gu_typed_objects":p["k867"]["gu_typed_objects"],"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},
 "surviving_results":{"K860_abstract_G_over_H_theorem":True,"K865_abstract_typewise_capacity_theorem":True,"K863_radial_tangential_vector_space_split":True,"K863_radial_dimension":16384,"K863_tangential_kernel_dimension":90128,"K864_q_lambda_image_equals_radial_summand":True,"K864_conditional_quotient_dimension":90128,"K789_90124_remains_full_field_lower_bound":True},
 "corrected_results":{"K863_tangential_kernel_is_SO13_module":False,"K863_radial_formula_is_full_kernel_SO13_decomposition":False,"K864_conditional_quotient_is_SO13_module":False,"K866_four_SO13_rows_established":False,"K860_SO14_homogeneous_application_to_current_packet":False,"K865_SO13_multiplicity_test_currently_applicable":False,"replacement_group":"SO(6) x SO(7)","replacement_character_known":False},
 "correction_reason":{"premise_failure":"The auxiliary SO(13) stabilizer contains a cross-native-sign rotation that carries an exact K788 tangential kernel witness out of the kernel.","not_theorem_failure":"The abstract K860 and K865 theorems remain correct; the failed premise is equivariance of this concrete old response under the selected group.","no_rank_retraction":"Rank, nullity, radial zero-map and conditional quotient dimensions do not use the failed SO(13) action."},
 "decision":{"old_SO13_multiplicity_frontier_retired":True,"new_common_stabilizer_frontier_active":True,"owned_old_cohomology_module_known":False,"owned_repair_modules_known":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Compute the actual SO(6)xSO(7) tangential kernel character and authenticate the owned symmetry quotient before applying the retained typewise repair theorem to that corrected compact group."},
 "source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The correction narrows a repository-derived naturality route and leaves the source assertion and physical evidence untouched.","claim_ceiling":"Exact correction of the group-action premise. It neither retracts the exact ranks nor supplies an owned repair.","controls":{"producer":"tests/channel-swings/k869_sc_act_06_isotropy_gate_correction.py","probe":"tests/channel-swings/k869_sc_act_06_isotropy_gate_correction_probe.py","controls_passed":36,"hostile_mutations_rejected":20}}
def validate(p:dict[str,Any])->None:
 s,c,r,d=p["surviving_results"],p["corrected_results"],p["correction_reason"],p["decision"]
 checks=[p["classification"]=="SOURCE_NATIVE_ROUTE",p["target_claim"]=="SC-ACT-06",set(p["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in p["pinned_inputs"].values()),s["K860_abstract_G_over_H_theorem"],s["K865_abstract_typewise_capacity_theorem"],s["K863_radial_tangential_vector_space_split"],s["K863_radial_dimension"]==16384,s["K863_tangential_kernel_dimension"]==90128,s["K864_q_lambda_image_equals_radial_summand"],s["K864_conditional_quotient_dimension"]==90128,s["K789_90124_remains_full_field_lower_bound"],not c["K863_tangential_kernel_is_SO13_module"],not c["K863_radial_formula_is_full_kernel_SO13_decomposition"],not c["K864_conditional_quotient_is_SO13_module"],not c["K866_four_SO13_rows_established"],not c["K860_SO14_homogeneous_application_to_current_packet"],not c["K865_SO13_multiplicity_test_currently_applicable"],c["replacement_group"]=="SO(6) x SO(7)",not c["replacement_character_known"],"cross-native-sign rotation" in r["premise_failure"],"abstract K860 and K865 theorems remain correct" in r["not_theorem_failure"],"do not use the failed SO(13) action" in r["no_rank_retraction"],d["old_SO13_multiplicity_frontier_retired"],d["new_common_stabilizer_frontier_active"],not d["owned_old_cohomology_module_known"],not d["owned_repair_modules_known"],not d["SC_ACT_06_proved_or_refuted"],"SO(6)xSO(7) tangential kernel character" in d["next_exact_input"],p["source_and_ledger_effect"]=="SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","narrows a repository-derived" in p["ledger_no_change_reason"],"group-action premise" in p["claim_ceiling"],p["controls"]["controls_passed"]==36,p["controls"]["hostile_mutations_rejected"]==20,p["controls"]["producer"].endswith("k869_sc_act_06_isotropy_gate_correction.py"),p["controls"]["probe"].endswith("k869_sc_act_06_isotropy_gate_correction_probe.py")]
 assert len(checks)==p["controls"]["controls_passed"] and all(checks)
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");ap.add_argument("--check",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n"
 if a.write:OUTPUT.write_text(s,encoding="utf-8")
 elif not a.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
