#!/usr/bin/env python3
"""K870: compile the corrected basepoint-isotropy disposition."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k870-sc-act-06-corrected-isotropy-disposition.json"
PATHS={"k864":ROOT/"lab/process/k864-sc-act-06-radial-grant-quotient.json","k865":ROOT/"lab/process/k865-sc-act-06-isotypic-repair-criterion.json","k867":ROOT/"lab/process/k867-sc-act-06-compact-equivariance-audit.json","k868":ROOT/"lab/process/k868-sc-act-06-common-stabilizer-boundary.json","k869":ROOT/"lab/process/k869-sc-act-06-isotropy-gate-correction.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 ps={k:json.loads(v.read_text()) for k,v in PATHS.items()};rows=["exact radial/tangential vector-space kernel split","conditional q-lambda quotient dimension 90128","auxiliary SO(13) equivariance of the pinned response kernel","authenticated common compact stabilizer SO(6)xSO(7)","real SO(6)xSO(7) tangential-kernel multiplicities","authenticated source/action-owned old symmetry image","source/action-owned repair-domain and repair-target multiplicities","typewise repair capacity on the corrected group","constructed corrected-group intertwiners S_0,tau_0","descent, composition and image-kernel equality","globalized natural maps and analytic robustness"]
 status={row:state for row,state in zip(rows,[True,True,False,True,False,False,False,False,False,False,False])}
 return {"schema_version":"1.0","result_id":"K870-SC-ACT-06-CORRECTED-ISOTROPY-DISPOSITION","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Compiled correction after the pinned response fails auxiliary-SO(13) equivariance and the common SO(6)xSO(7) stabilizer replaces the retired multiplicity frontier.","gu_typed_objects":ps["k867"]["gu_typed_objects"],"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"compiled_result":{"dimension_split_survives":True,"radial_dimension":16384,"tangential_kernel_dimension":90128,"conditional_q_lambda_quotient_dimension":90128,"auxiliary_SO13_kernel_module_retracted":True,"common_stabilizer":"SO(6) x SO(7)","common_stabilizer_character_known":False,"owned_old_cohomology_module_known":False,"owned_repair_modules_known":False,"current_flat_exact_admitted":False},"corrected_certificate":{"row_count":len(rows),"rows":rows,"current_GU_candidate":status,"satisfied_row_count":sum(status.values()),"failed_row_count":sum(v is False for v in status.values()),"all_rows_conjunctive":True,"current_GU_candidate_admitted":all(status.values()),"failed_SO13_row_cannot_be_counted_as_satisfied":True},"decision":{"K866_disposition_current":False,"correction_required_and_applied":True,"current_flat_packet_repaired":False,"current_flat_packet_repairability_refuted":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Compute the real SO(6)xSO(7) character of the 90128-dimensional tangential kernel, authenticate the actual owned quotient, and then apply the retained compact typewise criterion to corrected-group repair modules."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The correction removes an invalid naturality claim but preserves the local rank obstruction and supplies no physical complex.","claim_ceiling":"Corrected local group and exact surviving dimensions only. No GU repair, global no-go or physical conclusion follows.","controls":{"producer":"tests/channel-swings/k870_sc_act_06_corrected_isotropy_disposition.py","probe":"tests/channel-swings/k870_sc_act_06_corrected_isotropy_disposition_probe.py","controls_passed":38,"hostile_mutations_rejected":20}}
def validate(p:dict[str,Any])->None:
 c,x,d=p["compiled_result"],p["corrected_certificate"],p["decision"]
 checks=[p["classification"]=="SOURCE_NATIVE_ROUTE",p["target_claim"]=="SC-ACT-06",set(p["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in p["pinned_inputs"].values()),c["dimension_split_survives"],c["radial_dimension"]==16384,c["tangential_kernel_dimension"]==90128,c["conditional_q_lambda_quotient_dimension"]==90128,c["auxiliary_SO13_kernel_module_retracted"],c["common_stabilizer"]=="SO(6) x SO(7)",not c["common_stabilizer_character_known"],not c["owned_old_cohomology_module_known"],not c["owned_repair_modules_known"],not c["current_flat_exact_admitted"],x["row_count"]==11,len(x["rows"])==11,len(x["current_GU_candidate"])==11,x["satisfied_row_count"]==3,x["failed_row_count"]==8,sum(x["current_GU_candidate"].values())==3,x["all_rows_conjunctive"],not x["current_GU_candidate_admitted"],x["failed_SO13_row_cannot_be_counted_as_satisfied"],x["current_GU_candidate"]["auxiliary SO(13) equivariance of the pinned response kernel"] is False,x["current_GU_candidate"]["authenticated common compact stabilizer SO(6)xSO(7)"] is True,not d["K866_disposition_current"],d["correction_required_and_applied"],not d["current_flat_packet_repaired"],not d["current_flat_packet_repairability_refuted"],not d["SC_ACT_06_proved_or_refuted"],"SO(6)xSO(7) character" in d["next_exact_input"],p["source_and_ledger_effect"]=="SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","removes an invalid naturality claim" in p["ledger_no_change_reason"],"No GU repair" in p["claim_ceiling"],p["controls"]["controls_passed"]==38,p["controls"]["hostile_mutations_rejected"]==20,p["controls"]["producer"].endswith("k870_sc_act_06_corrected_isotropy_disposition.py"),p["controls"]["probe"].endswith("k870_sc_act_06_corrected_isotropy_disposition_probe.py")]
 assert len(checks)==p["controls"]["controls_passed"] and all(checks)
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");ap.add_argument("--check",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n"
 if a.write:OUTPUT.write_text(s,encoding="utf-8")
 elif not a.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
