#!/usr/bin/env python3
"""K874: compile the corrected owned-quotient typewise repair disposition."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/"lab/process/k874-sc-act-06-corrected-typewise-disposition.json"
PATHS={
 "k865":ROOT/"lab/process/k865-sc-act-06-isotypic-repair-criterion.json",
 "k870":ROOT/"lab/process/k870-sc-act-06-corrected-isotropy-disposition.json",
 "k872":ROOT/"lab/process/k872-sc-act-06-common-stabilizer-irreducible-character.json",
 "k873":ROOT/"lab/process/k873-sc-act-06-owned-symmetry-custody.json",
}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 ps={k:json.loads(v.read_text()) for k,v in PATHS.items()};k872,k873=ps["k872"],ps["k873"]
 rows=["exact radial/tangential vector-space kernel split","owned principal q-lambda quotient dimension 90128","auxiliary SO(13) equivariance of the pinned response kernel","authenticated common compact stabilizer SO(6)xSO(7)","real SO(6)xSO(7) tangential-quotient multiplicities","authenticated source/action-owned principal old symmetry image","source/action-owned repair-domain and repair-target multiplicities","typewise repair capacity on the corrected group","constructed corrected-group intertwiners S_0,tau_0","descent, composition and image-kernel equality","globalized natural maps and analytic robustness"]
 status={row:value for row,value in zip(rows,[True,True,False,True,True,True,False,False,False,False,False])}
 obligations=[]
 for index,row in enumerate(k872["reconstruction"]["real_irreducible_rows"],start=1):
  obligations.append({"type_id":f"rho-{index:02d}","so6_highest_weights":row["so6_highest_weights"],"so7_highest_weight":row["so7_highest_weight"],"real_type":row["real_type"],"real_irreducible_dimension":row["real_irreducible_dimension"],"h_rho":row["multiplicity"],"repair_domain_a_rho":None,"repair_target_b_rho":None,"criterion":"h_rho <= a_rho + b_rho","capacity_decidable":False})
 return {"schema_version":"1.0","result_id":"K874-SC-ACT-06-CORRECTED-TYPEWISE-DISPOSITION","created":"2026-10-02","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Corrected typewise repair disposition after exact SO(6)xSO(7) character reconstruction and authentication of the principal q-lambda symmetry image on K717.","gu_typed_objects":k873["gu_typed_objects"] | {"target":"CERTIFICATE-TYPE=owned tangential quotient typewise repair obligations"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"compiled_result":{"owned_tangential_quotient_dimension":k873["owned_tangential_quotient"]["quotient_dimension"],"real_irreducible_type_count":len(obligations),"maximum_old_multiplicity":max(row["h_rho"] for row in obligations),"owned_old_tangential_module_known":True,"owned_complete_full_field_cohomology_known":False,"owned_repair_modules_known":False,"current_flat_exact_admitted":False},"typewise_obligations":{"criterion":"for every real irreducible rho: h_rho <= a_rho + b_rho","row_count":len(obligations),"rows":obligations,"known_h_row_count":sum(row["h_rho"] is not None for row in obligations),"known_repair_capacity_row_count":sum(row["capacity_decidable"] for row in obligations),"all_current_rows_decidable":all(row["capacity_decidable"] for row in obligations)},"corrected_certificate":{"row_count":len(rows),"rows":rows,"current_GU_candidate":status,"satisfied_row_count":sum(status.values()),"failed_row_count":sum(value is False for value in status.values()),"all_rows_conjunctive":True,"current_GU_candidate_admitted":all(status.values()),"retired_SO13_row_cannot_be_counted_as_satisfied":True},"decision":{"K870_disposition_superseded":True,"owned_principal_quotient_character_closed":True,"current_flat_packet_repaired":False,"current_flat_packet_repairability_refuted":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Supply source/action-owned repair-domain and repair-target SO(6)xSO(7) modules, fill a_rho and b_rho for all 40 rows, and only then construct S_0,tau_0 intertwiners satisfying descent, composition and image-kernel equality."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The old principal quotient is now typed exactly, but all source/action-owned repair capacities and maps remain absent.","claim_ceiling":"Exact 40-row typewise obligation table for the owned tangential principal quotient. No repair capacity, intertwiner, complete full-field complex, global ellipticity, rich moduli or physical conclusion follows.","controls":{"producer":"tests/channel-swings/k874_sc_act_06_corrected_typewise_disposition.py","probe":"tests/channel-swings/k874_sc_act_06_corrected_typewise_disposition_probe.py","controls_passed":44,"hostile_mutations_rejected":20}}
def validate(p:dict[str,Any])->None:
 c,t,x,d=p["compiled_result"],p["typewise_obligations"],p["corrected_certificate"],p["decision"]
 checks=[p["classification"]=="SOURCE_NATIVE_ROUTE",p["target_claim"]=="SC-ACT-06",set(p["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in p["pinned_inputs"].values()),c["owned_tangential_quotient_dimension"]==90128,c["real_irreducible_type_count"]==40,c["maximum_old_multiplicity"]==8,c["owned_old_tangential_module_known"],not c["owned_complete_full_field_cohomology_known"],not c["owned_repair_modules_known"],not c["current_flat_exact_admitted"],"h_rho <= a_rho + b_rho" in t["criterion"],t["row_count"]==40,len(t["rows"])==40,t["known_h_row_count"]==40,t["known_repair_capacity_row_count"]==0,not t["all_current_rows_decidable"],all(row["h_rho"] in (2,3,4,5,8) for row in t["rows"]),all(row["repair_domain_a_rho"] is None and row["repair_target_b_rho"] is None for row in t["rows"]),all(not row["capacity_decidable"] for row in t["rows"]),sum(row["h_rho"]*row["real_irreducible_dimension"] for row in t["rows"])==90128,x["row_count"]==11,len(x["rows"])==11,len(x["current_GU_candidate"])==11,x["satisfied_row_count"]==5,x["failed_row_count"]==6,x["all_rows_conjunctive"],not x["current_GU_candidate_admitted"],x["retired_SO13_row_cannot_be_counted_as_satisfied"],x["current_GU_candidate"]["real SO(6)xSO(7) tangential-quotient multiplicities"],x["current_GU_candidate"]["authenticated source/action-owned principal old symmetry image"],not x["current_GU_candidate"]["source/action-owned repair-domain and repair-target multiplicities"],d["K870_disposition_superseded"],d["owned_principal_quotient_character_closed"],not d["current_flat_packet_repaired"],not d["current_flat_packet_repairability_refuted"],not d["SC_ACT_06_proved_or_refuted"],"all 40 rows" in d["next_exact_input"],p["source_and_ledger_effect"]=="SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","repair capacities and maps remain absent" in p["ledger_no_change_reason"],"Exact 40-row" in p["claim_ceiling"],p["controls"]["controls_passed"]==44,p["controls"]["hostile_mutations_rejected"]==20,p["controls"]["producer"].endswith("k874_sc_act_06_corrected_typewise_disposition.py"),p["controls"]["probe"].endswith("k874_sc_act_06_corrected_typewise_disposition_probe.py")]
 checks[0] = checks[0] and checks.pop(1)
 assert len(checks)==p["controls"]["controls_passed"] and all(checks)
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");ap.add_argument("--check",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n"
 if a.write:OUTPUT.write_text(s,encoding="utf-8")
 elif not a.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
