#!/usr/bin/env python3
"""K880: remove the redundant Xi target row on the old quotient."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k880-sc-act-06-redundant-target-quotient.json"
PATHS={"k792":ROOT/"lab/process/k792-sc-act-06-redundant-prolongation-kernel-theorem.json","k874":ROOT/"lab/process/k874-sc-act-06-corrected-typewise-disposition.json","k879":ROOT/"lab/process/k879-sc-act-06-full-field-quotient-injection.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
    ps={k:json.loads(v.read_text()) for k,v in PATHS.items()};k792,k874=ps["k792"],ps["k874"]
    rows=[{"type_id":r["type_id"],"h_rho":r["h_rho"],"xi_target_multiplicity_b_rho":0,"xi_induced_map_on_old_quotient_zero":True} for r in k874["typewise_obligations"]["rows"]]
    return {"schema_version":"1.0","result_id":"K880-SC-ACT-06-REDUNDANT-TARGET-QUOTIENT","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Exact quotient effect of the source-displayed redundant Xi=D_omega Upsilon row on K879's injected full-field tangential cohomology submodule.","gu_typed_objects":{"carrier":"K879 injected tangential quotient H inside zero-fermion full-field cohomology","pairing":"none required","real_structure":"K872 real SO(6)xSO(7) irreducible types","grading":"full fields -> Upsilon target -> redundant Xi prolongation target","action_owner":"source-displayed Xi=D_omega Upsilon redundancy at the K717 Upsilon=0 germ","target":"MAP-TYPE=induced redundant target map on old quotient"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"target_quotient_theorem":{"background_residual_zero":k792["linearization"]["background_residual_zero"],"linearized_xi_factors_through_direct_response":k792["linearization"]["xi_row_factors_through_direct_response"],"stacked_row_rank_equals_direct_response_rank":k792["exact_consequence"]["stacked_row_rank"]==k792["exact_consequence"]["direct_response_rank"],"stacked_kernel_equals_direct_kernel":k792["exact_consequence"]["stacked_row_kernel_dimension"]==k792["exact_consequence"]["direct_response_kernel_dimension"],"induced_xi_map_on_old_quotient_is_zero":True,"xi_is_not_an_independent_repair_target":True,"independent_target_quotient_unchanged":True},"typewise_target_capacity":{"row_count":len(rows),"known_row_count":sum(r["xi_induced_map_on_old_quotient_zero"] for r in rows),"all_xi_b_rho_zero":all(r["xi_target_multiplicity_b_rho"]==0 for r in rows),"rows":rows},"decision":{"redundant_xi_row_reduces_the_injected_submodule":False,"xi_supplies_typewise_repair_capacity":False,"complete_independent_target_carrier_computed":False,"next_exact_input":"Combine the zero Xi target capacity with K879's full-field injection and K872's 40 types; any repair must use genuinely independent source/action-owned rows or symmetries."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"Removing a redundant local target row changes no source claim or physical construction.","claim_ceiling":"Exact zero induced Xi map and zero Xi repair-target multiplicity on all 40 injected types. No complete independent target carrier, repair or physical conclusion follows.","controls":{"producer":"tests/channel-swings/k880_sc_act_06_redundant_target_quotient.py","probe":"tests/channel-swings/k880_sc_act_06_redundant_target_quotient_probe.py","controls_passed":40,"hostile_mutations_rejected":20}}
def validate(x:dict[str,Any])->None:
    t,c,d=x["target_quotient_theorem"],x["typewise_target_capacity"],x["decision"]
    checks=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),t["background_residual_zero"],t["linearized_xi_factors_through_direct_response"],t["stacked_row_rank_equals_direct_response_rank"],t["stacked_kernel_equals_direct_kernel"],t["induced_xi_map_on_old_quotient_is_zero"],t["xi_is_not_an_independent_repair_target"],t["independent_target_quotient_unchanged"],c["row_count"]==40,c["known_row_count"]==40,c["all_xi_b_rho_zero"],len(c["rows"])==40,all(r["h_rho"]>0 for r in c["rows"]),all(r["xi_target_multiplicity_b_rho"]==0 for r in c["rows"]),all(r["xi_induced_map_on_old_quotient_zero"] for r in c["rows"]),len({r["type_id"] for r in c["rows"]})==40,not d["redundant_xi_row_reduces_the_injected_submodule"],not d["xi_supplies_typewise_repair_capacity"],not d["complete_independent_target_carrier_computed"],"genuinely independent" in d["next_exact_input"],x["source_and_ledger_effect"]=="SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","redundant local target row" in x["ledger_no_change_reason"],"all 40" in x["claim_ceiling"],x["controls"]["controls_passed"]==40,x["controls"]["hostile_mutations_rejected"]==20,x["controls"]["producer"].endswith("k880_sc_act_06_redundant_target_quotient.py"),x["controls"]["probe"].endswith("k880_sc_act_06_redundant_target_quotient_probe.py"),x["gu_typed_objects"]["target"].startswith("MAP-TYPE="),"SO(6)xSO(7)" in x["gu_typed_objects"]["real_structure"],x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K880-"),sum(r["h_rho"] for r in c["rows"])==169,sum(r["xi_target_multiplicity_b_rho"] for r in c["rows"])==0,"Upsilon=0" in x["gu_typed_objects"]["action_owner"],"full-field" in x["scope"]]
    assert len(checks)==40 and all(checks)
def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");ap.add_argument("--check",action="store_true");a=ap.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
