#!/usr/bin/env python3
"""K889: preserve all 40 deficits because selected I1B has no induced map."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k889-sc-act-06-selected-i1b-typewise-nonadmission.json"
PATHS={"k884":ROOT/"lab/process/k884-sc-act-06-residual-square-typewise-capacity.json","k887":ROOT/"lab/process/k887-sc-act-06-selected-i1b-gauge-descent-obstruction.json","k888":ROOT/"lab/process/k888-sc-act-06-selected-i1b-gauge-defect-character.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 p={n:json.loads(path.read_text()) for n,path in PATHS.items()};defects={r["overlapping_old_type_id"]:r for r in p["k888"]["character_theorem"]["rows"]};rows=[]
 for r in p["k884"]["typewise_capacity"]["rows"]:
  z=defects.get(r["type_id"]);rows.append({"type_id":r["type_id"],"so6_highest_weights":r["so6_highest_weights"],"so7_highest_weight":r["so7_highest_weight"],"real_type":r["real_type"],"real_irreducible_dimension":r["real_irreducible_dimension"],"injected_multiplicity_lower_bound":r["injected_multiplicity_lower_bound"],"selected_i1b_induced_capacity":None,"selected_i1b_map_well_defined":False,"explicit_gauge_defect_multiplicity":z["gauge_defect_multiplicity"] if z else 0,"remaining_credited_deficit_lower_bound":r["remaining_deficit_lower_bound"]})
 return {"schema_version":"1.0","result_id":"K889-SC-ACT-06-SELECTED-I1B-TYPEWISE-NONADMISSION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Forty-type repair accounting after K887 proves the selected-I1B Hessian has no induced map on K879's authenticated quotient.","gu_typed_objects":{"carrier":"K884 forty-type injected obstruction submodule","pairing":"selected-I1B formal Euler pairing, rejected before quotient rank","real_structure":"K872 real SO(6)xSO(7) types","grading":"old cohomology quotient -> proposed selected-I1B target","action_owner":"frozen K132/K720 selected-I1B packet only","target":"INVENTORY-TYPE=typewise nonadmission, not a zero-rank assertion"},"pinned_inputs":{n:{"path":str(path.relative_to(ROOT)),"sha256":dg(path)} for n,path in PATHS.items()},"typewise_nonadmission":{"row_count":len(rows),"undefined_induced_rank_row_count":sum(r["selected_i1b_induced_capacity"] is None for r in rows),"rows_with_explicit_gauge_defect":sum(r["explicit_gauge_defect_multiplicity"]>0 for r in rows),"rows_without_explicit_defect_do_not_restore_global_descent":True,"sum_of_preserved_deficit_lower_bounds":sum(r["remaining_credited_deficit_lower_bound"] for r in rows),"dimension_of_preserved_deficit_lower_bound":sum(r["remaining_credited_deficit_lower_bound"]*r["real_irreducible_dimension"] for r in rows),"rows":rows},"decision":{"selected_i1b_capacity_is_zero":False,"selected_i1b_capacity_is_undefined_on_current_quotient":True,"any_of_40_deficits_credited_as_repaired":False,"completion_gate_satisfied_rows":5,"completion_gate_total_rows":11,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Restore gauge descent with a complete action-owned cancellation packet, then recompute all forty induced ranks; otherwise construct a genuinely new owned response/symmetry module or stationary germ."},"source_and_ledger_effect":"SC-ACT-01_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"Undefined local quotient ranks preserve the prior credited deficits and supply no physical quotient or verdict.","claim_ceiling":"Exact forty-type nonadmission of the current selected-I1B map. This is not a forty-type zero-rank theorem and does not exclude a completed action packet.","controls":{"producer":"tests/channel-swings/k889_sc_act_06_selected_i1b_typewise_nonadmission.py","probe":"tests/channel-swings/k889_sc_act_06_selected_i1b_typewise_nonadmission_probe.py","controls_passed":40,"hostile_mutations_rejected":20}}
def validate(x):
 t,d=x["typewise_nonadmission"],x["decision"];r=t["rows"];q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),t["row_count"]==40,t["undefined_induced_rank_row_count"]==40,t["rows_with_explicit_gauge_defect"]==16,t["rows_without_explicit_defect_do_not_restore_global_descent"],t["sum_of_preserved_deficit_lower_bounds"]==169,t["dimension_of_preserved_deficit_lower_bound"]==90128,len(r)==40,len({z["type_id"] for z in r})==40,all(z["selected_i1b_induced_capacity"] is None for z in r),all(not z["selected_i1b_map_well_defined"] for z in r),all(z["remaining_credited_deficit_lower_bound"]==z["injected_multiplicity_lower_bound"] for z in r),sum(z["explicit_gauge_defect_multiplicity"]>0 for z in r)==16,sum(z["explicit_gauge_defect_multiplicity"] for z in r)==55,not d["selected_i1b_capacity_is_zero"],d["selected_i1b_capacity_is_undefined_on_current_quotient"],not d["any_of_40_deficits_credited_as_repaired"],d["completion_gate_satisfied_rows"]==5,d["completion_gate_total_rows"]==11,not d["SC_ACT_06_proved_or_refuted"],"all forty" in d["next_exact_input"],x["source_and_ledger_effect"]=="SC-ACT-01_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","no physical quotient" in x["ledger_no_change_reason"],"not a forty-type zero-rank" in x["claim_ceiling"],x["controls"]["controls_passed"]==40,x["controls"]["hostile_mutations_rejected"]==20,x["gu_typed_objects"]["target"].startswith("INVENTORY-TYPE="),x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K889-"),all(z["real_irreducible_dimension"]>0 for z in r),all(z["injected_multiplicity_lower_bound"]>0 for z in r),sum(z["remaining_credited_deficit_lower_bound"]*z["real_irreducible_dimension"] for z in r)==90128,not d["selected_i1b_capacity_is_zero"] and d["selected_i1b_capacity_is_undefined_on_current_quotient"],t["undefined_induced_rank_row_count"]==t["row_count"],d["completion_gate_satisfied_rows"]<d["completion_gate_total_rows"]]
 assert len(q)==40 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
