#!/usr/bin/env python3
"""K890: disposition of the released independent selected-I1B parent."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k890-sc-act-06-independent-parent-disposition.json"
PATHS={"k874":ROOT/"lab/process/k874-sc-act-06-corrected-typewise-disposition.json","k885":ROOT/"lab/process/k885-sc-act-06-released-action-parent-quotient-inventory.json","k887":ROOT/"lab/process/k887-sc-act-06-selected-i1b-gauge-descent-obstruction.json","k888":ROOT/"lab/process/k888-sc-act-06-selected-i1b-gauge-defect-character.json","k889":ROOT/"lab/process/k889-sc-act-06-selected-i1b-typewise-nonadmission.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 p={n:json.loads(path.read_text()) for n,path in PATHS.items()};return {"schema_version":"1.0","result_id":"K890-SC-ACT-06-INDEPENDENT-PARENT-DISPOSITION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Disposition of the current released selected-I1B realization after exact gauge-descent and typewise nonadmission checks.","gu_typed_objects":{"carrier":"K879 injected quotient and K873 radial gauge image","pairing":"selected-I1B formal Euler pairing kept distinct from residual-square parents","real_structure":"K888 real SO(6)xSO(7) defect character","grading":"released parent -> gauge descent -> old quotient -> typewise capacity","action_owner":"current selected-I1B realization only; missing completion remains unowned","target":"DISPOSITION-TYPE=current independent parent boundary"},"pinned_inputs":{n:{"path":str(path.relative_to(ROOT)),"sha256":dg(path)} for n,path in PATHS.items()},"released_parent_disposition":{"residual_square_class":"closed_zero_quotient_capacity","selected_i1b_current_realization":"closed_as_nondescending_map","selected_i1b_independence_from_J":"preserved","selected_i1b_zero_on_quotient":"not_asserted","selected_i1b_complete_action_class":"open","source_silent_path_adapter":"unbuilt_not_credited","other_owned_response_or_symmetry":"absent_in_current_custody","other_stationary_germ":"open","nonzero_fermion_stationary_germ":"open"},"exact_effect":{"radial_gauge_dimension":16384,"selected_i1b_radial_defect_rank":8191,"defect_real_type_count":16,"old_obstruction_real_type_count":40,"credited_selected_i1b_repair_rows":0,"corrected_completion_gate_satisfied_rows":5,"corrected_completion_gate_total_rows":11},"decision":{"complete_flat_packet_repairability_refuted":False,"all_action_parents_exhausted":False,"current_released_parent_frontier_exhausted":True,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"A complete action-owned I1B completion must cancel the 8191-dimensional radial defect before quotient ranks; absent that input, construct a genuinely new owned response/symmetry module or a source-owned nonzero-fermion stationary germ."},"source_and_ledger_effect":"SC-ACT-01_03_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The current released-parent frontier is sharply classified but no complete action, physical state, observable, prediction or confirmation is constructed.","claim_ceiling":"Exact disposition of current released parents: residual squares induce zero, while selected I1B is independent but fails gauge descent. Future completions, new parents and other germs remain open.","controls":{"producer":"tests/channel-swings/k890_sc_act_06_independent_parent_disposition.py","probe":"tests/channel-swings/k890_sc_act_06_independent_parent_disposition_probe.py","controls_passed":38,"hostile_mutations_rejected":20}}
def validate(x):
 r,e,d=x["released_parent_disposition"],x["exact_effect"],x["decision"];q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),r["residual_square_class"]=="closed_zero_quotient_capacity",r["selected_i1b_current_realization"]=="closed_as_nondescending_map",r["selected_i1b_independence_from_J"]=="preserved",r["selected_i1b_zero_on_quotient"]=="not_asserted",r["selected_i1b_complete_action_class"]=="open",r["source_silent_path_adapter"]=="unbuilt_not_credited",r["other_owned_response_or_symmetry"]=="absent_in_current_custody",r["other_stationary_germ"]=="open",r["nonzero_fermion_stationary_germ"]=="open",e["radial_gauge_dimension"]==16384,e["selected_i1b_radial_defect_rank"]==8191,e["defect_real_type_count"]==16,e["old_obstruction_real_type_count"]==40,e["credited_selected_i1b_repair_rows"]==0,e["corrected_completion_gate_satisfied_rows"]==5,e["corrected_completion_gate_total_rows"]==11,not d["complete_flat_packet_repairability_refuted"],not d["all_action_parents_exhausted"],d["current_released_parent_frontier_exhausted"],not d["SC_ACT_06_proved_or_refuted"],"8191-dimensional" in d["next_exact_input"],x["source_and_ledger_effect"]=="SC-ACT-01_03_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","no complete action" in x["ledger_no_change_reason"],"selected I1B is independent" in x["claim_ceiling"],x["controls"]["controls_passed"]==38,x["controls"]["hostile_mutations_rejected"]==20,x["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K890-"),e["credited_selected_i1b_repair_rows"]==0 and e["old_obstruction_real_type_count"]==40,e["corrected_completion_gate_satisfied_rows"]<e["corrected_completion_gate_total_rows"]]
 q.append("gauge descent" in x["claim_ceiling"])
 assert len(q)==38 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();p=build();validate(p);s=json.dumps(p,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
