#!/usr/bin/env python3
"""K898: freeze the corrected action-owned completion boundary after Helmholtz classification."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k898-sc-act-06-corrected-action-completion-boundary.json"
PATHS={"k874":ROOT/"lab/process/k874-sc-act-06-corrected-typewise-disposition.json","k893":ROOT/"lab/process/k893-sc-act-06-released-block-cancellation-audit.json","k895":ROOT/"lab/process/k895-sc-act-06-helmholtz-symmetry-obstruction.json","k896":ROOT/"lab/process/k896-sc-act-06-formal-projector-integrability-audit.json","k897":ROOT/"lab/process/k897-sc-act-06-variational-completion-classification.json"}
def dg(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict[str,Any]:
 return {"schema_version":"1.0","result_id":"K898-SC-ACT-06-CORRECTED-ACTION-COMPLETION-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06",
 "scope":"Corrected admission boundary for any same-domain action-owned completion of the frozen selected-I1B formal Euler map after K895--K897.",
 "gu_typed_objects":{"carrier":"K717 fixed even bosonic field/gauge/Euler/preboundary domain","pairing":"one fixed nondegenerate real pairing through transpose, Euler and Green data","real_structure":"real SO(6)xSO(7) nonnull symbol","grading":"action ownership -> Hessian symmetry -> gauge descent -> old quotient -> forty ranks","action_owner":"future symmetric gauge-basic block S unresolved","target":"DISPOSITION-TYPE=corrected variational action-completion admission boundary"},
 "pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},
 "admission_boundary":{"same_germ":"K717 or a separately source-owned stationary germ with every block recomputed","same_common_domain":"field, gauge, Euler, transpose and preboundary/Green domains must coincide or be explicitly transported","completion_form":"C=-A+S","forced_skew_cancellation_rank":130912,"surviving_hessian":"T=S","helmholtz_identity":"S^T=S","gauge_identity":"SG=0","action_evidence":"derive nonzero S from a named source/action-owned field or gauge block","preboundary_evidence":"rederive the complete Euler linearization and Green/preboundary data for S","quotient_gate":"only an owned S satisfying every preceding row may be ranked on ker(J)/im(G)","formal_projector_disposition":"restores descent but fails Helmholtz symmetry at exact defect rank 130912"},
 "current_disposition":{"selected_formal_A_rank":130912,"selected_formal_A_action_hessian":False,"formal_projector_descends":True,"formal_projector_variational":False,"released_owned_nonzero_S_present":False,"forty_quotient_ranks_defined":False,"credited_quotient_repair_rows":0,"corrected_completion_gate_satisfied_rows":5,"corrected_completion_gate_total_rows":11,"SC_ACT_06_proved_or_refuted":False},
 "decision":{"current_selected_i1b_formal_map_closed_as_action_hessian":True,"all_completed_i1b_actions_exhausted":False,"all_action_parents_exhausted":False,"global_no_go_claimed":False,"next_exact_input":"Construct one named nonzero action-owned symmetric gauge-basic block S on the common domain and compute its forty quotient ranks; otherwise move to a genuinely new owned response/symmetry module or source-owned nonzero-fermion stationary germ."},
 "source_and_ledger_effect":"SC-ACT-01_03_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The corrected boundary rejects action-Hessian credit for A and its projector control but constructs no owned S or physical quotient.",
 "claim_ceiling":"Exact local variational admission boundary for the frozen same-domain even-bosonic packet. New symmetric parents, moving domains, odd sectors, boundary completions and other germs remain open.",
 "controls":{"producer":"tests/channel-swings/k898_sc_act_06_corrected_action_completion_boundary.py","probe":"tests/channel-swings/k898_sc_act_06_corrected_action_completion_boundary_probe.py","controls_passed":40,"hostile_mutations_rejected":20}}
def validate(x:dict[str,Any])->None:
 a,c,d=x["admission_boundary"],x["current_disposition"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),"source-owned stationary germ" in a["same_germ"],"preboundary/Green" in a["same_common_domain"],a["completion_form"]=="C=-A+S",a["forced_skew_cancellation_rank"]==130912,a["surviving_hessian"]=="T=S",a["helmholtz_identity"]=="S^T=S",a["gauge_identity"]=="SG=0","named source/action-owned" in a["action_evidence"],"complete Euler linearization" in a["preboundary_evidence"],"owned S" in a["quotient_gate"],"fails Helmholtz symmetry" in a["formal_projector_disposition"],c["selected_formal_A_rank"]==130912,not c["selected_formal_A_action_hessian"],c["formal_projector_descends"],not c["formal_projector_variational"],not c["released_owned_nonzero_S_present"],not c["forty_quotient_ranks_defined"],c["credited_quotient_repair_rows"]==0,c["corrected_completion_gate_satisfied_rows"]==5,c["corrected_completion_gate_total_rows"]==11,not c["SC_ACT_06_proved_or_refuted"],d["current_selected_i1b_formal_map_closed_as_action_hessian"],not d["all_completed_i1b_actions_exhausted"],not d["all_action_parents_exhausted"],not d["global_no_go_claimed"],"symmetric gauge-basic block S" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"constructs no owned S" in x["ledger_no_change_reason"],"New symmetric parents" in x["claim_ceiling"],x["controls"]["controls_passed"]==40,x["controls"]["hostile_mutations_rejected"]==20,x["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",c["corrected_completion_gate_satisfied_rows"]<c["corrected_completion_gate_total_rows"]]
 assert len(q)==40 and all(q),[i for i,v in enumerate(q) if not v]
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");z=p.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
