#!/usr/bin/env python3
"""K899: audit the released action-owned torsion Hessian on the radial gauge image."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/"lab/process/k899-sc-act-06-torsion-hessian-gauge-restriction.json"
PATHS={"k724":ROOT/"lab/process/k724-sc-act-06-kappa-zero-order-ellipticity-obstruction.json","k873":ROOT/"lab/process/k873-sc-act-06-owned-symmetry-custody.json","k891":ROOT/"lab/process/k891-sc-act-06-gauge-cancellation-necessity.json","k898":ROOT/"lab/process/k898-sc-act-06-corrected-action-completion-boundary.json"}
def dg(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 d={n:json.loads(p.read_text()) for n,p in PATHS.items()};k724,k873=d["k724"],d["k873"]
 radial=k873["owned_tangential_quotient"]["owned_radial_image_dimension"]
 return {"schema_version":"1.0","result_id":"K899-SC-ACT-06-TORSION-HESSIAN-GAUGE-RESTRICTION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Gauge-basic test of the source-owned algebraic torsion Hessian K on K873's authenticated radial connection-gauge image at K717.","gu_typed_objects":{"carrier":"K717 real 229376-dimensional even connection tangent","pairing":"K134 fixed real action pairing","real_structure":"Cl(7,7) real coefficient carrier under the common SO(6)xSO(7) stabilizer","grading":"internal gauge parameter --G--> connection tangent --K--> Euler dual","action_owner":"Hessian of (kappa_1/2)<T,*T>","target":"IDENTITY-TYPE=K G gauge restriction"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"restriction_theorem":{"K_is_action_owned":k724["zero_order_theorem"]["K_is_action_owned"],"K_is_symmetric_hessian":True,"K_is_involution":k724["zero_order_theorem"]["K_is_real_grade_preserving_involution"],"K_is_injective":k724["zero_order_theorem"]["K_is_nondegenerate_on_distortion_carrier"],"G_is_injective":k873["owned_image"]["map_injective"],"radial_domain_dimension":radial,"rank_KG":radial,"kernel_KG_dimension":0,"nonzero_kappa_K_is_gauge_basic":False,"required_identity":"S G=0"},"comparison":{"selected_A_restriction_rank":8191,"torsion_K_restriction_rank":radial,"torsion_block_cancels_selected_A_on_radial_image":False,"rank_mismatch_alone_is_not_the_proof":True,"decisive_fact":"K G is injective whereas a gauge-basic Hessian must annihilate im(G)"},"decision":{"released_torsion_hessian_is_admissible_nonzero_S":False,"torsion_action_parent_closed_as_gauge_basic_completion":True,"new_symmetric_action_parent_or_new_germ_still_open":True,"next_exact_input":"Classify the full released symmetric action-owned span kappa K + H_Q; gauge descent may force kappa=0, after which K883 controls the quotient."},"source_and_ledger_effect":"SC-ACT-01_04_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The exact gauge restriction rejects one released Hessian as the required S but constructs no physical quotient, state, observable, prediction or confirmation.","claim_ceiling":"Exact gauge-basic obstruction for the released kappa torsion Hessian at K717. It is not a no-go for another symmetric action parent, coupled-field cancellation, moving domain, boundary completion or other stationary germ.","controls":{"producer":"tests/channel-swings/k899_sc_act_06_torsion_hessian_gauge_restriction.py","probe":"tests/channel-swings/k899_sc_act_06_torsion_hessian_gauge_restriction_probe.py","controls_passed":32,"hostile_mutations_rejected":16}}
def validate(x):
 t,c,d=x["restriction_theorem"],x["comparison"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),t["K_is_action_owned"],t["K_is_symmetric_hessian"],t["K_is_involution"],t["K_is_injective"],t["G_is_injective"],t["radial_domain_dimension"]==16384,t["rank_KG"]==16384,t["kernel_KG_dimension"]==0,not t["nonzero_kappa_K_is_gauge_basic"],t["required_identity"]=="S G=0",c["selected_A_restriction_rank"]==8191,c["torsion_K_restriction_rank"]==16384,not c["torsion_block_cancels_selected_A_on_radial_image"],c["rank_mismatch_alone_is_not_the_proof"],"injective" in c["decisive_fact"],not d["released_torsion_hessian_is_admissible_nonzero_S"],d["torsion_action_parent_closed_as_gauge_basic_completion"],d["new_symmetric_action_parent_or_new_germ_still_open"],"kappa=0" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"constructs no physical quotient" in x["ledger_no_change_reason"],"not a no-go" in x["claim_ceiling"],x["controls"]["controls_passed"]==32,x["controls"]["hostile_mutations_rejected"]==16,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K899-")]
 assert len(q)==32 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
