#!/usr/bin/env python3
"""K900: classify the released symmetric action-owned span kappa K + H_Q."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k900-sc-act-06-released-symmetric-parent-classification.json"
PATHS={"k883":ROOT/"lab/process/k883-sc-act-06-residual-square-quotient-annihilation.json","k897":ROOT/"lab/process/k897-sc-act-06-variational-completion-classification.json","k899":ROOT/"lab/process/k899-sc-act-06-torsion-hessian-gauge-restriction.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K900-SC-ACT-06-RELEASED-SYMMETRIC-PARENT-CLASSIFICATION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Complete gauge-basic classification of the released symmetric action-owned linear span S_{kappa,Q}=kappa K+H_Q on K717.","gu_typed_objects":{"carrier":"K717 fixed even connection domain and K879 old quotient submodule","pairing":"K134 torsion-action pairing plus any symmetric residual pairing Q admitted by K743","real_structure":"real SO(6)xSO(7) symbol","grading":"fields --S_{kappa,Q}--> Euler dual, restricted to im(G) and old cohomology","action_owner":"released I1B torsion quadratic plus released I2B residual-norm-square class","target":"CLASSIFICATION-TYPE=released symmetric gauge-basic action parents"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"classification_theorem":{"family":"S_{kappa,Q}=kappa K+H_Q","both_summands_symmetric":True,"residual_square_gauge_identity":"H_Q G=0","torsion_restriction_identity":"rank(KG)=16384","family_gauge_restriction":"S_{kappa,Q}G=kappa K G","gauge_basic_iff":"kappa=0","admissible_released_family":"S_{0,Q}=H_Q","admissible_family_can_have_nonzero_raw_rank":True,"induced_map_on_K879_old_cohomology":"zero","induced_quotient_rank":0},"proof":{"if_kappa_zero":"H_Q G=0","if_gauge_basic":"kappa K G=0 and KG injective imply kappa=0","quotient":"Jh=0 implies H_Qh=J^*QJh=0","no_cross_cancellation":"H_QG is identically zero and therefore cannot cancel any nonzero kappa KG"},"decision":{"released_symmetric_action_owned_span_contains_nonzero_gauge_basic_raw_hessians":True,"released_span_contains_nonzero_gauge_basic_quotient_capacity":False,"released_span_repairs_any_old_type":False,"all_action_parents_exhausted":False,"next_exact_input":"Transfer the zero induced rank to all forty old types, then require a genuinely independent symmetric action parent or a source-owned nonzero-fermion stationary germ."},"source_and_ledger_effect":"SC-ACT-01_04_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The theorem closes one released parent span locally and changes no source attribution or physics-ledger row.","claim_ceiling":"Exact classification of the two currently released symmetric action-owned parent classes at K717. Coupled-field cross terms, new parents, moving domains, boundaries, odd sectors and other germs remain open.","controls":{"producer":"tests/channel-swings/k900_sc_act_06_released_symmetric_parent_classification.py","probe":"tests/channel-swings/k900_sc_act_06_released_symmetric_parent_classification_probe.py","controls_passed":36,"hostile_mutations_rejected":18}}
def validate(x):
 t,p,d=x["classification_theorem"],x["proof"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),t["family"]=="S_{kappa,Q}=kappa K+H_Q",t["both_summands_symmetric"],t["residual_square_gauge_identity"]=="H_Q G=0",t["torsion_restriction_identity"]=="rank(KG)=16384",t["family_gauge_restriction"]=="S_{kappa,Q}G=kappa K G",t["gauge_basic_iff"]=="kappa=0",t["admissible_released_family"]=="S_{0,Q}=H_Q",t["admissible_family_can_have_nonzero_raw_rank"],t["induced_map_on_K879_old_cohomology"]=="zero",t["induced_quotient_rank"]==0,"H_Q G=0" in p["if_kappa_zero"],"KG injective" in p["if_gauge_basic"],"Jh=0" in p["quotient"],"cannot cancel" in p["no_cross_cancellation"],d["released_symmetric_action_owned_span_contains_nonzero_gauge_basic_raw_hessians"],not d["released_span_contains_nonzero_gauge_basic_quotient_capacity"],not d["released_span_repairs_any_old_type"],not d["all_action_parents_exhausted"],"forty old types" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"changes no source attribution" in x["ledger_no_change_reason"],"currently released" in x["claim_ceiling"],x["controls"]["controls_passed"]==36,x["controls"]["hostile_mutations_rejected"]==18,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K900-"),t["induced_quotient_rank"]==0,not d["released_span_contains_nonzero_gauge_basic_quotient_capacity"],not d["released_span_repairs_any_old_type"],d["released_symmetric_action_owned_span_contains_nonzero_gauge_basic_raw_hessians"]]
 assert len(q)==36 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
