#!/usr/bin/env python3
"""K901: transfer released-parent zero capacity across all forty old quotient types."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k901-sc-act-06-released-parent-typewise-capacity.json"
PATHS={"k874":ROOT/"lab/process/k874-sc-act-06-corrected-typewise-disposition.json","k884":ROOT/"lab/process/k884-sc-act-06-residual-square-typewise-capacity.json","k900":ROOT/"lab/process/k900-sc-act-06-released-symmetric-parent-classification.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 k874=json.loads(PATHS["k874"].read_text());rows=[]
 for r in k874["typewise_obligations"]["rows"]:
  rows.append({"type_id":r["type_id"],"real_type":r["real_type"],"so6_highest_weights":r["so6_highest_weights"],"so7_highest_weight":r["so7_highest_weight"],"real_irreducible_dimension":r["real_irreducible_dimension"],"old_multiplicity_h_rho":r["h_rho"],"released_gauge_basic_capacity_rank":0,"remaining_multiplicity_deficit":r["h_rho"],"repaired":False})
 return {"schema_version":"1.0","result_id":"K901-SC-ACT-06-RELEASED-PARENT-TYPEWISE-CAPACITY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"SO(6)xSO(7)-typewise quotient capacity of the full released symmetric gauge-basic action-parent span classified by K900.","gu_typed_objects":{"carrier":"K874 forty-type 90128-dimensional old tangential quotient","pairing":"released symmetric parent pairings retained from K900","real_structure":"real SO(6)xSO(7) irreducible decomposition","grading":"released gauge-basic Hessian induced on old quotient","action_owner":"K900 admissible released family H_Q","target":"CAPACITY-TYPE=forty quotient ranks"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"typewise_capacity":{"row_count":len(rows),"rows":rows,"all_released_induced_ranks_zero":all(r["released_gauge_basic_capacity_rank"]==0 for r in rows),"all_occupied_types_unrepaired":all(not r["repaired"] for r in rows),"old_total_dimension":sum(r["real_irreducible_dimension"]*r["old_multiplicity_h_rho"] for r in rows),"old_total_real_multiplicity":sum(r["old_multiplicity_h_rho"] for r in rows),"released_total_quotient_rank":0,"remaining_type_deficit_count":sum(r["remaining_multiplicity_deficit"]>0 for r in rows)},"theorem":{"reason":"K900 forces every released gauge-basic symmetric parent to H_Q, and K883/K884 prove its induced map is zero","zero_map_is_equivariant":True,"raw_nonzero_hessian_rank_is_not_quotient_capacity":True,"forty_ranks_are_defined_for_released_admissible_class":True,"forty_ranks_are_all_zero":True},"decision":{"released_symmetric_parent_class_repairs_old_quotient":False,"all_forty_old_types_remain_deficient":True,"current_flat_packet_globally_refuted":False,"next_exact_input":"A genuinely independent source/action-owned symmetric gauge-basic response or symmetry block, or a source-owned nonzero-fermion stationary germ; do not retry any linear combination of K and H_Q."},"source_and_ledger_effect":"SC-ACT-01_04_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"All forty local ranks are zero only for the released parent span; no complete physical complex or observable is constructed.","claim_ceiling":"Exact forty-type zero-capacity theorem for the released symmetric action-parent span at K717. It does not cover unreleased cross terms, new parents, other domains or other stationary germs.","controls":{"producer":"tests/channel-swings/k901_sc_act_06_released_parent_typewise_capacity.py","probe":"tests/channel-swings/k901_sc_act_06_released_parent_typewise_capacity_probe.py","controls_passed":44,"hostile_mutations_rejected":20}}
def validate(x):
 t,h,d=x["typewise_capacity"],x["theorem"],x["decision"];rows=t["rows"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),t["row_count"]==40,len(rows)==40,len({r["type_id"] for r in rows})==40,t["all_released_induced_ranks_zero"],t["all_occupied_types_unrepaired"],t["old_total_dimension"]==90128,t["old_total_real_multiplicity"]==169,t["released_total_quotient_rank"]==0,t["remaining_type_deficit_count"]==40,all(r["released_gauge_basic_capacity_rank"]==0 for r in rows),all(r["remaining_multiplicity_deficit"]==r["old_multiplicity_h_rho"] for r in rows),all(not r["repaired"] for r in rows),all(r["old_multiplicity_h_rho"]>0 for r in rows),all(r["real_irreducible_dimension"]>0 for r in rows),"K900" in h["reason"] and "K883/K884" in h["reason"],h["zero_map_is_equivariant"],h["raw_nonzero_hessian_rank_is_not_quotient_capacity"],h["forty_ranks_are_defined_for_released_admissible_class"],h["forty_ranks_are_all_zero"],not d["released_symmetric_parent_class_repairs_old_quotient"],d["all_forty_old_types_remain_deficient"],not d["current_flat_packet_globally_refuted"],"do not retry" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"released parent span" in x["ledger_no_change_reason"],"does not cover" in x["claim_ceiling"],x["controls"]["controls_passed"]==44,x["controls"]["hostile_mutations_rejected"]==20,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K901-"),sum(r["old_multiplicity_h_rho"] for r in rows)==169,sum(r["real_irreducible_dimension"]*r["old_multiplicity_h_rho"] for r in rows)==90128,max(r["old_multiplicity_h_rho"] for r in rows)==8,min(r["old_multiplicity_h_rho"] for r in rows)>0,t["released_total_quotient_rank"]<t["old_total_dimension"],t["remaining_type_deficit_count"]==t["row_count"],not d["released_symmetric_parent_class_repairs_old_quotient"],d["all_forty_old_types_remain_deficient"]]
 assert len(q)==44 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
