#!/usr/bin/env python3
"""K902: freeze the released symmetric action-parent boundary."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k902-sc-act-06-released-symmetric-parent-boundary.json"
PATHS={"k898":ROOT/"lab/process/k898-sc-act-06-corrected-action-completion-boundary.json","k899":ROOT/"lab/process/k899-sc-act-06-torsion-hessian-gauge-restriction.json","k900":ROOT/"lab/process/k900-sc-act-06-released-symmetric-parent-classification.json","k901":ROOT/"lab/process/k901-sc-act-06-released-parent-typewise-capacity.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K902-SC-ACT-06-RELEASED-SYMMETRIC-PARENT-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Disposition of every linear combination of the currently released symmetric torsion and residual-square action parents after K899--K901.","gu_typed_objects":{"carrier":"K717 common even connection/gauge/Euler domain and K879 old quotient submodule","pairing":"released K and H_Q pairings only","real_structure":"real SO(6)xSO(7) nonnull symbol","grading":"released action parents -> gauge-basic Hessian -> forty old quotient types","action_owner":"SC-ACT-01 torsion quadratic and SC-ACT-04 residual-norm-square","target":"DISPOSITION-TYPE=released symmetric action-parent boundary"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"boundary":{"released_parent_span":"span{K,H_Q}","torsion_disposition":"nonzero coefficient forbidden by SG=0 because rank(KG)=16384","residual_square_disposition":"gauge-basic but zero on old cohomology","gauge_basic_released_span":"{H_Q}","forty_released_quotient_ranks":"all zero","repaired_old_types":0,"remaining_old_types":40,"old_obstruction_dimension":90128,"old_total_real_multiplicity":169,"corrected_completion_gate_satisfied_rows":5,"corrected_completion_gate_total_rows":11},"decision":{"released_symmetric_action_parent_span_closed":True,"selected_i1b_completed_by_released_span":False,"complete_flat_packet_refuted":False,"all_action_parents_exhausted":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Construct a genuinely independent source/action-owned symmetric gauge-basic block on the common domain, or recompute every block on a source-owned nonzero-fermion stationary germ. The released K/H_Q span must not be retried."},"source_and_ledger_effect":"SC-ACT-01_03_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The released-span closure is local to K717 and supplies no complete deformation complex, rich moduli, physical state, observable, prediction or confirmation.","claim_ceiling":"Exact local closure of the currently released symmetric K/H_Q action-parent span. Unreleased cross terms, new action parents, coupled-field cancellations, odd sectors, moving domains, boundaries and other stationary germs remain open.","controls":{"producer":"tests/channel-swings/k902_sc_act_06_released_symmetric_parent_boundary.py","probe":"tests/channel-swings/k902_sc_act_06_released_symmetric_parent_boundary_probe.py","controls_passed":40,"hostile_mutations_rejected":20}}
def validate(x):
 b,d=x["boundary"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),b["released_parent_span"]=="span{K,H_Q}","rank(KG)=16384" in b["torsion_disposition"],"zero on old cohomology" in b["residual_square_disposition"],b["gauge_basic_released_span"]=="{H_Q}",b["forty_released_quotient_ranks"]=="all zero",b["repaired_old_types"]==0,b["remaining_old_types"]==40,b["old_obstruction_dimension"]==90128,b["old_total_real_multiplicity"]==169,b["corrected_completion_gate_satisfied_rows"]==5,b["corrected_completion_gate_total_rows"]==11,d["released_symmetric_action_parent_span_closed"],not d["selected_i1b_completed_by_released_span"],not d["complete_flat_packet_refuted"],not d["all_action_parents_exhausted"],not d["SC_ACT_06_proved_or_refuted"],"must not be retried" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"supplies no complete deformation complex" in x["ledger_no_change_reason"],"Unreleased cross terms" in x["claim_ceiling"],x["controls"]["controls_passed"]==40,x["controls"]["hostile_mutations_rejected"]==20,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K902-"),b["repaired_old_types"]+b["remaining_old_types"]==40,b["corrected_completion_gate_satisfied_rows"]<b["corrected_completion_gate_total_rows"],not d["selected_i1b_completed_by_released_span"],d["released_symmetric_action_parent_span_closed"],not d["complete_flat_packet_refuted"],not d["all_action_parents_exhausted"],not d["SC_ACT_06_proved_or_refuted"],b["old_obstruction_dimension"]>0,b["remaining_old_types"]==40,b["repaired_old_types"]==0]
 assert len(q)==40 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
