#!/usr/bin/env python3
"""K903: split the full-field Ward identity when the gauge symbol is old-slot supported."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/"lab/process/k903-sc-act-06-full-field-ward-block-splitting.json"
PATHS={"k873":ROOT/"lab/process/k873-sc-act-06-owned-symmetry-custody.json","k897":ROOT/"lab/process/k897-sc-act-06-variational-completion-classification.json","k902":ROOT/"lab/process/k902-sc-act-06-released-symmetric-parent-boundary.json"}
def dg(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K903-SC-ACT-06-FULL-FIELD-WARD-BLOCK-SPLITTING","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Blockwise Ward identity for a symmetric full-field Hessian on X direct-sum Y when the authenticated principal internal-gauge map is G_full=(G,0).","gu_typed_objects":{"old_field":"K873 connection carrier X","added_fields":"arbitrary complementary even/odd body carrier Y at principal-symbol grade","gauge":"G_full=(G,0) with rank(G)=16384","hessian":"T=[[S,B^T],[B,D]]","target":"IDENTITY-TYPE=full-field Ward splitting"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"theorem":{"field_split":"X direct-sum Y","symmetric_hessian":"T=[[S,B^T],[B,D]]","old_supported_gauge":"G_full=(G,0)","ward_product":"T G_full=(S G,B G)","ward_iff":"S G=0 and B G=0","off_diagonal_cannot_cancel_old_euler_defect":True,"new_self_block_D_is_irrelevant_to_gauge_restriction":True,"converse":True},"proof":{"direct_sum":"The two components of (S G,B G) lie in independent Euler-dual summands X* and Y*.","necessity":"A direct-sum vector vanishes iff each component vanishes.","sufficiency":"S G=0 and B G=0 imply T(G,0)=0.","source_application":"K873 authenticates the principal internal-gauge symbol in the connection slot; other field components are zero at this grade."},"decision":{"coupled_cross_blocks_can_cancel_nonzero_SG":False,"coupled_cross_blocks_can_carry_independent_old_quotient_response":True,"future_cross_block_must_annihilate_gauge_image":True,"next_exact_input":"Apply the split identity to S=kappa K+H_Q, then compute the minimum quotient-target representation budget for B."},"source_and_ledger_effect":"SC-ACT-01_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The theorem types a necessary principal Ward condition and constructs no action, state, observable or complete complex.","claim_ceiling":"Exact block-linear theorem at K873's flat principal gauge grade. It does not cover a changed gauge symbol, nonzero-background gauge components, moving domains, boundary pairings or another germ.","controls":{"producer":"tests/channel-swings/k903_sc_act_06_full_field_ward_block_splitting.py","probe":"tests/channel-swings/k903_sc_act_06_full_field_ward_block_splitting_probe.py","controls_passed":36,"hostile_mutations_rejected":18}}
def validate(x):
 t,d=x["theorem"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),t["field_split"]=="X direct-sum Y",t["symmetric_hessian"]=="T=[[S,B^T],[B,D]]",t["old_supported_gauge"]=="G_full=(G,0)",t["ward_product"]=="T G_full=(S G,B G)",t["ward_iff"]=="S G=0 and B G=0",t["off_diagonal_cannot_cancel_old_euler_defect"],t["new_self_block_D_is_irrelevant_to_gauge_restriction"],t["converse"],"independent Euler-dual summands" in x["proof"]["direct_sum"],"iff each component" in x["proof"]["necessity"],"imply T(G,0)=0" in x["proof"]["sufficiency"],"K873" in x["proof"]["source_application"],not d["coupled_cross_blocks_can_cancel_nonzero_SG"],d["coupled_cross_blocks_can_carry_independent_old_quotient_response"],d["future_cross_block_must_annihilate_gauge_image"],"kappa K+H_Q" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"constructs no action" in x["ledger_no_change_reason"],"changed gauge symbol" in x["claim_ceiling"],x["controls"]["controls_passed"]==36,x["controls"]["hostile_mutations_rejected"]==18,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K903-"),t["ward_iff"].count("=0")==2,t["ward_product"].endswith("(S G,B G)"),not d["coupled_cross_blocks_can_cancel_nonzero_SG"],d["coupled_cross_blocks_can_carry_independent_old_quotient_response"],d["future_cross_block_must_annihilate_gauge_image"],"flat principal gauge grade" in x["claim_ceiling"],x["gu_typed_objects"]["gauge"].endswith("rank(G)=16384")]
 assert len(q)==36 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write: OUTPUT.write_text(s)
 elif not z.check: print(s,end="")
 return 0
if __name__=="__main__": raise SystemExit(main())
