#!/usr/bin/env python3
"""K904: apply K903 to the released K/H_Q diagonal with arbitrary cross block."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k904-sc-act-06-cross-block-gauge-noncancellation.json"
PATHS={"k899":ROOT/"lab/process/k899-sc-act-06-torsion-hessian-gauge-restriction.json","k900":ROOT/"lab/process/k900-sc-act-06-released-symmetric-parent-classification.json","k903":ROOT/"lab/process/k903-sc-act-06-full-field-ward-block-splitting.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K904-SC-ACT-06-CROSS-BLOCK-GAUGE-NONCANCELLATION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Full-field symmetric Hessians whose old connection diagonal is the released S_{kappa,Q}=kappa K+H_Q and whose authenticated principal gauge map is (G,0), with arbitrary off-diagonal B and new self-block D.","gu_typed_objects":{"hessian":"T=[[kappa K+H_Q,B^T],[B,D]]","gauge":"G_full=(G,0)","old_quotient":"K879 forty-type H_old","target":"CLASSIFICATION-TYPE=released diagonal plus arbitrary coupled cross block"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"classification_theorem":{"ward_product":"T G_full=(kappa K G,B G)","uses":"H_Q G=0","old_euler_condition":"kappa K G=0","cross_euler_condition":"B G=0","gauge_basic_iff":"kappa=0 and B G=0","off_diagonal_B_cannot_rescue_nonzero_kappa":True,"new_self_block_D_unconstrained_by_this_identity":True,"cross_response_on_old_cohomology":"[h] maps to B h because H_Q h=0","cross_response_is_new_capacity_not_cancellation":True},"decision":{"released_nonzero_torsion_coefficient_reopened_by_cross_coupling":False,"gauge_basic_cross_coupling_remains_open":True,"cross_coupling_requires_independent_action_ownership":True,"next_exact_input":"Compute the necessary dimension and SO(6)xSO(7) multiplicity budget for an induced B_bar injective on the 90128-dimensional old quotient."},"source_and_ledger_effect":"SC-ACT-01_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The classification narrows a coupled repair route but constructs no cross block or physical complex.","claim_ceiling":"Exact classification only while the old diagonal remains in the released K/H_Q span and the principal gauge vector is (G,0). A new old-old block, changed gauge components, moving domain, boundary completion or other germ remains open.","controls":{"producer":"tests/channel-swings/k904_sc_act_06_cross_block_gauge_noncancellation.py","probe":"tests/channel-swings/k904_sc_act_06_cross_block_gauge_noncancellation_probe.py","controls_passed":38,"hostile_mutations_rejected":18}}
def validate(x):
 t,d=x["classification_theorem"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),t["ward_product"]=="T G_full=(kappa K G,B G)",t["uses"]=="H_Q G=0",t["old_euler_condition"]=="kappa K G=0",t["cross_euler_condition"]=="B G=0",t["gauge_basic_iff"]=="kappa=0 and B G=0",t["off_diagonal_B_cannot_rescue_nonzero_kappa"],t["new_self_block_D_unconstrained_by_this_identity"],t["cross_response_on_old_cohomology"]=="[h] maps to B h because H_Q h=0",t["cross_response_is_new_capacity_not_cancellation"],not d["released_nonzero_torsion_coefficient_reopened_by_cross_coupling"],d["gauge_basic_cross_coupling_remains_open"],d["cross_coupling_requires_independent_action_ownership"],"90128-dimensional" in d["next_exact_input"],"SO(6)xSO(7)" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"constructs no cross block" in x["ledger_no_change_reason"],"old diagonal remains" in x["claim_ceiling"],x["controls"]["controls_passed"]==38,x["controls"]["hostile_mutations_rejected"]==18,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K904-"),"kappa K+H_Q" in x["scope"],"arbitrary off-diagonal B" in x["scope"],t["old_euler_condition"].startswith("kappa"),t["cross_euler_condition"].startswith("B"),t["gauge_basic_iff"].count("=0")==2,not d["released_nonzero_torsion_coefficient_reopened_by_cross_coupling"],d["gauge_basic_cross_coupling_remains_open"],d["cross_coupling_requires_independent_action_ownership"],"changed gauge components" in x["claim_ceiling"],x["gu_typed_objects"]["gauge"]=="G_full=(G,0)",x["gu_typed_objects"]["old_quotient"].startswith("K879")]
 assert len(q)==38 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
