#!/usr/bin/env python3
"""K905: compute the necessary typewise target budget for a cross-only repair."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k905-sc-act-06-cross-target-typewise-budget.json"
PATHS={"k874":ROOT/"lab/process/k874-sc-act-06-corrected-typewise-disposition.json","k901":ROOT/"lab/process/k901-sc-act-06-released-parent-typewise-capacity.json","k904":ROOT/"lab/process/k904-sc-act-06-cross-block-gauge-noncancellation.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 k=json.loads(PATHS["k874"].read_text());rows=[]
 for r in k["typewise_obligations"]["rows"]:
  rows.append({"type_id":r["type_id"],"real_type":r["real_type"],"so6_highest_weights":r["so6_highest_weights"],"so7_highest_weight":r["so7_highest_weight"],"real_irreducible_dimension":r["real_irreducible_dimension"],"old_multiplicity_h_rho":r["h_rho"],"minimum_cross_target_multiplicity_for_injectivity":r["h_rho"],"minimum_cross_target_dimension":r["real_irreducible_dimension"]*r["h_rho"]})
 return {"schema_version":"1.0","result_id":"K905-SC-ACT-06-CROSS-TARGET-TYPEWISE-BUDGET","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Necessary SO(6)xSO(7)-equivariant target budget for a gauge-basic cross block B_bar to be injective on K874's old quotient when the released diagonal acts trivially there.","gu_typed_objects":{"domain":"K874 old quotient H_old","map":"B_bar:H_old->Y*","condition":"injective equivariant repair on the authenticated old obstruction submodule","target":"CAPACITY-TYPE=cross-target multiplicity budget"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"budget":{"row_count":len(rows),"rows":rows,"minimum_total_real_dimension":sum(r["minimum_cross_target_dimension"] for r in rows),"minimum_total_real_multiplicity":sum(r["minimum_cross_target_multiplicity_for_injectivity"] for r in rows),"occupied_real_type_count":len(rows),"all_forty_types_required":True,"injectivity_required_for_complete_old_submodule_repair":True},"theorem":{"schur_multiplicity_condition":"For each real irreducible type rho, target multiplicity b_rho must satisfy b_rho>=h_rho for an equivariant injection.","dimension_condition":"dim(Y*)>=90128","necessity_not_sufficiency":True,"partial_cross_rank_can_only_repair_its_actual_image":True,"raw_target_dimension_without_intertwiners_is_not_capacity":True},"decision":{"cross_only_complete_repair_requires_all_forty_types":True,"cross_only_complete_repair_minimum_dimension":90128,"cross_only_complete_repair_minimum_real_multiplicity":169,"current_released_zero_fermion_mixed_blocks_meet_budget":False,"next_exact_input":"Construct and action-own B with BG=0 and the complete forty-type target/intertwiner inventory, or supply a new gauge-basic old-old symmetric block or another stationary germ."},"source_and_ledger_effect":"SC-ACT-01_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The budget is a necessary representation condition and supplies no cross operator, stationary solution or physical quotient.","claim_ceiling":"Exact necessary budget on the authenticated 90128-dimensional old submodule only. It is not sufficient for a complex, exactness, analytic globalization or SC-ACT-06.","controls":{"producer":"tests/channel-swings/k905_sc_act_06_cross_target_typewise_budget.py","probe":"tests/channel-swings/k905_sc_act_06_cross_target_typewise_budget_probe.py","controls_passed":44,"hostile_mutations_rejected":20}}
def validate(x):
 b,t,d=x["budget"],x["theorem"],x["decision"];rows=b["rows"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),b["row_count"]==40,len(rows)==40,len({r["type_id"] for r in rows})==40,b["minimum_total_real_dimension"]==90128,b["minimum_total_real_multiplicity"]==169,b["occupied_real_type_count"]==40,b["all_forty_types_required"],b["injectivity_required_for_complete_old_submodule_repair"],all(r["minimum_cross_target_multiplicity_for_injectivity"]==r["old_multiplicity_h_rho"] for r in rows),all(r["minimum_cross_target_dimension"]==r["real_irreducible_dimension"]*r["old_multiplicity_h_rho"] for r in rows),sum(r["minimum_cross_target_dimension"] for r in rows)==90128,sum(r["minimum_cross_target_multiplicity_for_injectivity"] for r in rows)==169,"b_rho>=h_rho" in t["schur_multiplicity_condition"],t["dimension_condition"]=="dim(Y*)>=90128",t["necessity_not_sufficiency"],t["partial_cross_rank_can_only_repair_its_actual_image"],t["raw_target_dimension_without_intertwiners_is_not_capacity"],d["cross_only_complete_repair_requires_all_forty_types"],d["cross_only_complete_repair_minimum_dimension"]==90128,d["cross_only_complete_repair_minimum_real_multiplicity"]==169,not d["current_released_zero_fermion_mixed_blocks_meet_budget"],"BG=0" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"necessary representation condition" in x["ledger_no_change_reason"],"not sufficient" in x["claim_ceiling"],x["controls"]["controls_passed"]==44,x["controls"]["hostile_mutations_rejected"]==20,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K905-"),max(r["old_multiplicity_h_rho"] for r in rows)==8,min(r["old_multiplicity_h_rho"] for r in rows)>0,b["minimum_total_real_dimension"]==d["cross_only_complete_repair_minimum_dimension"],b["minimum_total_real_multiplicity"]==d["cross_only_complete_repair_minimum_real_multiplicity"],b["occupied_real_type_count"]==40,all(r["minimum_cross_target_dimension"]>0 for r in rows),t["necessity_not_sufficiency"],not d["current_released_zero_fermion_mixed_blocks_meet_budget"],d["cross_only_complete_repair_requires_all_forty_types"],x["gu_typed_objects"]["map"]=="B_bar:H_old->Y*"]
 assert len(q)==45 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
