#!/usr/bin/env python3
"""K907: certify cross-map injectivity versus adjoint surjectivity."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k907-sc-act-06-cross-adjoint-rank-equivalence.json"
PATHS={"k903":ROOT/"lab/process/k903-sc-act-06-full-field-ward-block-splitting.json","k905":ROOT/"lab/process/k905-sc-act-06-cross-target-typewise-budget.json","k906":ROOT/"lab/process/k906-sc-act-06-coupled-repair-boundary.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K907-SC-ACT-06-CROSS-ADJOINT-RANK-EQUIVALENCE","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Finite-dimensional paired-space criterion for a gauge-basic cross map on K905's authenticated old quotient.","gu_typed_objects":{"old_quotient":"H_old, dimension 90128, forty real types, multiplicity 169","cross_map":"B_bar:H_old->Y*","adjoint":"B_bar*:Y->H_old*","pairings":"nondegenerate finite-dimensional real pairings","target":"THEOREM-TYPE=cross-adjoint rank equivalence"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"theorem":{"rank_identity":"rank(B_bar)=rank(B_bar*)","old_kernel_eliminated_iff":"B_bar is injective","old_cokernel_eliminated_iff":"B_bar* is surjective","injective_iff_adjoint_surjective":True,"injective_rank":90128,"minimum_target_dimension":90128,"adjoint_kernel_dimension_formula":"dim ker(B_bar*)=dim(Y)-90128 when B_bar is injective","symmetric_cross_pair_controls_both_old_sides":True},"decision":{"one_sided_rank_check_sufficient_for_old_pair":True,"raw_target_dimension_alone_sufficient":False,"action_owned_cross_map_still_required":True,"full_coupled_nondegeneracy_decided":False,"next_exact_input":"Resolve the minimal-target and surplus-target cases of the full symmetric block separately."},"source_and_ledger_effect":"SC-ACT-01_04_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The theorem is finite-dimensional linear algebra on the authenticated old quotient and supplies no action-owned cross operator or physical quotient.","claim_ceiling":"Exact rank equivalence only under nondegenerate finite-dimensional pairings on K905's old quotient. It does not construct B_bar or prove the full deformation complex.","controls":{"producer":"tests/channel-swings/k907_sc_act_06_cross_adjoint_rank_equivalence.py","probe":"tests/channel-swings/k907_sc_act_06_cross_adjoint_rank_equivalence_probe.py","controls_passed":38,"hostile_mutations_rejected":20}}
def validate(x):
 t,d=x["theorem"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),x["gu_typed_objects"]["cross_map"]=="B_bar:H_old->Y*",x["gu_typed_objects"]["adjoint"]=="B_bar*:Y->H_old*","nondegenerate" in x["gu_typed_objects"]["pairings"],t["rank_identity"]=="rank(B_bar)=rank(B_bar*)",t["old_kernel_eliminated_iff"]=="B_bar is injective",t["old_cokernel_eliminated_iff"]=="B_bar* is surjective",t["injective_iff_adjoint_surjective"],t["injective_rank"]==90128,t["minimum_target_dimension"]==90128,"dim(Y)-90128" in t["adjoint_kernel_dimension_formula"],t["symmetric_cross_pair_controls_both_old_sides"],d["one_sided_rank_check_sufficient_for_old_pair"],not d["raw_target_dimension_alone_sufficient"],d["action_owned_cross_map_still_required"],not d["full_coupled_nondegeneracy_decided"],"minimal-target" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"supplies no action-owned" in x["ledger_no_change_reason"],"does not construct" in x["claim_ceiling"],x["controls"]["controls_passed"]==38,x["controls"]["hostile_mutations_rejected"]==20,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K907-"),"90128" in x["gu_typed_objects"]["old_quotient"],"forty" in x["gu_typed_objects"]["old_quotient"],t["minimum_target_dimension"]==t["injective_rank"],d["action_owned_cross_map_still_required"],not d["full_coupled_nondegeneracy_decided"],t["injective_iff_adjoint_surjective"],t["symmetric_cross_pair_controls_both_old_sides"],"paired-space" in x["scope"]]
 assert len(q)==37 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
