#!/usr/bin/env python3
"""K908: classify the exact-minimum equivariant cross target."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k908-sc-act-06-minimal-target-isotypic-isomorphism.json"
PATHS={"k905":ROOT/"lab/process/k905-sc-act-06-cross-target-typewise-budget.json","k907":ROOT/"lab/process/k907-sc-act-06-cross-adjoint-rank-equivalence.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 k=json.loads(PATHS["k905"].read_text());rows=[{"type_id":r["type_id"],"real_irreducible_dimension":r["real_irreducible_dimension"],"old_multiplicity_h_rho":r["old_multiplicity_h_rho"],"minimal_target_multiplicity_b_rho":r["old_multiplicity_h_rho"],"cross_block_condition":"invertible on multiplicity space"} for r in k["budget"]["rows"]]
 return {"schema_version":"1.0","result_id":"K908-SC-ACT-06-MINIMAL-TARGET-ISOTYPIC-ISOMORPHISM","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Exact-minimum SO(6)xSO(7)-equivariant target classification for an injective cross repair on K905's old quotient.","gu_typed_objects":{"domain":"H_old","minimal_target_dual":"Y* congruent to H_old as a real SO(6)xSO(7) module","cross_map":"B_bar:H_old->Y*","target":"THEOREM-TYPE=minimal-target isotypic isomorphism"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"minimal_target":{"total_real_dimension":90128,"total_real_multiplicity":169,"occupied_real_type_count":40,"row_count":len(rows),"rows":rows,"all_type_multiplicities_saturated":True},"theorem":{"dimension_equality_plus_injectivity_implies_isomorphism":True,"equivariant_isomorphism_requires_every_type_block_invertible":True,"minimal_character_matches_old_quotient":True,"no_unused_target_complement":True,"adjoint_isomorphism":True},"decision":{"minimal_target_can_be_checked_typewise":True,"mere_character_match_constructs_cross_map":False,"action_ownership_and_BG_zero_still_required":True,"next_exact_input":"Determine whether a symmetric block with isomorphic cross map needs any condition on its new-field self-block D."},"source_and_ledger_effect":"SC-ACT-01_04_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The isotypic theorem classifies a hypothetical exact-minimum target but constructs no action-owned intertwiner.","claim_ceiling":"Exact finite-dimensional equivariant classification only; character equality is not an action, Ward identity, Green operator or preboundary complex.","controls":{"producer":"tests/channel-swings/k908_sc_act_06_minimal_target_isotypic_isomorphism.py","probe":"tests/channel-swings/k908_sc_act_06_minimal_target_isotypic_isomorphism_probe.py","controls_passed":42,"hostile_mutations_rejected":20}}
def validate(x):
 b,t,d=x["minimal_target"],x["theorem"],x["decision"];rows=b["rows"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),b["total_real_dimension"]==90128,b["total_real_multiplicity"]==169,b["occupied_real_type_count"]==40,b["row_count"]==40,len(rows)==40,len({r["type_id"] for r in rows})==40,all(r["minimal_target_multiplicity_b_rho"]==r["old_multiplicity_h_rho"] for r in rows),sum(r["real_irreducible_dimension"]*r["minimal_target_multiplicity_b_rho"] for r in rows)==90128,sum(r["minimal_target_multiplicity_b_rho"] for r in rows)==169,all(r["cross_block_condition"]=="invertible on multiplicity space" for r in rows),b["all_type_multiplicities_saturated"],t["dimension_equality_plus_injectivity_implies_isomorphism"],t["equivariant_isomorphism_requires_every_type_block_invertible"],t["minimal_character_matches_old_quotient"],t["no_unused_target_complement"],t["adjoint_isomorphism"],d["minimal_target_can_be_checked_typewise"],not d["mere_character_match_constructs_cross_map"],d["action_ownership_and_BG_zero_still_required"],"self-block D" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"constructs no action-owned" in x["ledger_no_change_reason"],"character equality is not an action" in x["claim_ceiling"],x["controls"]["controls_passed"]==42,x["controls"]["hostile_mutations_rejected"]==20,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K908-"),x["gu_typed_objects"]["cross_map"]=="B_bar:H_old->Y*","congruent" in x["gu_typed_objects"]["minimal_target_dual"],max(r["old_multiplicity_h_rho"] for r in rows)==8,min(r["old_multiplicity_h_rho"] for r in rows)>0,b["row_count"]==b["occupied_real_type_count"],t["no_unused_target_complement"],not d["mere_character_match_constructs_cross_map"],d["action_ownership_and_BG_zero_still_required"],"equivariant target classification" in x["scope"]]
 assert len(q)==42 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
