#!/usr/bin/env python3
"""K909: prove the exact surplus-complement criterion for the symmetric block."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k909-sc-act-06-surplus-complement-compression.json"
PATHS={"k907":ROOT/"lab/process/k907-sc-act-06-cross-adjoint-rank-equivalence.json","k908":ROOT/"lab/process/k908-sc-act-06-minimal-target-isotypic-isomorphism.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K909-SC-ACT-06-SURPLUS-COMPLEMENT-COMPRESSION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Kernel criterion for T=[[0,B_bar*],[B_bar,D]] after an injective cross map repairs the authenticated old quotient.","gu_typed_objects":{"coupled_block":"T on H_old direct_sum Y","cross_map":"B_bar:H_old->Y* injective","riesz_range":"R=im(tilde B_bar) subset Y","surplus_complement":"K=ker(B_bar*)=R_perp","compression":"D_KK=P_K D restricted to K","target":"THEOREM-TYPE=surplus-complement compression criterion"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"theorem":{"orthogonal_split":"Y=R direct_sum K","kernel_isomorphism":"ker(T) congruent to ker(D_KK)","full_block_nondegenerate_iff":"D_KK is nondegenerate on K","minimal_target_has_K_dimension":0,"minimal_target_full_block_nondegenerate_for_every_D":True,"surplus_dimension_formula":"dim(K)=dim(Y)-90128","surplus_cross_rank_does_not_control_D_KK":True,"proof_route":["The H_old equation B_bar* y=0 forces y into K.","The R component of the Y equation uniquely solves h because B_bar:H_old->R is an isomorphism.","The remaining K component is exactly D_KK y=0."]},"synthetic_controls":{"case":"H=R^1, Y=R^2, B(h)=(h,0)","singular_D_KK":{"D":"zero matrix","kernel_dimension":1},"invertible_D_KK":{"D":"diag(0,1)","kernel_dimension":0},"minimal_case":"H=Y=R^1 with B=1 is nondegenerate for arbitrary scalar D"},"decision":{"minimum_budget_plus_injective_B_suffices_for_block_nondegeneracy":True,"surplus_target_requires_action_owned_complement_self_block":True,"target_character_and_cross_rank_alone_suffice_in_surplus_case":False,"full_deformation_complex_proved":False,"next_exact_input":"For a surplus target, provide D_KK with its action ownership, domain, Green and preboundary data; at the minimum target, provide the named action-owned gauge-basic isomorphism B_bar."},"source_and_ledger_effect":"SC-ACT-01_04_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The compression theorem decides a hypothetical finite-dimensional block but supplies neither the cross map nor the complementary action Hessian.","claim_ceiling":"Exact finite-dimensional paired-space criterion only. It does not establish ellipticity, gauge-complex exactness, Green operators, boundary compatibility or SC-ACT-06.","controls":{"producer":"tests/channel-swings/k909_sc_act_06_surplus_complement_compression.py","probe":"tests/channel-swings/k909_sc_act_06_surplus_complement_compression_probe.py","controls_passed":43,"hostile_mutations_rejected":20}}
def validate(x):
 t,s,d=x["theorem"],x["synthetic_controls"],x["decision"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),x["gu_typed_objects"]["cross_map"].endswith("injective"),x["gu_typed_objects"]["surplus_complement"]=="K=ker(B_bar*)=R_perp",x["gu_typed_objects"]["compression"]=="D_KK=P_K D restricted to K",t["orthogonal_split"]=="Y=R direct_sum K",t["kernel_isomorphism"]=="ker(T) congruent to ker(D_KK)",t["full_block_nondegenerate_iff"]=="D_KK is nondegenerate on K",t["minimal_target_has_K_dimension"]==0,t["minimal_target_full_block_nondegenerate_for_every_D"],"dim(Y)-90128" in t["surplus_dimension_formula"],t["surplus_cross_rank_does_not_control_D_KK"],len(t["proof_route"])==3,"forces y into K" in t["proof_route"][0],"uniquely solves h" in t["proof_route"][1],"exactly D_KK" in t["proof_route"][2],s["singular_D_KK"]["kernel_dimension"]==1,s["invertible_D_KK"]["kernel_dimension"]==0,"arbitrary scalar D" in s["minimal_case"],d["minimum_budget_plus_injective_B_suffices_for_block_nondegeneracy"],d["surplus_target_requires_action_owned_complement_self_block"],not d["target_character_and_cross_rank_alone_suffice_in_surplus_case"],not d["full_deformation_complex_proved"],"D_KK" in d["next_exact_input"],"Green" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"supplies neither" in x["ledger_no_change_reason"],"does not establish ellipticity" in x["claim_ceiling"],x["controls"]["controls_passed"]==43,x["controls"]["hostile_mutations_rejected"]==20,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K909-"),"T=[[0,B_bar*],[B_bar,D]]" in x["scope"],s["case"].startswith("H=R^1"),s["singular_D_KK"]["D"]=="zero matrix",s["invertible_D_KK"]["D"]=="diag(0,1)",t["minimal_target_full_block_nondegenerate_for_every_D"],t["surplus_cross_rank_does_not_control_D_KK"],d["surplus_target_requires_action_owned_complement_self_block"],not d["full_deformation_complex_proved"]]
 assert len(q)==44 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
