#!/usr/bin/env python3
"""K910: freeze the exact cross-completion admission boundary."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k910-sc-act-06-cross-completion-admission-boundary.json"
PATHS={"k875":ROOT/"lab/process/k875-sc-act-06-zero-fermion-mixed-block-vanishing.json","k906":ROOT/"lab/process/k906-sc-act-06-coupled-repair-boundary.json","k907":ROOT/"lab/process/k907-sc-act-06-cross-adjoint-rank-equivalence.json","k908":ROOT/"lab/process/k908-sc-act-06-minimal-target-isotypic-isomorphism.json","k909":ROOT/"lab/process/k909-sc-act-06-surplus-complement-compression.json"}
def dg(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K910-SC-ACT-06-CROSS-COMPLETION-ADMISSION-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Admission boundary for a future action-owned symmetric cross completion of K906's released old quotient obstruction.","gu_typed_objects":{"old_quotient":"H_old: dimension 90128, forty real types, multiplicity 169","cross_map":"B_bar:H_old->Y* with B G=0","coupled_block":"T=[[0,B_bar*],[B_bar,D]]","target":"DISPOSITION-TYPE=cross-completion admission boundary"},"pinned_inputs":{n:{"path":str(p.relative_to(ROOT)),"sha256":dg(p)} for n,p in PATHS.items()},"admission":{"common_requirements":["named action ownership for B and D","B G=0 on the authenticated principal gauge image","B_bar injective on all forty old types","compatible domains, Green operators and preboundary data"],"minimal_target":{"dimension":90128,"multiplicity":169,"character":"exactly H_old","extra_algebraic_requirement":"none beyond injective B_bar; it is then an isomorphism","full_symmetric_block_nondegenerate_for_arbitrary_D":True},"surplus_target":{"dimension":">90128","unused_complement":"K=ker(B_bar*)","extra_algebraic_requirement":"D_KK=P_K D|K nondegenerate","cross_rank_alone_sufficient":False},"released_zero_fermion_mixed_capacity":0,"released_inventory_admitted":False,"corrected_completion_gate_satisfied_rows":5,"corrected_completion_gate_total_rows":11},"decision":{"minimal_hypothetical_sufficiency_now_exact":True,"surplus_hypothetical_sufficiency_now_exact":True,"current_action_owned_B_available":False,"current_action_owned_D_KK_available":False,"cross_completion_constructed":False,"SC_ACT_06_proved_or_refuted":False,"distance_only_cross_budget_waves_exhausted":True,"next_exact_input":"Provide a named source/action-owned gauge-basic B_bar meeting the full forty-type budget and complete domain/Green/preboundary data; if Y is larger than minimal, also provide nondegenerate D_KK. Otherwise switch route to a new old-old block, changed gauge/domain, or source-owned nonzero-fermion germ."},"source_and_ledger_effect":"SC-ACT-01_03_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The boundary makes hypothetical sufficiency exact but the released inventory contains no admitted cross map or complement Hessian.","claim_ceiling":"Exact local finite-dimensional admission theorem for the released germ only. It does not provide an action, elliptic complex, globalization, physical quotient or SC-ACT-06.","controls":{"producer":"tests/channel-swings/k910_sc_act_06_cross_completion_admission_boundary.py","probe":"tests/channel-swings/k910_sc_act_06_cross_completion_admission_boundary_probe.py","controls_passed":45,"hostile_mutations_rejected":20}}
def validate(x):
 a,d=x["admission"],x["decision"];m,s=a["minimal_target"],a["surplus_target"]
 q=[x["classification"]=="SOURCE_NATIVE_ROUTE",x["target_claim"]=="SC-ACT-06",set(x["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in x["pinned_inputs"].values()),len(a["common_requirements"])==4,"named action ownership" in a["common_requirements"][0],a["common_requirements"][1].startswith("B G=0"),"all forty" in a["common_requirements"][2],"Green" in a["common_requirements"][3],m["dimension"]==90128,m["multiplicity"]==169,m["character"]=="exactly H_old","isomorphism" in m["extra_algebraic_requirement"],m["full_symmetric_block_nondegenerate_for_arbitrary_D"],s["dimension"]==">90128",s["unused_complement"]=="K=ker(B_bar*)",s["extra_algebraic_requirement"]=="D_KK=P_K D|K nondegenerate",not s["cross_rank_alone_sufficient"],a["released_zero_fermion_mixed_capacity"]==0,not a["released_inventory_admitted"],a["corrected_completion_gate_satisfied_rows"]==5,a["corrected_completion_gate_total_rows"]==11,d["minimal_hypothetical_sufficiency_now_exact"],d["surplus_hypothetical_sufficiency_now_exact"],not d["current_action_owned_B_available"],not d["current_action_owned_D_KK_available"],not d["cross_completion_constructed"],not d["SC_ACT_06_proved_or_refuted"],d["distance_only_cross_budget_waves_exhausted"],"D_KK" in d["next_exact_input"],"switch route" in d["next_exact_input"],x["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"hypothetical sufficiency exact" in x["ledger_no_change_reason"],"does not provide an action" in x["claim_ceiling"],x["controls"]["controls_passed"]==45,x["controls"]["hostile_mutations_rejected"]==20,x["schema_version"]=="1.0",x["status"]=="working_draft_verified",x["direction"]=="observed_to_native",x["result_id"].startswith("K910-"),x["gu_typed_objects"]["cross_map"].endswith("B G=0"),"90128" in x["gu_typed_objects"]["old_quotient"],a["corrected_completion_gate_satisfied_rows"]<a["corrected_completion_gate_total_rows"],not a["released_inventory_admitted"],d["distance_only_cross_budget_waves_exhausted"],not d["cross_completion_constructed"]]
 assert len(q)==46 and all(q),[i for i,v in enumerate(q) if not v]
def main():
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();x=build();validate(x);s=json.dumps(x,indent=2,sort_keys=True)+"\n"
 if z.write:OUTPUT.write_text(s)
 elif not z.check:print(s,end="")
 return 0
if __name__=="__main__":raise SystemExit(main())
