#!/usr/bin/env python3
"""K924: audit locality, naturality and ownership of the projector parent."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/"lab/process/k924-sc-act-06-projector-locality-ownership-boundary.json"
PATHS={"k855":ROOT/"lab/process/k855-sc-act-06-cohomology-bundle.json","k858":ROOT/"lab/process/k858-sc-act-06-topological-repair-disposition.json","k862":ROOT/"lab/process/k862-sc-act-06-naturality-repair-disposition.json","k921":ROOT/"lab/process/k921-sc-act-06-quotient-projector-parent.json","k922":ROOT/"lab/process/k922-sc-act-06-quadratic-projector-action.json","k923":ROOT/"lab/process/k923-sc-act-06-forty-type-projector-repair.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
    rows=[
        {"row":"complete_constant_rank_family","current":False,"why":"K879 authenticates a basepoint old submodule, not the complete old cohomology bundle over the cosphere"},
        {"row":"positive_auxiliary_metric_owner","current":False,"why":"the orthogonal complement and adjoints depend on a chosen positive auxiliary metric"},
        {"row":"natural_equivariant_projector","current":False,"why":"K862 still requires authenticated isotropy modules and source/action-owned intertwiners"},
        {"row":"local_differential_symbol","current":False,"why":"the orthogonal projector is defined through kernels, complements and generalized inverses; no polynomial local symbol is supplied"},
        {"row":"source_action_ownership","current":False,"why":"the quadratic control is repository-defined and absent from the source action inventory"},
        {"row":"common_green_domain","current":False,"why":"no common closed domain or Green realization for the complete field complex is constructed"},
        {"row":"preboundary_bv_bfv_data","current":False,"why":"no variational preboundary form, gauge quotient or BFV/BV completion is constructed"},
        {"row":"authenticated_old_submodule_identity","current":True,"why":"K923 proves identity on the 90,128-dimensional forty-type old submodule"},
    ]
    return {"schema_version":"1.0","result_id":"K924-SC-ACT-06-PROJECTOR-LOCALITY-OWNERSHIP-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Admission audit of K921--K923's auxiliary quotient-projector action against the complete-family, locality, naturality, ownership, Green and preboundary obligations for GU credit.","gu_typed_objects":{"candidate":"auxiliary orthogonal quotient projector P_H","action":"repository-defined quadratic A_H","consuming_family":"complete Euclidean old-field symbol family over the nonzero covector cosphere","target":"ADMISSION-TYPE=local natural source/action-owned old-old Hessian"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"audit":{"rows":rows,"row_count":len(rows),"satisfied_rows":sum(r["current"] for r in rows),"missing_rows":sum(not r["current"] for r in rows),"formal_identity_row_only":True,"generalized_inverse_dependency":"P_ker(J) and P_im(G) require auxiliary adjoints/complements and, in formulas, Moore-Penrose or Green-type inverses","finite_symbol_existence_implies_local_action":False,"ordinary_bundle_triviality_implies_natural_action":False},"decision":{"formal_parent_rejected_as_algebraically_invalid":False,"formal_parent_admitted_as_source_GU_action":False,"locality_or_naturality_no_go_for_all_future_parents":False,"remaining_obstruction_relocated_to_family_ownership_and_analysis":True,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Supply a complete constant-rank Euclidean family and derive a polynomial local or explicitly accepted pseudodifferential natural projector from the source/action, with owned auxiliary structure, common Green domain and preboundary/BV data."},"source_and_ledger_effect":"SC-ACT-01_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"Seven unsatisfied admission rows prevent the formal identity parent from becoming a GU action or physical complex.","claim_ceiling":"Exact current-custody audit. It does not prove that every local or natural old-old parent is impossible, and it does not grant source, action, ellipticity or moduli credit to the projector.","controls":{"producer":"tests/channel-swings/k924_sc_act_06_projector_locality_ownership_boundary.py","probe":"tests/channel-swings/k924_sc_act_06_projector_locality_ownership_boundary_probe.py","controls_passed":38,"hostile_mutations_rejected":20}}
def validate(d:dict)->None:
    a,x=d["audit"],d["decision"];rows=a["rows"]
    checks=[d["schema_version"]=="1.0",d["result_id"].startswith("K924-"),d["status"]=="working_draft_verified",d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",d["target_claim"]=="SC-ACT-06","locality" in d["scope"],set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("ADMISSION-TYPE="),a["row_count"]==8,a["satisfied_rows"]==1,a["missing_rows"]==7,a["formal_identity_row_only"],"Moore-Penrose" in a["generalized_inverse_dependency"],not a["finite_symbol_existence_implies_local_action"],not a["ordinary_bundle_triviality_implies_natural_action"],len({r["row"] for r in rows})==8,[r["row"] for r in rows if r["current"]]==["authenticated_old_submodule_identity"],all(r["why"] for r in rows),not x["formal_parent_rejected_as_algebraically_invalid"],not x["formal_parent_admitted_as_source_GU_action"],not x["locality_or_naturality_no_go_for_all_future_parents"],x["remaining_obstruction_relocated_to_family_ownership_and_analysis"],not x["SC_ACT_06_proved_or_refuted"],"constant-rank" in x["next_exact_input"],"pseudodifferential" in x["next_exact_input"],"common Green" in x["next_exact_input"],d["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"Seven unsatisfied" in d["ledger_no_change_reason"],"does not prove" in d["claim_ceiling"],d["controls"]["controls_passed"]==38,d["controls"]["hostile_mutations_rejected"]==20,a["satisfied_rows"]+a["missing_rows"]==a["row_count"],not x["formal_parent_admitted_as_source_GU_action"],not x["SC_ACT_06_proved_or_refuted"],rows[-1]["current"],not rows[0]["current"]]
    assert len(checks)==38 and all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
    p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n"
    if a.write:OUTPUT.write_text(s,encoding="utf-8")
    elif not a.check:print(s,end="")
    return 0
if __name__=="__main__":raise SystemExit(main())
