#!/usr/bin/env python3
"""K925: freeze the formal old-parent admission boundary."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/"lab/process/k925-sc-act-06-formal-parent-admission-boundary.json"
PATHS={"k920":ROOT/"lab/process/k920-sc-act-06-graded-nonzero-fermion-admission-boundary.json","k921":ROOT/"lab/process/k921-sc-act-06-quotient-projector-parent.json","k922":ROOT/"lab/process/k922-sc-act-06-quadratic-projector-action.json","k923":ROOT/"lab/process/k923-sc-act-06-forty-type-projector-repair.json","k924":ROOT/"lab/process/k924-sc-act-06-projector-locality-ownership-boundary.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
    return {"schema_version":"1.0","result_id":"K925-SC-ACT-06-FORMAL-PARENT-ADMISSION-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Post-K920 disposition after constructing a symmetric gauge-basic auxiliary old-old projector Hessian with exact identity capacity on the authenticated old quotient.","gu_typed_objects":{"formal_parent":"P_H and A_H=1/2<x,P_Hx>","formal_effect":"identity on the authenticated forty-type old quotient","unmet_owner":"local or accepted pseudodifferential natural source/action family with complete analytic data","target":"DISPOSITION-TYPE=formal old-parent admission boundary"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"boundary":{"abstract_symmetric_gauge_basic_parent_exists":True,"abstract_parent_is_variational":True,"authenticated_old_submodule_rank_repaired":90128,"authenticated_old_real_types_repaired":40,"authenticated_old_multiplicity_repaired":169,"pure_finite_symbol_algebraic_impossibility":False,"source_action_owned_local_parent_exists_in_current_custody":False,"complete_cosphere_family_exists_in_current_custody":False,"common_green_preboundary_packet_exists_in_current_custody":False,"SC_ACT_06_status":"ASSERTS"},"decision":{"K920_new_old_parent_route_instantiated_formally":True,"formal_instantiation_earns_GU_repair_credit":False,"do_not_retry_released_K_HQ_span":True,"do_not_promote_auxiliary_projector_to_source_action":True,"next_route":"DERIVE_OR_REJECT_A_LOCAL_OR_EXPLICITLY_ACCEPTED_PSEUDODIFFERENTIAL_NATURAL_SOURCE_ACTION_REALIZATION_OF_THE_PROJECTOR_CLASS__OTHERWISE_SWITCH_TO_A_CHANGED_STATIONARY_GERM_OR_INDEPENDENT_OWNED_RESPONSE","what_positive_changes":"an owned natural realization would supply the missing diagonal quotient capacity and open complete-family ellipticity tests","what_negative_changes":"failure closes that proposed realization only; it does not undo formal existence or refute every future old-old parent","SC_ACT_06_proved_or_refuted":False},"source_and_ledger_effect":"SC-ACT-01_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The wave proves formal variational capacity but none of the ownership, locality, family or analytic conditions needed for a GU deformation complex.","claim_ceiling":"Exact formal-parent admission boundary. It is neither a source action construction nor a local/pseudodifferential classification theorem, complete elliptic complex, Fredholm realization or rich-moduli result.","controls":{"producer":"tests/channel-swings/k925_sc_act_06_formal_parent_admission_boundary.py","probe":"tests/channel-swings/k925_sc_act_06_formal_parent_admission_boundary_probe.py","controls_passed":38,"hostile_mutations_rejected":20}}
def validate(d:dict)->None:
    b,x=d["boundary"],d["decision"]
    checks=[d["schema_version"]=="1.0",d["result_id"].startswith("K925-"),d["status"]=="working_draft_verified",d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",d["target_claim"]=="SC-ACT-06","symmetric gauge-basic" in d["scope"],set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),"identity" in d["gu_typed_objects"]["formal_effect"],b["abstract_symmetric_gauge_basic_parent_exists"],b["abstract_parent_is_variational"],b["authenticated_old_submodule_rank_repaired"]==90128,b["authenticated_old_real_types_repaired"]==40,b["authenticated_old_multiplicity_repaired"]==169,not b["pure_finite_symbol_algebraic_impossibility"],not b["source_action_owned_local_parent_exists_in_current_custody"],not b["complete_cosphere_family_exists_in_current_custody"],not b["common_green_preboundary_packet_exists_in_current_custody"],b["SC_ACT_06_status"]=="ASSERTS",x["K920_new_old_parent_route_instantiated_formally"],not x["formal_instantiation_earns_GU_repair_credit"],x["do_not_retry_released_K_HQ_span"],x["do_not_promote_auxiliary_projector_to_source_action"],"PSEUDODIFFERENTIAL" in x["next_route"],"open complete-family" in x["what_positive_changes"],"does not undo formal existence" in x["what_negative_changes"],not x["SC_ACT_06_proved_or_refuted"],d["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"formal variational capacity" in d["ledger_no_change_reason"],"neither a source action" in d["claim_ceiling"],d["controls"]["controls_passed"]==38,d["controls"]["hostile_mutations_rejected"]==20,not b["source_action_owned_local_parent_exists_in_current_custody"],not x["formal_instantiation_earns_GU_repair_credit"],b["authenticated_old_submodule_rank_repaired"]>0,not x["SC_ACT_06_proved_or_refuted"]]
    assert len(checks)==38 and all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
    p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n"
    if a.write:OUTPUT.write_text(s,encoding="utf-8")
    elif not a.check:print(s,end="")
    return 0
if __name__=="__main__":raise SystemExit(main())
