#!/usr/bin/env python3
"""K926: compose the complete constant-rank connection quotient bundle."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/"lab/process/k926-sc-act-06-complete-connection-quotient-bundle.json"
PATHS={"k788":ROOT/"lab/process/k788-sc-act-06-direct-response-orbit-classification.json","k855":ROOT/"lab/process/k855-sc-act-06-cohomology-bundle.json","k873":ROOT/"lab/process/k873-sc-act-06-owned-symmetry-custody.json","k879":ROOT/"lab/process/k879-sc-act-06-full-field-quotient-injection.json","k921":ROOT/"lab/process/k921-sc-act-06-quotient-projector-parent.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
    return {"schema_version":"1.0","result_id":"K926-SC-ACT-06-COMPLETE-CONNECTION-QUOTIENT-BUNDLE","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Complete nonzero-covector connection-sector complex on K717's fixed flat germ; the complementary full-field cohomology is not computed.","gu_typed_objects":{"carrier":"real connection-symbol bundle E1=T*Y tensor Cl_14 over the auxiliary Euclidean cosphere S^13","gauge_map":"G_q(lambda)=q tensor lambda","response":"J_q(u)=K_LIFT(SHIAB(q_WEDGE_u))","quotient":"H_q=ker(J_q) intersect im(G_q)^perp","target":"BUNDLE-TYPE=complete constant-rank owned connection quotient"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"composition":{"base":"S^13","field_dimension":229376,"response_rank":122864,"response_nullity":106512,"gauge_rank":16384,"cohomology_rank":90128,"rank_identity":"229376-122864-16384=90128","nonzero_covector_orbits":["native_positive","native_negative","native_null"],"response_rank_constant_on_all_orbits":True,"gauge_rank_constant_for_all_nonzero_covectors":True,"JG_zero_on_flat_zero_locus":True,"continuous_polynomial_symbol_family":True,"constant_rank_bundle_conclusion":True,"uniform_full_field_injection":True},"decision":{"complete_connection_sector_cosphere_bundle_established":True,"complete_full_field_cohomology_computed":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Compose the K717 background-owned positive metric with this bundle, derive the smooth Moore-Penrose projector symbol, and classify local versus pseudodifferential realization without promoting it to a source action."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The result authenticates the connection-sector quotient bundle only; it supplies no source/action-owned repairing Hessian, full field complex, domain or observable.","claim_ceiling":"Exact complete connection-sector bundle theorem on the fixed flat germ. It does not identify the complete full-field cohomology, a source/action-owned repair, Fredholm realization, rich moduli or physical result.","controls":{"producer":"tests/channel-swings/k926_sc_act_06_complete_connection_quotient_bundle.py","probe":"tests/channel-swings/k926_sc_act_06_complete_connection_quotient_bundle_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
    c,x=d["composition"],d["decision"]
    checks=[d["schema_version"]=="1.0",d["result_id"].startswith("K926-"),d["status"]=="working_draft_verified",d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",d["target_claim"]=="SC-ACT-06",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("BUNDLE-TYPE="),c["base"]=="S^13",c["field_dimension"]==229376,c["response_rank"]==122864,c["response_nullity"]==106512,c["gauge_rank"]==16384,c["cohomology_rank"]==90128,c["response_nullity"]-c["gauge_rank"]==c["cohomology_rank"],len(c["nonzero_covector_orbits"])==3,c["response_rank_constant_on_all_orbits"],c["gauge_rank_constant_for_all_nonzero_covectors"],c["JG_zero_on_flat_zero_locus"],c["continuous_polynomial_symbol_family"],c["constant_rank_bundle_conclusion"],c["uniform_full_field_injection"],x["complete_connection_sector_cosphere_bundle_established"],not x["complete_full_field_cohomology_computed"],not x["SC_ACT_06_proved_or_refuted"],"Moore-Penrose" in x["next_exact_input"],d["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10]
    assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
    p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n"
    if a.write:OUTPUT.write_text(s,encoding="utf-8")
    elif not a.check:print(s,end="")
    return 0
if __name__=="__main__":raise SystemExit(main())
