#!/usr/bin/env python3
"""K927: compose the background-owned metric with the projector family."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k927-sc-act-06-background-metric-projector-family.json"
PATHS={"k713":ROOT/"lab/process/k713-sc-act-06-native-symmetry-gauge-metric-obstruction.json","k716":ROOT/"lab/process/k716-sc-act-06-compact-reduction-selection-boundary.json","k717":ROOT/"lab/process/k717-sc-act-06-flat-euclidean-gimmel-germ.json","k926":ROOT/"lab/process/k926-sc-act-06-complete-connection-quotient-bundle.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 return {"schema_version":"1.0","result_id":"K927-SC-ACT-06-BACKGROUND-METRIC-PROJECTOR-FAMILY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Orthogonal-projector family on K926's complete connection quotient using the positive Frobenius reduction owned by K717's fixed flat germ.","gu_typed_objects":{"carrier":"K926 real connection-symbol bundle","pairing":"K717 background Frobenius q on T*Y with the pinned positive coefficient Frobenius pairing","projector":"P_H(q)=P_ker(J_q)-P_im(G_q)","target":"MAP-TYPE=background-relative smooth orthogonal projector family"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"composition":{"background_positive_metric_exists":True,"background_owns_metric_on_fixed_flat_germ":True,"metric_is_globally_unique_or_full_native_invariant":False,"projector_family_is_smooth":True,"projector_family_rank":90128,"self_adjoint":True,"idempotent":True,"gauge_basic":"P_H(q) G_q=0","response_closed":"J_q P_H(q)=0","induced_quotient_map":"identity","full_native_naturality_without_background_reduction":False},"decision":{"positive_auxiliary_metric_owner_row_closed_on_fixed_germ":True,"global_or_source_action_ownership_follows":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Write the constant-rank Moore-Penrose formula, prove degree-zero smooth homogeneity, and separate its pseudodifferential principal-symbol realization from local differential and source/action ownership."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"Background ownership closes one auxiliary row only; it neither makes the projector a term of the source action nor supplies global uniqueness or a Green domain.","claim_ceiling":"Exact background-relative metric/projector composition on K717. No globally canonical metric, source/action parent, complete quantization, Green domain, BV/BFV data or physical result follows.","controls":{"producer":"tests/channel-swings/k927_sc_act_06_background_metric_projector_family.py","probe":"tests/channel-swings/k927_sc_act_06_background_metric_projector_family_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 c,x=d["composition"],d["decision"];checks=[d["result_id"].startswith("K927-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",d["target_claim"]=="SC-ACT-06",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("MAP-TYPE="),c["background_positive_metric_exists"],c["background_owns_metric_on_fixed_flat_germ"],not c["metric_is_globally_unique_or_full_native_invariant"],c["projector_family_is_smooth"],c["projector_family_rank"]==90128,c["self_adjoint"],c["idempotent"],c["gauge_basic"]=="P_H(q) G_q=0",c["response_closed"]=="J_q P_H(q)=0",c["induced_quotient_map"]=="identity",not c["full_native_naturality_without_background_reduction"],x["positive_auxiliary_metric_owner_row_closed_on_fixed_germ"],not x["global_or_source_action_ownership_follows"],not x["SC_ACT_06_proved_or_refuted"],"Moore-Penrose" in x["next_exact_input"],d["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),d["controls"]["hostile_mutations_rejected"]==10]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
