#!/usr/bin/env python3
"""K928: derive the order-zero pseudodifferential projector symbol."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k928-sc-act-06-pseudodifferential-projector-symbol.json"
PATHS={"k855":ROOT/"lab/process/k855-sc-act-06-cohomology-bundle.json","k926":ROOT/"lab/process/k926-sc-act-06-complete-connection-quotient-bundle.json","k927":ROOT/"lab/process/k927-sc-act-06-background-metric-projector-family.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 return {"schema_version":"1.0","result_id":"K928-SC-ACT-06-PSEUDODIFFERENTIAL-PROJECTOR-SYMBOL","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Principal-symbol classification of K927's smooth constant-rank projector family; no full quantization, source/action ownership or common domain is asserted.","gu_typed_objects":{"gauge_symbol":"degree-one G(q)","response_symbol":"degree-one J(q)","projector_symbol":"P_H(q)=I-J(q)^dagger J(q)-G(q)(G(q)^*G(q))^-1G(q)^*","target":"OPERATOR-TYPE=classical order-zero pseudodifferential principal symbol"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"theorem":{"constant_rank_makes_moore_penrose_smooth":True,"G_pseudoinverse_degree":-1,"J_pseudoinverse_degree":-1,"projector_homogeneous_degree":0,"projector_smooth_on_nonzero_cosphere":True,"projector_rank":90128,"principal_symbol_class":"S^0_classical","order_zero_pseudodifferential_quantization_exists":True,"formal_self_adjoint_idempotent_at_principal_grade":True,"exact_operator_idempotence_after_arbitrary_quantization":False,"lower_order_recursive_correction_required":True,"common_closed_domain_and_green_realization_constructed":False},"decision":{"pseudodifferential_principal_symbol_row_closed":True,"complete_owned_pseudodifferential_action_constructed":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Test whether the same nonzero gauge-basic projector can be a local order-zero differential endomorphism; then freeze the remaining source/action, lower-symbol, Green-domain and preboundary obligations."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"A classical principal symbol is an operator-class construction, not a source/action term, exact quantization, domain or physical observable.","claim_ceiling":"Exact smooth homogeneous principal-symbol theorem and conditional order-zero pseudodifferential realization. No full symbol, exact operator projector, source/action ownership, Green domain, ellipticity or physical result follows.","controls":{"producer":"tests/channel-swings/k928_sc_act_06_pseudodifferential_projector_symbol.py","probe":"tests/channel-swings/k928_sc_act_06_pseudodifferential_projector_symbol_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 t,x=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K928-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("OPERATOR-TYPE="),"dagger" in d["gu_typed_objects"]["projector_symbol"],t["constant_rank_makes_moore_penrose_smooth"],t["G_pseudoinverse_degree"]==-1,t["J_pseudoinverse_degree"]==-1,t["projector_homogeneous_degree"]==0,t["projector_smooth_on_nonzero_cosphere"],t["projector_rank"]==90128,t["principal_symbol_class"]=="S^0_classical",t["order_zero_pseudodifferential_quantization_exists"],t["formal_self_adjoint_idempotent_at_principal_grade"],not t["exact_operator_idempotence_after_arbitrary_quantization"],t["lower_order_recursive_correction_required"],not t["common_closed_domain_and_green_realization_constructed"],x["pseudodifferential_principal_symbol_row_closed"],not x["complete_owned_pseudodifferential_action_constructed"],not x["SC_ACT_06_proved_or_refuted"],"local order-zero" in x["next_exact_input"],d["controls"]["hostile_mutations_rejected"]==10]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
