#!/usr/bin/env python3
"""K929: prove the local order-zero projector obstruction."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k929-sc-act-06-local-projector-obstruction.json"
PATHS={"k873":ROOT/"lab/process/k873-sc-act-06-owned-symmetry-custody.json","k926":ROOT/"lab/process/k926-sc-act-06-complete-connection-quotient-bundle.json","k928":ROOT/"lab/process/k928-sc-act-06-pseudodifferential-projector-symbol.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 return {"schema_version":"1.0","result_id":"K929-SC-ACT-06-LOCAL-PROJECTOR-OBSTRUCTION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Exact realization of the nonzero K928 projector family by a covector-independent order-zero differential endomorphism on the same connection carrier.","gu_typed_objects":{"local_candidate":"A(x):E1->E1 with principal symbol independent of nonzero q","gauge_family":"G_q(lambda)=q tensor lambda","desired_rank":90128,"target":"OBSTRUCTION-TYPE=local order-zero realization of quotient projector"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"theorem":{"order_zero_differential_symbol_is_covector_independent":True,"gauge_basic_requirement":"A G_q=0 for every nonzero q","gauge_images_span_connection_carrier":True,"span_identity":"span{q tensor lambda:q nonzero, lambda in Cl_14}=T*Y tensor Cl_14=E1","forced_local_candidate_rank":0,"desired_projector_rank":90128,"exact_local_order_zero_realization_exists":False,"pseudodifferential_realization_remains_open_at_full_operator_grade":True,"higher_order_or_different_parent_classes_excluded":False},"decision":{"same_projector_local_differential_route_closed":True,"all_local_action_parents_refuted":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"An admitted continuation must explicitly own the order-zero pseudodifferential parent and construct its full lower symbol, common domain/Green realization and preboundary/BV data, or switch to a different local parent, stationary germ or independent response."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The obstruction closes only a covector-independent local realization of this projector; it does not exclude different local Hessians or create an owned pseudodifferential action.","claim_ceiling":"Exact no-go for the same nonzero quotient projector as an order-zero differential endomorphism. It does not exclude higher-order local parents, different symbols, nonlocal realizations, changed germs or independent responses.","controls":{"producer":"tests/channel-swings/k929_sc_act_06_local_projector_obstruction.py","probe":"tests/channel-swings/k929_sc_act_06_local_projector_obstruction_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 t,x=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K929-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("OBSTRUCTION-TYPE="),t["order_zero_differential_symbol_is_covector_independent"],"every nonzero q" in t["gauge_basic_requirement"],t["gauge_images_span_connection_carrier"],t["span_identity"].endswith("=E1"),t["forced_local_candidate_rank"]==0,t["desired_projector_rank"]==90128,not t["exact_local_order_zero_realization_exists"],t["pseudodifferential_realization_remains_open_at_full_operator_grade"],not t["higher_order_or_different_parent_classes_excluded"],x["same_projector_local_differential_route_closed"],not x["all_local_action_parents_refuted"],not x["SC_ACT_06_proved_or_refuted"],"full lower symbol" in x["next_exact_input"],d["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"does not exclude" in d["claim_ceiling"],d["controls"]["hostile_mutations_rejected"]==10]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
