#!/usr/bin/env python3
"""K930: freeze the corrected projector realization boundary."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k930-sc-act-06-projector-realization-boundary.json"
PATHS={"k924":ROOT/"lab/process/k924-sc-act-06-projector-locality-ownership-boundary.json","k925":ROOT/"lab/process/k925-sc-act-06-formal-parent-admission-boundary.json","k926":ROOT/"lab/process/k926-sc-act-06-complete-connection-quotient-bundle.json","k927":ROOT/"lab/process/k927-sc-act-06-background-metric-projector-family.json","k928":ROOT/"lab/process/k928-sc-act-06-pseudodifferential-projector-symbol.json","k929":ROOT/"lab/process/k929-sc-act-06-local-projector-obstruction.json"}
def digest(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 rows=[{"row":"complete_constant_rank_connection_family","current":True},{"row":"background_positive_metric_owner_on_fixed_germ","current":True},{"row":"smooth_degree_zero_projector_symbol","current":True},{"row":"classical_pseudodifferential_principal_symbol","current":True},{"row":"local_order_zero_differential_realization","current":False},{"row":"source_action_ownership","current":False},{"row":"full_lower_symbol_and_common_green_domain","current":False},{"row":"preboundary_bv_bfv_data","current":False},{"row":"authenticated_old_quotient_identity","current":True}]
 return {"schema_version":"1.0","result_id":"K930-SC-ACT-06-PROJECTOR-REALIZATION-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Post-K925 disposition after completing the connection-sector family, background metric composition, pseudodifferential principal-symbol theorem and local order-zero obstruction.","gu_typed_objects":{"formal_parent":"P_H and A_H=1/2<x,P_Hx>","realization":"smooth degree-zero classical pseudodifferential principal symbol","closed_route":"covector-independent local order-zero differential realization","target":"DISPOSITION-TYPE=projector realization admission boundary"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":digest(v)} for k,v in PATHS.items()},"certificate":{"rows":rows,"row_count":9,"satisfied_row_count":5,"missing_row_count":4,"connection_bundle_rank":90128,"SC_ACT_06_status":"ASSERTS","full_GU_repair_credit":False},"decision":{"complete_connection_family_exists":True,"pseudodifferential_principal_symbol_exists":True,"same_projector_local_order_zero_route_closed":True,"source_action_owned_complete_operator_exists":False,"SC_ACT_06_proved_or_refuted":False,"next_route":"EXPLICITLY_OWN_AND_COMPLETE_THE_PSEUDODIFFERENTIAL_PARENT_WITH_FULL_LOWER_SYMBOL_GREEN_DOMAIN_AND_PREBOUNDARY_BV_DATA__OR_SWITCH_TO_A_DIFFERENT_LOCAL_PARENT_CHANGED_STATIONARY_GERM_OR_INDEPENDENT_RESPONSE"},"source_and_ledger_effect":"SC-ACT-01_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The wave closes family and principal-symbol rows but leaves source/action ownership and analytic/variational completion absent.","claim_ceiling":"Exact connection-family and operator-class boundary. It is not a source action, complete pseudodifferential operator, Green/Fredholm realization, BV/BFV complex, global SC-ACT-06 verdict or physical result.","controls":{"producer":"tests/channel-swings/k930_sc_act_06_projector_realization_boundary.py","probe":"tests/channel-swings/k930_sc_act_06_projector_realization_boundary_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 c,x=d["certificate"],d["decision"];rows=c["rows"];checks=[d["result_id"].startswith("K930-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),c["row_count"]==9,c["satisfied_row_count"]==5,c["missing_row_count"]==4,c["satisfied_row_count"]+c["missing_row_count"]==c["row_count"],sum(r["current"] for r in rows)==5,len({r["row"] for r in rows})==9,c["connection_bundle_rank"]==90128,c["SC_ACT_06_status"]=="ASSERTS",not c["full_GU_repair_credit"],x["complete_connection_family_exists"],x["pseudodifferential_principal_symbol_exists"],x["same_projector_local_order_zero_route_closed"],not x["source_action_owned_complete_operator_exists"],not x["SC_ACT_06_proved_or_refuted"],"FULL_LOWER_SYMBOL" in x["next_route"],d["source_and_ledger_effect"].endswith("LEDGER_UNCHANGED"),"not a source action" in d["claim_ceiling"],d["controls"]["hostile_mutations_rejected"]==10]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
