#!/usr/bin/env python3
"""K933: close the auxiliary Sobolev/Hodge domain packet."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k933-sc-act-06-sobolev-hodge-domain.json"
PATHS={"k873":ROOT/"lab/process/k873-sc-act-06-owned-symmetry-custody.json","k932":ROOT/"lab/process/k932-sc-act-06-toroidal-exact-projector.json"}
def dg(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 return {"schema_version":"1.0","result_id":"K933-SC-ACT-06-SOBOLEV-HODGE-DOMAIN","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Common Sobolev-scale and generalized-inverse analysis for K932's exact auxiliary toroidal projection.","gu_typed_objects":{"operator":"Pi on H^s(T^14;E1)","gauge_map":"d0 lambda has Fourier symbol i k tensor lambda","harmonic_projector":"H=I-Pi","generalized_inverse":"G_H=Pi","target":"DOMAIN-TYPE=auxiliary Sobolev Hodge realization"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":dg(v)} for k,v in PATHS.items()},"theorem":{"bounded_on_every_real_sobolev_order":True,"Hs_operator_norm":1,"common_domain":"H^s to H^s for every real s","range_closed":True,"kernel_closed":True,"orthogonal_decomposition":"H^s=ran(Pi) direct_sum ker(Pi)","moore_penrose_inverse_equals_operator":True,"hodge_identity":"Pi G_H=G_H Pi=Pi=I-H","gauge_image_in_kernel":True,"Pi_d0_zero":True,"formal_cokernel_equals_kernel":True,"kernel_and_cokernel_infinite_dimensional":True,"fredholm_realization":False,"retarded_or_advanced_green_operator_constructed":False,"native_global_domain_owned":False},"decision":{"common_auxiliary_sobolev_domain_constructed":True,"hodge_generalized_inverse_constructed":True,"native_fredholm_or_causal_green_row_closed":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Use Pi d0=0 to construct the exact bounded quadratic formal action and its Noether identity, while preserving the infinite-dimensional non-Fredholm and noncausal boundary."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"A Hodge generalized inverse for an auxiliary projection is not a source-owned Fredholm or causal Green realization.","claim_ceiling":"Exact common Sobolev scale, closed orthogonal decomposition and Moore--Penrose/Hodge generalized inverse for the auxiliary toroidal projection. No Fredholm, retarded/advanced, native-global, BV/BFV or physical conclusion follows.","controls":{"producer":"tests/channel-swings/k933_sc_act_06_sobolev_hodge_domain.py","probe":"tests/channel-swings/k933_sc_act_06_sobolev_hodge_domain_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 t,x=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K933-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("DOMAIN-TYPE="),t["bounded_on_every_real_sobolev_order"],t["Hs_operator_norm"]==1,t["range_closed"],t["kernel_closed"],"direct_sum" in t["orthogonal_decomposition"],t["moore_penrose_inverse_equals_operator"],"I-H" in t["hodge_identity"],t["gauge_image_in_kernel"],t["Pi_d0_zero"],t["formal_cokernel_equals_kernel"],t["kernel_and_cokernel_infinite_dimensional"],not t["fredholm_realization"],not t["retarded_or_advanced_green_operator_constructed"],not t["native_global_domain_owned"],x["common_auxiliary_sobolev_domain_constructed"],x["hodge_generalized_inverse_constructed"],not x["native_fredholm_or_causal_green_row_closed"],not x["SC_ACT_06_proved_or_refuted"]]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if z.write else (None if z.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
