#!/usr/bin/env python3
"""K935: freeze the exact auxiliary realization and remaining ownership boundary."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k935-sc-act-06-exact-auxiliary-realization-boundary.json"
PATHS={f"k{k}":ROOT/f"lab/process/k{k}-sc-act-06-{name}.json" for k,name in [(930,"projector-realization-boundary"),(931,"low-frequency-extension-obstruction"),(932,"toroidal-exact-projector"),(933,"sobolev-hodge-domain"),(934,"toroidal-formal-action")]}
def dg(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 rows=[("complete_nonzero_connection_family","satisfied"),("fixed_germ_positive_metric","satisfied"),("smooth_nonconstant_degree_zero_symbol","satisfied"),("continuous_euclidean_zero_frequency_extension","closed_negative"),("auxiliary_toroidal_full_symbol","satisfied"),("exact_self_adjoint_operator_projection","satisfied"),("common_auxiliary_sobolev_domain","satisfied"),("auxiliary_hodge_generalized_inverse","satisfied"),("native_fredholm_or_causal_green_realization","missing"),("native_global_topology_and_zero_mode_owner","missing"),("source_action_ownership","missing"),("preboundary_bv_bfv_data","missing"),("authenticated_old_quotient_identity","satisfied")]
 return {"schema_version":"1.0","result_id":"K935-SC-ACT-06-EXACT-AUXILIARY-REALIZATION-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Post-K930 disposition after resolving the exact quantization and common-domain feasibility of the projector on an explicitly auxiliary compact flat carrier.","gu_typed_objects":{"euclidean_boundary":"no continuous full symbol equal to P_H at every nonzero frequency","auxiliary_realization":"exact toroidal Fourier projection on T^14","formal_parent":"A_T(u)=1/2<u,Pi u>","target":"DISPOSITION-TYPE=exact auxiliary realization versus native ownership"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":dg(v)} for k,v in PATHS.items()},"certificate":{"rows":[{"row":r,"state":s} for r,s in rows],"row_count":13,"satisfied_row_count":8,"closed_negative_row_count":1,"missing_row_count":4,"connection_fiber_rank":90128,"SC_ACT_06_status":"ASSERTS","full_GU_repair_credit":False},"decision":{"pure_analytic_impossibility_of_a_complete_formal_parent_removed":True,"exact_auxiliary_operator_and_hodge_domain_exist":True,"same_projector_global_euclidean_s0_route_closed":True,"native_source_owned_complete_operator_exists":False,"native_fredholm_or_causal_green_exists":False,"preboundary_bv_bfv_exists":False,"SC_ACT_06_proved_or_refuted":False,"next_route":"SOURCE_OR_ACTION_MUST_OWN_THE_GLOBAL_CARRIER_ZERO_MODE_COMPLETE_OPERATOR_AND_VARIATIONAL_DOMAIN__THEN_SUPPLY_NATIVE_FREDHOLM_OR_CAUSAL_GREEN_AND_PREBOUNDARY_BV_DATA__OTHERWISE_SWITCH_PARENT_OR_STATIONARY_GERM"},"source_and_ledger_effect":"SC-ACT-01_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"Exact auxiliary feasibility relocates the frontier to native/source ownership and global variational data; it supplies no owned action or physical prediction.","claim_ceiling":"Exact auxiliary full-operator, Sobolev/Hodge-domain and formal-action boundary. It is not a native compactification, source action, Fredholm/causal Green realization, BV/BFV complex, global SC-ACT-06 verdict or physical result.","controls":{"producer":"tests/channel-swings/k935_sc_act_06_exact_auxiliary_realization_boundary.py","probe":"tests/channel-swings/k935_sc_act_06_exact_auxiliary_realization_boundary_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 c,x=d["certificate"],d["decision"];rows=c["rows"];checks=[d["result_id"].startswith("K935-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),c["row_count"]==13,c["satisfied_row_count"]==8,c["closed_negative_row_count"]==1,c["missing_row_count"]==4,sum(v for v in [c["satisfied_row_count"],c["closed_negative_row_count"],c["missing_row_count"]])==c["row_count"],len({r["row"] for r in rows})==13,c["connection_fiber_rank"]==90128,c["SC_ACT_06_status"]=="ASSERTS",not c["full_GU_repair_credit"],x["pure_analytic_impossibility_of_a_complete_formal_parent_removed"],x["exact_auxiliary_operator_and_hodge_domain_exist"],x["same_projector_global_euclidean_s0_route_closed"],not x["native_source_owned_complete_operator_exists"],not x["native_fredholm_or_causal_green_exists"],not x["preboundary_bv_bfv_exists"],not x["SC_ACT_06_proved_or_refuted"],"SOURCE_OR_ACTION" in x["next_route"],d["controls"]["hostile_mutations_rejected"]==10]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if z.write else (None if z.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
