#!/usr/bin/env python3
"""K937: prove zero-mode changes cannot repair Fredholm failure."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; OUTPUT=ROOT/"lab/process/k937-sc-act-06-fredholm-essential-obstruction.json"
PATHS={"k933":ROOT/"lab/process/k933-sc-act-06-sobolev-hodge-domain.json","k936":ROOT/"lab/process/k936-sc-act-06-zero-mode-nonselection.json"}
def dg(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 return {"schema_version":"1.0","result_id":"K937-SC-ACT-06-FREDHOLM-ESSENTIAL-OBSTRUCTION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Fredholm and essential-spectrum classification for every K936 zero-mode extension of the auxiliary toroidal projection.","gu_typed_objects":{"operator":"Pi_Q0 with p(k)=P_H(k) for k nonzero and p(0)=Q0","domain":"H^s(T^14;E1) to itself","target":"OBSTRUCTION-TYPE=finite-low-mode Fredholm repair"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":dg(v)} for k,v in PATHS.items()},"theorem":{"nonzero_mode_range_dimension":90128,"nonzero_mode_kernel_dimension":139248,"range_infinite_dimensional":True,"kernel_infinite_dimensional":True,"cokernel_infinite_dimensional":True,"essential_spectrum":[0,1],"zero_and_one_have_infinite_multiplicity":True,"every_Q0_extension_fredholm":False,"finite_rank_zero_mode_changes_preserve_essential_spectrum":True,"finite_rank_zero_mode_changes_preserve_nonfredholm_status":True},"decision":{"zero_mode_repair_route_closed":True,"native_fredholm_realization_constructed":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"A Fredholm completion must act nontrivially on the infinite-dimensional complement ker(Pi), not merely change the isolated zero mode. Classify that required complement operator and domain as new data."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The theorem closes only finite-low-mode repair of an auxiliary projection; it neither supplies nor excludes a different source-owned operator.","claim_ceiling":"Exact non-Fredholm theorem for every finite-dimensional zero-mode extension of the auxiliary toroidal projector. Different infinite-mode parents, domains, stationary germs and source actions remain open.","controls":{"producer":"tests/channel-swings/k937_sc_act_06_fredholm_essential_obstruction.py","probe":"tests/channel-swings/k937_sc_act_06_fredholm_essential_obstruction_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 t,x=d["theorem"],d["decision"]; checks=[d["result_id"].startswith("K937-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("OBSTRUCTION-TYPE="),t["nonzero_mode_range_dimension"]==90128,t["nonzero_mode_kernel_dimension"]==139248,t["range_infinite_dimensional"],t["kernel_infinite_dimensional"],t["cokernel_infinite_dimensional"],t["essential_spectrum"]==[0,1],t["zero_and_one_have_infinite_multiplicity"],not t["every_Q0_extension_fredholm"],t["finite_rank_zero_mode_changes_preserve_essential_spectrum"],t["finite_rank_zero_mode_changes_preserve_nonfredholm_status"],x["zero_mode_repair_route_closed"],not x["native_fredholm_realization_constructed"],not x["SC_ACT_06_proved_or_refuted"],d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if z.write else (None if z.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
