#!/usr/bin/env python3
"""K938: identify the exact complement operator needed for Fredholm completion."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k938-sc-act-06-complement-completion-interface.json"
PATHS={"k934":ROOT/"lab/process/k934-sc-act-06-toroidal-formal-action.json","k937":ROOT/"lab/process/k937-sc-act-06-fredholm-essential-obstruction.json"}
def dg(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 return {"schema_version":"1.0","result_id":"K938-SC-ACT-06-COMPLEMENT-COMPLETION-INTERFACE","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Abstract Fredholm-completion theorem for the orthogonal split ran(Pi) direct-sum ker(Pi) on the auxiliary toroidal carrier.","gu_typed_objects":{"split":"H^s=ran(Pi) direct_sum ker(Pi)","completion":"L_A=identity on ran(Pi) direct sum A on ker(Pi)","graph_domain":"ran(Pi)H^s direct sum D(A)","target":"INTERFACE-TYPE=missing complement operator and domain"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":dg(v)} for k,v in PATHS.items()},"theorem":{"L_A_fredholm_iff_A_fredholm":True,"index_L_A_equals_index_A":True,"kernel_L_A_equals_kernel_A":True,"cokernel_L_A_isomorphic_to_cokernel_A":True,"invertible_A_gives_inverse":"identity on ran(Pi) direct sum A^-1 on ker(Pi)","projector_alone_specifies_A":False,"projector_alone_specifies_graph_domain":False,"auxiliary_choice_A_equals_Bessel_potential_is_possible":True,"auxiliary_choice_is_source_owned":False,"completion_changes_infinite_mode_dynamics":True},"decision":{"fredholm_completion_is_analytically_possible_with_new_data":True,"native_fredholm_row_closed":False,"exact_missing_input":"a source/action-owned closed operator A on ker(Pi), its graph domain, and compatibility with the full gauge/response/preboundary complex","SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Separate the algebraic BV identities already forced by Pi d0=0 from the still-unowned local preboundary/BFV and causal-domain data."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The theorem identifies the missing owner interface; selecting an auxiliary A is not a GU action or native domain.","claim_ceiling":"Exact Fredholm equivalence for block completion of the auxiliary projector. It proves analytic feasibility only after a new infinite-mode complement operator and graph domain are supplied.","controls":{"producer":"tests/channel-swings/k938_sc_act_06_complement_completion_interface.py","probe":"tests/channel-swings/k938_sc_act_06_complement_completion_interface_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 t,x=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K938-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("INTERFACE-TYPE="),t["L_A_fredholm_iff_A_fredholm"],t["index_L_A_equals_index_A"],t["kernel_L_A_equals_kernel_A"],t["cokernel_L_A_isomorphic_to_cokernel_A"],"A^-1" in t["invertible_A_gives_inverse"],not t["projector_alone_specifies_A"],not t["projector_alone_specifies_graph_domain"],t["auxiliary_choice_A_equals_Bessel_potential_is_possible"],not t["auxiliary_choice_is_source_owned"],t["completion_changes_infinite_mode_dynamics"],x["fredholm_completion_is_analytically_possible_with_new_data"],not x["native_fredholm_row_closed"],"source/action-owned" in x["exact_missing_input"],not x["SC_ACT_06_proved_or_refuted"],d["controls"]["hostile_mutations_rejected"]==10]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if z.write else (None if z.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
