#!/usr/bin/env python3
"""K940: freeze the post-projector analytic ownership boundary."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k940-sc-act-06-analytic-ownership-boundary.json"
PATHS={f"k{k}":ROOT/f"lab/process/k{k}-sc-act-06-{name}.json" for k,name in [(935,"exact-auxiliary-realization-boundary"),(936,"zero-mode-nonselection"),(937,"fredholm-essential-obstruction"),(938,"complement-completion-interface"),(939,"closed-carrier-bv-skeleton")]}
def dg(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def build()->dict:
 rows=[("complete_nonzero_connection_family","satisfied"),("fixed_germ_positive_metric","satisfied"),("smooth_nonconstant_degree_zero_symbol","satisfied"),("continuous_euclidean_zero_frequency_extension","closed_negative"),("auxiliary_toroidal_full_symbol","satisfied"),("exact_self_adjoint_operator_projection","satisfied"),("common_auxiliary_sobolev_domain","satisfied"),("auxiliary_hodge_generalized_inverse","satisfied"),("zero_mode_family_classified","satisfied"),("finite_low_mode_fredholm_repair","closed_negative"),("complement_fredholm_interface","satisfied"),("auxiliary_closed_carrier_bv_skeleton","satisfied"),("native_fredholm_realization","missing"),("native_causal_green_realization","missing"),("native_global_topology_and_zero_mode_owner","missing"),("source_action_ownership","missing"),("local_preboundary_bfv_data","missing"),("authenticated_old_quotient_identity","satisfied")]
 return {"schema_version":"1.0","result_id":"K940-SC-ACT-06-ANALYTIC-OWNERSHIP-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Post-K935 disposition after exhausting zero-mode repair, classifying Fredholm complement data and constructing the auxiliary closed-carrier BV skeleton.","gu_typed_objects":{"projector":"Pi_Q0 on auxiliary T^14","fredholm_interface":"L_A=identity on ran(Pi) direct sum A on ker(Pi)","bv_skeleton":"minimal linear closed-carrier Q","target":"DISPOSITION-TYPE=analytic feasibility versus native ownership"},"pinned_inputs":{k:{"path":str(v.relative_to(ROOT)),"sha256":dg(v)} for k,v in PATHS.items()},"certificate":{"rows":[{"row":r,"state":s} for r,s in rows],"row_count":18,"satisfied_row_count":11,"closed_negative_row_count":2,"missing_row_count":5,"connection_fiber_rank":90128,"SC_ACT_06_status":"ASSERTS","full_GU_repair_credit":False},"decision":{"zero_mode_choice_cannot_repair_fredholm_failure":True,"abstract_fredholm_completion_requires_new_infinite_mode_owner":True,"auxiliary_algebraic_bv_exists":True,"native_fredholm_or_causal_green_exists":False,"native_local_preboundary_bfv_exists":False,"source_action_owned_complete_operator_exists":False,"projector_parent_route_exhausted_without_new_owned_input":True,"SC_ACT_06_proved_or_refuted":False,"next_route":"SWITCH_TO_A_DIFFERENT_SOURCE_ACTION_OWNED_PARENT_OR_STATIONARY_GERM_WITH_COMPLETE_OPERATOR_DOMAIN_CAUSAL_OR_FREDHOLM_AND_PREBOUNDARY_BV_BFV_DATA"},"source_and_ledger_effect":"SC-ACT-01_04_05_06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The wave exhausts auxiliary analytic freedom without supplying a source-owned action, topology, complement operator, causal structure or boundary theory.","claim_ceiling":"Exact auxiliary zero-mode, Fredholm-interface and algebraic-BV boundary. It neither proves nor refutes SC-ACT-06 and grants no native action, causal, BV-BFV or physical credit.","controls":{"producer":"tests/channel-swings/k940_sc_act_06_analytic_ownership_boundary.py","probe":"tests/channel-swings/k940_sc_act_06_analytic_ownership_boundary_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d:dict)->None:
 c,x=d["certificate"],d["decision"];rows=c["rows"];checks=[d["result_id"].startswith("K940-"),d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native",set(d["pinned_inputs"])==set(PATHS),all(len(v["sha256"])==64 for v in d["pinned_inputs"].values()),d["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),c["row_count"]==18,c["satisfied_row_count"]==11,c["closed_negative_row_count"]==2,c["missing_row_count"]==5,c["satisfied_row_count"]+c["closed_negative_row_count"]+c["missing_row_count"]==c["row_count"],len({r["row"] for r in rows})==18,c["connection_fiber_rank"]==90128,c["SC_ACT_06_status"]=="ASSERTS",not c["full_GU_repair_credit"],x["zero_mode_choice_cannot_repair_fredholm_failure"],x["abstract_fredholm_completion_requires_new_infinite_mode_owner"],x["auxiliary_algebraic_bv_exists"],not x["native_fredholm_or_causal_green_exists"],not x["native_local_preboundary_bfv_exists"],not x["source_action_owned_complete_operator_exists"],x["projector_parent_route_exhausted_without_new_owned_input"],not x["SC_ACT_06_proved_or_refuted"],"SWITCH_TO_A_DIFFERENT" in x["next_route"]]
 assert all(checks),[i for i,o in enumerate(checks) if not o]
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--write",action="store_true");a.add_argument("--check",action="store_true");z=a.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if z.write else (None if z.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
