#!/usr/bin/env python3
"""K942: zero-level reduction of the source-epsilon cotangent parent."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k942-source-epsilon-zero-reduction.json";PATHS={"k941":ROOT/"lab/process/k941-source-epsilon-cotangent-moment-map.json"}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 n=91
 return {"schema_version":"1.0","result_id":"K942-SOURCE-EPSILON-ZERO-REDUCTION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Exact zero-level symplectic reduction of the action-owned finite source-epsilon cotangent parent.","gu_typed_objects":{"carrier":"J_L^{-1}(0)=Spin_0(7,7) x {0}","pairing":"canonical cotangent symplectic form","real_structure":"real split group","grading":"regular first-class zero level","action_owner":"formal source epsilon parent, not constraint selection","target":"QUOTIENT-TYPE=zero-level cotangent reduction"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"theorem":{"group_dimension":n,"zero_level_dimension":n,"zero_stabilizer_dimension":n,"zero_level_is_regular":True,"action_on_zero_level_is_free_and_transitive":True,"reduced_dimension":0,"reduced_space_is_one_point":True,"nontrivial_edge_modes_after_full_zero_gauging":False},"decision":{"full_zero_constraint_is_mathematically_proper":True,"full_zero_constraint_is_selected_by_source_action":False,"selected_nonzero_endpoint_lies_on_zero_level":False,"zero_reduction_supplies_physical_edge_sector":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Classify reduction at the actual nonzero charge orbit and identify the extra invariant-locking law it requires."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"A regular but trivial zero quotient does not authorize imposing zero or change a physical verdict.","claim_ceiling":"Exact finite zero-level quotient only. It does not select the zero constraint, bind the nonzero endpoint, or construct functional physical cohomology.","controls":{"producer":"tests/channel-swings/k942_source_epsilon_zero_reduction.py","probe":"tests/channel-swings/k942_source_epsilon_zero_reduction_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 t,q=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K942-"),set(d["pinned_inputs"])==set(PATHS),t["group_dimension"]==91,t["zero_level_dimension"]==91,t["zero_stabilizer_dimension"]==91,t["zero_level_is_regular"],t["action_on_zero_level_is_free_and_transitive"],t["reduced_dimension"]==0,t["reduced_space_is_one_point"],not t["nontrivial_edge_modes_after_full_zero_gauging"],q["full_zero_constraint_is_mathematically_proper"],not q["full_zero_constraint_is_selected_by_source_action"],not q["selected_nonzero_endpoint_lies_on_zero_level"],not q["zero_reduction_supplies_physical_edge_sector"],not q["SC_ACT_06_proved_or_refuted"],d["target_claim"]=="SC-ACT-06",d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10,d["gu_typed_objects"]["target"].startswith("QUOTIENT-TYPE="),"LEDGER_UNCHANGED" in d["source_and_ledger_effect"],"does not select" in d["claim_ceiling"],len(d["pinned_inputs"]["k941"]["sha256"])==64,d["classification"]=="SOURCE_NATIVE_ROUTE",d["direction"]=="observed_to_native"]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
