#!/usr/bin/env python3
"""K943: nonzero coadjoint-orbit reduction of the source-epsilon parent."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k943-source-epsilon-orbit-reduction.json";PATHS={"k941":ROOT/"lab/process/k941-source-epsilon-cotangent-moment-map.json","invariants":ROOT/"lab/process/selected-k77-coadjoint-invariant-variation-gate.json"}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K943-SOURCE-EPSILON-ORBIT-REDUCTION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Exact fixed-charge and orbit reduction of the action-owned finite source-epsilon cotangent parent at the regular selected endpoint type.","gu_typed_objects":{"carrier":"J_L^{-1}(mu)/G_mu and J_L^{-1}(O_mu)/G","pairing":"Kirillov-Kostant-Souriau form inherited by cotangent reduction","real_structure":"regular real coadjoint orbit of Spin_0(7,7)","grading":"finite formal preboundary orbit sector","action_owner":"source epsilon parent; orbit locking remains unowned","target":"QUOTIENT-TYPE=nonzero coadjoint-orbit reduction"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"theorem":{"group_dimension":91,"regular_stabilizer_dimension":7,"fixed_mu_fiber_dimension":91,"fixed_mu_quotient_dimension":84,"orbit_dimension":84,"fixed_mu_reduction_is_coadjoint_orbit":True,"orbit_reduction_is_same_coadjoint_orbit":True,"reduced_form_is_KKS_up_to_convention_sign":True,"nonzero_reduction_is_point":False,"seven_independent_invariants_must_be_locked":True},"decision":{"nonzero_reduction_preserves_formal_edge_modes":True,"current_action_locks_all_seven_invariants":False,"current_off_shell_line_changes_all_seven_invariants":True,"orbit_reduction_is_action_selected":False,"physical_cohomology_constructed":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Supply an action-owned boundary or Green law locking the seven coadjoint invariants, or retain the transformations as charged boundary symmetry."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__AC-F1_LT-SM8_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The formal nonzero reduction is nontrivial but the current action does not select its fixed orbit.","claim_ceiling":"Exact finite coadjoint-orbit reduction theorem. It supplies neither the invariant-locking owner nor a functional domain, positivity or observed physical cohomology.","controls":{"producer":"tests/channel-swings/k943_source_epsilon_orbit_reduction.py","probe":"tests/channel-swings/k943_source_epsilon_orbit_reduction_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 t,q=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K943-"),set(d["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in d["pinned_inputs"].values()),t["group_dimension"]==91,t["regular_stabilizer_dimension"]==7,t["fixed_mu_fiber_dimension"]==91,t["fixed_mu_quotient_dimension"]==84,t["orbit_dimension"]==84,t["fixed_mu_reduction_is_coadjoint_orbit"],t["orbit_reduction_is_same_coadjoint_orbit"],t["reduced_form_is_KKS_up_to_convention_sign"],not t["nonzero_reduction_is_point"],t["seven_independent_invariants_must_be_locked"],q["nonzero_reduction_preserves_formal_edge_modes"],not q["current_action_locks_all_seven_invariants"],q["current_off_shell_line_changes_all_seven_invariants"],not q["orbit_reduction_is_action_selected"],not q["physical_cohomology_constructed"],not q["SC_ACT_06_proved_or_refuted"],d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10,d["gu_typed_objects"]["target"].startswith("QUOTIENT-TYPE="),"LEDGER_UNCHANGED" in d["source_and_ledger_effect"],"neither" in d["claim_ceiling"]]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
