#!/usr/bin/env python3
"""K944: proper finite BFV boundary for the full canonical cotangent parent."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k944-source-epsilon-regular-bfv-boundary.json";PATHS={"k941":ROOT/"lab/process/k941-source-epsilon-cotangent-moment-map.json","k942":ROOT/"lab/process/k942-source-epsilon-zero-reduction.json","k943":ROOT/"lab/process/k943-source-epsilon-orbit-reduction.json","old_bfv":ROOT/"lab/process/selected-k77-full-bfv-master-equation-gate.json"}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K944-SOURCE-EPSILON-REGULAR-BFV-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Proper finite-dimensional Koszul/BFV consequence of the regular canonical cotangent zero-level constraint, separated from the singular frozen-distortion presentation.","gu_typed_objects":{"constraint":"J_L=0 on T*Spin_0(7,7)","ghosts":"91 irreducible first-class generators","koszul":"regular sequence at the full cotangent zero level","bfv":"Omega=c^a J_a-(1/2)f_ab^c c^a c^b b_c","target":"COHOMOLOGY-TYPE=finite formal zero-reduction"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"theorem":{"constraint_count":91,"constraint_rank":91,"first_stage_reducibility":0,"minimal_ghost_count":91,"master_equation_closes":True,"koszul_tate_is_proper_at_zero":True,"degree_zero_reduced_observables":"constants","positive_degree_regular_reduction_cohomology":"zero in the finite polynomial/Koszul model","frozen_distortion_rank70_nonregularity_transfers":False},"decision":{"finite_zero_level_BFV_complete":True,"finite_zero_level_BFV_nontrivial_physics":False,"current_nonzero_endpoint_admitted_by_zero_BFV":False,"nonzero_orbit_BFV_requires_invariant_locking_owner":True,"functional_field_space_BV_BFV_constructed":False,"analytic_domain_constructed":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Do not extend the finite zero quotient into physical credit; obtain the seven-invariant boundary law for the nonzero orbit or retain charged symmetry."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__AC-F1_LT-SM8_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The proper finite BFV model has only constant reduced observables and excludes the actual nonzero endpoint.","claim_ceiling":"Proper finite polynomial/Koszul BFV at the canonical zero level only. No functional locality, Green domain, positivity, observed state space or physical cohomology follows.","controls":{"producer":"tests/channel-swings/k944_source_epsilon_regular_bfv_boundary.py","probe":"tests/channel-swings/k944_source_epsilon_regular_bfv_boundary_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 t,q=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K944-"),set(d["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in d["pinned_inputs"].values()),t["constraint_count"]==91,t["constraint_rank"]==91,t["first_stage_reducibility"]==0,t["minimal_ghost_count"]==91,t["master_equation_closes"],t["koszul_tate_is_proper_at_zero"],t["degree_zero_reduced_observables"]=="constants",t["positive_degree_regular_reduction_cohomology"]=="zero in the finite polynomial/Koszul model",not t["frozen_distortion_rank70_nonregularity_transfers"],q["finite_zero_level_BFV_complete"],not q["finite_zero_level_BFV_nontrivial_physics"],not q["current_nonzero_endpoint_admitted_by_zero_BFV"],q["nonzero_orbit_BFV_requires_invariant_locking_owner"],not q["functional_field_space_BV_BFV_constructed"],not q["analytic_domain_constructed"],not q["SC_ACT_06_proved_or_refuted"],d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10,d["gu_typed_objects"]["target"].startswith("COHOMOLOGY-TYPE="),"LEDGER_UNCHANGED" in d["source_and_ledger_effect"],"No functional" in d["claim_ceiling"]]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
