#!/usr/bin/env python3
"""K945: compose the source-epsilon cotangent gauge ownership boundary."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k945-source-epsilon-gauge-ownership-boundary.json";PATHS={"k940":ROOT/"lab/process/k940-sc-act-06-analytic-ownership-boundary.json","k941":ROOT/"lab/process/k941-source-epsilon-cotangent-moment-map.json","k942":ROOT/"lab/process/k942-source-epsilon-zero-reduction.json","k943":ROOT/"lab/process/k943-source-epsilon-orbit-reduction.json","k944":ROOT/"lab/process/k944-source-epsilon-regular-bfv-boundary.json"}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 rows=[("action_owned_full_cotangent_parent","satisfied"),("canonical_moment_map_submersion","satisfied"),("regular_zero_level","satisfied"),("proper_finite_zero_BFV","satisfied"),("zero_reduced_space","closed_trivial"),("regular_nonzero_orbit_reduction","satisfied"),("seven_invariant_locking_law","missing"),("source_selected_constraint_value","missing"),("functional_local_BV_BFV","missing"),("closed_Green_or_causal_domain","missing"),("positive_observed_physical_cohomology","missing")]
 return {"schema_version":"1.0","result_id":"K945-SOURCE-EPSILON-GAUGE-OWNERSHIP-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Integrated disposition of the genuinely action-owned source-epsilon cotangent parent after exact zero, nonzero-orbit and finite BFV reduction.","gu_typed_objects":{"parent":"T*Spin_0(7,7)","zero_quotient":"one point","nonzero_quotient":"84-dimensional regular coadjoint orbit","missing_owner":"boundary/Green law locking seven invariant values","target":"DISPOSITION-TYPE=charged symmetry versus gauge quotient"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"certificate":{"rows":[{"row":r,"state":s} for r,s in rows],"row_count":11,"satisfied_row_count":5,"closed_trivial_row_count":1,"missing_row_count":5,"SC_ACT_06_status":"ASSERTS"},"decision":{"projector_parent_not_retried":True,"source_epsilon_parent_is_genuinely_action_owned":True,"full_zero_gauging_leaves_nontrivial_edge_sector":False,"regular_nonzero_orbit_leaves_dimension":84,"current_action_selects_fixed_nonzero_orbit":False,"charged_boundary_symmetry_retains_zero_import_primacy":True,"new_boundary_or_Green_owner_required":True,"functional_domain_and_physical_cohomology_remain_open":True,"SC_ACT_06_proved_or_refuted":False,"next_route":"CONSTRUCT_AN_ACTION_OWNED_BOUNDARY_OR_GREEN_LAW_LOCKING_THE_SEVEN_COADJOINT_INVARIANTS_ON_THE_SOURCE_EPSILON_PARENT__OTHERWISE_RETAIN_CHARGED_BOUNDARY_SYMMETRY_AND_SWITCH_TO_ANOTHER_REVERSE_EDGE"},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__AC-F1_LT-SM8_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The finite parent is classified exactly, but neither zero nor a fixed nonzero orbit is selected by the current source/action and no functional physical quotient is built.","claim_ceiling":"Exact finite source-epsilon cotangent reduction and ownership boundary. No source-selected gauge constraint, functional BV-BFV, causal/Fredholm domain, positivity, chirality, generation count or physical cohomology follows.","controls":{"producer":"tests/channel-swings/k945_source_epsilon_gauge_ownership_boundary.py","probe":"tests/channel-swings/k945_source_epsilon_gauge_ownership_boundary_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 c,q=d["certificate"],d["decision"];states=[x["state"] for x in c["rows"]];checks=[d["result_id"].startswith("K945-"),set(d["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in d["pinned_inputs"].values()),c["row_count"]==11,len(c["rows"])==11,c["satisfied_row_count"]==states.count("satisfied")==5,c["closed_trivial_row_count"]==states.count("closed_trivial")==1,c["missing_row_count"]==states.count("missing")==5,c["SC_ACT_06_status"]=="ASSERTS",q["projector_parent_not_retried"],q["source_epsilon_parent_is_genuinely_action_owned"],not q["full_zero_gauging_leaves_nontrivial_edge_sector"],q["regular_nonzero_orbit_leaves_dimension"]==84,not q["current_action_selects_fixed_nonzero_orbit"],q["charged_boundary_symmetry_retains_zero_import_primacy"],q["new_boundary_or_Green_owner_required"],q["functional_domain_and_physical_cohomology_remain_open"],not q["SC_ACT_06_proved_or_refuted"],d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10,d["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),"LEDGER_UNCHANGED" in d["source_and_ledger_effect"],"No source-selected" in d["claim_ceiling"],d["target_claim"]=="SC-ACT-06"]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
