#!/usr/bin/env python3
"""K947: selection power of collective invariant boundary Hamiltonians."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; OUTPUT=ROOT/"lab/process/k947-source-epsilon-invariant-hamiltonian-boundary.json"
PATHS={"k943":ROOT/"lab/process/k943-source-epsilon-orbit-reduction.json","k946":ROOT/"lab/process/k946-source-epsilon-invariant-coordinate-chart.json"}
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K947-SOURCE-EPSILON-INVARIANT-HAMILTONIAN-BOUNDARY","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Collective boundary Hamiltonians h(I_1,...,I_7) pulled back through the canonical source-epsilon moment map.","gu_typed_objects":{"carrier":"T*Spin_0(7,7) regular nonzero charge sector","pairing":"canonical cotangent symplectic form","real_structure":"split real group and coadjoint charge","grading":"finite preboundary Hamiltonian","action_owner":"auxiliary h is not source-owned","target":"DYNAMICS-TYPE=collective invariant boundary Hamiltonian"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"theorem":{"invariant_coordinate_count":7,"collective_hamiltonian":"H_h=h(I_1(J_L),...,I_7(J_L))","poisson_commutes_with_all_moment_map_components":True,"all_seven_invariant_values_are_conserved":True,"hamiltonian_generator_lies_in_charge_stabilizer":True,"flow_remains_in_initial_charge_orbit":True,"hamiltonian_evolution_imposes_initial_value_equations":False,"arbitrary_initial_regular_invariant_values_remain_allowed":True},"decision":{"conservation_is_selection":False,"invariant_hamiltonian_selects_a_fixed_nonzero_orbit":False,"boundary_euler_multiplier_law_supplied":False,"current_source_action_owns_h":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Add an independently owned regular boundary Euler law for the invariant values; conservation by h alone cannot select them."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__AC-F1_LT-SM8_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"Collective invariant evolution preserves whichever charge is supplied and therefore does not select a GU endpoint.","claim_ceiling":"Exact finite Hamiltonian conservation-versus-selection boundary; no source-owned boundary Euler law, functional Green domain or physical state selection follows.","controls":{"producer":"tests/channel-swings/k947_source_epsilon_invariant_hamiltonian_boundary.py","probe":"tests/channel-swings/k947_source_epsilon_invariant_hamiltonian_boundary_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 t,q=d["theorem"],d["decision"]; checks=[d["result_id"].startswith("K947-"),set(d["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in d["pinned_inputs"].values()),t["invariant_coordinate_count"]==7,t["poisson_commutes_with_all_moment_map_components"],t["all_seven_invariant_values_are_conserved"],t["hamiltonian_generator_lies_in_charge_stabilizer"],t["flow_remains_in_initial_charge_orbit"],not t["hamiltonian_evolution_imposes_initial_value_equations"],t["arbitrary_initial_regular_invariant_values_remain_allowed"],not q["conservation_is_selection"],not q["invariant_hamiltonian_selects_a_fixed_nonzero_orbit"],not q["boundary_euler_multiplier_law_supplied"],not q["current_source_action_owns_h"],not q["SC_ACT_06_proved_or_refuted"],d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10,d["gu_typed_objects"]["target"].startswith("DYNAMICS-TYPE="),"LEDGER_UNCHANGED" in d["source_and_ledger_effect"],"conservation-versus-selection" in d["claim_ceiling"]]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser(); p.add_argument("--write",action="store_true"); p.add_argument("--check",action="store_true"); a=p.parse_args(); d=build(); validate(d); s=json.dumps(d,indent=2,sort_keys=True)+"\n"; OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end="")); return 0
if __name__=="__main__": raise SystemExit(main())
