#!/usr/bin/env python3
"""K948: regular one-scalar charge-selection obstruction."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k948-source-epsilon-single-scalar-selection-obstruction.json"
PATHS={"k946":ROOT/"lab/process/k946-source-epsilon-invariant-coordinate-chart.json","k947":ROOT/"lab/process/k947-source-epsilon-invariant-hamiltonian-boundary.json"}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 return {"schema_version":"1.0","result_id":"K948-SOURCE-EPSILON-SINGLE-SCALAR-SELECTION-OBSTRUCTION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Implicit-function-theorem classification of one regular scalar boundary equation F(I_1,...,I_7)=0 near the authenticated regular charge.","gu_typed_objects":{"carrier":"seven-dimensional local invariant chart","pairing":"regular scalar differential dF","real_structure":"real invariant-value space","grading":"finite preboundary constraint","action_owner":"candidate scalar law unowned","target":"OBSTRUCTION-TYPE=regular scalar charge selection"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"theorem":{"ambient_invariant_dimension":7,"regular_scalar_constraint_rank":1,"regular_scalar_level_dimension":6,"regular_scalar_level_is_locally_isolated":False,"one_regular_scalar_locks_all_seven_values":False,"six_local_invariant_directions_remain":True,"singular_scalar_can_be_isolating_in_principle":True,"singular_isolating_case_is_regular_constraint":False,"regular_BFV_transfer_to_singular_case_allowed":False},"decision":{"single_energy_or_boundary_value_is_sufficient":False,"seven_independent_regular_locking_equations_required":True,"singular_one_function_escape_requires_separate_properness_analysis":True,"current_action_supplies_either_route":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Construct a rank-seven invariant locking map, or separately prove a singular selector with its own proper BV-BFV and analytic domain."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__AC-F1_LT-SM8_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The obstruction scopes ordinary regular scalar laws and explicitly leaves singular selection as a separately unowned route.","claim_ceiling":"Local regular-constraint obstruction only; it does not rule out singular selectors and supplies no source ownership or functional properness theorem.","controls":{"producer":"tests/channel-swings/k948_source_epsilon_single_scalar_selection_obstruction.py","probe":"tests/channel-swings/k948_source_epsilon_single_scalar_selection_obstruction_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 t,q=d["theorem"],d["decision"];checks=[d["result_id"].startswith("K948-"),set(d["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in d["pinned_inputs"].values()),t["ambient_invariant_dimension"]==7,t["regular_scalar_constraint_rank"]==1,t["regular_scalar_level_dimension"]==6,not t["regular_scalar_level_is_locally_isolated"],not t["one_regular_scalar_locks_all_seven_values"],t["six_local_invariant_directions_remain"],t["singular_scalar_can_be_isolating_in_principle"],not t["singular_isolating_case_is_regular_constraint"],not t["regular_BFV_transfer_to_singular_case_allowed"],not q["single_energy_or_boundary_value_is_sufficient"],q["seven_independent_regular_locking_equations_required"],q["singular_one_function_escape_requires_separate_properness_analysis"],not q["current_action_supplies_either_route"],not q["SC_ACT_06_proved_or_refuted"],d["controls"]["hostile_mutations_rejected"]==10,d["gu_typed_objects"]["target"].startswith("OBSTRUCTION-TYPE="),"LEDGER_UNCHANGED" in d["source_and_ledger_effect"],"does not rule out singular" in d["claim_ceiling"]]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
