#!/usr/bin/env python3
"""K949: minimal regular seven-lock boundary contract."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k949-source-epsilon-seven-lock-boundary-contract.json"
PATHS={"k945":ROOT/"lab/process/k945-source-epsilon-gauge-ownership-boundary.json","k946":ROOT/"lab/process/k946-source-epsilon-invariant-coordinate-chart.json","k948":ROOT/"lab/process/k948-source-epsilon-single-scalar-selection-obstruction.json"}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 rows=[("seven_component_lock_map","required"),("full_rank_jacobian_at_selected_value","required"),("gauge_invariant_dependence_on_primitive_invariants","required"),("seven_target_values_or_equivalent_boundary_data","required"),("source_or_action_ownership","missing"),("functional_boundary_domain","missing"),("proper_bv_bfv_extension","missing"),("green_or_causal_realization","missing")]
 return {"schema_version":"1.0","result_id":"K949-SOURCE-EPSILON-SEVEN-LOCK-BOUNDARY-CONTRACT","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Smallest regular gauge-invariant finite boundary contract that locally selects one regular nonzero coadjoint orbit.","gu_typed_objects":{"constraint":"Phi(I(J_L))=0 with Phi:R^7->R^7","multipliers":"seven auxiliary boundary multipliers","quotient":"J_L^{-1}(I^{-1}(c))/Spin_0(7,7) locally","action_owner":"not supplied by current source/action","target":"CONTRACT-TYPE=regular seven-invariant lock"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"theorem":{"lock_component_count":7,"required_jacobian_rank":7,"selected_invariant_level_dimension":0,"selected_charge_orbit_dimension":84,"constraint_functions_are_gauge_invariant":True,"quotient_by_full_group_is_separate_declared_step":True,"local_fixed_orbit_selection_follows_if_full_rank":True,"seven_auxiliary_multipliers_can_enforce_contract_formally":True,"formal_multiplier_action_is_source_owned":False},"certificate":{"rows":[{"row":r,"state":s} for r,s in rows],"row_count":8,"required_row_count":4,"missing_row_count":4},"decision":{"minimal_regular_contract_constructed":True,"physical_boundary_law_constructed":False,"current_action_selects_constants_or_couplings":False,"finite_lock_implies_functional_green_domain":False,"finite_lock_implies_physical_cohomology":False,"SC_ACT_06_proved_or_refuted":False,"next_exact_input":"Derive Phi, its seven values and multiplier/Green realization from the source action; otherwise retain charged symmetry and switch reverse edge."},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__AC-F1_LT-SM8_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The contract is a necessary finite interface, not an action-owned law or admitted functional realization.","claim_ceiling":"Minimal regular finite selection contract only; its auxiliary multipliers, values, functional domain and physical interpretation are unowned.","controls":{"producer":"tests/channel-swings/k949_source_epsilon_seven_lock_boundary_contract.py","probe":"tests/channel-swings/k949_source_epsilon_seven_lock_boundary_contract_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 t,c,q=d["theorem"],d["certificate"],d["decision"];states=[x["state"] for x in c["rows"]];checks=[d["result_id"].startswith("K949-"),set(d["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in d["pinned_inputs"].values()),t["lock_component_count"]==7,t["required_jacobian_rank"]==7,t["selected_invariant_level_dimension"]==0,t["selected_charge_orbit_dimension"]==84,t["constraint_functions_are_gauge_invariant"],t["quotient_by_full_group_is_separate_declared_step"],t["local_fixed_orbit_selection_follows_if_full_rank"],t["seven_auxiliary_multipliers_can_enforce_contract_formally"],not t["formal_multiplier_action_is_source_owned"],c["row_count"]==len(c["rows"])==8,c["required_row_count"]==states.count("required")==4,c["missing_row_count"]==states.count("missing")==4,q["minimal_regular_contract_constructed"],not q["physical_boundary_law_constructed"],not q["current_action_selects_constants_or_couplings"],not q["finite_lock_implies_functional_green_domain"],not q["finite_lock_implies_physical_cohomology"],not q["SC_ACT_06_proved_or_refuted"],d["controls"]["hostile_mutations_rejected"]==10,"LEDGER_UNCHANGED" in d["source_and_ledger_effect"]]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
