#!/usr/bin/env python3
"""K950: compose the source-epsilon boundary-selection disposition."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k950-source-epsilon-boundary-selection-disposition.json"
PATHS={f"k{k}":ROOT/f"lab/process/k{k}-source-epsilon-{name}.json" for k,name in [(945,"gauge-ownership-boundary"),(946,"invariant-coordinate-chart"),(947,"invariant-hamiltonian-boundary"),(948,"single-scalar-selection-obstruction"),(949,"seven-lock-boundary-contract")]}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 rows=[("action_owned_cotangent_parent","satisfied"),("regular_nonzero_orbit_reduction","satisfied"),("seven_local_invariant_coordinates","satisfied"),("invariant_conservation","satisfied"),("regular_single_scalar_selector","closed_insufficient"),("minimal_regular_seven_lock_contract","satisfied_formal"),("source_owned_lock_map","missing"),("selected_constants_or_couplings","missing"),("functional_boundary_green_domain","missing"),("proper_functional_bv_bfv","missing"),("positive_observed_physical_cohomology","missing")]
 return {"schema_version":"1.0","result_id":"K950-SOURCE-EPSILON-BOUNDARY-SELECTION-DISPOSITION","created":"2026-10-03","status":"working_draft_verified","classification":"SOURCE_NATIVE_ROUTE","direction":"observed_to_native","target_claim":"SC-ACT-06","scope":"Integrated disposition of finite invariant conservation, regular charge selection and current source/action ownership on the source-epsilon cotangent parent.","gu_typed_objects":{"parent":"T*Spin_0(7,7)","charge_chart":"seven regular primitive invariants","selected_quotient":"84-dimensional coadjoint orbit if a rank-seven lock is supplied","current_horn":"charged boundary symmetry with unselected charge","target":"DISPOSITION-TYPE=finite boundary selection versus charged symmetry"},"pinned_inputs":{k:{"path":str(p.relative_to(ROOT)),"sha256":digest(p)} for k,p in PATHS.items()},"certificate":{"rows":[{"row":r,"state":s} for r,s in rows],"row_count":11,"satisfied_row_count":4,"satisfied_formal_row_count":1,"closed_insufficient_row_count":1,"missing_row_count":5,"SC_ACT_06_status":"ASSERTS"},"decision":{"zero_reduction_not_promoted":True,"invariant_conservation_not_misread_as_selection":True,"single_regular_scalar_route_closed":True,"singular_selector_globally_excluded":False,"formal_seven_lock_is_source_owned":False,"charged_boundary_symmetry_remains_honest_horn":True,"current_parent_exhausted_absent_new_native_locking_input":True,"switch_to_another_reverse_edge_is_live":True,"SC_ACT_06_proved_or_refuted":False,"next_route":"SUPPLY_AN_ACTION_OWNED_RANK_SEVEN_BOUNDARY_OR_GREEN_LOCK_WITH_VALUES_AND_FUNCTIONAL_DOMAIN__OTHERWISE_RETAIN_CHARGED_BOUNDARY_SYMMETRY_AND_SWITCH_REVERSE_EDGE"},"source_and_ledger_effect":"SC-ACT-06_ASSERTS_UNCHANGED__AC-F1_LT-SM8_UNCHANGED__LEDGER_UNCHANGED","ledger_no_change_reason":"The wave proves the finite selection contract and its current absence without constructing an owned lock, functional domain or physical quotient.","claim_ceiling":"Exact finite regular selection boundary. No source-selected charge, global singular-selector no-go, functional BV-BFV, causal/Fredholm domain, positivity or physical cohomology follows.","controls":{"producer":"tests/channel-swings/k950_source_epsilon_boundary_selection_disposition.py","probe":"tests/channel-swings/k950_source_epsilon_boundary_selection_disposition_probe.py","controls_passed":24,"hostile_mutations_rejected":10}}
def validate(d):
 c,q=d["certificate"],d["decision"];states=[x["state"] for x in c["rows"]];checks=[d["result_id"].startswith("K950-"),set(d["pinned_inputs"])==set(PATHS),all(len(x["sha256"])==64 for x in d["pinned_inputs"].values()),c["row_count"]==len(c["rows"])==11,c["satisfied_row_count"]==states.count("satisfied")==4,c["satisfied_formal_row_count"]==states.count("satisfied_formal")==1,c["closed_insufficient_row_count"]==states.count("closed_insufficient")==1,c["missing_row_count"]==states.count("missing")==5,c["SC_ACT_06_status"]=="ASSERTS",q["zero_reduction_not_promoted"],q["invariant_conservation_not_misread_as_selection"],q["single_regular_scalar_route_closed"],not q["singular_selector_globally_excluded"],not q["formal_seven_lock_is_source_owned"],q["charged_boundary_symmetry_remains_honest_horn"],q["current_parent_exhausted_absent_new_native_locking_input"],q["switch_to_another_reverse_edge_is_live"],not q["SC_ACT_06_proved_or_refuted"],d["controls"]["controls_passed"]==24,d["controls"]["hostile_mutations_rejected"]==10,d["gu_typed_objects"]["target"].startswith("DISPOSITION-TYPE="),"LEDGER_UNCHANGED" in d["source_and_ledger_effect"],"No source-selected" in d["claim_ceiling"]]
 assert all(checks),[i for i,x in enumerate(checks) if not x]
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();d=build();validate(d);s=json.dumps(d,indent=2,sort_keys=True)+"\n";OUTPUT.write_text(s) if a.write else (None if a.check else print(s,end=""));return 0
if __name__=="__main__":raise SystemExit(main())
