#!/usr/bin/env python3
"""K990 composition and native-owner boundary for the Levy phase horns."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUTPUT=ROOT/"lab/process/k990-k989-levy-horn-action-disposition.json";NAMES=["k986-k985-brownian-phase-diffusion","k987-k986-symmetric-compound-poisson-family","k988-k987-controlled-process-nonidentifiability","k989-k988-record-law-discriminator"]
def build():
    ps=[json.loads((ROOT/f"lab/process/{n}.json").read_text()) for n in NAMES]
    return {"schema_version":"1.0","result_id":"K990-LEVY-HORN-ACTION-DISPOSITION","created":"2026-10-04","status":"working_draft_verified","direction":"observed_to_native","classification":"INTERNAL_REQUIREMENT_DISPOSITION","target_claim":"NONE-NOT-A-KILL","scope":"Composition of K986--K989 into the Levy phase-horn, controlled-process identifiability and record-owner boundary for K956.","dependency_checks":{"input_ids":[p["result_id"] for p in ps],"all_source_and_ledger_effect_none":all(p["source_and_ledger_effect"]=="none" for p in ps),"all_prediction_or_confirmation_withheld":all(not p["ownership"]["prediction_or_confirmation_credit"] for p in ps),"record_holdout_frozen_not_scored":ps[3]["preregistration"]["status"]=="frozen_not_scored"},"revised_fork":{"brownian_diffusion_horn":"exact reduced semigroup with continuous imported Gaussian record","symmetric_compound_poisson_horns":"continuum of exact finite-activity jump realizations with imported angle/rate/record","poisson_phase_flip_horn":"theta=pi/2 member up to pathwise global phase","deterministic_fresh_grid_horn":"uniformly convergent with h^-1/2 coupling and 1/h refresh costs","bounded_autonomous_fixed_product_horn":"excluded by K976--K977","unbounded_spectral_horn":"exact only on singular energy-domain state in K966--K975","classification_exhaustive":False},"identifiability":{"one_time_system_data_selects_horn":False,"finite_controlled_system_only_process_selects_independent_increment_horn":False,"record_or_environment_sensitive_holdout_required":True,"record_holdout_frozen":True,"empirical_score_assigned":False},"demand":{"gu_physical_quotient_and_positive_effect_pairing_required":True,"gu_action_owned_characteristic_exponent_required":True,"selected_horn_and_common_domain_required":True,"clock_noise_limit_or_record_accounting_required":True,"remote_marginal_and_locality_theorem_required":True,"inequivalent_native_record_observable_required":True},"ownership":{"repository_conditional_models_only":True,"gu_action_clock_record_or_physical_quotient_constructed":False,"source_claim_or_ledger_verdict_changed":False,"prediction_or_confirmation_credit":False},"decision":{"system_only_markov_process_data_do_not_select_levy_unravelling":True,"expanded_horn_family_does_not_supply_gu_owner":True,"next_exact_input":"A GU-owned physical quotient and positive state/effect pairing plus an action must select a characteristic exponent and horn, own its common domain, locality and clock/noise/limit/record resources, and expose an inequivalent native record observable before scoring."},"source_and_ledger_effect":"none","claim_ceiling":"Non-exhaustive Levy-horn family and unscored record-owner requirement only; no empirical score, GU derivation, prediction, confirmation or protected verdict."}
def validate(p):
    c,f,i,d,o,x=p["dependency_checks"],p["revised_fork"],p["identifiability"],p["demand"],p["ownership"],p["decision"]
    assert len(c["input_ids"])==4 and c["all_source_and_ledger_effect_none"] and c["all_prediction_or_confirmation_withheld"] and c["record_holdout_frozen_not_scored"]
    assert len(f)==7 and not f["classification_exhaustive"]
    assert not i["one_time_system_data_selects_horn"] and not i["finite_controlled_system_only_process_selects_independent_increment_horn"] and i["record_or_environment_sensitive_holdout_required"] and i["record_holdout_frozen"] and not i["empirical_score_assigned"]
    assert all(d.values()) and o["repository_conditional_models_only"] and not o["gu_action_clock_record_or_physical_quotient_constructed"] and not o["source_claim_or_ledger_verdict_changed"] and not o["prediction_or_confirmation_credit"]
    assert x["system_only_markov_process_data_do_not_select_levy_unravelling"] and x["expanded_horn_family_does_not_supply_gu_owner"] and p["source_and_ledger_effect"]=="none"
def main():
    ap=argparse.ArgumentParser();ap.add_argument("--write",action="store_true");ap.add_argument("--check",action="store_true");a=ap.parse_args();p=build();validate(p);t=json.dumps(p,indent=2,sort_keys=True)+"\n"
    if a.check:assert OUTPUT.read_text()==t
    elif a.write:OUTPUT.write_text(t)
    else:print(t,end="")
    print("K990 controls: 19/19")
if __name__=="__main__":main()
