#!/usr/bin/env python3
import copy,importlib.util
from pathlib import Path
H=Path(__file__).resolve().parent;s=importlib.util.spec_from_file_location("k995",H/"k995_k994_harmonic_action_disposition.py");m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
def ok(p):
    try:m.validate(p);return True
    except (AssertionError,KeyError):return False
def main():
    p=m.build();muts=[lambda x:x["dependency_checks"].__setitem__("input_ids",[]),lambda x:x["dependency_checks"].__setitem__("all_source_and_ledger_effect_none",False),lambda x:x["dependency_checks"].__setitem__("all_prediction_or_confirmation_withheld",False),lambda x:x["dependency_checks"].__setitem__("holdout_frozen_not_scored",False),lambda x:x["observability"].__setitem__("original_qubit_samples_only_gap_two",False),lambda x:x["observability"].__setitem__("qutrit_gap_one_separates_named_brownian_and_compound_poisson_pair",False),lambda x:x["observability"].__setitem__("qutrit_is_a_declared_system_enlargement",False),lambda x:x["observability"].__setitem__("microscopic_record_not_required_for_named_pair",False),lambda x:x["observability"].__setitem__("arbitrary_finite_charge_spectrum_identifies_general_phase_law",True),lambda x:x["observability"].__setitem__("record_and_unbounded_harmonic_access_remain_distinct_routes",False),lambda x:x["demand"].__setitem__("gu_physical_quotient_and_positive_effect_pairing_required",False),lambda x:x["demand"].__setitem__("gu_action_owned_charge_generator_and_spectrum_required",False),lambda x:x["demand"].__setitem__("gu_action_owned_characteristic_exponent_required",False),lambda x:x["demand"].__setitem__("native_preparation_and_gap_coherence_observable_required",False),lambda x:x["demand"].__setitem__("common_domain_and_locality_theorem_required",False),lambda x:x["demand"].__setitem__("finite_probe_claim_ceiling_required",False),lambda x:x["demand"].__setitem__("record_or_infinite_harmonic_completion_required_for_full_identification",False),lambda x:x["ownership"].__setitem__("repository_conditional_models_only",False),lambda x:x["ownership"].__setitem__("gu_action_charge_observable_or_physical_quotient_constructed",True),lambda x:x["ownership"].__setitem__("source_claim_or_ledger_verdict_changed",True),lambda x:x["ownership"].__setitem__("prediction_or_confirmation_credit",True),lambda x:x["decision"].__setitem__("k990_inequivalent_observable_requirement_sharpened",False),lambda x:x["decision"].__setitem__("pairwise_separation_does_not_select_full_microscopic_law",False),lambda x:x.__setitem__("source_and_ledger_effect","changed")];caught=0
    for f in muts:q=copy.deepcopy(p);f(q);caught+=not ok(q)
    print(f"K995 hostile: {caught}/{len(muts)}");return 0 if caught==len(muts) else 1
if __name__=="__main__":raise SystemExit(main())
