#!/usr/bin/env python3
"""M1 THIRD READING -- Mannheim's both-modes/complex-pair construction,
formalized at matrix grade in the repo's Krein setting and applied to the
ACTUAL N2 crossing rays (the cone-crossing walls of the faithful Y14-end
model, where the boundary family's spectrum leaves the real axis in
complex-conjugate pairs).

CHANNEL: convergence swing (Joe direct chat, 2026-07-20, parallel wave:
         Mannheim third reading). N2 named its obstruction (Krein
         collision walls, spectrum off the real axis in pairs); Mannheim's
         third realization of antilinear symmetry is a method for exactly
         that situation.
AXIOM:   lab/process/boundary-adapter-standing-axiom.md (adapter assumed
         for any SECTOR reading; the algebra below is unconditional).
DESIGN:  explorations/m1-third-reading-2026-07-20.md
EXTENDS: tests/channel-swings/n2_end_family_probe.py   (the end-model --
         its fiber/frame/holonomy machinery is REPLICATED here verbatim,
         same seed, so the crossing rays are the SAME rays; nothing in the
         n2 probe is edited or re-run)
         tests/channel-swings/f5_signed_fraction_probe.py (canonical cut
         closed form S = K_S e^{alpha w}, consumed as a regression target)
         explorations/W172-interacting-c-operator-nogo-2026-07-14.md (the
         unbroken-PT conditional this swing retypes -- or fails to)
STATUS:  exploration tier; no claim, canon, scorecard, or public-posture
         movement. Honest outcomes count as passes.

PRIMARIES (verified 2026-07-20, this swing; see the design doc Section 1):
  [P1] P. D. Mannheim, "Antilinearity rather than Hermiticity as a guiding
       principle for quantum theory", J. Phys. A 51 (2018) 315302
       [arXiv:1512.04915]. The both-modes construction is eqs (8)-(13):
       for a complex-conjugate pair E0 +- i Gamma, introduce V with
       V H V^-1 = H^dag; the V-inner products obey (eq 9)
           u+^dag V u+ = 0,  u-^dag V u- = 0   (each member SELF-NULL),
           u-^dag V u+ = +1, u+^dag V u- = -1  (cross-pairing, RELATIVE
                                                MINUS SIGN),
       closure u+ u-^dag V - u- u+^dag V = I; the paired propagator is
       (eqs 10, 13)
           D(E) = 1/(E-(E0-iGamma)) - 1/(E-(E0+iGamma))
                = -2iGamma/((E-E0)^2 + Gamma^2),
       sign-definite at real E; the inner product is time independent
       BECAUSE the only nonzero pairings connect the decaying and growing
       members (E-^* = E+), so keeping BOTH modes conserves probability
       ("the total population remains fixed"). V in eq (8) is
       ANTI-Hermitian in the complex-pair regime (machine-checked below);
       with a HERMITIAN fundamental symmetry (our K_S) the same normal
       form has cross-pairings +-i r -- one factor of i of convention,
       located and stated, not hidden.
  [P2] P. D. Mannheim, "Unitarity of loop diagrams for the ghostlike
       1/(k^2-M1^2)-1/(k^2-M2^2) propagator", Phys. Rev. D 98 (2018)
       045014 [arXiv:1801.03220]. Supplies the V-formalism at field grade:
       V H - H^dag V = 0 (eq 34) makes all <R|V|R'> time independent
       (eq 33); pseudo-unitarity U V^-1 U^dag V = I (eq 37),
       S V^-1 S^dag V = I (eq 38); the propagator is the LEFT-RIGHT
       vacuum object <Omega_L|T(phi phi)|Omega_R> = <Omega_R|V T(...)>
       (eq 7) and the relative minus sign is generated BY V, "not through
       any negative norm properties of the states"; all cut lines have
       positive norm; tree-graph discontinuities cancel loop-graph
       negatives. Transcript rows verified against these primaries:
       lab/sources/claim-mining-toe-mannheim-2026-07-20.md rows 2.5
       [01:44:44-01:47:21] (both-modes condition) and 2.6
       [02:10:40-02:12:47] (relative-minus resonance propagator).

THE TRANSPOSITION (the one object, constructions named -- the
GEOMETER-VS-PHYSICS-OBJECTS discipline):
  Mannheim's V-operator  <->  K_S (PROGRAM-NATIVE: the family D(t,s) is
      K_S-self-adjoint, K_S D^dag K_S = D, i.e. K_S D - D^dag K_S = 0 --
      EXACTLY [P2] eq (34) with V = K_S. No new operator is introduced;
      the Krein-native presentation already IS the Mannheim V-structure.)
  Mannheim's antilinear symmetry  <->  J_quat = C_J o conj (PROGRAM-
      NATIVE: commutes with the Clifford action and with K_S, J^2 = -I;
      it maps each half of a complex pair onto the other -- the
      mode-exchange is supplied, not chosen.)
  Mannheim's u+/u- pair  <->  the spectral halves E_{+i g}/E_{-i g} of
      D past a cone-crossing wall (D^2 = q I, q < 0, g = sqrt(-q)),
      with the pairing-canonical partner chosen by the SVD of the
      K_S cross-Gram (derivable from {D, K_S} alone).
  Mannheim's "keep both modes"  <->  keep BOTH halves with the conserved
      indefinite pairing x^dag K_S y; no half is discarded and no
      positive metric is asserted (none exists there -- the universal-
      null lemma below).

PRE-DECLARED KILL CONDITIONS (stated before running; the verdict line
reports which fired):
  K-a: the construction requires structure GU's Krein setup cannot supply
       (a preferred positive pairing, or an extra antilinear choice not
       derivable from K_S/J_quat)  ->  wall CONFIRMED SHARPER; W172
       stands as is.
  K-b: the pairing exists but breaks deck-exchange/holonomy compatibility
       ->  third reading incompatible with the carrier; construction-
       local no-go.
  K-c (success): conserved pairing exists, deck-compatible  ->  the
       crossing sector gains defined accounting; W172's unbroken-PT
       conditional retypes from wall to scheme choice (typed
       fork-conditional; NO claim/canon movement).

WHAT IS TESTED (headline shape):
  A. Primary fidelity: [P1] eqs (8)-(13) reconstructed machine-exactly
     (V anti-Hermitian, self-null, +-1 cross, closure, V H V^-1 = H^dag,
     the -2iGamma/((E-E0)^2+Gamma^2) lineshape).
  B. The V-structure is native: V = K_S satisfies [P2] eq (34) on the
     whole family; evolution is K_S-pseudo-unitary on BOTH sides of the
     wall and AT it; the UNIVERSAL-NULL LEMMA (two lines, machine-
     checked): ANY conserved pairing is null on each nonreal half, so NO
     conserved positive pairing exists past the wall -- the both-modes
     shape is the ONLY conserved accounting available there.
  C. The both-modes normal form holds at the ACTUAL N2 crossings
     (conf-down, boost, and seeded sweep crossing rays -- the same rays
     as the n2 probe, same seed/stream): halves self-null, cross-Gram
     nondegenerate with ALL singular values equal (quaternionic
     uniformity), Mannheim gauge reachable (residues -+i r, relative
     minus REALIZED), Lorentzian lineshape of width sqrt|q|, population
     accounting (Dirac norms grow/decay exponentially, ALL K_S pairings
     exactly constant), J_quat as mode exchange with antisymmetric
     (Kramers) composite pairing.
  D. The wall itself: exact-null representative of the actual collision
     point; Jordan structure (rank-64 D, Ker = Range, K-null kernel),
     linear-in-tau growth with CONSTANT overlaps ([P1] eqs (6)-(7)
     analog); the evolution is ENTIRE IN q (series = closed forms on
     both sides), hence continuous across the wall while the canonical
     cut's margin collapses -- the pairing datum crosses; the cut does
     not.
  E. Deck/holonomy: the pairing transports ANTI-invariantly under the
     faithful 6-leg deck (U_h^dag K_S U_h = -K_S exactly), returns +K_S
     on the double cover, is UNTOUCHED by the same-sign-plane seam --
     the SAME Z/2 twist as the two-section exchange, not a new
     incompatibility; and the pairing datum is defined at EVERY t of the
     loop at crossing radii, where the cut datum has t-holes.
  F. Gapped-side degeneration: where q > 0 the both-modes datum REFINES
     to the canonical cut S = K_S e^{alpha w} (f5 closed form reproduced
     from the pairing's definite blocks) -- the pairing is not a rival
     structure; it is the cut's wall-crossing extension.

NONCLAIMS. Symbol/matrix grade only (no operator on the end, no L^2, no
QFT lift -- the N2 theorem stays missing and is named); the OVERALL SIGN
of the paired lineshape (decay vs anti-damping orientation) is a GAUGE at
matrix grade and is NOT claimed derived -- W172's dynamical sign question
stays open at operator grade; ontology guard: Mannheim's decay
interpretation is imported as TECHNOLOGY, never as ontology (intake doc
guard honored); no claim/canon/posture movement. Deterministic; numpy
only; seeded 20260720.
"""
from __future__ import annotations

import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "generation-sector"))
import gen_sector_bridge as gb  # noqa: E402
import oq_rk1_cl95_explicit_rep as cl95  # noqa: E402

N_DIRS, DIM = 14, 128
ETA = np.array([1.0] * 9 + [-1.0] * 5)
LAM = 0.5
RNG = np.random.default_rng(20260720)

RESULTS = []


def check(tag, name, ok, detail=""):
    RESULTS.append((tag, name, bool(ok)))
    line = f"[{tag}] {'PASS' if ok else 'FAIL'}  {name}"
    if detail:
        line += f"   ({detail})"
    print(line)
    return ok


# --- the verified Clifford objects -------------------------------------------
e = gb.gammas()
K_S = e[0].copy()
for a in range(1, 9):
    K_S = K_S @ e[a]
XI = np.real(np.asarray(gb.XI)).astype(float)
I128 = np.eye(DIM, dtype=complex)


def cvec(v):
    return sum(v[a] * e[a] for a in range(N_DIRS))


def qform(v):
    return float(np.real(np.vdot(v, ETA * v)))


# --- J_quat (identical construction to the n2/f2 probes) ---------------------
G_raw = cl95.jordan_wigner_gammas(7)
r_sign, sigma_s = [], []
for a in range(N_DIRS):
    real_g = float(np.max(np.abs(np.conj(G_raw[a]) - G_raw[a]))) < 1e-12
    r_sign.append(+1 if real_g else -1)
    sigma_s.append(r_sign[a] if a < 9 else -r_sign[a])
S_even = [a for a in range(N_DIRS) if sigma_s[a] == -1]
S_odd = [a for a in range(N_DIRS) if sigma_s[a] == +1]
S_pick = S_even if len(S_even) % 2 == 0 else S_odd
C_J = I128.copy()
for a in S_pick:
    C_J = C_J @ G_raw[a]


# --- the end-model machinery (REPLICATED from n2_end_family_probe.py, same
#     conventions, same seed/stream discipline; that file is not touched) -----
SYM_IDX = [(0, 0), (1, 1), (2, 2), (3, 3),
           (0, 1), (0, 2), (1, 2), (0, 3), (1, 3), (2, 3)]


def sym_mat(i):
    a, b = SYM_IDX[i]
    m = np.zeros((4, 4))
    if a == b:
        m[a, a] = 1.0
    else:
        m[a, b] = m[b, a] = 1.0 / np.sqrt(2.0)
    return m


HMODES = [sym_mat(i) for i in range(10)]


def fixsign(v):
    k = int(np.argmax(np.abs(v)))
    return v if v[k] > 0 else -v


def frame_diag(a4, lam=LAM):
    a0, a1, a2, a3 = [float(x) for x in a4]
    F = np.zeros((14, 14))
    F[0, 0] = 1.0 / np.sqrt(a0)
    F[1, 1] = 1.0 / np.sqrt(a1)
    F[2, 2] = 1.0 / np.sqrt(a2)
    F[3, 9] = 1.0 / np.sqrt(a3)
    F[8, 3] = np.sqrt(a0 * a1)
    F[9, 4] = np.sqrt(a0 * a2)
    F[10, 5] = np.sqrt(a1 * a2)
    F[11, 10] = np.sqrt(a0 * a3)
    F[12, 11] = np.sqrt(a1 * a3)
    F[13, 12] = np.sqrt(a2 * a3)
    u = np.array([1.0 / a0, 1.0 / a1, 1.0 / a2, -1.0 / a3])
    M = np.diag(u * u) - lam * np.outer(u, u)
    w, V = np.linalg.eigh(M)
    refs = np.array([[1., -1., 0., 0.], [0., 1., -1., 0.],
                     [0., 0., 1., -1.], [1., 1., 1., 1.]]).T
    k0 = 0
    while k0 < 4:
        k1 = k0 + 1
        while k1 < 4 and abs(w[k1] - w[k0]) <= 1e-9 * max(1.0, abs(w[k0])):
            k1 += 1
        if k1 - k0 > 1:
            P = V[:, k0:k1]
            B = []
            for r in refs.T:
                v = P @ (P.T @ r)
                for b in B:
                    v = v - b * float(b @ v)
                nv = float(np.linalg.norm(v))
                if nv > 1e-8:
                    B.append(v / nv)
                if len(B) == k1 - k0:
                    break
            V[:, k0:k1] = np.stack(B, axis=1)
        k0 = k1
    pos = [k for k in range(4) if w[k] > 0]
    neg = [k for k in range(4) if w[k] < 0]
    if len(pos) != 3 or len(neg) != 1:
        raise ValueError(f"diag block signature not (3,1): {w}")
    for j, k in enumerate(pos):
        F[4:8, 6 + j] = fixsign(V[:, k]) / np.sqrt(w[k])
    F[4:8, 13] = fixsign(V[:, neg[0]]) / np.sqrt(-w[neg[0]])
    return F


def rot4(th):
    R = np.eye(4)
    R[0, 0] = R[3, 3] = np.cos(th)
    R[0, 3] = -np.sin(th)
    R[3, 0] = np.sin(th)
    return R


def rot4_ss(th):
    R = np.eye(4)
    R[0, 0] = R[1, 1] = np.cos(th)
    R[0, 1] = -np.sin(th)
    R[1, 0] = np.sin(th)
    return R


def rho(R):
    P = np.zeros((14, 14))
    P[:4, :4] = R
    for i in range(10):
        RhR = R @ HMODES[i] @ R.T
        for j in range(10):
            P[4 + j, 4 + i] = float(np.sum(RhR * HMODES[j]))
    return P


F_BASE = frame_diag((1.0, 1.0, 1.0, 1.0))
XI_VEC = F_BASE @ XI


def xi_of(t, a4, lam=LAM):
    F = rho(rot4(np.pi * t)) @ frame_diag(a4, lam)
    return np.linalg.solve(F, XI_VEC)


def ray(alpha, s):
    al = np.asarray(alpha, dtype=float)
    return tuple(np.exp(2.0 * al * s))


A_CONF_UP = (1.0, 1.0, 1.0, 1.0)
A_CONF_DN = (-1.0, -1.0, -1.0, -1.0)
A_BOOST = (1.0, 0.0, 0.0, 1.0)
TGRID = np.linspace(0.0, 1.0, 41)


def q_profile(alpha, s):
    a4 = ray(alpha, s)
    return np.array([qform(xi_of(t, a4)) for t in TGRID])


def crossing_scan(alpha, s_hi):
    for s in np.linspace(0.0, s_hi, 61):
        q = q_profile(alpha, s)
        if np.min(q) < 0.0:
            t_star = float(TGRID[int(np.argmin(q))])
            return float(s), t_star
    return None, None


def bisect_wall(alpha, t_star, s_hi):
    lo, hi = 0.0, s_hi
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        if qform(xi_of(t_star, ray(alpha, mid))) > 0:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


# --- both-modes helpers -------------------------------------------------------
def halves_complex(D, q):
    """Spectral projectors/bases of the +-i sqrt(-q) halves (q < 0)."""
    g = np.sqrt(-q)
    Pg = 0.5 * (I128 - 1j * D / g)   # growing half E_{+i g}
    Pd = 0.5 * (I128 + 1j * D / g)   # decaying half E_{-i g}
    Bg = np.linalg.svd(Pg)[0][:, :DIM // 2]
    Bd = np.linalg.svd(Pd)[0][:, :DIM // 2]
    return Pg, Pd, Bg, Bd, g


def evolve(D, q, tau):
    """U(tau) = exp(-i D tau) via the ENTIRE-in-q closed form
    U = C(q,tau) I - i S(q,tau) D, C = cos(sqrt(q) tau),
    S = sin(sqrt(q) tau)/sqrt(q) -- valid on BOTH sides of the wall and
    AT it (C, S are entire functions of q; series form in ent_CS)."""
    if q > 0:
        r = np.sqrt(q)
        return np.cos(r * tau) * I128 - 1j * (np.sin(r * tau) / r) * D
    if q < 0:
        r = np.sqrt(-q)
        return np.cosh(r * tau) * I128 - 1j * (np.sinh(r * tau) / r) * D
    return I128 - 1j * tau * D


def ent_CS(q, tau, nterms=40):
    """The entire series C(q,tau) = sum (-q)^k tau^{2k}/(2k)!,
    S(q,tau) = sum (-q)^k tau^{2k+1}/(2k+1)!."""
    C = 0.0
    S = 0.0
    term_c, term_s = 1.0, tau
    for k in range(nterms):
        C += term_c
        S += term_s
        term_c *= (-q) * tau * tau / ((2 * k + 1) * (2 * k + 2))
        term_s *= (-q) * tau * tau / ((2 * k + 2) * (2 * k + 3))
    return C, S


def space_time_split(x14):
    xs = x14.copy()
    xs[9:] = 0.0
    xt = x14 - xs
    return xs, xt


def canonical_cut_S(x14):
    """The f5 closed form S = K_S e^{alpha w} (q > 0 only)."""
    xs, xt = space_time_split(x14)
    P = float(xs @ xs)
    T = float(xt @ xt)
    al = np.arctanh(np.sqrt(T / P))
    w_inv = (cvec(xs) @ cvec(xt)) / np.sqrt(P * T)
    return K_S @ (np.cosh(al) * I128 + np.sinh(al) * w_inv), al


def built_cut_S(D, q):
    """The Gram-spectral cut S = Q_+ - Q_- built exactly as in the
    n2/f2 probes (K-positive parts of both halves vs K-negative)."""
    chp = 0.5 * (I128 + D / np.sqrt(q))
    chm = I128 - chp
    parts = {}
    for lbl, ch in (("p", chp), ("m", chm)):
        B = np.linalg.svd(ch)[0][:, :DIM // 2]
        Gm = B.conj().T @ K_S @ B
        Gm = 0.5 * (Gm + Gm.conj().T)
        w, Sv = np.linalg.eigh(Gm)
        parts[lbl] = (B @ Sv[:, w > 0], B @ Sv[:, w < 0])
    Wp = np.hstack([parts["p"][0], parts["m"][0]])
    Wm = np.hstack([parts["p"][1], parts["m"][1]])

    def kproj(Xc):
        M = Xc.conj().T @ K_S @ Xc
        return Xc @ np.linalg.solve(M, Xc.conj().T @ K_S)

    return kproj(Wp) - kproj(Wm)


U_h = e[0] @ e[3] @ e[4] @ e[9] @ e[11] @ e[12]
U_ss = e[0] @ e[1] @ e[4] @ e[5] @ e[10] @ e[11]


# =============================================================================
# [T] setup
# =============================================================================
cliff_ok = True
for a in range(N_DIRS):
    for b in range(a, N_DIRS):
        want = 2.0 * (ETA[a] if a == b else 0.0)
        got = e[a] @ e[b] + e[b] @ e[a]
        if float(np.max(np.abs(got - want * I128))) > 1e-9:
            cliff_ok = False
herm = float(np.max(np.abs(K_S - K_S.conj().T)))
invol = float(np.max(np.abs(K_S @ K_S - I128)))
jj = float(np.max(np.abs(C_J @ np.conj(C_J) + I128)))
jks = float(np.max(np.abs(C_J @ np.conj(K_S) - K_S @ C_J)))
# fixed deterministic test covector (NOT drawn from RNG: the RNG stream is
# reserved so the sweep below replays the n2 probe's stream exactly)
x_fix = np.cos(1.7 * np.arange(N_DIRS)) + 0.3
jcl = float(np.max(np.abs(C_J @ np.conj(cvec(x_fix)) - cvec(x_fix) @ C_J)))
check("T", "rep integrity: Clifford relations for eta (9,5); K_S Hermitian "
           "involution; J_quat = C_J o conj has J^2 = -I, commutes with K_S "
           "and with the Clifford action of every real covector (the "
           "antilinear structure is native, not chosen)",
      cliff_ok and herm < 1e-9 and invol < 1e-9 and jj < 1e-12
      and jks < 1e-12 and jcl < 1e-12)

base_id = float(np.max(np.abs(xi_of(0.0, (1.0, 1.0, 1.0, 1.0)) - XI)))
q_base = qform(XI)
c2_closed = np.sqrt(3328.0 / 7.0) * float(np.linalg.norm(XI))
check("T", "end-model machinery replicated faithfully: xi(0,0) = XI "
           "machine-exactly (the same family as the n2 probe; anchors "
           "inherited, C2 closed form = 155.3625), base q = 30.13 spacelike",
      base_id < 1e-12 and abs(c2_closed - 155.3625) < 1e-2 and q_base > 0,
      f"base id {base_id:.1e}, q(XI) = {q_base:.4f}")

# the ACTUAL N2 crossing rays: replicate the n2 probe's seeded sweep with
# the SAME stream discipline (one 14-draw precedes the 200-ray sweep there;
# reproduced here so the rays are THE SAME rays)
_stream_align = RNG.standard_normal(N_DIRS)
sweep_rays = []
n_gap, n_cross, n_time, n_und = 0, 0, 0, 0
for _ in range(200):
    al = RNG.standard_normal(4)
    al = al / np.linalg.norm(al)
    cls = []
    for s in (3.0, 4.0):
        q = q_profile(al, s)
        if np.min(q) > 0:
            cls.append("gap")
        elif np.max(q) < 0:
            cls.append("time")
        else:
            cls.append("cross")
    if cls[0] != cls[1]:
        n_und += 1
    elif cls[1] == "gap":
        n_gap += 1
    elif cls[1] == "time":
        n_time += 1
    else:
        n_cross += 1
        sweep_rays.append(al)
check("T", "the n2 end-model sweep REPRODUCED (same seed, same stream): "
           "200 diagonal rays classify 132 gapped / 53 cone-crossing / 0 "
           "timelike / 15 undecided-at-s4 -- the crossing rays below are "
           "the n2 probe's own crossing rays, not a new catalogue",
      n_gap == 132 and n_cross == 53 and n_time == 0 and n_und == 15,
      f"gapped {n_gap} / crossing {n_cross} / timelike {n_time} / "
      f"undecided {n_und}")


# =============================================================================
# Part A -- primary fidelity: [P1] eqs (8)-(13) reconstructed machine-exactly
# =============================================================================
s_m = 0.6
nu = np.sqrt(1.0 - s_m * s_m)
shb = nu / s_m
chb = np.sqrt(1.0 + shb * shb)
beta = np.arcsinh(shb)
s0 = np.eye(2, dtype=complex)
s2 = np.array([[0.0, -1j], [1j, 0.0]])
V_M = (s0 + s2 * chb) / (1j * shb)
u_p = (1.0 / np.sqrt(2 * shb)) * np.array([np.exp(beta / 2),
                                           -1j * np.exp(-beta / 2)])
u_m = (1.0 / np.sqrt(2 * shb)) * np.array([1j * np.exp(-beta / 2),
                                           np.exp(beta / 2)])


def ipV(a, b):
    return complex(a.conj() @ V_M @ b)


lam_p, lam_m = 1.0 + 1j * nu, 1.0 - 1j * nu
H_M = lam_p * np.outer(u_p, u_m.conj()) @ V_M \
    - lam_m * np.outer(u_m, u_p.conj()) @ V_M
closure = np.outer(u_p, u_m.conj()) @ V_M - np.outer(u_m, u_p.conj()) @ V_M
ph_ok = float(np.max(np.abs(V_M @ H_M @ np.linalg.inv(V_M)
                            - H_M.conj().T)))
prop_ok = True
for E in (0.3, 1.0, 2.2):
    d10 = ipV(u_m, u_p) / (E - lam_m) + ipV(u_p, u_m) / (E - lam_p)
    d13 = -2j * nu / ((E - 1.0) ** 2 + nu * nu)
    if abs(d10 - d13) > 1e-12:
        prop_ok = False
tind_ok = True
for t in (0.7, 2.0):
    upt = u_p * np.exp((-1j + nu) * t)
    umt = u_m * np.exp((-1j - nu) * t)
    if abs(complex(umt.conj() @ V_M @ upt) - 1.0) > 1e-12 or \
       abs(complex(upt.conj() @ V_M @ upt)) > 1e-12:
        tind_ok = False
check("E", "PRIMARY FIDELITY [P1] eqs (8)-(13), machine-exact: V is "
           "ANTI-Hermitian; u+^dag V u+ = u-^dag V u- = 0 (self-null); "
           "u-^dag V u+ = +1, u+^dag V u- = -1 (cross, relative minus); "
           "closure = I; the reconstructed H obeys V H V^-1 = H^dag with "
           "eigenvalues 1 +- i nu; the paired propagator equals "
           "-2iGamma/((E-E0)^2+Gamma^2) on an E-grid; and BOTH pairings "
           "are time independent while each member grows/decays -- "
           "Mannheim's both-modes construction verified from the primary, "
           "not from the transcript",
      float(np.max(np.abs(V_M + V_M.conj().T))) < 1e-12
      and abs(ipV(u_p, u_p)) < 1e-12 and abs(ipV(u_m, u_m)) < 1e-12
      and abs(ipV(u_m, u_p) - 1.0) < 1e-12
      and abs(ipV(u_p, u_m) + 1.0) < 1e-12
      and float(np.max(np.abs(closure - np.eye(2)))) < 1e-12
      and ph_ok < 1e-12 and prop_ok and tind_ok)


# =============================================================================
# Part B -- the V-structure is native: V = K_S, pseudo-unitarity, and the
#           universal-null lemma
# =============================================================================
s_dn, t_dn = crossing_scan(A_CONF_DN, 3.0)
s_star = bisect_wall(A_CONF_DN, t_dn, s_dn)
x_gap = xi_of(t_dn, ray(A_CONF_DN, max(s_star - 0.4, 0.0)))
x_cross = xi_of(t_dn, ray(A_CONF_DN, s_star + 0.4))
q_gap, q_cross = qform(x_gap), qform(x_cross)
D_gap, D_cross = cvec(x_gap), cvec(x_cross)
ok_v = True
for Dx in (D_gap, D_cross):
    if float(np.max(np.abs(K_S @ Dx - Dx.conj().T @ K_S))) > 1e-9 * max(
            1.0, float(np.max(np.abs(Dx)))):
        ok_v = False
ok_pu = True
for (Dx, qx) in ((D_gap, q_gap), (D_cross, q_cross)):
    for tau in (0.2, 0.8):
        U = evolve(Dx, qx, tau)
        if float(np.max(np.abs(U.conj().T @ K_S @ U - K_S))) > 1e-8 * max(
                1.0, float(np.max(np.abs(U))) ** 2):
            ok_pu = False
check("E", "V = K_S IS Mannheim's V on the actual family: K_S D - D^dag "
           "K_S = 0 ([P2] eq 34) on both sides of the conf-down wall, and "
           "the evolution exp(-i D tau) is K_S-PSEUDO-UNITARY ([P2] eq 37) "
           "on both sides -- the conserved indefinite pairing EXISTS across "
           "the wall and is supplied by the repo's own fundamental "
           "symmetry, with no new operator introduced (kill K-a, clause 1: "
           "does not fire)",
      ok_v and ok_pu,
      f"wall at s* = {s_star:.4f} (t* = {t_dn:.3f}); "
      f"q gap {q_gap:.2f} -> crossed {q_cross:.2f}")

# universal-null lemma: ANY conserved pairing is null on each nonreal half.
# Proof (two lines, machine-checked): V D = D^dag V and D x = lam x,
# D y = lam y give lam x^dag V y = x^dag V D y = (D x)^dag V y =
# conj(lam) x^dag V y, so (lam - conj(lam)) x^dag V y = 0.
_, _, Bg_c, Bd_c, g_c = halves_complex(D_cross, q_cross)
null_all = True
for (ac, bc) in ((1.0, 0.7), (0.3, -1.2), (2.0, 0.0)):
    Vc = K_S @ (ac * I128 + bc * D_cross)   # V_c D = D^dag V_c by K_S-s.a.
    if float(np.max(np.abs(Vc @ D_cross - D_cross.conj().T @ Vc))) > 1e-7:
        null_all = False
    if float(np.max(np.abs(Bg_c.conj().T @ Vc @ Bg_c))) > 1e-7 or \
       float(np.max(np.abs(Bd_c.conj().T @ Vc @ Bd_c))) > 1e-7:
        null_all = False
check("E", "the UNIVERSAL-NULL LEMMA at the actual crossing (two-line "
           "proof, machine-checked on a conserved-V family): EVERY pairing "
           "conserved by the crossed family is EXACTLY null on each "
           "complex half -- so NO conserved positive-definite pairing "
           "exists past the wall, for any scheme. W172's 'broken PT => no "
           "positive C-metric' is CONFIRMED and UPGRADED to all conserved "
           "pairings; the only conserved accountings available past the "
           "wall are both-modes-shaped (self-null + cross)",
      null_all)


# =============================================================================
# Part C -- the both-modes normal form at the ACTUAL N2 crossings
# =============================================================================
deep_rays = [("conf-down", A_CONF_DN, t_dn, s_star),
             ("boost", A_BOOST, None, None),
             ("sweep-0", tuple(sweep_rays[0]), None, None),
             ("sweep-1", tuple(sweep_rays[1]), None, None),
             ("sweep-2", tuple(sweep_rays[2]), None, None)]
ok_null, ok_cross, ok_uni = True, True, True
sv_report = []
pair_data = None
for (nm, al, t_c, s_c) in deep_rays:
    if t_c is None:
        s_hit, t_c = crossing_scan(al, 4.0)
        if s_hit is None:
            ok_cross = False
            continue
        s_c = bisect_wall(al, t_c, s_hit)
    x_c = xi_of(t_c, ray(al, s_c + 0.4))
    q_c = qform(x_c)
    if q_c >= 0:
        ok_cross = False
        continue
    D_c = cvec(x_c)
    _, _, Bg, Bd, gam = halves_complex(D_c, q_c)
    n_g = float(np.max(np.abs(Bg.conj().T @ K_S @ Bg)))
    n_d = float(np.max(np.abs(Bd.conj().T @ K_S @ Bd)))
    Gx = Bd.conj().T @ K_S @ Bg
    sv = np.linalg.svd(Gx, compute_uv=False)
    if n_g > 1e-8 or n_d > 1e-8:
        ok_null = False
    if sv.min() < 1e-3:
        ok_cross = False
    if (sv.max() - sv.min()) > 1e-8 * sv.max():
        ok_uni = False
    sv_report.append(f"{nm}: r = {sv[0]:.4f}")
    if nm == "conf-down":
        pair_data = (x_c, q_c, D_c, Bg, Bd, Gx, gam, sv[0])
check("E", "BOTH-MODES NORMAL FORM at five ACTUAL crossing walls "
           "(conf-down, boost, three seeded n2 sweep rays): past each "
           "wall the halves E_{+-i sqrt|q|} are EXACTLY K_S-null (the n2 "
           "little theorem = Mannheim's self-null condition u^dag V u = "
           "0), while the CROSS-Gram Bd^dag K_S Bg is NONDEGENERATE with "
           "ALL 64 singular values EQUAL (quaternionic uniformity) -- the "
           "conserved accounting on the crossing sector is defined, "
           "indefinite, and cross-paired exactly as in [P1] eq (9)",
      ok_null and ok_cross and ok_uni,
      "; ".join(sv_report))

x_c, q_c, D_c, Bg, Bd, Gx, gam, r_pair = pair_data
Uu, sv_x, Vvh = np.linalg.svd(Gx)
w0 = Vvh.conj().T[:, 0]
x_g = Bg @ w0
x_d = Bd @ (Uu[:, 0])
g_raw = complex(np.vdot(x_d, K_S @ x_g))
x_g = x_g * (-1j * abs(g_raw) / g_raw)   # the Mannheim gauge: g -> -i r
g_pair = complex(np.vdot(x_d, K_S @ x_g))
res_g, res_d = g_pair, np.conj(g_pair)
ls_ok, real_ok = True, True
for E in (0.0, 0.5 * gam, 2.0 * gam):
    wv = x_g + x_d
    dE_direct = complex(np.vdot(wv, K_S @ np.linalg.solve(
        E * I128 - D_c, wv)))
    dE_closed = res_g / (E - 1j * gam) + res_d / (E + 1j * gam)
    dE_lorentz = -2.0 * gam * np.imag(g_pair) / (E * E + gam * gam)
    if abs(dE_direct - dE_closed) > 1e-8 * max(1.0, abs(dE_closed)):
        ls_ok = False
    if abs(np.imag(dE_direct)) > 1e-8 or \
       abs(dE_direct - dE_lorentz) > 1e-8 * max(1.0, abs(dE_lorentz)):
        real_ok = False
check("E", "the RELATIVE-MINUS pair propagator, realized on the actual "
           "crossed family: in the Mannheim gauge the cross-residues are "
           "-i r and +i r (r = the uniform pairing weight) -- residues "
           "CONJUGATE with the relative minus in the imaginary part, "
           "self-residues ZERO (both poles enter only through cross "
           "terms) -- and the paired two-point function w^dag K_S "
           "(E - D)^-1 w is REAL on the real axis and is EXACTLY the "
           "sign-definite Lorentzian 2 r Gamma/(E^2 + Gamma^2) of width "
           "Gamma = sqrt|q| ([P1] eq (13) transposed; the factor i "
           "between his +-1 and our -+i r is the anti-Hermitian-V vs "
           "Hermitian-K_S convention, stated not hidden)",
      abs(g_pair + 1j * r_pair) < 1e-9 and ls_ok and real_ok,
      f"r = {r_pair:.4f}, Gamma = {gam:.4f}")

# population accounting: Dirac norms move exponentially; ALL pairings fixed
ok_pop, ok_grow = True, False
for tau in (0.1, 0.3, 0.6):
    Uev = evolve(D_c, q_c, tau)
    xg_t, xd_t = Uev @ x_g, Uev @ x_d
    if abs(complex(np.vdot(xd_t, K_S @ xg_t)) - g_pair) > 1e-6 * abs(g_pair):
        ok_pop = False
    if abs(complex(np.vdot(xg_t, K_S @ xg_t))) > 1e-6:
        ok_pop = False
    dirac = float(np.linalg.norm(xg_t)) ** 2
    if tau == 0.6 and dirac > np.exp(2 * gam * 0.6) * 0.5:
        ok_grow = True
check("E", "POPULATION ACCOUNTING (the [01:44:44] both-modes condition, "
           "machine-realized): under exp(-i D tau) the growing member's "
           "Dirac norm inflates as e^{2 Gamma tau} while EVERY K_S "
           "pairing is exactly constant -- the growing-decaying "
           "transition element never grows, the self-pairings stay zero, "
           "'the total population remains fixed' in the conserved "
           "accounting; kept-both-modes probability conservation holds "
           "with NO positive metric anywhere in sight",
      ok_pop and ok_grow)

# J_quat as the mode exchange; Kramers antisymmetry of the composite form
JBg = C_J @ np.conj(Bg)
resid_J = float(np.linalg.norm(JBg - Bd @ (Bd.conj().T @ JBg)))
Bmat = JBg.conj().T @ K_S @ Bg          # B(x,y) = (Jx)^dag K_S y, bilinear
anti = float(np.max(np.abs(Bmat + Bmat.T)))
nondeg = float(np.min(np.linalg.svd(Bmat, compute_uv=False)))
check("E", "J_quat IS the antilinear mode exchange: J maps the growing "
           "half ONTO the decaying half (no external antilinear choice -- "
           "kill K-a, clause 2: does not fire), and the composite bilinear "
           "form B(x,y) = (Jx)^dag K_S y on the growing half is "
           "ANTISYMMETRIC and nondegenerate (checked on an 8-dim block) -- "
           "the Kramers/symplectic shape that forced the J-partner's "
           "self-pairing to vanish; the Mannheim partner is the "
           "PAIRING-CANONICAL (SVD) partner, derivable from {D, K_S} alone",
      resid_J < 1e-8 and anti < 1e-9 and nondeg > 1e-3,
      f"J-residual {resid_J:.1e}, antisym {anti:.1e}")


# =============================================================================
# Part D -- the wall itself: Jordan structure and entire-in-q continuity
# =============================================================================
x_wall = xi_of(t_dn, ray(A_CONF_DN, s_star))
xs_w, xt_w = space_time_split(x_wall)
P_w, T_w = float(xs_w @ xs_w), float(xt_w @ xt_w)
x_null = xs_w + xt_w * np.sqrt(P_w / T_w)   # exact-null representative
dist_null = float(np.linalg.norm(x_null - x_wall) / np.linalg.norm(x_wall))
q_null = qform(x_null)
D_null = cvec(x_null)
s_E_null = float(x_null @ x_null)
sq = float(np.max(np.abs(D_null @ D_null)))
U_n, sv_n, Vh_n = np.linalg.svd(D_null)
rank64 = int(np.sum(sv_n > 1e-8 * sv_n[0])) == 64
Bk = Vh_n.conj().T[:, 64:]                 # kernel basis
Br = U_n[:, :64]                           # range basis
Bw = Vh_n.conj().T[:, :64]                 # a (Dirac) complement of Ker
ker_eq_range = float(np.linalg.norm(Bk @ Bk.conj().T - Br @ Br.conj().T))
ker_null = float(np.max(np.abs(Bk.conj().T @ K_S @ Bk)))
ker_perp_range = float(np.max(np.abs(Bk.conj().T @ K_S @ Br)))
sv_comp = np.linalg.svd(Bk.conj().T @ K_S @ Bw, compute_uv=False)
ok_jordan = True
y_j = Bw[:, 0]                             # a non-kernel vector
z_j = D_null @ y_j
ov0 = complex(np.vdot(z_j, K_S @ y_j))
grew = False
for tau in (0.5, 2.0):
    Uj = I128 - 1j * tau * D_null
    if abs(complex(np.vdot(Uj @ z_j, K_S @ (Uj @ y_j))) - ov0) > \
       1e-8 * max(1.0, abs(ov0)):
        ok_jordan = False
    if float(np.max(np.abs(Uj.conj().T @ K_S @ Uj - K_S))) > \
       1e-7 * float(np.max(np.abs(K_S @ D_null))):
        ok_jordan = False
    if tau == 2.0 and float(np.linalg.norm(Uj @ y_j)) > \
       1.5 * float(np.linalg.norm(y_j)):
        grew = True
check("E", "THE WALL ITSELF is the Jordan-block case of [P1] (eqs (6)-(7) "
           "analog), at the actual conf-down collision: the exact-null "
           "representative of the collision direction has D^2 = 0 with D "
           "of rank exactly 64, Ker D = Range D, the kernel EXACTLY "
           "K_S-null AND K_S-orthogonal to the range (the zero-norm "
           "states of [P1]'s equal-frequency PU case), while K_S pairs "
           "the kernel with a complement ISOMETRICALLY (all 64 singular "
           "values = 1); the Jordan evolution I - i tau D grows states "
           "linearly while every K_S pairing stays EXACTLY constant -- "
           "the conserved accounting covers the wall point itself, not "
           "just its two sides",
      dist_null < 0.05 and abs(q_null) < 1e-10 * s_E_null
      and sq < 1e-9 * sv_n[0] ** 2
      and rank64 and ker_eq_range < 1e-8 and ker_null < 1e-9
      and ker_perp_range < 1e-9
      and sv_comp.min() > 0.999 and sv_comp.max() < 1.001
      and ok_jordan and grew,
      f"|q_null| = {abs(q_null):.1e}, rank "
      f"{int(np.sum(sv_n > 1e-8 * sv_n[0]))}, "
      f"complement pairing sv in [{sv_comp.min():.6f}, {sv_comp.max():.6f}]")

# entire-in-q evolution: series = closed forms on all three regimes; the
# wall crossing is continuous in every GAUGE-INVARIANT quantity. (The
# replicated n2 frame machinery has a per-s cluster gauge; the n2 probe
# consumed no s-continuity of that gauge and neither do we: q, the collar
# margins, the pairing weight r, and U(D_null, q) are all gauge-invariant.)
ok_ent = True
for (qq, DD) in ((q_gap, D_gap), (q_cross, D_cross), (0.0, D_null)):
    for tau in (0.3, 1.0):
        Cs, Ss = ent_CS(qq, tau)
        U_series = Cs * I128 - 1j * Ss * DD
        U_closed = evolve(DD, qq, tau)
        if float(np.max(np.abs(U_series - U_closed))) > 1e-9 * max(
                1.0, float(np.max(np.abs(U_closed)))):
            ok_ent = False
q_sm, margins, r_col, contU = [], [], [], []
for dlt in (0.2, 0.02, 0.002):
    xm = xi_of(t_dn, ray(A_CONF_DN, s_star - dlt))
    xp = xi_of(t_dn, ray(A_CONF_DN, s_star + dlt))
    qm, qp = qform(xm), qform(xp)
    q_sm.append((qm / dlt, -qp / dlt))     # two-sided slope estimates
    xs_m, xt_m = space_time_split(xm)
    Pm, Tm = float(xs_m @ xs_m), float(xt_m @ xt_m)
    margins.append(float(np.sqrt(1.0 - Tm / Pm)))   # sech(alpha) closed form
    _, _, Bg_p, Bd_p, _ = halves_complex(cvec(xp), qp)
    r_col.append(float(np.linalg.svd(Bd_p.conj().T @ K_S @ Bg_p,
                                     compute_uv=False)[0]))
    Um = evolve(D_null, qm, 0.5)           # same D: isolates the q-passage
    Up = evolve(D_null, qp, 0.5)
    contU.append(float(np.max(np.abs(Up - Um))))
slope_ok = abs(q_sm[2][0] / q_sm[2][1] - 1.0) < 0.05 \
    and abs(q_sm[1][0] / q_sm[1][1] - 1.0) < 0.05 \
    and abs(q_sm[1][0] / q_sm[2][0] - 1.0) < 0.05
# (the two-sided slope equality is a NEAR-WALL statement -- at dlt = 0.2
#  the ray is far from the wall and q is visibly nonlinear, as it should be)
lipU = contU[0] / contU[1] > 3.0 and contU[1] / contU[2] > 3.0
collapse = margins[0] > margins[1] > margins[2] and margins[2] < 0.15 \
    and r_col[0] > r_col[1] > r_col[2] and r_col[2] < 0.25
check("E", "WALL CONTINUITY vs MODE-NORMALIZATION COLLAPSE (the "
           "exceptional-point structure, measured on the actual ray): the "
           "evolution is ENTIRE in q (one power series = cos/sin, "
           "cosh/sinh, AND the Jordan form, machine-exact); q(s) passes "
           "through 0 with equal two-sided slopes; U(D, q(s), tau) is "
           "Lipschitz through the wall (|U(q+) - U(q-)| shrinks linearly); "
           "while BOTH normalized mode structures collapse at the wall "
           "symmetrically -- the canonical-cut margin sech(alpha) from the "
           "gapped side AND the normalized cross-pairing weight r from "
           "the crossed side both -> 0. The conserved accounting (pairing "
           "+ evolution) crosses the wall; the MODE NORMALIZATION is "
           "singular exactly AT it -- which is [P1]'s own structure: the "
           "exceptional point is where the construction hands over to the "
           "Jordan-block realization, verified in the previous check",
      ok_ent and slope_ok and lipU and collapse,
      f"q-slopes {q_sm[2][0]:.2f}/{q_sm[2][1]:.2f}; contU "
      f"{contU[0]:.2e}/{contU[1]:.2e}/{contU[2]:.2e}; margins "
      f"{margins[0]:.3f}/{margins[1]:.3f}/{margins[2]:.3f}; r "
      f"{r_col[0]:.3f}/{r_col[1]:.3f}/{r_col[2]:.3f}")


# =============================================================================
# Part E -- deck-exchange/holonomy compatibility (kill K-b)
# =============================================================================
uh_props = (float(np.max(np.abs(U_h @ U_h - I128))) < 1e-9
            and float(np.max(np.abs(U_h.conj().T - U_h))) < 1e-9
            and float(np.max(np.abs(U_h.conj().T @ U_h - I128))) < 1e-9)
tw = float(np.max(np.abs(U_h.conj().T @ K_S @ U_h + K_S)))
dc = float(np.max(np.abs(U_h.conj().T @ (U_h.conj().T @ K_S @ U_h)
                         @ U_h - K_S)))
# the seam identity at a crossing radius on the conf-down ray
a4_c = ray(A_CONF_DN, s_star + 0.4)
D0c, D1c = cvec(xi_of(0.0, a4_c)), cvec(xi_of(1.0, a4_c))
seam_c = float(np.max(np.abs(D1c - U_h @ D0c @ np.linalg.inv(U_h))))
# spectrum is preserved leg by leg: U_h maps the halves of D(0) to D(1)
q0c = qform(xi_of(0.0, a4_c))
ok_map = True
if q0c < 0:
    _, _, Bg0, Bd0, _ = halves_complex(D0c, q0c)
    _, _, Bg1, Bd1, _ = halves_complex(D1c, qform(xi_of(1.0, a4_c)))
    for (Bsrc, Bdst) in ((Bg0, Bg1), (Bd0, Bd1)):
        Y = U_h @ Bsrc
        if float(np.linalg.norm(Y - Bdst @ (Bdst.conj().T @ Y))) > 1e-7:
            ok_map = False
check("E", "DECK COMPATIBILITY (kill K-b: does not fire): U_h is a "
           "Hermitian unitary involution; transporting the pairing around "
           "the loop gives U_h^dag K_S U_h = -K_S EXACTLY (the datum "
           "returns to MINUS itself -- the same Z/2 twist as the "
           "two-section exchange and the signed-C2 flip, not a new "
           "obstruction), returns to +K_S on the double cover; the seam "
           "identity D(1,s) = U_h D(0,s) U_h^-1 holds AT the crossing "
           "radius and U_h maps each complex half of D(0,s) onto the "
           "SAME-eigenvalue half of D(1,s) -- the both-modes datum is a "
           "section-like object twisted by the KNOWN character",
      uh_props and tw < 1e-9 and dc < 1e-9
      and seam_c < 1e-7 * max(1.0, float(np.max(np.abs(D0c)))),
      f"twist defect {tw:.1e}, seam {seam_c:.1e}"
      + ("" if q0c >= 0 else ", halves mapped"))

# the pairing datum has no t-holes at crossing radii (the cut does)
qs_t = np.array([qform(xi_of(float(t), a4_c)) for t in TGRID])
frac_crossed = float(np.mean(qs_t < 0))
ok_all_t = True
for t in TGRID[::8]:
    x_t = xi_of(float(t), a4_c)
    D_t = cvec(x_t)
    if float(np.max(np.abs(K_S @ D_t - D_t.conj().T @ K_S))) > 1e-8 * max(
            1.0, float(np.max(np.abs(D_t)))):
        ok_all_t = False
check("E", "SECTION-LIKE COVERAGE at a crossing radius: along the loop at "
           "s* + 0.4 the boundary family crosses the null cone for an "
           "open t-interval (the canonical cut is UNDEFINED there -- the "
           "n2 t-holes), yet K_S D(t) = D(t)^dag K_S holds at EVERY t: "
           "the conserved-pairing datum is defined on the WHOLE loop, "
           "gapped and crossed alike -- the crossing sector gains a "
           "globally-defined accounting where the cut section has holes",
      0.05 < frac_crossed < 0.95 and ok_all_t,
      f"crossed fraction of the loop: {frac_crossed:.2f}")


# =============================================================================
# Part F -- gapped-side degeneration to the canonical cut (f5 regression)
# =============================================================================
ok_degen = True
degen_report = []
for (nm, x14) in (("base XI", XI),
                  ("conf-down gapped", x_gap)):
    q_x = qform(x14)
    if q_x <= 0:
        ok_degen = False
        continue
    S_blt = built_cut_S(cvec(x14), q_x)
    S_cls, al_x = canonical_cut_S(x14)
    d_S = float(np.max(np.abs(S_blt - S_cls)))
    if d_S > 1e-7:
        ok_degen = False
    degen_report.append(f"{nm}: |S_built - K_S e^(aw)| = {d_S:.1e}, "
                        f"alpha = {al_x:.4f}")
check("E", "GAPPED-SIDE DEGENERATION: where q > 0 the both-modes pairing "
           "datum (K_S restricted to the D-eigenspaces, sign-diagonalized) "
           "REBUILDS the canonical cut, and the built cut equals the f5 "
           "closed form S = K_S e^{alpha w} machine-exactly at the base "
           "point AND on the crossing ray's gapped side -- the pairing is "
           "not a rival structure: it refines to the canonical cut "
           "exactly where the cut exists, and survives where it dies",
      ok_degen, "; ".join(degen_report))


# =============================================================================
# [F] controls
# =============================================================================
ss_props = (float(np.max(np.abs(U_ss @ U_ss + I128))) < 1e-9
            and float(np.max(np.abs(U_ss.conj().T + U_ss))) < 1e-9)
ss_pres = float(np.max(np.abs(U_ss.conj().T @ K_S @ U_ss - K_S)))
check("F", "trichotomy control: the same-sign-plane seam U_ss (6 legs, "
           "FOUR K_S factors -- even) PRESERVES the pairing exactly "
           "(U_ss^dag K_S U_ss = +K_S; U_ss^2 = -I, anti-Hermitian): the "
           "pairing's Z/2 twist fires precisely on the genuine mixed-plane "
           "generator, exactly as the two-section twist does -- the deck "
           "anti-invariance is holonomy content, not a bookkeeping artifact",
      ss_props and ss_pres < 1e-9)

surv_ok = True
for s in (0.0, 1.5, 3.0):
    x_s = xi_of(0.3, ray(A_CONF_UP, s))
    if qform(x_s) <= 0:
        surv_ok = False
x_inf = xi_of(0.3, (1.0, 1.0, 1.0, 1.0)).copy()
x_inf[[3, 4, 5, 6, 7, 8, 10, 11, 12, 13]] = 0.0
surv_ok = surv_ok and qform(x_inf) > 0
check("F", "no-manufacture control: on the SURVIVING (conformal blow-up) "
           "ray the family is gapped at every sampled collar radius and "
           "at the boundary-at-infinity direction -- no complex pairs "
           "exist there and the both-modes machinery has nothing to pair: "
           "the construction reads the wall structure, it does not "
           "manufacture it on the gapped sector",
      surv_ok)

gauge_flip = None
x_g_flip = x_g * np.exp(1j * np.pi)   # theta -> theta + pi
g_flip = complex(np.vdot(x_d, K_S @ x_g_flip))
d0 = -2.0 * gam * np.imag(g_pair) / (gam * gam)
d1 = -2.0 * gam * np.imag(g_flip) / (gam * gam)
gauge_flip = abs(d0 + d1) < 1e-9 * abs(d0)
check("F", "OVERALL-SIGN HONESTY (this control PASSES by exhibiting the "
           "gauge): rephasing one pair member by pi flips the sign of the "
           "paired Lorentzian -- at matrix grade the both-modes accounting "
           "fixes |residues|, conjugacy, relative minus, width, and "
           "conservation, but NOT the decay-vs-anti-damping orientation; "
           "that sign is operator-grade data (W172's dynamical question "
           "stays open and is NOT settled here)",
      bool(gauge_flip))

std_blind = True
for (Dx, qx) in ((D_gap, q_gap),):
    chp = 0.5 * (I128 + Dx / np.sqrt(qx))
    B_std = np.linalg.svd(chp)[0][:, :DIM // 2]
    Gm = B_std.conj().T @ K_S @ B_std
    w_std = np.linalg.eigvalsh(0.5 * (Gm + Gm.conj().T))
    if not (int(np.sum(w_std > 0)) == 32 and int(np.sum(w_std < 0)) == 32):
        std_blind = False
check("F", "constructions-fork record (GEOMETER-VS-PHYSICS-OBJECTS): the "
           "standard positive-Hilbert half is K-INDEFINITE (signature "
           "(32,32)) on the gapped side of the crossing ray -- the "
           "standard fork neither sees the sector datum nor supplies a "
           "conserved positive pairing; the both-modes reading lives "
           "entirely on the Krein-native fork, named as such",
      std_blind)


# =============================================================================
# verdict + headline
# =============================================================================
nE = sum(1 for tag, _n, ok in RESULTS if tag == "E")
nF = sum(1 for tag, _n, ok in RESULTS if tag == "F")
nT = sum(1 for tag, _n, ok in RESULTS if tag == "T")
all_ok = all(ok for _t, _n, ok in RESULTS)
print()
print("KILL-CONDITION VERDICT: K-a did NOT fire (V = K_S natively; the "
      "antilinear exchange is J_quat; the partner map is pairing-"
      "canonical; no positive pairing is required -- and none exists, by "
      "the universal-null lemma). K-b did NOT fire (the pairing "
      "transports anti-invariantly under the faithful deck -- the KNOWN "
      "Z/2 twist -- and returns on the double cover; seam and halves map "
      "exactly). K-c FIRED: a conserved, K_S-derivable, deck-compatible "
      "indefinite pairing exists across the cone-crossing walls, "
      "continuous in the collar (entire in q), degenerating to the "
      "canonical cut on the gapped side. The crossing sector has DEFINED "
      "(indefinite, both-modes) accounting; W172's unbroken-PT "
      "conditional retypes from wall to scheme choice -- typed "
      "fork-conditional; NO claim or canon movement.")
print(f"HEADLINE: {nE} [E] + {nF} [F] = {nE + nF}   (setup [T] = {nT} "
      f"excluded)   {'ALL PASS' if all_ok else 'FAILURES PRESENT'}")
sys.exit(0 if all_ok else 1)
