#!/usr/bin/env python3
"""
N4 probe: the two-frozen-Z/3s comparison (Phase 1, pre-registered node N4 of
explorations/phase0-dictionary-gate-tree-2026-07-20.md, commit 67ea601).

QUESTION. The repo holds two independently frozen Z/3 structures:
  (i)  the torsion-arena subgroup A = <J(k)> = {0, 8nu, 16nu}, the 3-Sylow of
       pi_3^s = Z/24, with e_KO values {0, 1/3, 2/3}
       (explorations/torsion-generation-arena-2026-07-20.md, k = +-64);
  (ii) the order-3 Nikulin monodromy's equivariant rho character data:
       Dirac (0,1,2)/3 (canon/order3-equivariant-rho-RESULTS.md) and
       carrier B gamma-traceless (0,2,1)/3
       (canon/gamma-traceless-38-adjudication-RESULTS.md), with frozen
       Z/24-arena columns Dirac (0,16,8), A (0,0,0), B (0,8,16).
Are they THE SAME Z/3 -- a character-set isomorphism grounded in frozen
receipts? Construction tested: Phi = (e_KO|_A)^{-1} o rho : Ghat -> A, which
exists iff rho is an injective homomorphism into (Q/Z)_(3) with image = e_KO(A).

TYPE DISCIPLINE (tree obligation 1): the operational counter type is an
UNSIGNED CARDINALITY. This probe tests a STRUCTURAL IDENTIFICATION between two
frozen Z/3s. It declares NO generation count.

Tags: [T] table/frozen input (cited, not re-derived); [E] exact computation
(Fraction arithmetic, no floats); [F] falsifier/control (planted wrongness
must be REJECTED -- demonstrated power).

Deterministic; exact rational arithmetic; exit 0 iff all checks pass.
"""

import sys
from fractions import Fraction as Fr
from itertools import product

CHECKS = {"T": 0, "E": 0, "F": 0}
FAILED = []


def check(tag, name, cond):
    CHECKS[tag] += 1
    status = "PASS" if cond else "FAIL"
    print(f"[{tag}] {status}  {name}")
    if not cond:
        FAILED.append(name)


def mod1(x):
    return x - (x.numerator // x.denominator) if isinstance(x, Fr) else Fr(x) % 1


def m1(x):
    f = Fr(x)
    return f - (f.numerator // f.denominator)  # representative in [0,1)


# ---------------------------------------------------------------- frozen inputs
# [T] Adams (J(X) IV, via H6 census / arena doc table inputs): pi_3^s = Z/24,
#     generated by nu, e_KO(nu) = 1/24, e_KO injective on im J = Z/24.
E_KO_NU = Fr(1, 24)

# [T] torsion-arena doc: commutant twist k = +-64 on the irreducible carrier;
#     native carrier ledger multiplicities (H^{64m}).
K_TWIST = 64
LEDGER_M = [1, 7, 13, 14, 91]

# [T] canon rho receipts: mod-Z classes rho_k for flat characters alpha_k,
#     k = 0,1,2, per carrier; non-equivariant fiber indices; frozen Z/24
#     arena columns as printed in the canon docs.
RHO = {
    "Dirac": {0: Fr(0), 1: Fr(1, 3), 2: Fr(2, 3)},   # order3-equivariant-rho
    "B":     {0: Fr(0), 1: Fr(2, 3), 2: Fr(1, 3)},   # gamma-traceless-38
    "A":     {0: Fr(0), 1: Fr(0),    2: Fr(0)},      # ghost-subtracted RS
}
IND = {"Dirac": 2, "B": -38, "A": -42}
ARENA_COL = {"Dirac": (0, 16, 8), "B": (0, 8, 16), "A": (0, 0, 0)}

# [T] families-e-invariant doc: Lefschetz number of the order-3 Nikulin
#     monodromy (its TOPOLOGICAL families invariant).
LEFSCHETZ = 6

check("T", "Adams: e_KO(nu) = 1/24 (table input, cited)", E_KO_NU == Fr(1, 24))
check("T", "arena: twist k = +-64 frozen (torsion-arena doc)", K_TWIST == 64)
check("T", "rho receipts loaded: Dirac (0,1,2)/3, B (0,2,1)/3, A (0,0,0)",
      RHO["Dirac"][1] == Fr(1, 3) and RHO["B"][1] == Fr(2, 3) and RHO["A"][1] == 0)
check("T", "fiber indices loaded: ind(D)=2, ind(B)=-38, ind(A)=-42",
      IND == {"Dirac": 2, "B": -38, "A": -42})
check("T", "frozen Z/24 arena columns loaded: (0,16,8)/(0,8,16)/(0,0,0)",
      ARENA_COL["Dirac"] == (0, 16, 8) and ARENA_COL["B"] == (0, 8, 16))
check("T", "Lefschetz L(phi) = 6 (families-e-invariant doc)", LEFSCHETZ == 6)

# ------------------------------------------------------- side (i): the arena Z/3
SYLOW3 = sorted(n for n in range(24) if (3 * n) % 24 == 0)  # 3-torsion of Z/24


def subgroup(gen):
    s, x = {0}, gen % 24
    while x not in s:
        s.add(x)
        x = (x + gen) % 24
    return sorted(s)


A_PLUS = subgroup(K_TWIST % 24)      # <J(+64)> = <16>
A_MINUS = subgroup((-K_TWIST) % 24)  # <J(-64)> = <8>

check("E", "3-Sylow of Z/24 computed = {0,8,16}", SYLOW3 == [0, 8, 16])
check("E", "<J(+64)> = <J(-64)> = {0,8,16}: subgroup orientation-independent",
      A_PLUS == SYLOW3 and A_MINUS == SYLOW3)
order3_subgroups = {tuple(subgroup(g)) for g in range(1, 24) if len(subgroup(g)) == 3}
check("E", "uniqueness: {0,8,16} is the ONLY order-3 subgroup of Z/24 (canonical, no choice)",
      order3_subgroups == {(0, 8, 16)})

A = SYLOW3
EKO_ON_A = {a: m1(Fr(a, 24)) for a in A}
check("E", "e_KO on A injective with image {0, 1/3, 2/3} exactly",
      sorted(EKO_ON_A.values()) == [Fr(0), Fr(1, 3), Fr(2, 3)]
      and len(set(EKO_ON_A.values())) == 3)

# --------------------------------------------- side (ii): the monodromy characters
def is_hom(rho):
    return all(m1(rho[(k + l) % 3]) == m1(rho[k] + rho[l])
               for k, l in product(range(3), repeat=2))


def is_inj(rho):
    vals = [m1(rho[k]) for k in range(3)]
    return len(set(vals)) == 3


check("E", "rho_Dirac: Ghat -> Q/Z is an injective homomorphism (all 9 pairs exact)",
      is_hom(RHO["Dirac"]) and is_inj(RHO["Dirac"]))
check("E", "rho_B: Ghat -> Q/Z is an injective homomorphism (all 9 pairs exact)",
      is_hom(RHO["B"]) and is_inj(RHO["B"]))
check("E", "referee formula rho_k == -(k/3)*ind mod Z reproduces ALL three carriers",
      all(m1(RHO[c][k]) == m1(Fr(-k * IND[c], 3))
          for c in RHO for k in range(3)))

# --------------------------------------- the identification Phi = e_KO^{-1} o rho
def build_phi(rho):
    """Unique intertwiner Phi: Ghat -> Z/24 with e_KO(Phi(k)) = rho_k, if any."""
    phi = {}
    for k in range(3):
        cand = [a for a in range(24) if m1(Fr(a, 24)) == m1(rho[k])]
        if len(cand) != 1:
            return None
        phi[k] = cand[0]
    return phi


def is_identification(rho):
    """Full gate: intertwiner exists, lands bijectively on A, is a group iso."""
    phi = build_phi(rho)
    if phi is None:
        return False, None
    if sorted(phi.values()) != A:
        return False, phi
    hom = all(phi[(k + l) % 3] == (phi[k] + phi[l]) % 24
              for k, l in product(range(3), repeat=2))
    return hom, phi


ok_D, PHI_D = is_identification(RHO["Dirac"])
ok_B, PHI_B = is_identification(RHO["B"])
check("E", "Phi_Dirac EXISTS: unique iso Ghat -> A, alpha_1 -> 8nu, alpha_2 -> 16nu",
      ok_D and PHI_D == {0: 0, 1: 8, 2: 16})
check("E", "Phi_B EXISTS: unique iso Ghat -> A, alpha_1 -> 16nu, alpha_2 -> 8nu",
      ok_B and PHI_B == {0: 0, 1: 16, 2: 8})

# frozen arena columns: one consistent sign convention, image = A either way
check("E", "frozen arena columns == (-24*rho_k mod 24) for BOTH nonzero carriers "
           "(single consistent frozen sign convention)",
      all(tuple((-24 * m1(RHO[c][k])) % 24 for k in range(3)) == ARENA_COL[c]
          for c in ("Dirac", "B")))
check("E", "image set = {0,8,16} = <J(k)> under EITHER sign convention, both carriers",
      all(sorted(set((s * 24 * m1(RHO[c][k])) % 24 for k in range(3))) == A
          for c in ("Dirac", "B") for s in (1, -1)))

# ------------------------------------------------- equivariance / ambiguity audit
def inv3(k):
    return (-k) % 3


def inv24(a):
    return (-a) % 24


check("E", "carrier swap acts by inversion: Phi_B = inv o Phi_D = Phi_D o inv",
      all(PHI_B[k] == inv24(PHI_D[k]) for k in range(3))
      and all(PHI_B[k] == PHI_D[inv3(k)] for k in range(3)))

# admissible Phi over ALL frozen conventions: carrier in {Dirac, B} x generator
# choice (alpha_k -> alpha_{-k}); orientation of nu does not move A or e_KO|_A.
admissible = set()
for c in ("Dirac", "B"):
    for gen_swap in (False, True):
        rho = {k: RHO[c][inv3(k)] if gen_swap else RHO[c][k] for k in range(3)}
        ok, phi = is_identification(rho)
        if ok:
            admissible.add(tuple(phi[k] for k in range(3)))
check("E", "total ambiguity = exactly Aut(Z/3) = Z/2: admissible set = {Phi_D, Phi_B}, "
           "closed under inversion, size 2",
      admissible == {(0, 8, 16), (0, 16, 8)})

check("E", "3-primary purity both sides: every element of A has zero Z/8 component (CRT)",
      all(a % 8 == 0 for a in A))

# mechanism audit: the two nonzero-ness mechanisms are DISTINCT (stated, not hidden)
mono_mult = {c: (-IND[c]) % 3 for c in IND}   # rho multiplier = -ind mod 3
check("E", "monodromy nonzero-ness = carrier-selected: (-ind mod 3) = 1 (Dirac), 2 (B), 0 (A)",
      mono_mult == {"Dirac": 1, "B": 2, "A": 0})
check("E", "arena nonzero-ness = ledger-forced: 3 never divides 64m across the whole "
           "frozen carrier ledger (C-04)",
      all((64 * m) % 3 != 0 for m in LEDGER_M))

# ------------------------------------------------------------------ [F] controls
# F1: PLANTED MISMATCH (the demanded control). A deliberately mismatched character
# pairing: rho_fake = (0, 1/3, 1/3) -- values inside the right subgroup of Q/Z
# (so image-membership alone would wave it through) but NOT injective and NOT a
# homomorphism. The gate must REJECT it: power is image-equality is NOT the test.
rho_fake = {0: Fr(0), 1: Fr(1, 3), 2: Fr(1, 3)}
ok_fake, _ = is_identification(rho_fake)
check("F", "PLANTED MISMATCH (0,1/3,1/3) correctly REJECTED (values in the right "
           "subgroup, but no injective intertwiner exists): demonstrated power",
      not ok_fake and not is_hom(rho_fake) and not is_inj(rho_fake))

# F2: carrier A (ghost-subtracted RS, the 2-primary carrier) must FAIL: the
# comparison distinguishes carriers over IDENTICAL K3 geometry -- the rho classes
# are a property of the carrier K-class, NOT an artifact of the K3 benchmark
# (this is the tree's named kill mechanism, refuted by exact arithmetic).
ok_A, _ = is_identification(RHO["A"])
check("F", "carrier A (rho = 0) correctly REJECTED: same K3, different carrier, no "
           "identification -- rho is carrier-sensitive, not a benchmark artifact",
      not ok_A)

# F3: the TOPOLOGICAL invariant of the SAME monodromy (Lefschetz L = 6 == 0 mod 3)
# yields the trivial character map and must FAIL: the fine SPECTRAL level is
# load-bearing (families-e-invariant doc, computed there; recomputed here).
rho_lef = {k: m1(Fr(k * LEFSCHETZ, 3)) for k in range(3)}
ok_lef, _ = is_identification(rho_lef)
check("F", "Lefschetz control correctly REJECTED: L = 6 == 0 mod 3 gives the trivial "
           "map -- only the fine spectral rho carries the identification",
      not ok_lef and all(v == 0 for v in rho_lef.values()))

# F4: a Z/9 imposter (values k/9) must FAIL: no preimage in Z/24 at all -- the
# gate is order-sensitive (unlike the sylow-reading's indiscriminateness, G5).
rho_z9 = {0: Fr(0), 1: Fr(1, 9), 2: Fr(2, 9)}
check("F", "Z/9 imposter correctly REJECTED: 1/9 has NO e_KO preimage in Z/24 "
           "(a/24 = 1/9 has no integer solution) -- gate is order-sensitive",
      build_phi(rho_z9) is None)

# F5: type guard (tree obligation 1). Hom(Z/3, Z) = 0 re-verified exactly: no
# homomorphic passage from either Z/3 to a Z-valued count exists; this probe's
# positive result is a structural identification ONLY.
hom_z3_z = [h for h in range(-1000, 1001) if (3 * h) == 0]
check("F", "type guard: Hom(Z/3, Z) = 0 (only h = 0 satisfies 3h = 0) -- no "
           "generation COUNT is or can be declared from this identification",
      hom_z3_z == [0])

# ------------------------------------------------------------------------ verdict
print()
total = sum(CHECKS.values())
print(f"checks: {CHECKS['T']} [T] + {CHECKS['E']} [E] + {CHECKS['F']} [F] = {total}; "
      f"failed: {len(FAILED)}")
if FAILED:
    print("ABORT -- failed checks:")
    for name in FAILED:
        print("  -", name)
    sys.exit(1)

print()
print("HEADLINE: N4 SURVIVE -- the two frozen Z/3s are canonically identified up to "
      "inversion: Phi = (e_KO|_A)^{-1} o rho is the unique isomorphism from the Nikulin "
      "monodromy character group onto <J(k)> = {0,8,16} (Dirac: alpha_1 -> 8nu; carrier "
      "B: alpha_1 -> 16nu; the two differ by exactly Aut(Z/3) = Z/2, matching the "
      "independently-unpinned 8-vs-16 residue); rho is an exact injective homomorphism "
      "(not generic), the frozen Z/24 arena columns (0,16,8)/(0,8,16) land on the "
      "3-Sylow on the nose, and the planted mismatch / carrier-A / Lefschetz / Z/9 "
      "controls are all correctly REJECTED. STRUCTURAL IDENTIFICATION ONLY -- "
      "NO generation count declared (Hom(Z/3,Z) = 0 re-verified).")
sys.exit(0)
