#!/usr/bin/env python3
r"""RB5: conditional spectral/polar flag ownership and quotient Hessian gate.

This probe asks a deliberately narrow construction question:

    If a source action supplies a gapped G-self-adjoint endomorphism H and an
    invertible G-skew endomorphism Q, can the observer/Cartan flag and a
    compatible complex structure be recovered equivariantly, rather than
    supplied as separate continuous data?

Two finite candidates are predeclared below:

* ``H_SEED`` is G-self-adjoint with a real gap about zero.  Its negative
  spectral projector is the rank-four negative plane.
* ``Q_SEED`` is invertible and G-skew.  Its polar normalization

      J = Q (-Q^2)^(-1/2)

  is an orthogonal compatible complex structure.

They are source-*shaped planted fixtures*, not objects derived from GU and not
claims about the current GU source action.  The point of the probe is to make
the ownership route and its failure gates exact before asking an action to
produce H and Q.

The probe checks:

* the seed-stabilizer obstruction to descending an unframed
  ``Spin(9,5)`` Clifford-plane orbit to a ``4+10`` split or any finer flag;
* native trace-reversed DeWitt typing and the raw-Frobenius hostile control;
* spectral-sign recovery of P and polar recovery of J;
* exact joint O(6,4) covariance and frozen-flag failure;
* analytic versus central-finite-difference derivatives for both recovery
  maps;
* the extra central U(1) direction generated by J and a one-condition
  unimodularity gate;
* rejection at spectral gap closure, singular Q, and raw (7,3);
* a quotient-Hessian classifier that distinguishes gauge zero directions,
  positive physical directions, a physical quartic modulus, and a physical
  unstable direction.

NONCLAIMS: neither planted candidate is GU-native or source-owned.  This file
does not construct epsilon_IG as a spacetime field, a GU source term producing
H or Q, a retained mode, a compact/Standard-Model selector, a VEV, a mass,
stationarity of the GU action, an index/count result, or a cosmological
prediction.  The small Hessian fixtures are classifier controls only.
"""

from __future__ import annotations

import contextlib
import io
import os
import sys

import numpy as np


HERE = os.path.dirname(os.path.abspath(__file__))
TESTS_ROOT = os.path.abspath(os.path.join(HERE, ".."))
if TESTS_ROOT not in sys.path:
    sys.path.insert(0, TESTS_ROOT)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

with contextlib.redirect_stdout(io.StringIO()):
    import rb4_observer_cartan_moving_family_probe as rb4  # noqa: E402


TOL = 4.0e-8
DERIVATIVE_TOL = 2.0e-7
FAILURES: list[str] = []


class GapClosedError(ValueError):
    """The sign projector is undefined because zero meets the spectrum."""


class SingularPolarError(ValueError):
    """The polar complex structure is undefined at singular/invalid Q."""


class SignatureParityError(ValueError):
    """A real orthogonal complex structure is obstructed by metric parity."""


def check(label: str, condition: bool, detail: str = "") -> None:
    status = "PASS" if condition else "FAIL"
    suffix = f" ({detail})" if detail else ""
    print(f"{status}: {label}{suffix}")
    if not condition:
        FAILURES.append(label)


def info(message: str) -> None:
    print(f"INFO: {message}")


def max_abs(matrix: np.ndarray) -> float:
    return float(np.max(np.abs(matrix))) if matrix.size else 0.0


def signature(matrix: np.ndarray) -> tuple[int, int, int]:
    hermitian = 0.5 * (matrix + matrix.conj().T)
    values = np.linalg.eigvalsh(hermitian)
    scale = max(1.0, float(np.max(np.abs(values))))
    threshold = TOL * scale
    return (
        int(np.sum(values > threshold)),
        int(np.sum(values < -threshold)),
        int(np.sum(np.abs(values) <= threshold)),
    )


def g_adjoint(matrix: np.ndarray, metric: np.ndarray) -> np.ndarray:
    return np.linalg.solve(metric, matrix.T @ metric)


def real_eigendecomposition(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    values, vectors = np.linalg.eig(matrix)
    if max_abs(values.imag) > TOL or max_abs(vectors.imag) > 2.0e-6:
        raise ValueError("fixture left the real diagonalizable branch")
    return values.real, vectors.real


def spectral_sign_and_projector(
    matrix: np.ndarray,
    gap_tolerance: float = 1.0e-7,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    values, vectors = real_eigendecomposition(matrix)
    if float(np.min(np.abs(values))) <= gap_tolerance:
        raise GapClosedError("zero lies in the spectral gap")
    inverse = np.linalg.inv(vectors)
    sign_matrix = (
        vectors @ np.diag(np.sign(values)) @ inverse
    )
    projector = 0.5 * (np.eye(matrix.shape[0]) - sign_matrix)
    return sign_matrix, projector, values


def primary_inverse_square_root(matrix: np.ndarray) -> np.ndarray:
    values, vectors = real_eigendecomposition(matrix)
    if float(np.min(values)) <= 1.0e-7:
        raise SingularPolarError("-Q^2 lost its positive real spectrum")
    inverse = np.linalg.inv(vectors)
    return vectors @ np.diag(values ** -0.5) @ inverse


def metric_inertia_even(metric: np.ndarray) -> bool:
    positive, negative, zero = signature(metric)
    return zero == 0 and positive % 2 == 0 and negative % 2 == 0


def polar_complex(
    q_field: np.ndarray,
    metric: np.ndarray,
) -> np.ndarray:
    if not metric_inertia_even(metric):
        raise SignatureParityError(
            "orthogonal real J requires even positive and negative inertia"
        )
    if abs(float(np.linalg.det(q_field))) <= 1.0e-10:
        raise SingularPolarError("Q is singular")
    inverse_root = primary_inverse_square_root(-q_field @ q_field)
    return q_field @ inverse_root


def projector_range_basis(projector: np.ndarray) -> np.ndarray:
    _left, singular_values, right_t = np.linalg.svd(projector)
    rank = int(np.sum(singular_values > TOL))
    raw_basis = right_t[:rank].T
    image = projector @ raw_basis
    basis, _upper = np.linalg.qr(image)
    return basis[:, :rank]


def divided_difference(
    values: np.ndarray,
    scalar_function,
    scalar_derivative,
) -> np.ndarray:
    out = np.zeros((len(values), len(values)))
    for left in range(len(values)):
        for right in range(len(values)):
            if abs(float(values[left] - values[right])) < 1.0e-10:
                out[left, right] = scalar_derivative(values[left])
            else:
                out[left, right] = (
                    scalar_function(values[left])
                    - scalar_function(values[right])
                ) / (values[left] - values[right])
    return out


def quotient_hessian_class(
    hessian: np.ndarray,
    gauge_basis: np.ndarray,
) -> tuple[str, np.ndarray, float]:
    gauge_null_defect = max_abs(hessian @ gauge_basis)
    full_basis, _upper = np.linalg.qr(
        np.column_stack([gauge_basis, np.eye(hessian.shape[0])])
    )
    physical_basis = full_basis[:, gauge_basis.shape[1] :]
    physical_hessian = physical_basis.T @ hessian @ physical_basis
    values = np.linalg.eigvalsh(
        0.5 * (physical_hessian + physical_hessian.T)
    )
    if np.min(values) < -TOL:
        verdict = "UNSTABLE"
    elif np.any(np.abs(values) <= TOL):
        verdict = "MODULUS"
    else:
        verdict = "STRICTLY_POSITIVE"
    return verdict, values, gauge_null_defect


def controlled_action(
    point: np.ndarray,
    hessian: np.ndarray,
    modulus_direction: np.ndarray,
    quartic_coefficient: float,
) -> float:
    modulus_coordinate = float(modulus_direction @ point)
    return float(
        0.5 * point @ hessian @ point
        + 0.25 * quartic_coefficient * modulus_coordinate**4
    )


# =============================================================================
# The actual RB3 epsilon-plane orbit is tested before the planted H/Q calculus.
# =============================================================================

G14 = np.diag(
    [1.0, 1.0, 1.0, -1.0]
    + [1.0] * 6
    + [-1.0] * 4
)
IDENTITY14 = np.eye(14)
VERTICAL_PROJECTOR14 = np.diag([0.0] * 4 + [1.0] * 10)


def so_metric_generators(metric: np.ndarray) -> list[np.ndarray]:
    """Coordinate basis for X^T metric + metric X = 0."""
    signs = np.diag(metric)
    generators: list[np.ndarray] = []
    for left in range(metric.shape[0]):
        for right in range(left + 1, metric.shape[0]):
            generator = np.zeros_like(metric)
            generator[left, right] = 1.0
            generator[right, left] = -signs[left] / signs[right]
            generators.append(generator)
    return generators


SO95_GENERATORS = so_metric_generators(G14)


print("=" * 96)
print("A. RB3 UNFRAMED CLIFFORD-PLANE STABILIZER DESCENT")
print("=" * 96)

check(
    "the 14-vector metric is the required base (3,1) plus vertical (6,4) signature",
    signature(G14) == (9, 5, 0)
    and signature(G14[:4, :4]) == (3, 1, 0)
    and signature(G14[4:, 4:]) == (6, 4, 0),
)
check(
    "the explicit stabilizer basis spans so(9,5)",
    len(SO95_GENERATORS) == 91
    and all(
        max_abs(generator.T @ G14 + G14 @ generator) < TOL
        for generator in SO95_GENERATORS
    ),
)

split_preserving_generators = [
    generator
    for generator in SO95_GENERATORS
    if max_abs(
        generator @ VERTICAL_PROJECTOR14
        - VERTICAL_PROJECTOR14 @ generator
    )
    < TOL
]
split_moving_generators = [
    generator
    for generator in SO95_GENERATORS
    if max_abs(
        generator @ VERTICAL_PROJECTOR14
        - VERTICAL_PROJECTOR14 @ generator
    )
    >= TOL
]
check(
    "only the 51-dimensional so(3,1)+so(6,4) subalgebra preserves the prerequisite 4+10 split",
    len(split_preserving_generators) == 51
    and len(split_moving_generators) == 40,
    f"preserving={len(split_preserving_generators)}, moving={len(split_moving_generators)}",
)

# Identity and exp(alpha X) represent the same seed point of G/H_Cl because
# exp(alpha X) lies in H_Cl=Spin(9,5), but they transport a supplied split
# differently.  Hence a lift-dependent construction does not descend.
lift_change_generator = split_moving_generators[0]
lift_change = rb4.matrix_exponential_series(0.29 * lift_change_generator)
moved_vertical_projector14 = (
    lift_change
    @ VERTICAL_PROJECTOR14
    @ np.linalg.inv(lift_change)
)
lift_ambiguity_residual = float(
    np.linalg.norm(moved_vertical_projector14 - VERTICAL_PROJECTOR14)
)
check(
    "an H_Cl lift change preserves the Clifford plane but moves the supplied 4+10 split",
    max_abs(lift_change.T @ G14 @ lift_change - G14) < TOL
    and lift_ambiguity_residual > 0.1,
    f"split residual {lift_ambiguity_residual:.9f}",
)

# The commutant of the full standard so(9,5) action is scalar.  Therefore it
# contains no nontrivial invariant projector of rank 4 or 10.
commutator_system = np.vstack(
    [
        np.kron(IDENTITY14, generator)
        - np.kron(generator.T, IDENTITY14)
        for generator in SO95_GENERATORS
    ]
)
commutant_singular_values = np.linalg.svd(
    commutator_system,
    compute_uv=False,
)
commutant_nullity = int(
    np.sum(commutant_singular_values < TOL)
    + (commutator_system.shape[1] - len(commutant_singular_values))
)
check(
    "the full so(9,5) vector action has only the scalar commutant, so no nontrivial invariant split descends",
    commutant_nullity == 1,
    f"commutant nullity {commutant_nullity}",
)
check(
    "the homogeneous-space direction is refinement-to-plane, not plane-to-flag",
    64 * (2 * 64 + 1) == 8256
    and len(SO95_GENERATORS) == 91
    and 8256 - 91 == 8165
    and len(split_moving_generators) == 40,
)
info(
    "RB3 epsilon_plane has the finite-local G/Spin(9,5) orbit type; global "
    "associated reduction remains conditional.  Its stabilizer moves even "
    "the prerequisite 4+10 split, so it cannot own P_W, J, t, or a complex "
    "volume.  A refined flag field can forget to epsilon_plane; epsilon_plane "
    "cannot canonically recover the refinement."
)


# =============================================================================
# Predeclared planted candidate data.  These are inputs, not fitted outputs.
# =============================================================================

G_NATIVE = rb4.ETA10
G_RAW = rb4.raw_gram
IDENTITY10 = np.eye(10)

H_SPECTRUM = np.array(
    [1.3, 1.6, 2.1, 2.8, 3.4, 4.2, -1.1, -1.7, -2.3, -3.1]
)
H_SEED = np.diag(H_SPECTRUM)

Q_FREQUENCIES = np.array([1.2, 1.7, 2.1, 0.9, 1.4])
Q_SEED = np.zeros((10, 10))
J_SEED_EXPECTED = np.zeros((10, 10))
for pair_index, frequency in enumerate(Q_FREQUENCIES):
    first = 2 * pair_index
    second = first + 1
    J_SEED_EXPECTED[first, second] = -1.0
    J_SEED_EXPECTED[second, first] = 1.0
    Q_SEED[first, second] = -frequency
    Q_SEED[second, first] = frequency

O_JOINT = rb4.sym2_boost
O_JOINT_INVERSE = np.linalg.inv(O_JOINT)


print("\n" + "=" * 96)
print("B. PREDECLARED SOURCE-SHAPED H/Q FIXTURES AND NATIVE TYPING")
print("=" * 96)

check(
    "RB4 native DeWitt fixture is (6,4), while raw Frobenius is (7,3)",
    signature(G_NATIVE) == (6, 4, 0)
    and signature(G_RAW) == (7, 3, 0),
    f"native={signature(G_NATIVE)}, raw={signature(G_RAW)}",
)
check(
    "planted H is G-self-adjoint and predeclared with a nonzero real gap",
    max_abs(g_adjoint(H_SEED, G_NATIVE) - H_SEED) < TOL
    and float(np.min(np.abs(H_SPECTRUM))) > 1.0,
    f"gap {float(np.min(np.abs(H_SPECTRUM))):.3f}",
)
check(
    "planted Q is invertible and G-skew",
    abs(float(np.linalg.det(Q_SEED))) > 1.0e-6
    and max_abs(g_adjoint(Q_SEED, G_NATIVE) + Q_SEED) < TOL,
)
info(
    "H_SEED and Q_SEED are conditional source-shaped plants.  Passing below "
    "does not put either field in the GU action."
)


print("\n" + "=" * 96)
print("C. SPECTRAL-SIGN RECOVERY OF THE NEGATIVE FLAG")
print("=" * 96)

sign_h0, projector0, h_values = spectral_sign_and_projector(H_SEED)
projector_basis0 = projector_range_basis(projector0)
projector_gram0 = projector_basis0.T @ G_NATIVE @ projector_basis0
check(
    "spectral sign is an involution and P=(1-sign H)/2 is an exact projector",
    max_abs(sign_h0 @ sign_h0 - IDENTITY10) < TOL
    and max_abs(projector0 @ projector0 - projector0) < TOL
    and max_abs(projector0 - 0.5 * (IDENTITY10 - sign_h0)) < TOL,
)
check(
    "the gapped negative spectral flag has rank four and negative-definite restriction",
    np.linalg.matrix_rank(projector0, tol=TOL) == 4
    and signature(projector_gram0) == (0, 4, 0),
    f"restriction {signature(projector_gram0)}",
)
check(
    "the complementary spectral flag has positive rank six",
    np.linalg.matrix_rank(IDENTITY10 - projector0, tol=TOL) == 6
    and signature(
        projector_range_basis(IDENTITY10 - projector0).T
        @ G_NATIVE
        @ projector_range_basis(IDENTITY10 - projector0)
    )
    == (6, 0, 0),
)

H_JOINT = O_JOINT @ H_SEED @ O_JOINT_INVERSE
sign_h1, projector1, _h_values1 = spectral_sign_and_projector(H_JOINT)
check(
    "joint O(6,4) conjugation preserves G-self-adjointness and transports the spectral flag",
    max_abs(O_JOINT.T @ G_NATIVE @ O_JOINT - G_NATIVE) < TOL
    and max_abs(g_adjoint(H_JOINT, G_NATIVE) - H_JOINT) < TOL
    and max_abs(sign_h1 - O_JOINT @ sign_h0 @ O_JOINT_INVERSE) < TOL
    and max_abs(projector1 - O_JOINT @ projector0 @ O_JOINT_INVERSE) < TOL,
)
frozen_flag_residual = float(np.linalg.norm(projector1 - projector0))
check(
    "planted frozen spectral flag fails under the same non-stabilizer transport",
    frozen_flag_residual > 1.0,
    f"residual {frozen_flag_residual:.9f}",
)


print("\n" + "=" * 96)
print("D. SPECTRAL-PROJECTOR FIRST DERIVATIVE")
print("=" * 96)

spectral_raw_variation = (
    np.sin(0.37 * np.arange(1, 101).reshape(10, 10))
    + np.cos(0.13 * np.arange(1, 101).reshape(10, 10))
)
delta_h = 0.5 * (
    spectral_raw_variation
    + G_NATIVE @ spectral_raw_variation.T @ G_NATIVE
)
delta_h /= np.linalg.norm(delta_h)
spectral_divided_difference = np.zeros((10, 10))
for left in range(10):
    for right in range(10):
        if left == right:
            continue
        indicator_left = float(H_SPECTRUM[left] < 0.0)
        indicator_right = float(H_SPECTRUM[right] < 0.0)
        spectral_divided_difference[left, right] = (
            indicator_left - indicator_right
        ) / (H_SPECTRUM[left] - H_SPECTRUM[right])
analytic_delta_projector = spectral_divided_difference * delta_h
finite_step = 1.0e-5
_sign_plus, projector_plus, _values_plus = spectral_sign_and_projector(
    H_SEED + finite_step * delta_h
)
_sign_minus, projector_minus, _values_minus = spectral_sign_and_projector(
    H_SEED - finite_step * delta_h
)
finite_delta_projector = (
    projector_plus - projector_minus
) / (2.0 * finite_step)
spectral_derivative_error = max_abs(
    finite_delta_projector - analytic_delta_projector
)
check(
    "the planted H variation remains G-self-adjoint",
    max_abs(g_adjoint(delta_h, G_NATIVE) - delta_h) < TOL,
)
check(
    "central finite difference matches the analytic spectral-projector derivative",
    spectral_derivative_error < DERIVATIVE_TOL
    and np.linalg.norm(analytic_delta_projector) > 0.1,
    f"max error {spectral_derivative_error:.3e}",
)


print("\n" + "=" * 96)
print("E. POLAR RECOVERY OF J AND ITS FIRST DERIVATIVE")
print("=" * 96)

J0 = polar_complex(Q_SEED, G_NATIVE)
check(
    "polar normalization recovers the predeclared compatible J",
    max_abs(J0 - J_SEED_EXPECTED) < TOL,
)
check(
    "recovered J squares to -1 and is G-orthogonal",
    max_abs(J0 @ J0 + IDENTITY10) < TOL
    and max_abs(J0.T @ G_NATIVE @ J0 - G_NATIVE) < TOL,
)
check(
    "the two planted recovery routes are compatible because recovered J preserves recovered P",
    max_abs(J0 @ projector0 - projector0 @ J0) < TOL,
)

Q_JOINT = O_JOINT @ Q_SEED @ O_JOINT_INVERSE
J1 = polar_complex(Q_JOINT, G_NATIVE)
check(
    "joint O(6,4) conjugation preserves G-skewness and transports polar J",
    max_abs(g_adjoint(Q_JOINT, G_NATIVE) + Q_JOINT) < TOL
    and max_abs(J1 - O_JOINT @ J0 @ O_JOINT_INVERSE) < TOL,
)
check(
    "joint transport preserves compatibility of the recovered P/J flag",
    max_abs(J1 @ projector1 - projector1 @ J1) < TOL,
)
frozen_j_residual = float(np.linalg.norm(J1 - J0))
check(
    "planted frozen J fails under the non-stabilizer transport",
    frozen_j_residual > 1.0,
    f"residual {frozen_j_residual:.9f}",
)

polar_raw_variation = (
    np.sin(0.23 * np.arange(1, 101).reshape(10, 10))
    + np.cos(0.17 * np.arange(1, 101).reshape(10, 10))
)
delta_q = 0.5 * (
    polar_raw_variation
    - G_NATIVE @ polar_raw_variation.T @ G_NATIVE
)
delta_q /= np.linalg.norm(delta_q)
a0 = -Q_SEED @ Q_SEED
delta_a = -(delta_q @ Q_SEED + Q_SEED @ delta_q)
a0_values = np.diag(a0)
inverse_root0 = primary_inverse_square_root(a0)
inverse_root_divided_difference = divided_difference(
    a0_values,
    lambda value: value ** -0.5,
    lambda value: -0.5 * value ** -1.5,
)
delta_inverse_root = inverse_root_divided_difference * delta_a
analytic_delta_j = (
    delta_q @ inverse_root0 + Q_SEED @ delta_inverse_root
)
J_plus = polar_complex(Q_SEED + finite_step * delta_q, G_NATIVE)
J_minus = polar_complex(Q_SEED - finite_step * delta_q, G_NATIVE)
finite_delta_j = (J_plus - J_minus) / (2.0 * finite_step)
polar_derivative_error = max_abs(finite_delta_j - analytic_delta_j)
check(
    "the planted Q variation remains G-skew and excites a nonzero polar variation",
    max_abs(g_adjoint(delta_q, G_NATIVE) + delta_q) < TOL
    and np.linalg.norm(analytic_delta_j) > 0.1,
)
check(
    "central finite difference matches the analytic polar derivative",
    polar_derivative_error < DERIVATIVE_TOL,
    f"max error {polar_derivative_error:.3e}",
)


print("\n" + "=" * 96)
print("F. CENTRAL U(1) AND UNIMODULARITY GATE")
print("=" * 96)


def complex_linear_generator(coefficients: list[float]) -> np.ndarray:
    generator = np.zeros((10, 10))
    for pair_index, coefficient in enumerate(coefficients):
        first = 2 * pair_index
        second = first + 1
        generator[first, second] = -coefficient
        generator[second, first] = coefficient
    return generator


def central_coefficient(generator: np.ndarray, complex_structure: np.ndarray) -> float:
    dimension = generator.shape[0]
    return -float(np.trace(complex_structure @ generator)) / dimension


def remove_central_u1(
    generator: np.ndarray,
    complex_structure: np.ndarray,
) -> np.ndarray:
    return (
        generator
        - central_coefficient(generator, complex_structure) * complex_structure
    )


central_generator = J0.copy()
unimodular_generator = complex_linear_generator([2.0, -1.0, -1.0, 0.0, 0.0])
mixed_generator = unimodular_generator + 0.3 * central_generator
mixed_unimodular = remove_central_u1(mixed_generator, J0)
check(
    "J generates a G-skew complex-linear central U(1) direction",
    max_abs(g_adjoint(central_generator, G_NATIVE) + central_generator) < TOL
    and max_abs(central_generator @ J0 - J0 @ central_generator) < TOL
    and abs(central_coefficient(central_generator, J0) - 1.0) < TOL,
)
check(
    "the unimodularity trace gate rejects the central J direction and accepts a balanced generator",
    abs(float(np.trace(J0 @ central_generator))) > 1.0
    and abs(float(np.trace(J0 @ unimodular_generator))) < TOL
    and max_abs(g_adjoint(unimodular_generator, G_NATIVE) + unimodular_generator)
    < TOL
    and max_abs(unimodular_generator @ J0 - J0 @ unimodular_generator) < TOL,
)
check(
    "one explicit central subtraction enforces the finite unimodularity gate",
    abs(central_coefficient(mixed_generator, J0) - 0.3) < TOL
    and max_abs(mixed_unimodular - unimodular_generator) < TOL
    and abs(float(np.trace(J0 @ mixed_unimodular))) < TOL,
)
info(
    "A compatible J carries a central complex-linear direction.  This finite "
    "one-condition trace gate removes it; no GU-native unimodularity rule is "
    "claimed here."
)


print("\n" + "=" * 96)
print("G. KILL CONTROLS: GAP, SINGULAR POLAR FIELD, FROZEN FLAG, RAW SIGNATURE")
print("=" * 96)

gapless_h = H_SEED.copy()
gapless_h[6, 6] = 0.0
gap_control_fired = False
try:
    spectral_sign_and_projector(gapless_h)
except GapClosedError:
    gap_control_fired = True
check(
    "spectral ownership is rejected when the H gap closes",
    gap_control_fired,
)

singular_q = Q_SEED.copy()
singular_q[8:10, 8:10] = 0.0
singular_control_fired = False
try:
    polar_complex(singular_q, G_NATIVE)
except SingularPolarError:
    singular_control_fired = True
check(
    "polar ownership is rejected when Q becomes singular",
    singular_control_fired,
)

raw_range_gram = projector_basis0.T @ G_RAW @ projector_basis0
raw_parity_control_fired = False
try:
    polar_complex(Q_SEED, G_RAW)
except SignatureParityError:
    raw_parity_control_fired = True
check(
    "raw Frobenius makes the same rank-four flag indefinite rather than negative",
    signature(raw_range_gram) == (1, 3, 0),
    f"restriction {signature(raw_range_gram)}",
)
check(
    "raw (7,3) also fires the orthogonal-complex signature-parity gate",
    raw_parity_control_fired,
)
check(
    "frozen P and frozen J hostile controls both fired",
    frozen_flag_residual > 1.0 and frozen_j_residual > 1.0,
)


print("\n" + "=" * 96)
print("H. QUOTIENT-HESSIAN DISCRIMINATOR WITH GAUGE/MODULUS/INSTABILITY PLANTS")
print("=" * 96)

fixture_dimension = 7
fixture_seed = (
    np.sin(0.31 * np.arange(1, fixture_dimension**2 + 1))
    + np.cos(0.19 * np.arange(1, fixture_dimension**2 + 1))
).reshape(fixture_dimension, fixture_dimension)
fixture_frame, _fixture_upper = np.linalg.qr(fixture_seed)
gauge_basis = fixture_frame[:, :2]
physical_basis = fixture_frame[:, 2:]
modulus_direction = physical_basis[:, 0]


def planted_hessian(physical_values: list[float]) -> np.ndarray:
    return physical_basis @ np.diag(physical_values) @ physical_basis.T


stable_hessian = planted_hessian([0.8, 1.4, 2.1, 2.9, 3.8])
modulus_hessian = planted_hessian([0.0, 1.4, 2.1, 2.9, 3.8])
unstable_hessian = planted_hessian([-0.6, 1.4, 2.1, 2.9, 3.8])
stable_verdict, stable_values, stable_gauge_defect = quotient_hessian_class(
    stable_hessian,
    gauge_basis,
)
modulus_verdict, modulus_values, modulus_gauge_defect = quotient_hessian_class(
    modulus_hessian,
    gauge_basis,
)
unstable_verdict, unstable_values, unstable_gauge_defect = quotient_hessian_class(
    unstable_hessian,
    gauge_basis,
)
check(
    "all action Hessian fixtures have the two explicit gauge null directions",
    max(stable_gauge_defect, modulus_gauge_defect, unstable_gauge_defect) < TOL,
)
check(
    "quotienting gauge zeros recovers a strictly positive physical Hessian",
    stable_verdict == "STRICTLY_POSITIVE"
    and np.min(stable_values) > 0.7
    and signature(stable_hessian) == (5, 0, 2),
    f"quotient eigenvalues {np.round(stable_values, 6).tolist()}",
)
check(
    "the planted physical modulus survives the gauge quotient",
    modulus_verdict == "MODULUS"
    and abs(float(np.min(np.abs(modulus_values)))) < TOL
    and signature(modulus_hessian) == (4, 0, 3),
    f"quotient eigenvalues {np.round(modulus_values, 6).tolist()}",
)
check(
    "the planted unstable physical direction survives the gauge quotient",
    unstable_verdict == "UNSTABLE"
    and float(np.min(unstable_values)) < -0.5
    and signature(unstable_hessian) == (4, 1, 2),
    f"quotient eigenvalues {np.round(unstable_values, 6).tolist()}",
)

quartic_coefficient = 2.0
modulus_sample = 0.2 * modulus_direction
unstable_sample = 0.1 * modulus_direction
check(
    "the zero-Hessian modulus has a positive planted quartic action",
    controlled_action(
        modulus_sample,
        modulus_hessian,
        modulus_direction,
        quartic_coefficient,
    )
    > 0.0,
)
check(
    "the planted negative Hessian wins locally over the same stabilizing quartic",
    controlled_action(
        unstable_sample,
        unstable_hessian,
        modulus_direction,
        quartic_coefficient,
    )
    < 0.0,
)

test_point = np.linspace(-0.4, 0.5, fixture_dimension)
gauge_shift = gauge_basis @ np.array([0.27, -0.19])
check(
    "the planted action is exactly invariant along the explicit gauge orbit",
    abs(
        controlled_action(
            test_point + gauge_shift,
            modulus_hessian,
            modulus_direction,
            quartic_coefficient,
        )
        - controlled_action(
            test_point,
            modulus_hessian,
            modulus_direction,
            quartic_coefficient,
        )
    )
    < TOL,
)
info(
    "Full-Hessian zero modes cannot distinguish gauge from moduli.  The "
    "quotient classifier does: gauge zeros are removed, while the planted "
    "physical modulus and instability remain."
)


print("\n" + "=" * 96)
if FAILURES:
    print(f"FAIL: {len(FAILURES)} RB5 checks failed")
    for failure in FAILURES:
        print(f"  - {failure}")
    raise SystemExit(1)

print("PASS: RB5 conditional spectral/polar ownership and quotient-Hessian gate")
print(
    "In the deliberately target-encoded planted fixture, an admissible "
    "real-spectral gapped G-self-adjoint H recovers the negative rank-four "
    "flag, and an invertible G-skew Q with an admissible positive-real "
    "inverse-square-root branch recovers a compatible J.  This does not "
    "show that generic H/Q inputs have either property.  Both recovery maps "
    "are differentiable and jointly O(6,4)-covariant in the tested branch.  "
    "Gap closure, singular Q, frozen flags, raw Frobenius signature, an "
    "unremoved central U(1), physical moduli, and physical instabilities "
    "remain explicit gates.  The current GU action has not been shown to "
    "supply either planted field."
)
