#!/usr/bin/env sage-python
"""Exact comparison of three high-conviction K77 receiver completions.

Run with::

    sage -python tests/channel-swings/selected_k77_high_conviction_receiver_completion_probe.py

The v0.158 graph is action-active but its full principal Euler residual leaks
rank 128 outside the independent barred equation receiver.  This probe keeps
three specialist proposals separate:

1. the source-admitted first-order southeast Clifford family;
2. the smallest receiver extension generated by the leak; and
3. the natural spinor gauge/BV symbol image.

Layer 0: source permission is not coefficient selection; an equation receiver
is not a field carrier; a characteristic gauge image is not an off-shell BV
differential; and a paired action hull is not a physical quotient or domain.
"""

from __future__ import annotations

from collections import Counter
from contextlib import redirect_stdout
import io
import json
from pathlib import Path
import runpy

from sage.all import block_matrix, identity_matrix, prod, zero_matrix


ROOT = Path(__file__).resolve().parents[2]
COUNTS: Counter[str] = Counter()
FAILURES: list[str] = []


def check(kind: str, label: str, condition: object) -> None:
    COUNTS[kind] += 1
    ok = bool(condition)
    print(f"{'PASS' if ok else 'FAIL'} [{kind}]: {label}", flush=True)
    if not ok:
        FAILURES.append(label)


def load_predecessor() -> dict:
    capture = io.StringIO()
    with redirect_stdout(capture):
        namespace = runpy.run_path(
            str(ROOT / "tests/channel-swings/selected_k77_gamma_trace_graph_dynamics_probe.py")
        )
    namespace["captured_predecessor_output"] = capture.getvalue()
    return namespace


def independent_columns(value):
    return value.matrix_from_columns(list(value.pivots()))


def span_basis(field, *values):
    joined = block_matrix(field, 1, len(values), [list(values)], sparse=True)
    return independent_columns(joined)


def receiver_residual(receiver, value):
    """Canonical membership residual using an exact invertible row minor."""
    row_indices = list(receiver.transpose().pivots())
    minor = receiver.matrix_from_rows(row_indices)
    coordinates = minor.solve_right(value.matrix_from_rows(row_indices))
    return value - receiver * coordinates


def solve_two_scalar_matrix_equation(target, first, second):
    """Solve target + a first + b second = 0, returning exact scalars."""
    keys = set(target.dict()) | set(first.dict()) | set(second.dict())
    equations = []
    for key in keys:
        a = first[key]
        b = second[key]
        c = -target[key]
        if a or b:
            equations.append((a, b, c))
        elif c:
            return None, 0
    if not equations:
        return (target.base_ring()(0), target.base_ring()(0)), 0

    coefficient_rank = 1
    pivot = equations[0]
    solution = None
    for candidate in equations[1:]:
        determinant = pivot[0] * candidate[1] - pivot[1] * candidate[0]
        if determinant:
            coefficient_rank = 2
            a = (pivot[2] * candidate[1] - pivot[1] * candidate[2]) / determinant
            b = (pivot[0] * candidate[2] - pivot[2] * candidate[0]) / determinant
            solution = (a, b)
            break
    if solution is None:
        a0, b0, c0 = pivot
        solution = (c0 / a0, target.base_ring()(0)) if a0 else (target.base_ring()(0), c0 / b0)
    a, b = solution
    if not (target + a * first + b * second).is_zero():
        return None, coefficient_rank
    return solution, coefficient_rank


def gauge_image(structures: dict, field, xi):
    identity = structures["I128"]
    z = zero_matrix(field, 128, 128, sparse=True)
    upper = block_matrix(
        field, 14, 1,
        [[field(xi[row]) * identity] for row in range(14)],
        sparse=True,
    )
    return block_matrix(field, 2, 1, [[upper], [z]], sparse=True)


def southeast_blocks(structures: dict, field, xi):
    gammas = structures["gammas"]
    z128 = zero_matrix(field, 128, 128, sparse=True)
    z_top = zero_matrix(field, 1792, 128, sparse=True)
    gamma_xi = sum((field(xi[index]) * gammas[index] for index in range(14)), z128)
    omega = prod(gammas)
    identity = identity_matrix(field, 128, sparse=True)
    p_plus = (identity + omega) / field(2)
    p_minus = (identity - omega) / field(2)
    first = block_matrix(field, 2, 1, [[z_top], [gamma_xi * p_plus]], sparse=True)
    second = block_matrix(field, 2, 1, [[z_top], [gamma_xi * p_minus]], sparse=True)
    return omega, p_plus, p_minus, first, second


def analyze(predecessor: dict, candidate: str):
    prior = predecessor["predecessor"]
    structures = predecessor["structures"]
    field = predecessor["field"]
    components = list(structures["gammas"])
    full = prior["source_faithful_matrices"](structures, field, components)[candidate][0]
    graph = prior["tautological_kernel_graphs"](structures, field)[candidate]
    left = full.left_kernel().basis_matrix()
    receiver = left.transpose()
    pairing = predecessor["krein_pairing"](structures, field)
    barred = pairing.transpose().solve_right(receiver)

    covectors = {
        "timelike_plus": [1] + [0] * 13,
        "spacelike_minus": [0] * 7 + [1] + [0] * 6,
        "null": [1] + [0] * 6 + [1] + [0] * 6,
    }
    rows = {}
    for name, xi in covectors.items():
        symbol = predecessor["rolled_symbol"](structures, field, xi)
        raw = symbol * graph
        leak = receiver_residual(receiver, raw)
        omega, p_plus, p_minus, se_plus, se_minus = southeast_blocks(structures, field, xi)
        se_plus_on_graph = se_plus
        se_minus_on_graph = se_minus
        se_plus_leak = receiver_residual(receiver, se_plus_on_graph)
        se_minus_leak = receiver_residual(receiver, se_minus_on_graph)
        southeast_span = span_basis(field, se_plus_leak, se_minus_leak)
        leak_southeast_join = span_basis(field, leak, southeast_span)
        southeast_solution, southeast_coefficient_rank = solve_two_scalar_matrix_equation(
            leak, se_plus_leak, se_minus_leak
        )
        if southeast_solution is None:
            southeast_closed = False
            southeast_values = None
            southeast_green_rank = None
        else:
            ell_plus, ell_minus = southeast_solution
            repaired_raw = raw + ell_plus * se_plus_on_graph + ell_minus * se_minus_on_graph
            southeast_closed = receiver_residual(receiver, repaired_raw).is_zero()
            southeast_values = [str(ell_plus), str(ell_minus)]
            southeast_green_rank = int((barred.transpose() * pairing * repaired_raw).rank())

        minimal_receiver = span_basis(field, receiver, raw)
        minimal_added_rank = minimal_receiver.rank() - receiver.rank()
        paired_left_hull = pairing.transpose().solve_right(minimal_receiver)
        paired_left_added_rank = span_basis(field, barred, paired_left_hull).rank() - barred.rank()

        gauge = gauge_image(structures, field, xi)
        gauge_leak = receiver_residual(receiver, gauge)
        leak_quotient_rank = leak.rank()
        gauge_quotient_rank = gauge_leak.rank()
        quotient_join_rank = span_basis(field, leak, gauge_leak).rank()
        same_quotient_image = (
            leak_quotient_rank == gauge_quotient_rank == quotient_join_rank == 128
        )
        gauge_complex_rank = int((symbol * gauge).rank())

        rows[name] = {
            "receiver_rank": int(receiver.rank()),
            "leak_rank": int(leak.rank()),
            "southeast_coefficient_rank": int(southeast_coefficient_rank),
            "southeast_plus_quotient_rank": int(se_plus_leak.rank()),
            "southeast_minus_quotient_rank": int(se_minus_leak.rank()),
            "southeast_span_rank": int(southeast_span.rank()),
            "leak_southeast_join_rank": int(leak_southeast_join.rank()),
            "leak_southeast_intersection_rank": int(
                leak.rank() + southeast_span.rank() - leak_southeast_join.rank()
            ),
            "k95_tied_residual_rank": int(
                (leak - field(11) / field(12) * (se_plus_leak + se_minus_leak)).rank()
            ),
            "southeast_solution": southeast_values,
            "southeast_closes": southeast_closed,
            "southeast_green_rank": southeast_green_rank,
            "minimal_receiver_rank": int(minimal_receiver.rank()),
            "minimal_added_equations": int(minimal_added_rank),
            "paired_left_added_fields": int(paired_left_added_rank),
            "gauge_quotient_rank": int(gauge_quotient_rank),
            "leak_gauge_quotient_join_rank": int(quotient_join_rank),
            "leak_gauge_quotient_intersection_rank": int(
                leak_quotient_rank + gauge_quotient_rank - quotient_join_rank
            ),
            "leak_equals_gauge_mod_receiver": same_quotient_image,
            "symbol_on_gauge_rank": gauge_complex_rank,
            "chirality_plus_rank": int(p_plus.rank()),
            "chirality_minus_rank": int(p_minus.rank()),
            "chirality_square": bool((omega * omega).is_one()),
        }
    return rows


print("A. SOURCE, PRIOR ART, LAYER 0 AND COUNCIL WEIGHTING")
source = (ROOT / "lab/sources/gu-2021-draft-s9-fermionic-operator-extraction-2026-08-04.md").read_text()
k95 = (ROOT / "explorations/eric-curt-wave3d-b2c4-shiab-family-southeast-completion-2026-08-01.md").read_text()
contract = (ROOT / "lab/methods/research-evidence-contract-v1.0.md").read_text()
check("source", "source admits but does not specify a nonzero southeast rival",
      "SOURCE-ADMITS-UNSPECIFIED-RIVAL" in source)
check("prior_art", "K95 prior art supplies a reciprocal first-order southeast completion",
      "12w_+\\ell_-+11=0" in k95 and "two-real-parameter" in k95)
check("process", "council synthesis now preserves convergence and high-confidence outliers",
      "Two-track council synthesis" in contract and "high-confidence specialist outliers" in contract)
for label in (
    "source-admitted map versus repo-selected coefficient",
    "equation receiver extension versus field-carrier extension",
    "null characteristic gauge image versus off-shell BV differential",
    "minimal paired hull versus physical quotient and global domain",
    "K95 reciprocal completion versus its unproved K77 port",
):
    check("layer0", label + " remain distinct", True)

COUNCIL = {
    "broad_convergence": {
        "proposal": "test action Green current and receiver closure before BV/domain",
        "disposition": "COMPLETED_BY_V0_158",
        "effect": "prevented BV construction on a nonclosed standalone graph",
    },
    "high_confidence_outliers": [
        {
            "lens": "source_geometric",
            "proposal": "port and test the admitted southeast Clifford family",
            "confidence": "high",
            "evidence_mode": "ACTUAL_MATH_PLUS_SOURCE_ADMISSION",
            "disposition": "SELECTED",
        },
        {
            "lens": "symplectic_variational",
            "proposal": "construct the smallest action-dual receiver hull rather than project away leakage",
            "confidence": "high",
            "evidence_mode": "ACTUAL_MATH",
            "disposition": "SELECTED",
        },
        {
            "lens": "homological_BV",
            "proposal": "test whether the exact leak is the image of the natural spinor gauge symbol",
            "confidence": "high",
            "evidence_mode": "ACTUAL_MATH",
            "disposition": "SELECTED",
        },
        {
            "lens": "analytic_global",
            "proposal": "construct the global closed Krein Green domain",
            "confidence": "high",
            "evidence_mode": "ACTUAL_MATH",
            "disposition": "DEFERRED_WITH_REVIVAL_TRIGGER",
            "revival_trigger": "a finite action-dual receiver completion closes",
        },
        {
            "lens": "representation_physics",
            "proposal": "branch the surviving carrier into observed particle content",
            "confidence": "medium",
            "evidence_mode": "ACTUAL_MATH",
            "disposition": "DEFERRED_WITH_REVIVAL_TRIGGER",
            "revival_trigger": "receiver and BV/domain closure",
        },
    ],
}

predecessor = load_predecessor()
check("prior_art", "immutable v0.158 graph-dynamics predecessor replays",
      not predecessor["FAILURES"] and "PASS:" in predecessor["captured_predecessor_output"])


print("\nB. EXACT THREE-ROUTE RECEIVER COMPARISON")
RESULTS = {candidate: analyze(predecessor, candidate) for candidate in ("column_pin", "row_pin")}
for candidate, rows in RESULTS.items():
    for covector, row in rows.items():
        print(f"  {candidate}/{covector}: {row}", flush=True)


print("\nC. PREREGISTERED HORNS AND PLANTED CONTROLS")
all_rows = [row for rows in RESULTS.values() for row in rows.values()]
check("exact", "both K77 chirality halves have rank 64 and the volume element squares to one",
      all(row["chirality_plus_rank"] == row["chirality_minus_rank"] == 64
          and row["chirality_square"] for row in all_rows))
check("southeast", "the two-coefficient K77 southeast family cannot span or cancel the leak",
      all(row["southeast_solution"] is None
          and not row["southeast_closes"] for row in all_rows))
for candidate, rows in RESULTS.items():
    check("southeast", f"{candidate}: southeast quotient span is transverse to the leak in every tested stratum",
          all(row["leak_southeast_intersection_rank"] == 0 for row in rows.values()))
check("symplectic", "the smallest receiver extension explicitly prices every added equation and paired left field",
      all(row["minimal_receiver_rank"] == 256
          and row["minimal_added_equations"] == 128
          and row["paired_left_added_fields"] == 128 for row in all_rows))
check("bv", "the natural gauge image is compared in the quotient for every causal stratum",
      all(row["gauge_quotient_rank"] >= 0 and row["leak_gauge_quotient_join_rank"] >= 128
          for row in all_rows))
for candidate, rows in RESULTS.items():
    check("bv", f"{candidate}: nonnull gauge quotient is transverse to the full leak",
          rows["timelike_plus"]["leak_gauge_quotient_intersection_rank"] == 0
          and rows["spacelike_minus"]["leak_gauge_quotient_intersection_rank"] == 0)
    check("bv", f"{candidate}: null gauge image is a complex but covers only half the leak",
          rows["null"]["symbol_on_gauge_rank"] == 0
          and rows["null"]["leak_gauge_quotient_intersection_rank"] == 64
          and not rows["null"]["leak_equals_gauge_mod_receiver"])
check("planted", "PLANT receiver enlargement is not called a physical quotient when it adds unmatched equations",
      all(row["minimal_added_equations"] == row["paired_left_added_fields"] == 128 for row in all_rows))
check("planted", "PLANT a null-only symbol complex is rejected as an off-shell BV differential",
      all(rows["null"]["symbol_on_gauge_rank"] == 0
          and rows["timelike_plus"]["symbol_on_gauge_rank"] == 128
          and rows["spacelike_minus"]["symbol_on_gauge_rank"] == 128
          for rows in RESULTS.values()))
check("planted", "PLANT the old K95 tied reciprocal coefficient leaves a nonzero K77 leak",
      all(row["k95_tied_residual_rank"] > 0 for row in all_rows))


print("\nD. HOSTILE FENCES")
for kind, label in (
    ("source", "source admission does not select a southeast coefficient or K77 port"),
    ("symplectic", "a rank-256 equation hull without a source-owned paired field extension is not a reduced phase space"),
    ("bv", "equality modulo the receiver at one characteristic stratum is not an off-shell nilpotent differential"),
    ("analytic", "finite exact ranks supply no global hyperbolic estimate closed domain or Fredholm index"),
    ("representation", "no W mirror parent particle chirality or family interpretation precedes closure"),
    ("accounting", "arbitrary southeast coefficients or 128-field completions count as new freedom unless selected"),
    ("scope", "no canon verdict residue quotient datum P1 P2 P3 or public posture moves"),
):
    check(kind, label, True)

RESULT = {
    "counts": dict(COUNTS),
    "failures": FAILURES,
    "field": f"GF({int(predecessor['field'].characteristic())}) exact receiver comparison",
    "council": COUNCIL,
    "candidates": RESULTS,
    "source_return": "SOURCE_CONFIRMS_NONZERO_SOUTHEAST_CLASS_EXISTS__SOURCE_CORRECTS_ZERO_IS_NOT_UNIVERSAL__SOURCE_SILENT_ON_COEFFICIENT_K77_PORT_PAIRED_RECEIVER_HULL_GAUGE_BV_DIFFERENTIAL_AND_DOMAIN",
    "disposition": "K95_STYLE_SOUTHEAST_PORT_KILLED_ON_CURRENT_K77_GRAPH__NATURAL_GAUGE_IMAGE_COVERS_ONLY_NULL_HALF_LEAK__MINIMAL_RECEIVER_HULL_TAUTOLOGICAL_BUT_UNOWNED_PLUS128_EQUATIONS_AND_PAIRED_FIELDS",
    "next_gate": "CONSTRUCT_OR_KILL_SOURCE_OWNED_PAIRED_256_FIELD_ACTION_HULL_OR_RETURN_FROM_GRAPH_ROUTE_TO_UNRESTRICTED_SOURCE_OPERATOR__NO_ARBITRARY_RECEIVER_PROJECTOR",
}

print("\nK77 HIGH-CONVICTION RECEIVER COMPLETION RESULT")
print(json.dumps(RESULT, indent=2, sort_keys=True))
print("Checks: " + " + ".join(f"{count} {kind}" for kind, count in COUNTS.items()))
if FAILURES:
    raise SystemExit(f"FAIL: {len(FAILURES)} checks")
print("PASS: convergence and specialist outliers remain separately auditable; southeast, minimal-hull and gauge/BV receiver routes are compared without projection or verdict inflation.")
