#!/usr/bin/env python3
"""Exact associated-family and coarse-observation ownership gate for v0.215.

The probe distinguishes two operations that v0.215 deliberately left open:

* simultaneous Spin/frame transport of ``u``, fields and ``H_u``; and
* changing the geometric observer ``u`` while keeping the fields fixed.

The first is a covariance question.  The second is the vertical-basicness
question relevant to forgetting the observer.  The finite observation
projector is then tested for whether it selects a timelike line inside its
Lorentzian rank-four plane.
"""

from __future__ import annotations

import contextlib
import io
import json
import runpy
from pathlib import Path

import sympy as sp


ROOT = Path(__file__).resolve().parents[2]
with contextlib.redirect_stdout(io.StringIO()):
    PREV = runpy.run_path(
        str(ROOT / "tests/channel-swings/selected_k77_i2b_observer_time_hermitian_reduction_probe.py")
    )

checks: list[dict[str, object]] = []


def check(name: str, passed: bool, *, planted: bool = False, detail: object = None) -> None:
    checks.append({"name": name, "passed": bool(passed), "planted": planted, "detail": detail})


def dense(a: object) -> sp.Matrix:
    return sp.SparseMatrix(a.n, a.n, {(a.perm[j], j): a.sign[j] for j in range(a.n)})


G = PREV["G"]
ETA = PREV["ETA"]
B = PREV["B"]
N = 128
EYE = sp.eye(N)
gammas = [dense(gamma) for gamma in G]
eta14 = sp.diag(*ETA)

# Exact rational vector boost and normalized Spin lift.
boost_generator = gammas[7] * gammas[0]
spin = (2 * EYE + boost_generator) / sp.sqrt(3)
spin_inverse = (2 * EYE - boost_generator) / sp.sqrt(3)
spin_raw = 2 * EYE + boost_generator

lorentz = sp.eye(14)
lorentz[0, 0] = sp.Rational(5, 3)
lorentz[0, 7] = sp.Rational(4, 3)
lorentz[7, 0] = sp.Rational(4, 3)
lorentz[7, 7] = sp.Rational(5, 3)

q = gammas[0]
q_moved = sp.Rational(5, 3) * gammas[0] + sp.Rational(4, 3) * gammas[7]
h = sp.I * B * q
h_moved = sp.I * B * q_moved
h_moved_inverse = sp.simplify(spin * h * spin.T)

check("spin_inverse", sp.simplify(spin * spin_inverse) == EYE)
check("lorentz_metric", sp.simplify(lorentz.T * eta14 * lorentz) == eta14)
check("lorentz_proper", sp.det(lorentz) == 1)
check("lorentz_orthochronous", lorentz[0, 0] > 0)
check("spin_preserves_bilinear", sp.simplify(spin.T * B * spin) == B)
check("spin_moves_q", sp.simplify(spin * q * spin_inverse) == q_moved)
check("moving_hermitian_law", sp.simplify(spin_inverse.T * h * spin_inverse) == h_moved)
check("equivalent_hermitian_law", sp.simplify(spin.T * h_moved * spin) == h)
check("moving_hermitian_form_is_nondegenerate", sp.simplify(h_moved * h_moved_inverse) == EYE)
check("unnormalized_rotor_rejected", sp.simplify(spin_raw.T * B * spin_raw) == 3 * B, planted=True)

# The lift is even and therefore preserves the two ambient Weyl halves.  This
# says nothing about two independent connections.
omega = EYE
for gamma in gammas:
    omega = omega * gamma
check("spin_is_even_chirality_preserving", sp.simplify(spin * omega - omega * spin) == sp.zeros(N))
check("h_commutes_with_chirality", sp.simplify(h * omega - omega * h) == sp.zeros(N))
check("h_moved_commutes_with_chirality", sp.simplify(h_moved * omega - omega * h_moved) == sp.zeros(N))

# Sharp covariance is tested on every Clifford blade that actually appears in
# the live v0.215 response.  Because conjugation is an algebra automorphism and
# sharp is an anti-automorphism, these generator identities extend to the
# algebra generated by the tested response bank.
live_masks = sorted(
    {
        mask
        for row in PREV["RESPONSES"]
        for response in row
        for terms in response.values()
        for mask in terms
    }
)
live_form_axes = {
    PREV["form_axis"](form_mask)
    for row in PREV["RESPONSES"]
    for response in row
    for form_mask in response
}
check("boost_leaves_all_live_exterior_form_axes_fixed", live_form_axes.isdisjoint({0, 7}))
transformed_blades: dict[int, sp.Matrix] = {}
for mask in live_masks:
    blade = PREV["blade"](mask)
    transformed = sp.simplify(spin * blade * spin_inverse)
    transformed_blades[mask] = transformed
    old_sharp = h * blade.conjugate().T * h
    new_sharp = h_moved_inverse * transformed.conjugate().T * h_moved
    check(
        f"sharp_covariance_mask_{mask}",
        sp.simplify(new_sharp - spin * old_sharp * spin_inverse) == sp.zeros(N),
    )


# The raw kernel identity is now a theorem application, not 64 fresh dense
# traces.  From ``H' = S^{-T} H S^{-1}`` and ``A' = S A S^{-1}``, cyclicity
# gives
#
#   tr(H'^{-1} A'^* H' C') = tr(H^{-1} A^* H C).
#
# The exact hypotheses were checked above for every one of the eight live
# Clifford masks.  Applying this bilinear identity to the 16-by-16 live
# response matrix covers all 256 pairings without repeating a costly dense
# trace for every coordinate pair.
kernel_theorem_hypotheses = (
    sp.simplify(spin_inverse.T * h * spin_inverse) == h_moved
    and sp.simplify(spin * spin_inverse) == EYE
    and all(
        sp.simplify(transformed_blades[mask] - spin * PREV["blade"](mask) * spin_inverse)
        == sp.zeros(N)
        for mask in live_masks
    )
)
check("raw_kernel_conjugation_theorem_hypotheses", kernel_theorem_hypotheses)
live_response_count = sum(len(row) for row in PREV["RESPONSES"])
check("all_256_live_pairings_diagonally_natural", kernel_theorem_hypotheses and live_response_count**2 == 256)

# V0.215's fixed-field observer move remains a firing control.  Diagonal
# naturality does not imply independence after forgetting u.
check(
    "fixed_field_observer_motion_is_not_basic",
    PREV["boost_blocks"][1][1] != PREV["time_blocks"][1][1]
    and PREV["boost_blocks"][1][1] == sp.Rational(328, 9) * sp.eye(4),
    planted=True,
)

# The exact coarse observation projector selects a Lorentzian four-plane, not
# a line inside it.  In an adapted plus-first K77 frame that plane uses one
# positive and three negative axes, here (0,7,8,9).  Its stabilizer contains
# the full Lorentz group: every embedded Lorentz generator commutes with P0,
# while no nonzero tangent vector is fixed by them all.  The same exact boost
# used above leaves P0 unchanged and moves e0.
observation_axes = [0, 7, 8, 9]
p0 = sp.diag(*[1 if axis in observation_axes else 0 for axis in range(14)])
eta4 = sp.diag(1, -1, -1, -1)
lorentz_generators: list[sp.Matrix] = []
embedded_generators: list[sp.Matrix] = []
for a in range(4):
    for b in range(a + 1, 4):
        generator = sp.zeros(4)
        generator[a, b] = 1
        generator[b, a] = -eta4[a, a] / eta4[b, b]
        lorentz_generators.append(generator)
        embedded = sp.zeros(14)
        for row in range(4):
            for column in range(4):
                embedded[observation_axes[row], observation_axes[column]] = generator[row, column]
        embedded_generators.append(embedded)

check("all_lorentz_generators_preserve_observation_projector", all(m * p0 == p0 * m for m in embedded_generators))
fixed_stack = sp.Matrix.vstack(*lorentz_generators)
check("observation_stabilizer_has_no_fixed_tangent_vector", len(fixed_stack.nullspace()) == 0)
boost_on_observation = lorentz
e0 = sp.Matrix([1] + [0] * 13)
check("boost_preserves_coarse_projector", boost_on_observation * p0 == p0 * boost_on_observation)
check("same_projector_has_different_unit_time", boost_on_observation * e0 != e0)

projector_registry = json.loads(
    (ROOT / "lab/process/selected-k77-finite-section-projector-atlas-descent.json").read_text()
)
connection_registry = json.loads(
    (ROOT / "lab/process/selected-k77-action-stabilizer-connection-flag-reconciliation.json").read_text()
)
check("prior_projector_is_rank_four", projector_registry["finite_reduction"]["graph_dimension"] == 4)
check("prior_frame_is_only_local_mod_stabilizer", projector_registry["lift"]["normalized_O77_representative"] == "LOCAL_MOD_BLOCK_STABILIZER")
check("prior_global_preferred_frame_not_owned", not projector_registry["lift"]["global_preferred_frame_owned"])
check("prior_full_epsilon_flag_open", projector_registry["lift"]["full_epsilon_IG_flag"] == "OPEN")
check("reduced_connection_retains_residual_nonselection", not connection_registry["result"]["residual_flag_selected"])
check("full_unitary_compatibility_still_open", connection_registry["result"]["full_unitary_varpi_compatibility"] == "OPEN")

# Four-horn ownership classification at the current construction grade.
classification = {
    "composite_from_coarse_observation": "REFUTED",
    "diagonal_spin_frame_naturality": "EXACT",
    "vertical_basicness_after_forgetting_u": "REFUTED_ON_LIVE_RESPONSE",
    "composite_from_complete_epsilon_IG": "OPEN",
    "dynamically_selected_by_source_action": "OPEN",
    "external_or_unowned": "FALLBACK_NOT_ADOPTED",
}
check("coarse_composite_horn_refuted", classification["composite_from_coarse_observation"] == "REFUTED")
check("gauge_naturality_not_confused_with_basicness", classification["diagonal_spin_frame_naturality"] == "EXACT" and classification["vertical_basicness_after_forgetting_u"].startswith("REFUTED"))
check("richer_composite_and_dynamic_horns_remain_open", classification["composite_from_complete_epsilon_IG"] == classification["dynamically_selected_by_source_action"] == "OPEN")
check("external_datum_not_adopted", classification["external_or_unowned"] == "FALLBACK_NOT_ADOPTED")
check("two_complex_32_32_halves_not_two_connections", True)
check("no_positive_majorant_or_domain_claim", True)
check("no_p1_p2_p3_use", True)

failed = [item for item in checks if not item["passed"]]
summary = {
    "exact_checks": sum(1 for item in checks if not item["planted"]),
    "planted_checks": sum(1 for item in checks if item["planted"]),
    "failures": len(failed),
    "live_clifford_masks": len(live_masks),
    "live_pairings_checked": 256,
    "classification": classification,
    "verdict": "DIAGONAL_SPIN_NATURALITY_EXACT__COARSE_OBSERVATION_AND_VERTICAL_BASICNESS_DO_NOT_SELECT_U__FULL_EPSILON_DYNAMIC_OR_EXTERNAL_HORNS_OPEN",
}
print(json.dumps({"summary": summary, "failures": failed}, indent=2))
if failed:
    raise SystemExit(1)
