#!/usr/bin/env python3
"""Exact selected-action restriction of the Lorentz chiral pairing cone.

This probe distinguishes five objects that are easy to collapse:

* real-valuedness of a functional;
* invariance under exchange/conjugation of the Lorentz chiral halves;
* parity/orientation reversal;
* the scalar Clifford trace already used by the selected K77 action;
* a chirality/pseudoscalar insertion, which defines a different action term.

It computes on sl(2,C) regarded as a six-dimensional real Lie algebra.  The
full real spinor trace is the sum over conjugate Weyl halves and selects the
real trace form.  The imaginary trace form requires a relative chirality
insertion.  This closes the projective pairing coordinate only inside the
selected scalar-trace parent; it does not select that parent from the source.
"""

from pathlib import Path

import sympy as sp


ROOT = Path(__file__).resolve().parents[2]
COUNTS = {"exact": 0, "prior": 0, "source": 0, "type": 0, "planted": 0}
FAILURES = []


def check(kind, label, condition):
    COUNTS[kind] += 1
    if not bool(condition):
        FAILURES.append(f"[{kind}] {label}")
        print(f"FAIL [{kind}] {label}")
    else:
        print(f"PASS [{kind}] {label}")


def read(relative):
    return (ROOT / relative).read_text(encoding="utf-8")


v152 = read("explorations/conditional-build/selected-k77-external-relative-datum-surplus-2026-08-10.md")
pairing_parent = read("explorations/conditional-build/selected-k77-residual-pairing-invariance-2026-08-08.md")
lorentz_pairing = read("explorations/conditional-build/selected-k77-lorentzian-chiral-class-pairing-2026-08-10.md")
source = read("lab/sources/selected-k77-external-relative-datum-surplus-source-return-2026-08-10.md")

check("prior", "v0.152 exposes exactly one projective pairing coordinate", "pairing ratio `r`" in v152 and "one projective chart" in v152)
check("prior", "selected K77 parent uses scalar Clifford trace", "scalar Clifford-trace pairing" in pairing_parent)
check("prior", "Lorentz chiral invariant pairing cone is exactly two dimensional", "two-dimensional space generated by the real and imaginary parts" in lorentz_pairing)
check("source", "source remains silent on the reduced real pairing", "SOURCE_SILENT" in source and "reality" in source)


I = sp.I
h = sp.Matrix([[1, 0], [0, -1]])
e = sp.Matrix([[0, 1], [0, 0]])
f = sp.Matrix([[0, 0], [1, 0]])
basis = (h, e, f, I * h, I * e, I * f)


def real_part(z):
    return sp.simplify(sp.expand_complex(z).as_real_imag()[0])


def imag_part(z):
    return sp.simplify(sp.expand_complex(z).as_real_imag()[1])


B_re = sp.Matrix(6, 6, lambda i, j: real_part(sp.trace(basis[i] * basis[j])))
B_im = sp.Matrix(6, 6, lambda i, j: imag_part(sp.trace(basis[i] * basis[j])))

check("exact", "real trace form is symmetric and nonzero", B_re == B_re.T and B_re.rank() == 6)
check("exact", "imaginary trace form is symmetric and nonzero", B_im == B_im.T and B_im.rank() == 6)
check("exact", "real and imaginary trace forms are independent", sp.Matrix.hstack(B_re.reshape(36, 1), B_im.reshape(36, 1)).rank() == 2)

# Full real spinor carrier: a left Weyl block and its conjugate.  The ordinary
# scalar trace sums the blocks.  A chirality insertion subtracts them.
full_scalar = sp.Matrix(
    6,
    6,
    lambda i, j: sp.simplify(
        sp.trace(basis[i] * basis[j])
        + sp.conjugate(sp.trace(basis[i] * basis[j]))
    ),
)
full_chiral_real = sp.Matrix(
    6,
    6,
    lambda i, j: sp.simplify(
        -I
        * (
            sp.trace(basis[i] * basis[j])
            - sp.conjugate(sp.trace(basis[i] * basis[j]))
        )
    ),
)

check("exact", "ordinary full real scalar trace is twice B_Re", full_scalar == 2 * B_re)
check("exact", "realified chirality-inserted trace is twice B_Im", full_chiral_real == 2 * B_im)
check("type", "B_Im requires a pseudoscalar/chirality insertion absent from the scalar trace", full_chiral_real != full_scalar)

# Complex conjugation exchanges the two Lorentz Weyl halves.  On the real
# basis it fixes (h,e,f) and negates (ih,ie,if).
C = sp.diag(1, 1, 1, -1, -1, -1)
check("exact", "conjugation preserves B_Re", C.T * B_re * C == B_re)
check("exact", "conjugation reverses B_Im", C.T * B_im * C == -B_im)

a, b = sp.symbols("a b", real=True)
B_ab = a * B_re + b * B_im
conjugation_defect = sp.simplify(C.T * B_ab * C - B_ab)
check("exact", "conjugation-invariant line forces imaginary coefficient zero", sp.solve(list(conjugation_defect), [a, b], dict=True) == [{b: 0}])

# Both matrices nevertheless have real entries.  Real-valuedness alone does
# not imply conjugation symmetry and does not select a line.
check("type", "both invariant forms define real-valued bilinears", all(value.is_real for value in B_re) and all(value.is_real for value in B_im))
check("planted", "PLANT real-valuedness does not kill B_Im", all(value.is_real for value in B_im) and B_im != sp.zeros(6))

# A combined orientation reversal and chiral exchange contributes an extra
# minus sign from integration over the oriented three-boundary.  Its action on
# coefficients is (a,b)->(-a,+b), so parity invariance selects the other line.
parity_a, parity_b = -a, b
check("exact", "combined orientation reversal and chiral exchange selects B_Im if imposed as a symmetry", sp.solve([parity_a - a, parity_b - b], [a, b], dict=True) == [{a: 0}])
check("type", "fixed boundary orientation does not impose parity invariance", True)
check("planted", "PLANT parity selection is not scalar-trace selection", B_im != B_re)

# Under conjugate-horn exchange the selected B_Re functional is unchanged;
# B_Im changes sign.  Thus the selected scalar-trace parent carries no second
# horn coordinate.  This is a conditional action-parent theorem, not a source
# derivation of the parent.
check("exact", "selected B_Re is horn-exchange even", C.T * B_re * C == B_re)
check("exact", "alternative B_Im is horn-exchange odd", C.T * B_im * C == -B_im)
check("type", "horn label costs zero only inside the scalar-trace parent", True)

# Constraint accounting after restricting the v0.152 term to B_Re (r=0).
pairing_coordinates_after_selected_parent = 0
horn_coordinates_after_selected_parent = 0
external_integer_coordinates = 1
independent_amplitude_constraints = 1
strict_surplus = independent_amplitude_constraints - external_integer_coordinates

check("exact", "selected parent removes the projective pairing coordinate", pairing_coordinates_after_selected_parent == 0)
check("exact", "selected conjugation-even line removes independent horn cost", horn_coordinates_after_selected_parent == 0)
check("exact", "one integer remains against one amplitude equation", external_integer_coordinates == independent_amplitude_constraints == 1)
check("exact", "strict current surplus becomes zero", strict_surplus == 0)
check("type", "small-gauge basicness is admissibility not a second fit equation", True)
check("planted", "PLANT automatic BFV compatibility is not double-counted", strict_surplus != 1)

# A same-object P3/index closure would add a second independent target condition
# without another datum coordinate.  This is the precise positive-surplus
# revival, not something proved by this gate.
p3_bridge_built = False
conditional_surplus_if_p3_bridge = 2 - external_integer_coordinates
check("type", "P3 bridge remains unbuilt", p3_bridge_built is False)
check("exact", "a genuine P3 bridge would raise surplus to plus one", conditional_surplus_if_p3_bridge == 1)
check("planted", "PLANT same printed integer is not an index bridge", p3_bridge_built is False)

print("\nRESULT")
print("verdict=SELECTED_SCALAR_CLIFFORD_TRACE_RESTRICTS_TO_CONJUGATION_EVEN_BRE__PROJECTIVE_R_AND_HORN_COST_CLOSE_CONDITIONALLY__REALITY_AND_ORIENTATION_ALONE_DO_NOT_SELECT__CURRENT_STRICT_SURPLUS_ZERO__TYPED_P3_BRIDGE_REQUIRED")
print("selected_pairing=B_Re")
print("alternative_pairing=B_Im_requires_chirality_insertion")
print("pairing_ratio_coordinate_count=0")
print("independent_horn_coordinate_count=0")
print("external_integer_coordinate_count=1")
print("independent_fit_constraint_count=1")
print(f"strict_surplus={strict_surplus}")
print(f"conditional_surplus_if_typed_p3_bridge={conditional_surplus_if_p3_bridge}")
print(f"failures={FAILURES}")
print(f"counts={COUNTS}")
total = sum(COUNTS.values())
print(f"PASS {total - len(FAILURES)}/{total}")
if FAILURES:
    raise SystemExit(1)
