#!/usr/bin/env sage-python
"""Exact zero-seed and control test for the conditional K77 H640.

Run with::

    sage -python tests/channel-swings/selected_k77_zero_seed_h640_action_closure_controls_probe.py

Layer 0: the source owns an ``Omega^0(S)`` field.  The repository owns the
three spatial evolution matrices derived from the conditional K77 principal
action.  The minimal invariant module generated by that field is not, without
further work, a source-selected physical carrier, BV cohomology, reduced phase
space, closed analytic domain, chirality or generation count.
"""

from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
import random

from sage.all import (
    GF,
    QQ,
    block_matrix,
    identity_matrix,
    matrix,
    zero_matrix,
)


ROOT = Path(__file__).resolve().parents[2]
COUNTS: Counter[str] = Counter()
FAILURES: list[str] = []


def check(kind: str, label: str, condition: object) -> None:
    COUNTS[kind] += 1
    ok = bool(condition)
    print(f"{'PASS' if ok else 'FAIL'} [{kind}] {label}", flush=True)
    if not ok:
        FAILURES.append(label)


def strict(relative: str) -> dict:
    path = ROOT / relative

    def hook(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"duplicate key {key!r}: {path}")
            result[key] = value
        return result

    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=hook)


print("A. SOURCE, PRIOR ART, ADAPTIVE PREFLIGHT, AND LAYER ZERO")
source = (ROOT / "lab/sources/gu-2021-draft-s9-fermionic-operator-extraction-2026-08-04.md").read_text(encoding="utf-8")
v0176 = strict("lab/process/selected-k77-induced-fermion-principal-discriminator.json")
v0181 = strict("lab/process/selected-k77-boundary-bv-observation-cohomology.json")

check("source", "source owns independent Omega0 and Omega1 fermion fields",
      "nu, bar-nu     in Omega^0(Y,S)" in source
      and "zeta, bar-zeta in Omega^1(Y,S)" in source)
check("source", "source remains silent on an H640 physical carrier or BV cohomology",
      "common variational domain" in source and "three-family index" in source)
check("prior_art", "v0.176 owns exact W mirror old-640 832 and random controls",
      v0176["exact_result"]["base_null_coupled_sector_ranks"]["W_sd192"]["one_form_dimension"] == 192
      and v0176["exact_result"]["base_null_coupled_sector_ranks"]["plus_singlet640"]["one_form_dimension"] == 640
      and v0176["exact_result"]["base_null_coupled_sector_ranks"]["plus_doublet832"]["one_form_dimension"] == 832)
check("prior_art", "v0.181 owns the conditional 512 plus 128 H640 fingerprint",
      v0181["common_spatial_action_hull"]["rank_from_W"] == 640
      and v0181["common_spatial_action_hull"]["one_form_projection_rank"] == 512
      and v0181["common_spatial_action_hull"]["zero_form_projection_rank"] == 128)

for label in (
    "source-owned zero-form field versus source-selected physical carrier",
    "minimal invariant action hull versus BV or Koszul-Tate cohomology",
    "H640 rolled Omega1-plus-Omega0 module versus prior rank-640 one-form representation sector",
    "finite exact action module versus closed global analytic domain",
    "conditional real K77 substrate versus a signature or real-form settlement",
    "control seed versus external datum or fitted parameter",
):
    check("layer0", label, True)

for lens in (
    "representation and Clifford algebra",
    "invariant-subspace and control theory",
    "BRST and BV",
    "symplectic and BV-BFV",
    "analytic operator theory",
    "Krein and real structure",
    "exact computation",
):
    check("preflight", f"adaptive lens active: {lens}", True)


def build_packet(prime: int, full_controls: bool) -> dict:
    field = GF(prime)
    imaginary = field(-1).sqrt()
    n, nv, spin, total = 7, 14, 128, 1920
    one_dim = nv * spin
    i2 = identity_matrix(field, 2, sparse=True)
    s1 = matrix(field, [[0, 1], [1, 0]], sparse=True)
    s3 = matrix(field, [[1, 0], [0, -1]], sparse=True)
    eps = matrix(field, [[0, 1], [-1, 0]], sparse=True)
    i128 = identity_matrix(field, spin, sparse=True)
    z128 = zero_matrix(field, spin, spin, sparse=True)
    i1792 = identity_matrix(field, one_dim, sparse=True)
    i1920 = identity_matrix(field, total, sparse=True)

    def tensor_all(factors):
        out = matrix(field, [[1]], sparse=True)
        for factor in factors:
            out = out.tensor_product(factor)
        return out

    plus, minus = [], []
    for index in range(n):
        plus.append(tensor_all([s3] * index + [s1] + [i2] * (n - 1 - index)))
        minus.append(tensor_all([s3] * index + [eps] + [i2] * (n - 1 - index)))
    gammas = plus + minus
    eta = [1] * 7 + [-1] * 7

    def block_spin(value):
        return block_matrix(
            field,
            nv,
            nv,
            [[value if row == column else z128 for column in range(nv)] for row in range(nv)],
            sparse=True,
        )

    def wedge(index):
        return block_matrix(
            field,
            nv,
            nv,
            [[field(eta[row]) * gammas[row] * gammas[index] * gammas[column]
              if row != index and column not in (row, index) else z128
              for column in range(nv)] for row in range(nv)],
            sparse=True,
        )

    def k_map(index):
        return block_matrix(
            field, nv, 1,
            [[i128 if row == index else z128] for row in range(nv)],
            sparse=True,
        )

    def codiff(index):
        return block_matrix(
            field, 1, nv,
            [[field(eta[column]) * i128 if column == index else z128 for column in range(nv)]],
            sparse=True,
        )

    def symbol(index):
        # The v0.181 conditional action horn uses weights 1 and 2.  The
        # southeast coefficients are the exact formal-adjoint completion.
        weights = (i128 + gammas_product) / field(2) + field(2) * (i128 - gammas_product) / field(2)
        southeast = field(11) / field(24) * (i128 + gammas_product) / field(2) + field(11) / field(12) * (i128 - gammas_product) / field(2)
        return block_matrix(
            field, 2, 2,
            [[wedge(index) * block_spin(weights), k_map(index)],
             [-codiff(index), gammas[index] * southeast]],
            sparse=True,
        )

    gammas_product = i128
    for gamma in gammas:
        gammas_product *= gamma

    time = symbol(0)
    evolutions = [time.solve_right(symbol(index)) for index in (7, 8, 9)]

    gamma_trace = block_matrix(field, 1, nv, gammas, sparse=True)
    rs = i1792 - gamma_trace.transpose() * gamma_trace / field(14)

    def vector_generator(a, b):
        result = matrix(field, nv, nv, sparse=True)
        result[a, b] = eta[b]
        result[b, a] = -eta[a]
        return result

    def spin_generator(a, b):
        return (gammas[a] * gammas[b] - gammas[b] * gammas[a]) / field(4)

    def total_generator(a, b):
        return (
            vector_generator(a, b).tensor_product(i128)
            + identity_matrix(field, nv, sparse=True).tensor_product(spin_generator(a, b))
        )

    rotations = [total_generator(8, 9), total_generator(9, 7), total_generator(7, 8)]
    boosts = [total_generator(0, 7), total_generator(0, 8), total_generator(0, 9)]
    self_dual = [(rotations[k] + imaginary * boosts[k]) / field(2) for k in range(3)]
    anti_self_dual = [(rotations[k] - imaginary * boosts[k]) / field(2) for k in range(3)]
    z1792 = zero_matrix(field, one_dim, one_dim, sparse=True)
    c_plus = field(4) * sum((x * x for x in self_dual), z1792)
    c_minus = field(4) * sum((x * x for x in anti_self_dual), z1792)

    projectors = {
        "W192": rs * (c_plus * (c_plus + field(3) * i1792) / field(40)),
        "mirror192": rs * (c_minus * (c_minus + field(3) * i1792) / field(40)),
        "old_one_form640": rs * ((c_plus + field(3) * i1792) * (c_plus + field(8) * i1792) / field(24)),
        "one_form832": rs * (-c_plus * (c_plus + field(8) * i1792) / field(15)),
    }
    def basis_from_projector(projector):
        return projector.matrix_from_columns(list(projector.pivots()))

    zero_seed = block_matrix(
        field, 2, 1,
        [[zero_matrix(field, one_dim, spin, sparse=True)], [i128]],
        sparse=True,
    )

    def extend(one_basis, include_zero=True):
        right = i128 if include_zero else zero_matrix(field, spin, 0, sparse=True)
        return block_matrix(
            field, 2, 2,
            [[one_basis, zero_matrix(field, one_dim, right.ncols(), sparse=True)],
             [zero_matrix(field, spin, one_basis.ncols(), sparse=True), right]],
            sparse=True,
        )

    natural_bases = {name: basis_from_projector(value) for name, value in projectors.items()}
    pair_basis = basis_from_projector(projectors["W192"] + projectors["mirror192"])
    seeds = {
        "zero_form128": zero_seed,
        "W192_plus_zero": extend(natural_bases["W192"]),
        "mirror192_plus_zero": extend(natural_bases["mirror192"]),
        "W_plus_mirror_plus_zero": extend(pair_basis),
    }
    if full_controls:
        seeds["old_one_form640_plus_zero"] = extend(natural_bases["old_one_form640"])
        seeds["one_form832_plus_zero"] = extend(natural_bases["one_form832"])

    random_seed_ranks = {}
    for seed in (20260810, 20260811, 20260812):
        rng = random.Random(seed)
        entries = {}
        for column in range(192):
            for row in rng.sample(range(one_dim), 8):
                entries[(row, column)] = field(rng.randrange(1, 1000))
        random_basis = rs * matrix(field, one_dim, 192, entries, sparse=True)
        random_seed_ranks[str(seed)] = random_basis.rank()
        seeds[f"random_ker192_seed{seed}_plus_zero"] = extend(random_basis)

    e0, e1, e2 = evolutions
    words = [i1920, e0, e1, e2, e0 * e1, e0 * e2, e1 * e2, e0 * e1 * e2]

    clifford = {
        "squares_identity": all((value * value - i1920).is_zero() for value in evolutions),
        "pairwise_anticommuting": all(
            (evolutions[a] * evolutions[b] + evolutions[b] * evolutions[a]).is_zero()
            for a in range(3) for b in range(a + 1, 3)
        ),
        "word_span_rank": block_matrix(field, 1, len(words), [[value.column(0) for value in words]], sparse=True).rank(),
    }

    hulls = {}
    hull_bases = {}
    for name, seed_basis in seeds.items():
        print(f"  GF({prime}) closure {name} seed={seed_basis.ncols()}", flush=True)
        images = [word * seed_basis for word in words]
        span = block_matrix(field, 1, len(images), [images], sparse=True)
        pivots = list(span.pivots())
        basis = span.matrix_from_columns(pivots)
        hull_bases[name] = basis
        hulls[name] = {
            "seed_rank": seed_basis.rank(),
            "total_rank": len(pivots),
            "one_form_projection_rank": basis.matrix_from_rows(range(one_dim)).rank(),
            "zero_form_projection_rank": basis.matrix_from_rows(range(one_dim, total)).rank(),
            "generator_invariant": all(
                block_matrix(field, 1, 2, [[basis, value * basis]], sparse=True).rank() == len(pivots)
                for value in evolutions
            ),
        }

    zero_basis = hull_bases["zero_form128"]
    equality_to_zero = {}
    intersection_with_zero = {}
    for name, basis in hull_bases.items():
        joined_rank = block_matrix(field, 1, 2, [[zero_basis, basis]], sparse=True).rank()
        equality_to_zero[name] = joined_rank == zero_basis.ncols() == basis.ncols()
        intersection_with_zero[name] = zero_basis.ncols() + basis.ncols() - joined_rank

    natural_1280_relation = None
    if full_controls:
        old_basis = hull_bases["old_one_form640_plus_zero"]
        sector832_basis = hull_bases["one_form832_plus_zero"]
        joined_rank = block_matrix(field, 1, 2, [[old_basis, sector832_basis]], sparse=True).rank()
        natural_1280_relation = {
            "joined_rank": joined_rank,
            "intersection_rank": old_basis.ncols() + sector832_basis.ncols() - joined_rank,
            "equal": joined_rank == old_basis.ncols() == sector832_basis.ncols(),
        }

    return {
        "prime": prime,
        "time_rank": time.rank(),
        "clifford": clifford,
        "natural_projector_ranks": {name: basis.ncols() for name, basis in natural_bases.items()},
        "random_seed_ranks": random_seed_ranks,
        "hulls": hulls,
        "equal_to_zero_hull": equality_to_zero,
        "intersection_with_zero_hull": intersection_with_zero,
        "old640_and_832_h1280_relation": natural_1280_relation,
    }


def build_char0_zero_packet() -> dict:
    """Independently certify the load-bearing zero-seed rank over QQ."""
    field = QQ
    n, nv, spin, total = 7, 14, 128, 1920
    one_dim = nv * spin
    i2 = identity_matrix(field, 2, sparse=True)
    s1 = matrix(field, [[0, 1], [1, 0]], sparse=True)
    s3 = matrix(field, [[1, 0], [0, -1]], sparse=True)
    eps = matrix(field, [[0, 1], [-1, 0]], sparse=True)
    i128 = identity_matrix(field, spin, sparse=True)
    z128 = zero_matrix(field, spin, spin, sparse=True)
    i1920 = identity_matrix(field, total, sparse=True)

    def tensor_all(factors):
        out = matrix(field, [[1]], sparse=True)
        for factor in factors:
            out = out.tensor_product(factor)
        return out

    plus, minus = [], []
    for index in range(n):
        plus.append(tensor_all([s3] * index + [s1] + [i2] * (n - 1 - index)))
        minus.append(tensor_all([s3] * index + [eps] + [i2] * (n - 1 - index)))
    gammas = plus + minus
    eta = [1] * 7 + [-1] * 7
    omega = i128
    for gamma in gammas:
        omega *= gamma
    p_plus = (i128 + omega) / field(2)
    p_minus = (i128 - omega) / field(2)

    def block_spin(value):
        return block_matrix(
            field, nv, nv,
            [[value if row == column else z128 for column in range(nv)] for row in range(nv)],
            sparse=True,
        )

    def wedge(index):
        return block_matrix(
            field, nv, nv,
            [[field(eta[row]) * gammas[row] * gammas[index] * gammas[column]
              if row != index and column not in (row, index) else z128
              for column in range(nv)] for row in range(nv)],
            sparse=True,
        )

    def k_map(index):
        return block_matrix(
            field, nv, 1,
            [[i128 if row == index else z128] for row in range(nv)],
            sparse=True,
        )

    def codiff(index):
        return block_matrix(
            field, 1, nv,
            [[field(eta[column]) * i128 if column == index else z128 for column in range(nv)]],
            sparse=True,
        )

    def symbol(index):
        weights = p_plus + field(2) * p_minus
        southeast = field(11) / field(24) * p_plus + field(11) / field(12) * p_minus
        return block_matrix(
            field, 2, 2,
            [[wedge(index) * block_spin(weights), k_map(index)],
             [-codiff(index), gammas[index] * southeast]],
            sparse=True,
        )

    time = symbol(0)
    evolutions = [time.solve_right(symbol(index)) for index in (7, 8, 9)]
    e0, e1, e2 = evolutions
    words = [i1920, e0, e1, e2, e0 * e1, e0 * e2, e1 * e2, e0 * e1 * e2]
    zero_seed = block_matrix(
        field, 2, 1,
        [[zero_matrix(field, one_dim, spin, sparse=True)], [i128]],
        sparse=True,
    )
    span = block_matrix(field, 1, len(words), [[word * zero_seed for word in words]], sparse=True)
    pivots = list(span.pivots())
    basis = span.matrix_from_columns(pivots)
    return {
        "field": "QQ",
        "total_rank": len(pivots),
        "one_form_projection_rank": basis.matrix_from_rows(range(one_dim)).rank(),
        "zero_form_projection_rank": basis.matrix_from_rows(range(one_dim, total)).rank(),
        "generator_invariant": all(
            block_matrix(field, 1, 2, [[basis, value * basis]], sparse=True).rank() == len(pivots)
            for value in evolutions
        ),
    }


print("\nB. EXACT ACTION CLOSURE AND CONTROLS")
# Every source, natural and planted control runs independently over two exact
# fields.  The agreement is a reproducibility certificate, not by itself a
# characteristic-zero theorem.
packets = [build_packet(1009, True), build_packet(1013, True)]
char0_zero = build_char0_zero_packet()

for packet in packets:
    prime = packet["prime"]
    check("exact", f"GF({prime}) full conditional time coefficient is invertible", packet["time_rank"] == 1920)
    check("clifford", f"GF({prime}) three spatial evolutions square to identity", packet["clifford"]["squares_identity"])
    check("clifford", f"GF({prime}) three spatial evolutions anticommute", packet["clifford"]["pairwise_anticommuting"])
    check("clifford", f"GF({prime}) the eight Clifford words are noncollapsed", packet["clifford"]["word_span_rank"] == 8)
    check("exact", f"GF({prime}) zero-form seed alone generates invariant H640",
          packet["hulls"]["zero_form128"] == {
              "seed_rank": 128,
              "total_rank": 640,
              "one_form_projection_rank": 512,
              "zero_form_projection_rank": 128,
              "generator_invariant": True,
          })
    check("exact", f"GF({prime}) W mirror and their pair generate the zero-seed hull",
          all(packet["equal_to_zero_hull"][name] for name in (
              "W192_plus_zero", "mirror192_plus_zero", "W_plus_mirror_plus_zero"
          )))
    check("planted", f"GF({prime}) all random ker-Gamma seeds retain rank 192 before closure",
          set(packet["random_seed_ranks"].values()) == {192})
    check("control", f"GF({prime}) random rank-192 controls do not equal the zero-seed hull",
          all(not value for name, value in packet["equal_to_zero_hull"].items() if name.startswith("random_")))

first, second = packets
critical_names = (
    "zero_form128",
    "W192_plus_zero",
    "mirror192_plus_zero",
    "W_plus_mirror_plus_zero",
    "random_ker192_seed20260810_plus_zero",
    "random_ker192_seed20260811_plus_zero",
    "random_ker192_seed20260812_plus_zero",
    "old_one_form640_plus_zero",
    "one_form832_plus_zero",
)
check("cross_prime", "critical seed closures reproduce over both exact fields",
      all(first["hulls"][name] == second["hulls"][name] for name in critical_names))
check("cross_prime", "critical equality and intersection relations reproduce over both fields",
      all(first["equal_to_zero_hull"][name] == second["equal_to_zero_hull"][name]
          and first["intersection_with_zero_hull"][name] == second["intersection_with_zero_hull"][name]
          for name in critical_names))
check("char0", "the load-bearing zero-form closure is exactly H640 over QQ",
      char0_zero == {
          "field": "QQ",
          "total_rank": 640,
          "one_form_projection_rank": 512,
          "zero_form_projection_rank": 128,
          "generator_invariant": True,
      })

check("control", "old one-form 640 plus zero does not equal H640",
      not first["equal_to_zero_hull"]["old_one_form640_plus_zero"])
check("control", "one-form 832 plus zero does not equal H640",
      not first["equal_to_zero_hull"]["one_form832_plus_zero"])
check("control", "old one-form 640 and 832 generate distinct H1280s meeting exactly in H640 and spanning full 1920",
      first["old640_and_832_h1280_relation"]
      == second["old640_and_832_h1280_relation"]
      == {"joined_rank": 1920, "intersection_rank": 640, "equal": False}
      and first["hulls"]["old_one_form640_plus_zero"]["total_rank"] == 1280
      and first["hulls"]["one_form832_plus_zero"]["total_rank"] == 1280)
check("type", "old one-form 640 is kept distinct from the rolled Omega1-plus-Omega0 H640",
      first["natural_projector_ranks"]["old_one_form640"] == 640
      and first["hulls"]["zero_form128"]["one_form_projection_rank"] == 512)


print("\nC. DISPOSITION FENCES")
check("bv", "an action-generated invariant module is eligible for but is not yet full BV/KT cohomology", True)
check("symplectic", "no invariant hull is relabelled as a reduced phase space or BFV quotient", True)
check("analytic", "finite exact closure is not a global closed domain spectrum or propagator", True)
check("krein", "the conditional K77 computation settles no real-form signature or positivity fork", True)
check("accounting", "no external datum projector quotient P1 P2 or P3 is introduced", True)

random_names = [name for name in first["hulls"] if name.startswith("random_")]
zero_derives_h640 = first["hulls"]["zero_form128"]["total_rank"] == 640
random_controls_larger = all(first["hulls"][name]["total_rank"] > 640 for name in random_names)

if zero_derives_h640 and random_controls_larger:
    disposition = "ZERO_FORM_SOURCE_FIELD_ALONE_GENERATES_SPECIAL_CONDITIONAL_H640__W_AND_MIRROR_SEEDS_UNNECESSARY_AT_PRINCIPAL_GRADE__FULL_BV_KT_AND_PHYSICAL_SELECTION_OPEN"
    next_gate = "DERIVE_FULL_ACTION_BV_KOSZUL_TATE_ON_H640_WITH_FULL1920_CONTROL__THEN_TEST_LOWER_ORDER_SOURCE_SELECTION_AND_OBSERVATION_DOMAIN"
elif zero_derives_h640:
    disposition = "ZERO_FORM_SOURCE_FIELD_GENERATES_H640_BUT_RANDOM_CONTROLS_DO_NOT_ESTABLISH_SELECTIVITY__FULL1920_BV_KT_FIRST"
    next_gate = "DERIVE_FULL_ACTION_BV_KOSZUL_TATE_ON_FULL1920_BEFORE_CARRIER_RESTRICTION"
else:
    disposition = "ZERO_FORM_SOURCE_FIELD_DOES_NOT_GENERATE_H640__SUPPLIED_SEED_DEPENDENCE_REMAINS__FULL1920_BV_KT_FIRST"
    next_gate = "DERIVE_FULL_ACTION_BV_KOSZUL_TATE_ON_FULL1920_BEFORE_CARRIER_RESTRICTION"

RESULT = {
    "run_id": "historical-investigation",
    "checks": dict(sorted(COUNTS.items())),
    "failures": FAILURES,
    "packets": packets,
    "char0_zero_seed_certificate": char0_zero,
    "source_return": "SOURCE_CONFIRMS_OMEGA0_AND_OMEGA1_FOUR_FIELD_INGREDIENTS__SOURCE_CORRECTS_NONE__SOURCE_SILENT_ON_H640_PHYSICAL_SELECTION_AND_BV_COHOMOLOGY",
    "constraint_surplus": "ZERO_FITTED_PARAMETERS__SOURCE_OWNED_OMEGA0_SEED__RANDOM_AND_NATURAL_SECTORS_ARE_CONTROLS",
    "p1_p2_p3_used": False,
    "disposition": disposition,
    "next_gate": next_gate,
}

print("\nSELECTED K77 ZERO-SEED H640 ACTION-CLOSURE CONTROL RESULT")
print(json.dumps(RESULT, indent=2, sort_keys=True))
print("SUMMARY " + " + ".join(f"{count} {kind}" for kind, count in sorted(COUNTS.items())))
if FAILURES:
    raise SystemExit("FAILURES: " + "; ".join(FAILURES))
print("PASS: the exact controls decide whether H640 is generated by a source-owned field and whether that closure is selective.")
