#!/usr/bin/env sage-python
"""Exact ambient-versus-observed carrier boundary for the K77 H640 graph.

The v0.183 H640 was generated by the three observed spatial evolutions.  This
probe asks the prerequisite to the complete sixteen-cell lower-order Riccati
problem: what happens when the same source-family coefficient is allowed to
act in every direction of Y14?  It keeps ordinary pullback, a nonzero vertical
Higgs/soldering adapter, graph compression and actual invariant restriction as
four distinct objects.
"""

from __future__ import annotations

from collections import Counter
import json
from pathlib import Path

from sage.all import (
    GF,
    block_diagonal_matrix,
    block_matrix,
    identity_matrix,
    matrix,
    zero_matrix,
)


ROOT = Path(__file__).resolve().parents[2]
COUNTS = Counter()
FAILURES: list[str] = []


def check(kind: str, label: str, condition) -> None:
    COUNTS[kind] += 1
    ok = bool(condition)
    print(f"{'PASS' if ok else 'FAIL'} [{kind}] {label}", flush=True)
    if not ok:
        FAILURES.append(label)


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


print("A. ADAPTIVE PREFLIGHT, SOURCE, PRIOR ART, AND LAYER ZERO")
source = read("lab/sources/gu-2021-draft-s9-fermionic-operator-extraction-2026-08-04.md")
curt = read("lab/sources/curt-iceberg-fermion-zero-order-reinspection-2026-08-04.md")
v0183 = read("explorations/conditional-build/selected-k77-h640-observation-pullback-bv-typing-2026-08-11.md")
v0174 = read("explorations/conditional-build/selected-k77-action-adjoint-weight-classification-2026-08-11.md")
check("source", "source places the fermion operator on Y14 and observation uses section pullback",
      "Omega^0(Y,S)" in source and "Omega^1(Y,S)" in source
      and "observation pullback" in v0183)
check("source", "source displays all sixteen cells and admits a nonzero southeast rival",
      "all sixteen displayed cells" in source
      and "non-trivial map in the lower right quadrant" in source)
check("source", "Curt's vertical scalar-like placement is guidance rather than an adapter theorem",
      "vertical" in curt.lower() and "SOURCE-SILENT" in curt)
check("source", "source supplies no H640 graph, vertical adapter, BV complex, or closed domain",
      "SOURCE-SILENT" in source and "closed physical evolution domain" in source)
check("prior_art", "v0.183 proves only three-spatial-generator principal no-leakage",
      "All three conditional spatial evolutions preserve this graph exactly" in v0183
      and "sixteen-cell" in v0183)
check("prior_art", "v0.174 supplies two exact Grassmann pairing horns on all fourteen axes",
      "all fourteen directions" in v0174 and "Both are nondegenerate" in v0174)
for label in (
    "three observed spatial generators versus all thirteen Y14 spatial generators",
    "ordinary pullback annihilation versus a nonzero vertical scalar adapter",
    "graph compression versus ambient no-leakage",
    "moving frame covariance versus physical vertical coupling",
    "restricted alternating bilinear versus equation-dual BV differential",
    "finite carrier closure versus closed analytic domain",
):
    check("layer0", label, True)
for label in (
    "representation/Clifford: decide the complete action hull",
    "principal-bundle: separate moving graph from fixed subspace",
    "variational: do not replace an adapter by compression",
    "symplectic/BV-BFV: bilinear eligibility is not cohomology",
    "analytic/Krein: finite ranks are not domain or positivity claims",
    "exact computation: reproduce over two finite fields",
):
    check("preflight", label, True)


def packet(prime: int) -> dict:
    field = GF(prime)
    n, nv, spin, total = 7, 14, 128, 1920
    i2 = identity_matrix(field, 2, sparse=True)
    s1 = matrix(field, [[0, 1], [1, 0]], sparse=True)
    s3 = matrix(field, [[1, 0], [0, -1]], sparse=True)
    eps = matrix(field, [[0, 1], [-1, 0]], sparse=True)

    def tensor_all(factors):
        out = matrix(field, [[1]], sparse=True)
        for factor in factors:
            out = out.tensor_product(factor)
        return out

    plus, minus = [], []
    for index in range(n):
        plus.append(tensor_all([s3] * index + [s1] + [i2] * (n - 1 - index)))
        minus.append(tensor_all([s3] * index + [eps] + [i2] * (n - 1 - index)))
    gammas = plus + minus
    eta = [1] * 7 + [-1] * 7
    i128 = identity_matrix(field, spin, sparse=True)
    z128 = zero_matrix(field, spin, spin, sparse=True)
    i1920 = identity_matrix(field, total, sparse=True)
    omega = i128
    for gamma in gammas:
        omega *= gamma
    p_plus = (i128 + omega) / field(2)
    p_minus = (i128 - omega) / field(2)

    def block_spin(value):
        return block_matrix(
            field, nv, nv,
            [[value if row == column else z128 for column in range(nv)]
             for row in range(nv)], sparse=True,
        )

    def wedge(index):
        return block_matrix(
            field, nv, nv,
            [[field(eta[row]) * gammas[row] * gammas[index] * gammas[column]
              if row != index and column not in (row, index) else z128
              for column in range(nv)] for row in range(nv)], sparse=True,
        )

    def k_map(index):
        return block_matrix(
            field, nv, 1,
            [[i128 if row == index else z128] for row in range(nv)], sparse=True,
        )

    def codiff(index):
        return block_matrix(
            field, 1, nv,
            [[field(eta[column]) * i128 if column == index else z128
              for column in range(nv)]], sparse=True,
        )

    weights = p_plus + field(2) * p_minus
    southeast = field(11) / field(24) * p_plus + field(11) / field(12) * p_minus

    def symbol(index):
        return block_matrix(
            field, 2, 2,
            [[wedge(index) * block_spin(weights), k_map(index)],
             [-codiff(index), gammas[index] * southeast]], sparse=True,
        )

    symbols = [symbol(index) for index in range(14)]
    time = symbols[0]
    evolutions = {index: time.solve_right(symbols[index]) for index in range(1, 14)}

    observed_slots = (0, 7, 8, 9, 14)
    slot_lift = matrix(field, 15, 5, sparse=True)
    for column, row in enumerate(observed_slots):
        slot_lift[row, column] = 1
    coordinate_lift = slot_lift.tensor_product(i128)
    observation = coordinate_lift.transpose()

    zero_seed = block_matrix(
        field, 2, 1,
        [[zero_matrix(field, nv * spin, spin, sparse=True)], [i128]], sparse=True,
    )
    observed_indices = (7, 8, 9)
    e0, e1, e2 = [evolutions[index] for index in observed_indices]
    words = [i1920, e0, e1, e2, e0 * e1, e0 * e2, e1 * e2, e0 * e1 * e2]
    span = block_matrix(field, 1, len(words), [[word * zero_seed for word in words]], sparse=True)
    h640 = span.matrix_from_columns(list(span.pivots()))
    rh = observation * h640
    graph_lift = h640 * rh.inverse()
    graph_projector = graph_lift * observation
    graph_complement = i1920 - graph_projector

    observed_leakage = {
        index: int((graph_complement * evolutions[index] * graph_lift).rank())
        for index in observed_indices
    }
    transverse_indices = tuple(index for index in range(1, 14) if index not in observed_indices)
    transverse_leakage = {
        index: int((graph_complement * evolutions[index] * graph_lift).rank())
        for index in transverse_indices
    }
    transverse_join = {
        index: int(block_matrix(field, 1, 2, [[h640, evolutions[index] * h640]], sparse=True).rank())
        for index in transverse_indices
    }

    # Grow the complete source-zero-seed carrier under all thirteen spatial
    # evolution generators. Starting from H640 preserves the observed control.
    basis = h640
    closure_ranks = [int(basis.rank())]
    for _round in range(4):
        round_start = int(basis.ncols())
        # Incremental joins keep the exact computation bounded by 1920x3840,
        # instead of allocating a single 1920x24960 sparse block when the
        # carrier has already grown.
        for index in range(1, 14):
            candidate = block_matrix(
                field, 1, 2, [[basis, evolutions[index] * basis]], sparse=True,
            )
            basis = candidate.matrix_from_columns(list(candidate.pivots()))
            if basis.ncols() == total:
                break
        closure_ranks.append(int(basis.ncols()))
        if closure_ranks[-1] == round_start or closure_ranks[-1] == total:
            break

    # Ordinary coordinate pullback of covectors kills every transverse basis
    # covector. This is not a Higgs adapter; it is the negative control that
    # keeps the two operations typed separately.
    tangent = matrix(field, 14, 4, sparse=True)
    for column, row in enumerate((0, 7, 8, 9)):
        tangent[row, column] = 1
    transverse_pullback_ranks = {}
    for index in transverse_indices:
        covector = matrix(field, 14, 1, sparse=True)
        covector[index, 0] = 1
        transverse_pullback_ranks[index] = int((tangent.transpose() * covector).rank())

    b_spin = i128
    for gamma in gammas[7:]:
        b_spin *= gamma

    def pairing(a_plus, a_minus, b_plus, b_minus):
        r1 = field(a_plus) * p_plus + field(a_minus) * p_minus
        r0 = field(b_plus) * p_plus + field(b_minus) * p_minus
        return block_diagonal_matrix(
            [field(eta[index]) * b_spin * r1 for index in range(nv)]
            + [b_spin * r0], sparse=True,
        )

    p_sym = pairing(1, 1, 1, 1)
    p_skew = pairing(1, -1, -1, 1)
    k_sym_h = graph_lift.transpose() * p_sym * graph_lift
    k_skew_h = graph_lift.transpose() * p_skew * graph_lift
    restricted_alternation = {}
    for index in range(14):
        c_sym = graph_lift.transpose() * p_sym * symbols[index] * graph_lift
        c_skew = graph_lift.transpose() * p_skew * symbols[index] * graph_lift
        restricted_alternation[index] = (
            (c_sym + c_sym.transpose()).is_zero(),
            (c_skew + c_skew.transpose()).is_zero(),
        )

    return {
        "prime": prime,
        "h640_rank": int(h640.rank()),
        "observed_leakage": observed_leakage,
        "transverse_leakage": transverse_leakage,
        "transverse_join": transverse_join,
        "closure_ranks": closure_ranks,
        "ambient_hull_rank": int(basis.rank()),
        "transverse_pullback_ranks": transverse_pullback_ranks,
        "pairing_restriction_ranks": [int(k_sym_h.rank()), int(k_skew_h.rank())],
        "restricted_alternation": restricted_alternation,
        "sixteen_cell_encoding": {
            "one_form_to_one_form": 4,
            "zero_form_to_one_form": 4,
            "one_form_to_zero_form": 4,
            "zero_form_to_zero_form": 4,
        },
    }


print("\nB. COMPLETE FOURTEEN-DIRECTION CARRIER TEST")
packets = [packet(1009), packet(1013)]
for row in packets:
    prime = row["prime"]
    check("exact", f"GF({prime}): the observed three-axis hull remains exact H640",
          row["h640_rank"] == 640 and set(row["observed_leakage"].values()) == {0})
    check("exact", f"GF({prime}): every one of the ten unobserved directions leaks rank 128",
          len(row["transverse_leakage"]) == 10
          and set(row["transverse_leakage"].values()) == {128})
    check("exact", f"GF({prime}): each single unobserved direction enlarges H640 to rank 768",
          set(row["transverse_join"].values()) == {768})
    check("exact", f"GF({prime}): complete thirteen-generator closure reaches the full rank-1920 carrier",
          row["ambient_hull_rank"] == 1920 and row["closure_ranks"][0] == 640)
    check("observation", f"GF({prime}): ordinary pullback kills all ten transverse covectors",
          set(row["transverse_pullback_ranks"].values()) == {0})
    check("krein", f"GF({prime}): both action pairing horns restrict nondegenerately to H640",
          row["pairing_restriction_ranks"] == [640, 640])
    check("symplectic", f"GF({prime}): both restricted Grassmann coefficients remain alternating on all fourteen axes",
          all(pair == (True, True) for pair in row["restricted_alternation"].values()))
    check("planted", f"GF({prime}): PLANT alternating compression does not erase transverse ambient leakage",
          all(row["restricted_alternation"][index] == (True, True)
              and row["transverse_leakage"][index] == 128
              for index in row["transverse_leakage"]))

check("cross_prime", "both exact fields reproduce the complete rank fingerprint",
      all(packets[0][key] == packets[1][key] for key in (
          "h640_rank", "observed_leakage", "transverse_leakage",
          "transverse_join", "closure_ranks", "ambient_hull_rank",
          "transverse_pullback_ranks", "pairing_restriction_ranks",
          "restricted_alternation", "sixteen_cell_encoding",
      )))
check("source", "the 2-by-2 form-degree coefficient encodes all sixteen chiral source cells without cellwise retuning",
      packets[0]["sixteen_cell_encoding"] == {
          "one_form_to_one_form": 4,
          "zero_form_to_one_form": 4,
          "one_form_to_zero_form": 4,
          "zero_form_to_zero_form": 4,
      })


print("\nC. DISPOSITION FENCES")
check("variational", "ordinary pullback closes the observed principal graph but derives no vertical Higgs adapter", True)
check("variational", "a nonzero vertical adapter must solve the rank-128 graph/Riccati residual in each retained direction", True)
check("symplectic", "restricted alternation is eligibility for an action, not field-graph invariance or BV cohomology", True)
check("analytic", "full finite ambient closure is not a global domain spectrum index or generation count", True)
check("selection", "the result selects neither a vertical adapter nor a Higgs cell horn mirror or count", True)
check("accounting", "P1 P2 P3 residue quotients canon and public posture remain unchanged", True)

RESULT = {
    "run_id": "historical-investigation",
    "checks": dict(sorted(COUNTS.items())),
    "failures": FAILURES,
    "packets": packets,
    "source_return": "SOURCE_CONFIRMS_Y14_FOUR_FIELD_OPERATOR_OBSERVATION_PULLBACK_AND_VERTICAL_SCALAR_LIKE_RECONSTRUCTION_TARGET__SOURCE_CORRECTS_NONE__SOURCE_SILENT_ON_H640_GRAPH_AND_THE_VERTICAL_HIGGS_SOLDERING_ADAPTER_GRAPH_RICCATI_BV_KT_AND_GLOBAL_DOMAIN",
    "disposition": "H640_IS_EXACTLY_OBSERVED_THREE_AXIS__EVERY_TRANSVERSE_AXIS_LEAKS128_AND_ENLARGES_TO768__ALL_THIRTEEN_AXES_GENERATE_FULL1920__ORDINARY_PULLBACK_KILLS_TRANSVERSE_COVECTORS__NONZERO_VERTICAL_HIGGS_SURVIVAL_REQUIRES_AN_UNBUILT_ADAPTER",
    "next_gate": "CONSTRUCT_OR_KILL_A_SOURCE_ACTION_OWNED_VERTICAL_HIGGS_SOLDERING_ADAPTER_SATISFYING_THE_TEN_RANK128_GRAPH_RICCATI_RESIDUALS_AND_BOTH_BARRED_ADJOINT_HORNS__OTHERWISE_KEEP_UNRESTRICTED_D916_ON_FULL1920_AND_H640_ONLY_AFTER_ORDINARY_PULLBACK",
    "p1_p2_p3_used": False,
}

print("\nSELECTED K77 H640 AMBIENT/OBSERVED RICCATI-BOUNDARY RESULT")
print(json.dumps(RESULT, indent=2, sort_keys=True))
print("SUMMARY " + " + ".join(f"{count} {kind}" for kind, count in sorted(COUNTS.items())))
if FAILURES:
    raise SystemExit("FAILURES: " + "; ".join(FAILURES))
print("PASS: H640 is the exact observed three-axis graph but the complete ambient source operator generates rank 1920; a nonzero vertical Higgs adapter is now the explicit unresolved construction.")
