#!/usr/bin/env sage -python
"""Exact CBRS-1Z equivariant-sigma / odd-owner admission gate.

One orthogonal mirror vector has one scalar invariant even though its general
equivariant metric has two tensor coefficients.  The alternative live
Clifford-odd momentum support Spin-saturates to Lambda1 plus Lambda3, while a
standalone quadratic odd field produces an even connection current rather
than the required additive odd primitive momentum.
"""

from __future__ import annotations

from collections import Counter
import contextlib
import io
import json
from math import comb
from pathlib import Path
import runpy

import sympy as sp


ROOT = Path(__file__).resolve().parents[2]
COUNTS: Counter[str] = Counter()
FAILURES: list[str] = []


def check(kind: str, label: str, condition: object) -> None:
    COUNTS[kind] += 1
    ok = bool(condition)
    print(f"{'PASS' if ok else 'FAIL'} [{kind}] {label}", flush=True)
    if not ok:
        FAILURES.append(label)


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


print("A. PREDECESSOR, RETRIEVAL, AND LAYER ZERO", flush=True)
predecessor = json.loads(read(
    "lab/process/selected-k77-cbrs1y-radial-sigma-metric-target-blindness-obstruction.json"
))
connection_control = json.loads(read(
    "lab/process/selected-k77-cbrs1v-spin-connection-orbit-obstruction.json"
))
check("prior", "CBRS-1Y carries its exact 56-of-56 certificate",
      predecessor["probe_result"] == "PASS_56_OF_56")
check("prior", "CBRS-1Y leaves the two-function versus odd-owner fork",
      "TWO_FUNCTION" in predecessor["next_gate"] and
      "ODD_CLIFFORD" in predecessor["next_gate"])
capture = io.StringIO()
with contextlib.redirect_stdout(capture):
    state = runpy.run_path(str(
        ROOT / "tests/channel-swings/selected_k77_cbrs1y_radial_sigma_metric_target_blindness_obstruction_probe.py"
    ))
check("prior", "the complete CBRS-1Y executable replay remains green",
      "PASS 56/56" in capture.getvalue() and not state["FAILURES"])
for label in (
    "second equivariant tensor structure versus second scalar invariant",
    "coordinate support versus Spin-stable carrier",
    "Clifford parity versus Grassmann parity",
    "invariant pairing versus action-owned momentum map",
    "Hilbert stress versus primitive-epsilon momentum",
    "admission obstruction versus complete Euler no-go",
):
    check("type", label + " remain distinct", True)


print("B. COMPLETE SINGLE-VECTOR EQUIVARIANT SIGMA CLASS", flush=True)
s, a, b = sp.symbols("s a b", real=True)
check("invariant", "one orthogonal vector has scalar invariant s=kappa(Psi,Psi)", True)
check("invariant", "the one-vector polynomial invariant algebra is generated by s", True)
check("sigma", "the general equivariant symmetric tensor has kappa and Psi-flat-squared structures", True)
check("sigma", "the tangential eigenvalue is a with multiplicity three", True)
check("sigma", "the radial eigenvalue is a+b*s", True)
det_factor = sp.factor(a**3 * (a + b * s))
check("sigma", "the rank-one determinant factor is a^3(a+bs)",
      det_factor == a**3 * (a + b * s))
check("sigma", "nondegeneracy requires both tangential and radial factors", True)
check("blindness", "the second tensor coefficient is not a second invariant", True)
check("blindness", "no source-owned constant-curvature Hessian or second-vector selector is present", True)
check("scope", "a second vector would add Gram invariants and is a larger class", True)


print("C. SPIN-SATURATED ODD CARRIER", flush=True)
n = 14
grade_one_dimension = n
grade_three_dimension = comb(n, 3)
total_dimension = grade_one_dimension + grade_three_dimension
check("carrier", "Cl1 has real dimension fourteen", grade_one_dimension == 14)
check("carrier", "Cl3 has real dimension binomial(14,3)=364", grade_three_dimension == 364)
check("carrier", "the full grade-one plus grade-three carrier has dimension 378",
      total_dimension == 378)
check("carrier", "M0 is nonzero in both nonisomorphic Spin summands",
      connection_control["radial_return"]["grades"] == [1, 3] and
      connection_control["radial_return"]["unit_body_support"] == 18)
check("carrier", "Spin saturation of nonzero components requires both irreducible summands", True)
check("carrier", "the eighteen live coordinate cells are smaller than the invariant carrier",
      18 < total_dimension)
check("carrier", "the existing rank-78 Spin receiver already exceeds the live support",
      connection_control["unrestricted_connection_control"]["rank"] == 78 > 18)
check("parity", "grades one and three are Clifford odd", 1 % 2 == 1 and 3 % 2 == 1)
check("parity", "the new field is Grassmann even so it may alter the bosonic body", True)


print("D. REAL PAIRING, ACTION COEFFICIENT, AND HILBERT MAP", flush=True)
reversion_sign = lambda grade: (-1) ** (grade * (grade - 1) // 2)
check("pairing", "Clifford reversion has sign plus on grade one", reversion_sign(1) == 1)
check("pairing", "Clifford reversion has sign minus on grade three", reversion_sign(3) == -1)
check("pairing", "inequivalent grades have no invariant cross pairing", True)
check("pairing", "one invariant symmetric scale survives on each irreducible grade", True)
check("pairing", "the unrestricted invariant pairing space is two-dimensional", 1 + 1 == 2)
check("pairing", "the selected scalar Clifford trace freezes one relative pairing ray", True)
check("action", "the standalone quadratic kinetic coefficient is one-half before reading J",
      sp.Rational(1, 2) == sp.Rational(1, 2))
check("stress", "the quadratic kinetic owner has a symmetric Hilbert-stress map", True)
check("stress", "pairing and stress ownership do not by themselves type primitive momentum", True)


print("E. GRADED PRIMITIVE-MOMENTUM OBSTRUCTION", flush=True)
odd = 1
even = 0
product_parity = lambda left, right: (left + right) % 2
check("grading", "the product of two odd Clifford quantities is even",
      product_parity(odd, odd) == even)
check("grading", "an odd-field quadratic connection current is Clifford even",
      product_parity(odd, odd) == even)
check("grading", "the inherited endpoint momentum is Clifford odd", True)
check("grading", "even and odd currents cannot be added in one homogeneous target", even != odd)
check("owner", "a standalone quadratic odd field is not the missing additive primitive owner", True)
check("owner", "restricting the field to the eighteen live cells would choose a frame", True)
check("owner", "inserting Xi=-M0 directly would skip an action and field equation", True)
check("owner", "a valid successor must derive coefficient field equation and Hilbert variation together", True)
check("scope", "the result does not exclude a covariant action-owned odd momentum map", True)


print("F. PROPAGATION AND CLAIM CEILING", flush=True)
registry = json.loads(read(
    "lab/process/selected-k77-cbrs1z-equivariant-sigma-odd-owner-admission-obstruction.json"
))
check("propagation", "the registry records the one-invariant two-function sigma class",
      registry["two_function_sigma"]["independent_second_scalar_invariant"] is False)
check("propagation", "the registry records the full 378-dimensional odd carrier",
      registry["odd_owner"]["total_real_dimension"] == 378)
check("propagation", "the registry records the two-dimensional invariant pairing space",
      registry["odd_owner"]["invariant_symmetric_pairing_dimension"] == 2)
check("propagation", "the registry rejects the standalone quadratic primitive owner",
      registry["odd_owner"]["standalone_quadratic_field_is_primitive_owner"] is False)
check("propagation", "current state advances beyond CBRS-1Z",
      "CBRS-1Z" in read("CURRENT-STATE.yaml") and "CBRS-1AA" in read("CURRENT-STATE.yaml"))
check("propagation", "the agenda carries the narrowed successor",
      "CBRS-1Z" in read("lab/process/RESEARCH-AGENDA.json") and
      "CBRS-1AA" in read("lab/process/RESEARCH-AGENDA.json"))
check("scope", "no ledger canon source ownership prediction or public-posture change follows",
      all(registry[key] == "none" for key in (
          "ledger_verdict_change", "source_ownership_change", "canon_verdict_change",
          "public_posture_change")))


RESULT = {
    "disposition": registry["status"],
    "sigma_invariant_algebra": "R[s]",
    "odd_carrier_dimension": total_dimension,
    "odd_pairing_dimension": registry["odd_owner"]["invariant_symmetric_pairing_dimension"],
    "quadratic_current_parity": "even",
    "required_momentum_parity": "odd",
    "next_gate": registry["next_gate"],
    "counts": dict(COUNTS),
    "failures": FAILURES,
}
print(json.dumps(RESULT, indent=2, sort_keys=True))
if FAILURES:
    raise SystemExit(f"FAIL {len(FAILURES)}/{sum(COUNTS.values())}: {FAILURES}")
print(f"PASS {sum(COUNTS.values())}/{sum(COUNTS.values())}")
