#!/usr/bin/env sage
"""Independent Sage reconstruction of the selected K77 boundary bank."""


# This file was *autogenerated* from the file tests/channel-swings/selected_k77_action_boundary_coefficient_bank_independent.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_14 = Integer(14); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_176 = Integer(176); _sage_const_24 = Integer(24); _sage_const_8820818455167586715744550671819374592 = Integer(8820818455167586715744550671819374592); _sage_const_43046721 = Integer(43046721); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_352524857398662429170969678579148520580096 = Integer(352524857398662429170969678579148520580096); _sage_const_1688134559643 = Integer(1688134559643); _sage_const_9 = Integer(9)
from itertools import combinations

K = QuadraticField(-_sage_const_1 , names=('ii',)); (ii,) = K._first_ngens(1)
N = _sage_const_14 
ETA = (_sage_const_1 , -_sage_const_1 , -_sage_const_1 , -_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , -_sage_const_1 , -_sage_const_1 , -_sage_const_1 , -_sage_const_1 )
FULL = (_sage_const_1  << N) - _sage_const_1 
ZERO = K(_sage_const_0 )
FAIL = []
COUNTS = {"exact": _sage_const_0 , "planted": _sage_const_0 , "type": _sage_const_0 }


def check(kind, label, condition):
    COUNTS[kind] += _sage_const_1 
    ok = bool(condition)
    print(("PASS" if ok else "FAIL") + " [" + kind + "] " + label)
    if not ok:
        FAIL.append(label)


def inds(mask):
    return tuple(i for i in range(N) if mask & (_sage_const_1  << i))


def clean(element):
    return {mask: value for mask, value in element.items() if value != ZERO}


def eadd(*elements):
    out = {}
    for element in elements:
        for mask, value in element.items():
            out[mask] = out.get(mask, ZERO) + value
    return clean(out)


def escale(scalar, element):
    return clean({mask: K(scalar) * value for mask, value in element.items()})


def blade_product(left, right):
    inversions = sum(a > b for a in inds(left) for b in inds(right))
    sign = -_sage_const_1  if inversions % _sage_const_2  else _sage_const_1 
    for index in inds(left & right):
        sign *= ETA[index]
    return left ^ right, sign


def emul(left, right):
    out = {}
    for left_mask, left_value in left.items():
        for right_mask, right_value in right.items():
            mask, sign = blade_product(left_mask, right_mask)
            out[mask] = out.get(mask, ZERO) + sign * left_value * right_value
    return clean(out)


def blade(indices, coefficient=_sage_const_1 ):
    if isinstance(indices, (int, Integer)):
        indices = (int(indices),)
    return {sum(_sage_const_1  << i for i in indices): K(coefficient)}


def fclean(form):
    return {mask: clean(value) for mask, value in form.items() if clean(value)}


def fadd(*forms):
    out = {}
    for form in forms:
        for mask, value in form.items():
            out[mask] = eadd(out.get(mask, {}), value)
    return fclean(out)


def fscale(scalar, form):
    return fclean({mask: escale(scalar, value) for mask, value in form.items()})


def wedge_sign(left, right):
    if left & right:
        return _sage_const_0 
    return -_sage_const_1  if sum(a > b for a in inds(left) for b in inds(right)) % _sage_const_2  else _sage_const_1 


def coeff_product(left, right, channel):
    xy, yx = emul(left, right), emul(right, left)
    if channel == "comm":
        return eadd(xy, escale(-_sage_const_1 , yx))
    if channel == "symi":
        return escale(ii, eadd(xy, yx))
    raise ValueError(channel)


def wedge(left, right, channel=None):
    out = {}
    for lm, lv in left.items():
        for rm, rv in right.items():
            sign = wedge_sign(lm, rm)
            if not sign:
                continue
            value = emul(lv, rv) if channel is None else coeff_product(lv, rv, channel)
            out[lm | rm] = eadd(out.get(lm | rm, {}), escale(sign, value))
    return fclean(out)


def hodge(form):
    out = {}
    for mask, value in form.items():
        comp = FULL ^ mask
        norm = prod(ETA[i] for i in inds(mask))
        out[comp] = eadd(out.get(comp, {}), escale(wedge_sign(mask, comp) * norm, value))
    return fclean(out)


phi1 = {_sage_const_1  << i: blade(i) for i in range(N)}
phi2 = fscale(QQ(_sage_const_1 ) / _sage_const_2 , wedge(phi1, phi1))


def shiab(curvature):
    star = hodge(curvature)
    first = wedge(phi1, star, "comm")
    middle = hodge(wedge(phi2, star, "symi"))
    second = hodge(wedge(phi1, middle, "symi"))
    return fadd(first, fscale(-QQ(_sage_const_1 ) / _sage_const_2 , second))


def top(form):
    return form.get(FULL, {}).get(_sage_const_0 , ZERO)


def pairing(left, right):
    return top(wedge(left, right))


def direction(slot, coefficient):
    return {_sage_const_1  << slot: coefficient}


def packet(B, T):
    return fadd(wedge(B, B),
                fscale(QQ(_sage_const_1 ) / _sage_const_2 , fadd(wedge(B, T), wedge(T, B))),
                fscale(QQ(_sage_const_1 ) / _sage_const_3 , wedge(T, T)))


B = {}
T = {}
for i in range(N):
    B[_sage_const_1  << i] = blade(tuple(sorted(((i + _sage_const_1 ) % N, (i + _sage_const_2 ) % N))), i % _sage_const_3  + _sage_const_1 )
    T[_sage_const_1  << i] = blade((_sage_const_2  * i + _sage_const_2 ) % N, i % _sage_const_5  + _sage_const_1 )

P = packet(B, T)
SP = shiab(P)


def e_b(d):
    dP = fadd(wedge(d, B), wedge(B, d),
              fscale(QQ(_sage_const_1 ) / _sage_const_2 , fadd(wedge(d, T), wedge(T, d))))
    return pairing(T, shiab(dP))


def e_t(d):
    dP = fadd(fscale(QQ(_sage_const_1 ) / _sage_const_2 , fadd(wedge(B, d), wedge(d, B))),
              fscale(QQ(_sage_const_1 ) / _sage_const_3 , fadd(wedge(d, T), wedge(T, d))))
    mass = pairing(d, hodge(T)) + pairing(T, hodge(d))
    return pairing(d, SP) + pairing(T, shiab(dP)) + mass / _sage_const_2 


coefficients = [blade(i) for i in range(N)]
masks = [_sage_const_1  << i for i in range(N)]
for i, j in combinations(range(N), _sage_const_2 ):
    coefficients.append(blade((i, j)))
    masks.append((_sage_const_1  << i) | (_sage_const_1  << j))

bank_k = [[e_b(direction(a, c)) - e_t(direction(a, c)) for c in coefficients]
          for a in range(N)]
check("exact", "all reconstructed coefficients are real",
      all(value.imag() == _sage_const_0  for row in bank_k for value in row))
bank = matrix(QQ, [[QQ(value.real()) for value in row] for row in bank_k])
normal = bank[_sage_const_4 :_sage_const_14 , :]
supports = tuple(sum(value != _sage_const_0  for value in row) for row in bank.rows())
check("exact", "full action bank rank is fourteen", bank.rank() == _sage_const_14 )
check("exact", "normal action bank rank is ten", normal.rank() == _sage_const_10 )
check("exact", "normal support fingerprint agrees",
      supports[_sage_const_4 :] == (_sage_const_13 , _sage_const_14 , _sage_const_12 , _sage_const_16 , _sage_const_13 , _sage_const_16 , _sage_const_13 , _sage_const_12 , _sage_const_5 , _sage_const_8 ))
check("exact", "selected cubic and mass fingerprints agree",
      pairing(T, SP) == _sage_const_176  and pairing(T, hodge(T)) == -_sage_const_24 )

metric_signs = [blade_product(mask, mask)[_sage_const_1 ] for mask in masks]
metric = diagonal_matrix(QQ, metric_signs)
gram = normal * metric * normal.transpose()
check("exact", "raw inherited Gram is nondegenerate", gram.rank() == _sage_const_10 )
check("exact", "raw inherited Gram determinant agrees",
      gram.det() == QQ(_sage_const_8820818455167586715744550671819374592 ) / _sage_const_43046721 )

J = matrix(QQ, _sage_const_10 , _sage_const_4 , lambda i, j: QQ(((i + _sage_const_2 ) * (j + _sage_const_3 )) % _sage_const_11  - _sage_const_5 ) / _sage_const_7 )
O = block_matrix(QQ, [[identity_matrix(QQ, _sage_const_4 ), zero_matrix(QQ, _sage_const_4 , _sage_const_10 )],
                      [-J, identity_matrix(QQ, _sage_const_10 )]])
Oinv = block_matrix(QQ, [[identity_matrix(QQ, _sage_const_4 ), zero_matrix(QQ, _sage_const_4 , _sage_const_10 )],
                         [J, identity_matrix(QQ, _sage_const_10 )]])
observed = O * bank
observed_normal = observed[_sage_const_4 :_sage_const_14 , :]
observed_gram = observed_normal * metric * observed_normal.transpose()
check("exact", "observation equation dual has the stated inverse", Oinv * O == _sage_const_1 )
check("exact", "observation exactly recovers the full bank", Oinv * observed == bank)
check("exact", "observed normal bank remains rank ten", observed_normal.rank() == _sage_const_10 )
check("exact", "observed inherited Gram determinant agrees",
      observed_gram.det() == -QQ(_sage_const_352524857398662429170969678579148520580096 ) / _sage_const_1688134559643 )

check("type", "orientation reverses the covector and preserves its Gram",
      (-observed_normal) * metric * (-observed_normal).transpose() == observed_gram)
check("planted", "PLANT deleting one normal row drops rank", observed_normal[:_sage_const_9 , :].rank() == _sage_const_9 )
check("planted", "PLANT tangential pullback cannot retain ten normal rows", bank[:_sage_const_4 , :].rank() == _sage_const_4 )

print("RESULT=INDEPENDENT_SAGE_ACTION_BANK_AND_OBSERVATION_RECONSTRUCTION")
print("SUPPORTS=" + ",".join(str(value) for value in supports[_sage_const_4 :]))
print("COUNTS=" + ",".join(key + ":" + str(value) for key, value in sorted(COUNTS.items())))
print("PASS " + str(sum(COUNTS.values()) - len(FAIL)) + "/" + str(sum(COUNTS.values())))
if FAIL:
    raise SystemExit("failures: " + "; ".join(FAIL))

