"""
AS-A2b: the no-go twin, finished as a BOUNDED no-go (A2's original A2-doc build hit the
64k output cap and produced no result). The honest outcome is NOT the strong no-go A2 set out
to prove -- A1 and A4 already exhibit native potentials that DO select the mirror-hiding vacuum,
so "the native invariant ring is blind to the mirror axis" is FALSE. What is TRUE, and what this
script proves, is the bounded no-go that exactly complements A1/A3/A4:

  THEOREM (bounded no-go, kinematic/potential scope). On the P-even condensate space of the
  (9,5) triplet sector:
   (1) The invariance group of the native invariant ring -- generated by t_n = tr(Phi^n) and
       q_n = Str(Phi^n) = tr(P Phi^n) -- is Inv = { K-unitary S : [S,P]=0 } = U(96) x U(96)
       (block-diagonal on the Krein halves). Inv FIXES the Q5 axis (Q5 = -P). So the STRONG
       no-go ("the ring cannot see the mirror axis") is REFUTED: A1's scan is live.
   (2) chi (the Clifford volume, A3's native intertwiner: unitary involution, commutes with all
       91 so(9,5) gauge generators, chi P chi = -P, chi Q5 chi = -Q5) is a GU-native symmetry
       that is NOT in Inv. Under chi-conjugation the invariants split by parity: t_n are
       chi-EVEN, q_n are chi-ODD. The mirror-hiding order parameter q2 = tr(P Phi^2) is chi-odd.
   (3) Therefore every chi-SYMMETRIC native potential (even in the q's) has a chi-symmetric
       vacuum: q2 = 0 (mirror-blind) or a degenerate +/- q2 pair (spontaneous, no preferred
       half). Selecting a DEFINITE mirror-hiding orientation requires a chi-ODD native coupling,
       whose SIGN chi flips -- so it is fixed by no native invariant. The alignment import is
       exactly ONE BIT: the sign of the flip-odd coupling. (This is A1's sign(lq + l4/192) and
       A4's sign of tr(Q5 Phi^2), seen from the symmetry side.)

Verdict: STRONG no-go REFUTED, WEAK (bounded) no-go PROVEN. Consistent with A1 (phase), A3
(orientation discharged), A4 (saddle under chi-symmetric, minimum under the flip-odd sign).
Carrier recipe verbatim from A1/V8; chi = A3's C. Deterministic (seed 20260708).
"""
import numpy as np

np.random.seed(20260708)
N, DIM = 14, 128
TOL = 1e-9
nrm = np.linalg.norm
comm = lambda A, B: A @ B - B @ A
acomm = lambda A, B: A @ B + B @ A
FAIL = []
def check(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name} {detail}")
    if not ok:
        FAIL.append(name)

def jw(n):
    I = np.eye(2, dtype=complex)
    s1 = np.array([[0, 1], [1, 0]], dtype=complex)
    s2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
    s3 = np.array([[1, 0], [0, -1]], dtype=complex)
    G = []
    for k in range(n):
        L, R = [s3] * k, [I] * (n - 1 - k)
        for mid in (s1, s2):
            o = np.array([[1 + 0j]])
            for m in L + [mid] + R:
                o = np.kron(o, m)
            G.append(o)
    return G

base = jw(7)
I128, I14 = np.eye(DIM, dtype=complex), np.eye(N, dtype=complex)

def build(timelike):
    e = [(1j * base[a] if a in timelike else base[a]) for a in range(14)]
    spacelike = [a for a in range(14) if a not in timelike]
    def sgen(i, j): return 0.25 * (e[i] @ e[j] - e[j] @ e[i])
    def lvec(i, j):
        M = np.zeros((N, N), dtype=complex); M[i, j] = 1; M[j, i] = -1; return M
    def gen(i, j): return np.kron(I14, sgen(i, j)) + np.kron(lvec(i, j), I128)
    Gam = np.hstack(e)
    rankG = np.linalg.matrix_rank(Gam)
    Pi = np.eye(N * DIM, dtype=complex) - Gam.conj().T @ np.linalg.inv(Gam @ Gam.conj().T) @ Gam
    w, Vv = np.linalg.eigh(Pi)
    Wk = Vv[:, w > 0.5]
    SDp = [(0, 1, 2, 3), (0, 2, 3, 1), (0, 3, 1, 2)]
    J3full = [gen(a, b) + gen(c, d) for (a, b, c, d) in SDp]
    Cas = -(J3full[0] @ J3full[0] + J3full[1] @ J3full[1] + J3full[2] @ J3full[2])
    CasK = Wk.conj().T @ Cas @ Wk; CasK = 0.5 * (CasK + CasK.conj().T)
    ev, U = np.linalg.eigh(CasK)
    top = max(round(x.real, 3) for x in ev)
    Wt = Wk @ U[:, np.abs(ev - top) < 1e-3]
    bS = I128.copy()
    for s in spacelike:
        bS = bS @ e[s]
    if nrm(bS.conj().T + bS) < TOL:
        bS = 1j * bS
    bS = bS / np.sqrt(abs((bS @ bS)[0, 0].real))
    etaV = np.diag([(-1.0 if a in timelike else 1.0) for a in range(14)]).astype(complex)
    Kful = np.kron(etaV, bS)
    om = I128.copy()
    for a in range(14):
        om = om @ e[a]
    om2 = (np.trace(om @ om) / DIM).real
    Cful = np.kron(I14, om if om2 > 0 else (-1j) * om)
    Rc = lambda M: Wt.conj().T @ M @ Wt
    K = Rc(Kful); K = 0.5 * (K + K.conj().T)
    C = Rc(Cful)
    kev, kU = np.linalg.eigh(K)
    P = (kU * np.sign(kev)) @ kU.conj().T; P = 0.5 * (P + P.conj().T)
    Q5m = I128.copy()
    for a in [9, 10, 11, 12, 13]:
        Q5m = Q5m @ (1j * base[a]) if a in timelike else Q5m @ base[a]
    Q5 = Rc(np.kron(I14, Q5m))
    gauge = [Rc(gen(i, j)) for (i, j) in [(0, 1), (2, 3), (4, 5), (0, 9), (4, 9), (9, 10),
                                          (11, 12), (1, 13), (5, 11), (0, 4)]]
    return dict(K=K, P=P, C=C, Q5=Q5, kev=kev, kU=kU, gauge=gauge, rankG=rankG, kerdim=Wk.shape[1])

print("=" * 100)
print("AS-A2b: no-go twin, finished as a BOUNDED no-go (symmetry of the native invariant ring)")
print("=" * 100)

print("\n[0] ANCHORS (9,5), timelike={4..8}")
D = build({4, 5, 6, 7, 8})
K, P, C, Q5, kev, kU = D["K"], D["P"], D["C"], D["Q5"], D["kev"], D["kU"]
tdim = 192
npl, nmi = int((kev > TOL).sum()), int((kev < -TOL).sum())
check("triplet Krein signature (+96,-96,0)", (npl, nmi) == (96, 96), f"(+{npl},-{nmi})")
check("P = sign(K) = K|_W", nrm(P - K) < 1e-9, f"{nrm(P-K):.1e}")
check("V8 identity Q5 = -P", nrm(Q5 + P) < 1e-9, f"{nrm(Q5+P):.1e}")

# helpers on random P-even Phi (block-diagonal on Krein halves)
Ep, Em = kU[:, kev > 0], kU[:, kev < 0]
def rand_Peven():
    A = np.random.randn(96, 96) + 1j * np.random.randn(96, 96); A = A + A.conj().T
    B = np.random.randn(96, 96) + 1j * np.random.randn(96, 96); B = B + B.conj().T
    return Ep @ A @ Ep.conj().T + Em @ B @ Em.conj().T
def t_n(Phi, n): return np.trace(np.linalg.matrix_power(Phi, n)).real
def q_n(Phi, n): return np.trace(P @ np.linalg.matrix_power(Phi, n)).real

# ---------------------------------------------------------------- [1] invariance group Inv
print("\n[1] INVARIANCE GROUP of the native invariant ring {t_n, q_n = Str_n}:")
print("    Inv = { K-unitary S with [S,P]=0 } = U(96) x U(96) (block-diagonal on the K-halves).")
worst_t, worst_q, worst_comm, worst_Ku = 0, 0, 0, 0
for _ in range(30):
    Sp = np.linalg.qr(np.random.randn(96, 96) + 1j * np.random.randn(96, 96))[0]
    Sm = np.linalg.qr(np.random.randn(96, 96) + 1j * np.random.randn(96, 96))[0]
    S = Ep @ Sp @ Ep.conj().T + Em @ Sm @ Em.conj().T
    worst_comm = max(worst_comm, nrm(comm(S, P)))
    worst_Ku = max(worst_Ku, nrm(S.conj().T @ K @ S - K))
    Phi = rand_Peven(); Phi2 = S @ Phi @ S.conj().T
    for n in (2, 3, 4):
        worst_t = max(worst_t, abs(t_n(Phi2, n) - t_n(Phi, n)) / (abs(t_n(Phi, n)) + 1))
        worst_q = max(worst_q, abs(q_n(Phi2, n) - q_n(Phi, n)) / (abs(q_n(Phi, n)) + 1))
check("Inv elements are K-unitary and commute with P", worst_comm < 1e-9 and worst_Ku < 1e-9,
      f"max||[S,P]||={worst_comm:.1e}, max||S^K S - K||={worst_Ku:.1e}")
check("Inv preserves ALL native invariants t_n and q_n (n=2,3,4)", worst_t < 1e-10 and worst_q < 1e-10,
      f"max rel drift t={worst_t:.1e}, q={worst_q:.1e}")
# Inv fixes the Q5 axis
worst_fix = 0
for _ in range(30):
    Sp = np.linalg.qr(np.random.randn(96, 96) + 1j * np.random.randn(96, 96))[0]
    Sm = np.linalg.qr(np.random.randn(96, 96) + 1j * np.random.randn(96, 96))[0]
    S = Ep @ Sp @ Ep.conj().T + Em @ Sm @ Em.conj().T
    worst_fix = max(worst_fix, nrm(S @ Q5 @ S.conj().T - Q5))
check("Inv FIXES the Q5 axis (S Q5 S^-1 = Q5) => STRONG no-go REFUTED, A1 scan is live",
      worst_fix < 1e-9, f"max||S Q5 S^-1 - Q5|| = {worst_fix:.1e}")

# ---------------------------------------------------------------- [2] the native symmetry chi not in Inv
print("\n[2] chi (A3's native intertwiner = Clifford volume C): a native symmetry NOT in Inv.")
check("chi is a unitary involution on W (chi^2 = I, tr chi = 0)",
      nrm(C @ C - np.eye(tdim)) < 1e-8 and abs(np.trace(C)) < 1e-8,
      f"||chi^2-I||={nrm(C@C-np.eye(tdim)):.1e}, |tr|={abs(np.trace(C)):.1e}")
worst_g = max(nrm(comm(C, g)) for g in D["gauge"])
check("chi commutes with the sampled so(9,5) gauge generators (native)", worst_g < 1e-8,
      f"max||[chi, gauge]|| over 10 generators = {worst_g:.1e}")
check("chi P chi = -P and chi Q5 chi = -Q5 (flips orientation)",
      nrm(C @ P @ C + P) < 1e-8 and nrm(C @ Q5 @ C + Q5) < 1e-8,
      f"||chiPchi+P||={nrm(C@P@C+P):.1e}, ||chiQ5chi+Q5||={nrm(C@Q5@C+Q5):.1e}")
check("chi is NOT in Inv (it is norm-reversing: chi^K K chi != K, and {chi,P}=0 not [.,.]=0)",
      nrm(acomm(C, P)) < 1e-8 and nrm(comm(C, P)) > 1.0,
      f"||{{chi,P}}||={nrm(acomm(C,P)):.1e} (=0), ||[chi,P]||={nrm(comm(C,P)):.1f} (>0)")

# ---------------------------------------------------------------- [3] chi-parity of the invariants
print("\n[3] chi-PARITY of the native invariants (chi-conjugation Phi -> chi Phi chi):")
worst_even, worst_odd = 0, 0
for _ in range(20):
    Phi = rand_Peven(); Phic = C @ Phi @ C
    for n in (2, 3, 4):
        worst_even = max(worst_even, abs(t_n(Phic, n) - t_n(Phi, n)) / (abs(t_n(Phi, n)) + 1))
        worst_odd = max(worst_odd, abs(q_n(Phic, n) + q_n(Phi, n)) / (abs(q_n(Phi, n)) + 1))
check("t_n are chi-EVEN (tr invariant under conjugation)", worst_even < 1e-10, f"max drift {worst_even:.1e}")
check("q_n = Str_n are chi-ODD (q_n -> -q_n): mirror axis is a chi-odd order parameter",
      worst_odd < 1e-10, f"max||q_n(chi.Phi)+q_n(Phi)||_rel = {worst_odd:.1e}")

# ---------------------------------------------------------------- [4] the bounded no-go (reduced model)
print("\n[4] BOUNDED NO-GO on the A1 reduced 2-scalar model (u=tr A^2/96, v=tr B^2/96 >= 0):")
print("    q2 = 96(u-v) is chi-odd; chi acts by the block swap (u,v)->(v,u).")
def Vred(u, v, l0, lq, l4, hodd=0.0, mh=96):
    # native chi-EVEN quartic family + one chi-ODD coupling hodd*(q2*t2)=hodd*96^2*(u^2-v^2)
    return (-mh*(u+v) + l0*mh**2*(u+v)**2 + lq*mh**2*(u-v)**2 + l4*mh*(u**2+v**2)
            + hodd*mh**2*(u**2 - v**2))
def argmin(l0, lq, l4, hodd, mh=96, ng=401):
    a = l0 + lq + l4/mh
    umax = 1.0 / (2*mh*max(a, 1e-3)) * 4 + 0.05
    gs = np.linspace(0, umax, ng); U, Vv = np.meshgrid(gs, gs)
    Z = Vred(U, Vv, l0, lq, l4, hodd, mh)
    k = np.unravel_index(np.argmin(Z), Z.shape)
    return gs[k[1]], gs[k[0]]
# chi-symmetric (hodd=0), corner-phase couplings: vacuum is a DEGENERATE +/- pair (no preferred half)
l0, l4 = 1.0, 1.0; lq = -l4/192 - 0.02   # corner phase
us, vs = argmin(l0, lq, l4, 0.0)
us_flip, vs_flip = vs, us   # chi image
check("chi-symmetric native potential (hodd=0): vacuum is chi-symmetric -- the (u,0) and (0,v) "
      "corners are DEGENERATE, so which half gaps is NOT selected",
      abs(Vred(us, vs, l0, lq, l4, 0.0) - Vred(vs, us, l0, lq, l4, 0.0)) < 1e-9,
      f"V(u*,v*)=V(v*,u*) to {abs(Vred(us,vs,l0,lq,l4,0.0)-Vred(vs,us,l0,lq,l4,0.0)):.1e}; (u*,v*)=({us:.3f},{vs:.3f})")
# flip-odd coupling selects the orientation; its SIGN sets which half
usN, vsN = argmin(l0, lq, l4, -0.01)   # hodd<0
usP, vsP = argmin(l0, lq, l4, +0.01)   # hodd>0
sel_neg = "u>v (B half gapped)" if usN > vsN else "v>u (A half gapped)"
sel_pos = "u>v (B half gapped)" if usP > vsP else "v>u (A half gapped)"
check("flip-odd coupling SELECTS the orientation, and its SIGN sets which half (chi flips it)",
      (usN > vsN) != (usP > vsP), f"hodd<0 -> {sel_neg} ; hodd>0 -> {sel_pos}")
check("chi flips the flip-odd term (hodd -> -hodd under (u,v)->(v,u)): the sign is NOT native data",
      abs(Vred(0.01, 0.0, l0, lq, l4, 0.03) - Vred(0.0, 0.01, l0, lq, l4, -0.03)) < 1e-12,
      "V(u,0;+h) = V(0,u;-h) exactly")

# ---------------------------------------------------------------- [5] controls with power
print("\n[5] CONTROLS (must be able to fail):")
# (a) an IMPORTED operator that does NOT commute with the gauge algebra: it can carry an
#     orientation the ring cannot -- showing nativeness is exactly what forbids a fixed sign.
Dimp = rand_Peven()  # a generic P-even operator; not built from the invariant ring
worst_import_comm = max(nrm(comm(Dimp, g)) for g in D["gauge"])
check("  control: a generic (imported) P-even operator does NOT commute with the gauge algebra",
      worst_import_comm > 1e-2, f"max||[D_import, gauge]|| = {worst_import_comm:.2e} (>> 0: not native)")
# (b) scrambled 'invariant': tr(R Phi^2) for random non-scalar R is NOT Inv-invariant
R = rand_Peven()
Phi = rand_Peven()
Sp = np.linalg.qr(np.random.randn(96, 96) + 1j * np.random.randn(96, 96))[0]
Sm = np.linalg.qr(np.random.randn(96, 96) + 1j * np.random.randn(96, 96))[0]
S = Ep @ Sp @ Ep.conj().T + Em @ Sm @ Em.conj().T
lhs = np.trace(R @ (S @ Phi @ S.conj().T) @ (S @ Phi @ S.conj().T)).real
rhs = np.trace(R @ Phi @ Phi).real
check("  control: a scrambled weight tr(R Phi^2) (R not in {I,P}) is NOT Inv-invariant",
      abs(lhs - rhs) / (abs(rhs) + 1) > 1e-3, f"rel change under Inv = {abs(lhs-rhs)/(abs(rhs)+1):.2e}")

print("\n" + "=" * 100)
if FAIL:
    print(f"FAILURES: {FAIL}")
    raise SystemExit(1)
print("A2 BOUNDED NO-GO PROVEN (kinematic/potential scope):")
print("  - STRONG no-go REFUTED: Inv = U(96)xU(96) fixes the Q5 axis, so native potentials DO")
print("    see the mirror direction (A1's scan is live);")
print("  - WEAK no-go PROVEN: t_n chi-even, q_n chi-odd; every chi-symmetric native potential has")
print("    a chi-symmetric (degenerate/blind) vacuum, so it cannot SELECT which half gaps;")
print("  - the selecting datum is a chi-ODD native coupling whose sign chi flips => exactly ONE")
print("    non-native BIT (= A1's sign(lq+l4/192) = A4's sign of tr(Q5 Phi^2)).")
print("  This completes the alignment swing consistent with A1/A3/A4: the mirror-hiding vacuum is")
print("  native up to a single unfixed orientation-odd coupling sign, a source-action question.")
print("=" * 100)
