"""
VG-V3 (T1' executable form): is the conformal chain GU-NATIVE (canonical J) or merely
GU-compatible (family of J's)?

Arena: the 10-dim metric fiber V10 = Sym^2(R^4)* (symmetric 2-tensors h_{mu nu}) with
eta = diag(-1,1,1,1), the O(3,1)-invariant Frobenius form B(h,k) = tr(eta h eta k), and the
trace-REVERSED metric G(h,k) = B(h,k) - (1/2) tr_eta(h) tr_eta(k).

Sections:
  0  ANCHORS: B has signature (7,3); G has signature (6,4)  [independently re-derives the
     transcript's (7,3)->(6,4) claim at 00:43:47]; base (3,1) + fiber (6,4) = (9,5) assembly
     remark (matches the repo's Cl(9,5) carrier convention -- measured consistency, not import).
  A  THEOREM CHECK: an orthogonal complex structure J (J^2=-I, J^T g J = g) on R^{p,q} exists
     iff p AND q are both even. Constructive on (6,4) (explicit J0, residuals ~1e-13, Hermitian
     form of measured signature (3,2)); numerical falsification scan on (7,3) (40 random starts,
     residual floor bounded away from 0) with the (6,4) scan as the required success CONTROL.
  B  COMMUTANT SCAN (cumulative): which orthogonal J's commute with GU's own fiber data?
       step 0  no constraint            -> FAMILY, tangent dim 20 = dim O(6,4)/U(3,2)
       step 1  + trace/scale direction  -> EMPTY (exact 1-dim + 9-dim parity argument; floor)
       step 2  + base-vs-vertical split -> N/A at the 10-dim fiber level (lives on T(Y14))
       step 3  + SO(3,1) isotropy       -> EMPTY (commutant dim 2 = {a P9 + b P1}; exact floor
                                            ||J^2+I||_F^2 >= 10, attained at a=b=0)
       step 4  + SU(2)+ family action   -> acts on the REAL Lorentzian fiber only through its
                                            SO(3) rotation image (Hodge-* on Lambda^2(R^{1,3})
                                            squares to -I => SD/ASD split is complex);
                                            standalone commutant dim 6, still EMPTY (floor >= 8)
     CONTROLS: rank-2 G-definite projector (J exists, scan finds it ~1e-13); so(2) generated by
     J0 itself (scan finds J0). The empty results are therefore not optimizer theater.
  C  THE CHAIN (contingent / informational, since the scan is NOT canonical): centralizer of J0
     in so(6,4) has dim 25 and Hermitian signature (3,2)  => u(3,2); stabilizer of a G-positive
     complex line has dim 17 = dim(u(1) + u(2,2)); su(2,2) and so(4,2) both have dim 15, rank 3,
     Killing signature (8,7)  => the exceptional isomorphism checks at matrix level.
  D  VERDICT per the pre-registered downgrade rule.

TARGET-IMPORT GUARD: no 3, 8, 24, chi(K3), Ahat, rank_H, ind_H assumed, inserted, or divided by.
The "3" in u(3,2) is MEASURED (half of the measured 6 positive directions / the measured (3,2)
Hermitian signature); no count statement of any kind is made.

Run: python tests/big-swing/vg_v3_j_commutant_conformal_native.py   (exit 0)
"""
import sys
import numpy as np
from scipy.optimize import minimize

np.set_printoptions(linewidth=140, suppress=True)
rng_global = np.random.default_rng(20260706)

TOL_EQ = 1e-9        # equality residual tolerance
TOL_NULL = 1e-9      # singular-value threshold for null spaces (matrices are O(1))

FAIL = []
def check(name, ok, detail=""):
    tag = "PASS" if ok else "FAIL"
    print(f"  [{tag}] {name} {detail}")
    if not ok:
        FAIL.append(name)

# ----------------------------------------------------------------------------------------------
# SECTION 0 -- the fiber, the two forms, the ANCHORS
# ----------------------------------------------------------------------------------------------
print("=" * 98)
print("SECTION 0: V10 = Sym^2(R^4), eta = diag(-1,1,1,1); Frobenius form B and trace-reversed G")
print("=" * 98)

eta = np.diag([-1.0, 1.0, 1.0, 1.0])
PAIRS = [(0, 0), (1, 1), (2, 2), (3, 3), (0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

def basis_mat(a):
    i, j = PAIRS[a]
    E = np.zeros((4, 4))
    E[i, j] += 1.0
    E[j, i] += 1.0 if i != j else 0.0
    return E

S = [basis_mat(a) for a in range(10)]

def coords(H):
    """coordinates of a symmetric 4x4 matrix in the S basis"""
    return np.array([H[PAIRS[a]] for a in range(10)])

def tr_eta(H):
    return np.trace(eta @ H)      # eta^{-1} = eta

Bgram = np.array([[np.trace(eta @ S[a] @ eta @ S[b]) for b in range(10)] for a in range(10)])
Ggram = Bgram - 0.5 * np.outer([tr_eta(S[a]) for a in range(10)],
                               [tr_eta(S[b]) for b in range(10)])

def signature(M, tol=1e-9):
    w = np.linalg.eigvalsh(0.5 * (M + M.T))
    return int(np.sum(w > tol)), int(np.sum(w < -tol)), int(np.sum(np.abs(w) <= tol))

sigB, sigG = signature(Bgram), signature(Ggram)
print(f"  Frobenius form B on V10:        signature (+{sigB[0]}, -{sigB[1]}, 0:{sigB[2]})")
print(f"  trace-REVERSED metric G on V10: signature (+{sigG[0]}, -{sigG[1]}, 0:{sigG[2]})   <-- ANCHOR")
check("ANCHOR: B signature is (7,3)", sigB == (7, 3, 0), str(sigB))
check("ANCHOR: G signature is (6,4)  [transcript 00:43:47 re-derived]", sigG == (6, 4, 0), str(sigG))

v_eta = coords(eta)
Geta = v_eta @ Ggram @ v_eta
Beta_ = v_eta @ Bgram @ v_eta
print(f"  trace/scale direction (h = eta): B(eta,eta) = {Beta_:+.6f}, G(eta,eta) = {Geta:+.6f}")
check("trace direction is B-POSITIVE and G-NEGATIVE (trace-reversal flips exactly this direction)",
      Beta_ > 0 and Geta < 0, f"B={Beta_:+.3f}, G={Geta:+.3f}")

# trace-reversal operator T: h -> h - (1/2) eta tr_eta(h); eigenvalues +1 (traceless, x9), -1 (trace, x1)
Tmat = np.array([coords(S[a] - 0.5 * eta * tr_eta(S[a])) for a in range(10)]).T
wT = np.sort(np.linalg.eigvalsh(0.5 * (Tmat + Tmat.T)))
check("trace-reversal operator T has eigenvalues (-1 x1, +1 x9)",
      abs(wT[0] + 1) < TOL_EQ and np.allclose(wT[1:], 1.0, atol=TOL_EQ), str(np.round(wT, 6)))

# so(3,1) generators (vector rep: M^T eta + eta M = 0) and the induced action on V10
def so31_gens():
    gens = []
    for (i, j) in [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]:
        A = np.zeros((4, 4)); A[i, j], A[j, i] = 1.0, -1.0
        gens.append(eta @ A)
    return gens

M6 = so31_gens()
for M in M6:
    assert np.linalg.norm(M.T @ eta + eta @ M) < 1e-12

def rho(M):
    """induced action on lower-index symmetric tensors: h -> -(M^T h + h M), as a 10x10 matrix"""
    return np.array([coords(-(M.T @ S[a] + S[a] @ M)) for a in range(10)]).T

L6 = [rho(M) for M in M6]
resB = max(np.linalg.norm(L.T @ Bgram + Bgram @ L) for L in L6)
resG = max(np.linalg.norm(L.T @ Ggram + Ggram @ L) for L in L6)
print(f"  SO(3,1)-invariance residuals: B {resB:.1e}, G {resG:.1e}")
check("B and G are so(3,1)-invariant", resB < TOL_EQ and resG < TOL_EQ)

p_base, q_base = 3, 1     # eta = diag(-1,1,1,1): 3 plus, 1 minus
print(f"  assembly remark: base ({p_base},{q_base}) + fiber ({sigG[0]},{sigG[1]}) "
      f"= ({p_base + sigG[0]},{q_base + sigG[1]})  -- matches the Cl(9,5) carrier convention "
      f"(measured consistency)")
check("base (3,1) + fiber (6,4) = (9,5)", (p_base + sigG[0], q_base + sigG[1]) == (9, 5))
print("  NOTE: carrier anchors (triplet (+96,-96,0); beta_S residual; rank(Gamma)=128) are NOT used:")
print("        this route lives entirely on the 10-dim fiber; its required anchor is the (6,4) print above.")

# ----------------------------------------------------------------------------------------------
# SECTION A -- theorem check: orthogonal complex structure on R^{p,q} iff p, q both even
# ----------------------------------------------------------------------------------------------
print("=" * 98)
print("SECTION A: theorem check -- orthogonal J on R^{p,q} exists iff p and q are both even")
print("=" * 98)

I10 = np.eye(10)
j2 = np.array([[0.0, -1.0], [1.0, 0.0]])

# --- constructive on (6,4): congruence C with C^T Ggram C = diag(+1 x6, -1 x4), then block J
wG, QG = np.linalg.eigh(0.5 * (Ggram + Ggram.T))
order = np.argsort(-wG)                      # plus directions first
wG, QG = wG[order], QG[:, order]
C = QG / np.sqrt(np.abs(wG))
g0 = np.diag([1.0] * 6 + [-1.0] * 4)
assert np.linalg.norm(C.T @ Ggram @ C - g0) < 1e-10
J0_std = np.zeros((10, 10))
for k in range(3):
    J0_std[2 * k:2 * k + 2, 2 * k:2 * k + 2] = j2          # 3 complex planes in the +6 block
for k in range(2):
    J0_std[6 + 2 * k:8 + 2 * k, 6 + 2 * k:8 + 2 * k] = j2  # 2 complex planes in the -4 block
J0 = C @ J0_std @ np.linalg.inv(C)          # back to the S-coordinate basis
r1 = np.linalg.norm(J0 @ J0 + I10)
r2 = np.linalg.norm(J0.T @ Ggram @ J0 - Ggram)
print(f"  constructive J0 on (6,4): ||J0^2 + I|| = {r1:.2e}, ||J0^T G J0 - G|| = {r2:.2e}")
check("(6,4) admits an orthogonal complex structure (exhibited)", r1 < 1e-10 and r2 < 1e-10)

# Hermitian form H(x,y) = G(x,y) + i G(J x, y) on the complex 5-dim space (R^10, J): this is the
# proof mechanism of the theorem -- H is Hermitian, g = Re H, and signature (r,s) over C doubles to
# (2r,2s) over R, forcing p and q even. Compute H on a GENERICALLY built complex basis.
def hermitian_signature(J, G, seed=5):
    rng = np.random.default_rng(seed)
    Rb = []                                    # real basis w1, Jw1, w2, Jw2, ...
    while len(Rb) < 10:
        v = rng.normal(size=10)
        if Rb:
            Q, _ = np.linalg.qr(np.array(Rb).T)
            v = v - Q @ (Q.T @ v)
        if np.linalg.norm(v) < 1e-6:
            continue
        v = v / np.linalg.norm(v)
        Rb += [v, J @ v]
    W = [Rb[2 * k] for k in range(5)]
    H5 = np.array([[wk @ G @ wl + 1j * ((J @ wk) @ G @ wl) for wl in W] for wk in W])
    herm_res = np.linalg.norm(H5 - H5.conj().T)
    wH = np.linalg.eigvalsh(0.5 * (H5 + H5.conj().T))
    return (int(np.sum(wH > 1e-9)), int(np.sum(wH < -1e-9))), herm_res

(rH, sH), hres = hermitian_signature(J0, Ggram)
print(f"  Hermitian form of (G, J0) on C^5 (generic basis): Hermiticity residual {hres:.1e}, "
      f"signature ({rH},{sH}) => real ({2*rH},{2*sH})")
check("H is Hermitian at matrix level", hres < 1e-10)
check("measured Hermitian signature (3,2) doubles to the real (6,4)", (rH, sH) == (3, 2))

# --- falsification scan machinery
def scan(g, Bas=None, nstart=30, seed=1, label=""):
    """minimize ||J^2+I||_F^2 + ||J^T g J - g||_F^2 over J in span(Bas) (default: all of gl(10));
    returns (best value, best J)."""
    rng = np.random.default_rng(seed)
    if Bas is None:
        Bas = [np.zeros((10, 10)) for _ in range(100)]
        for k in range(100):
            Bas[k].flat[k] = 1.0
    Barr = np.array(Bas)
    Bflat = Barr.reshape(len(Bas), -1)
    def fg(t):
        J = np.tensordot(t, Barr, axes=1)
        F = J @ J + I10
        Rm = J.T @ g @ J - g
        val = float((F * F).sum() + (Rm * Rm).sum())
        grJ = 2.0 * (J.T @ F + F @ J.T) + 4.0 * (g @ J @ Rm)
        return val, Bflat @ grJ.ravel()
    best, bestJ = np.inf, None
    for _ in range(nstart):
        t0 = rng.normal(size=len(Bas))
        res = minimize(fg, t0, jac=True, method="L-BFGS-B",
                       options={"maxiter": 8000, "ftol": 1e-18, "gtol": 1e-13})
        if res.fun < best:
            best, bestJ = res.fun, np.tensordot(res.x, Barr, axes=1)
    print(f"  scan[{label}]: min residual over {nstart} starts = {best:.3e}")
    return best, bestJ

# gradient sanity check (so the scans are trustworthy)
_t = rng_global.normal(size=100)
_g73 = np.diag([1.0] * 7 + [-1.0] * 3)
_Bas = [np.zeros((10, 10)) for _ in range(100)]
for k in range(100):
    _Bas[k].flat[k] = 1.0
_Barr = np.array(_Bas); _Bflat = _Barr.reshape(100, -1)
def _fg(t):
    J = np.tensordot(t, _Barr, axes=1); F = J @ J + I10; Rm = J.T @ _g73 @ J - _g73
    return float((F * F).sum() + (Rm * Rm).sum()), _Bflat @ (2 * (J.T @ F + F @ J.T) + 4 * (_g73 @ J @ Rm)).ravel()
_v0, _gr = _fg(_t)
_num = np.array([( _fg(_t + 1e-6 * np.eye(100)[k])[0] - _fg(_t - 1e-6 * np.eye(100)[k])[0]) / 2e-6 for k in range(0, 100, 13)])
check("analytic gradient matches finite differences",
      np.max(np.abs(_num - _gr[::13])) / max(1.0, np.max(np.abs(_num))) < 1e-5)

g64 = np.diag([1.0] * 6 + [-1.0] * 4)
best73, _ = scan(_g73, nstart=40, seed=11, label="(7,3), unconstrained, 40 starts")
best64, J64 = scan(g64, nstart=10, seed=12, label="(6,4) CONTROL")
check("(7,3): every start stalls at a residual floor (obstruction; proof in doc)",
      best73 > 1e-2, f"floor {best73:.3e}")
check("(6,4) CONTROL: the same scan reaches ~0 (so the scan can find J when it exists)",
      best64 < 1e-12, f"{best64:.3e}")
# non-tautological theorem check: for ANY orthogonal J on (6,4) the Hermitian signature is forced
# to (3,2) (2r = p); verify on the optimizer-found J from a random start:
(rH2, sH2), hres2 = hermitian_signature(J64, g64, seed=7)
print(f"  optimizer-found control J on (6,4): Hermitian signature ({rH2},{sH2}), residual {hres2:.1e}")
check("optimizer-found J also gives Hermitian signature (3,2) (2r = p forced)",
      (rH2, sH2) == (3, 2) and hres2 < 1e-7)

# ----------------------------------------------------------------------------------------------
# SECTION B -- the commutant scan
# ----------------------------------------------------------------------------------------------
print("=" * 98)
print("SECTION B: cumulative commutant scan -- which orthogonal J's commute with GU's fiber data?")
print("=" * 98)

def nullspace(A, tol=TOL_NULL):
    U, s, Vt = np.linalg.svd(A)
    return Vt[(np.concatenate([s, np.zeros(Vt.shape[0] - len(s))]) < tol), :]

def linop(fun, n=10):
    cols = []
    for idx in range(n * n):
        E = np.zeros((n, n)); E.flat[idx] = 1.0
        cols.append(fun(E).ravel())
    return np.array(cols).T

def commutant_basis(mats):
    rows = [linop(lambda X, Cm=Cm: Cm @ X - X @ Cm) for Cm in mats]
    ns = nullspace(np.vstack(rows))
    return [v.reshape(10, 10) for v in ns]

# ---- step 0: no constraint. dimension of the solution manifold at J0 (linearization nullity)
Ltan = np.vstack([linop(lambda X: X @ J0 + J0 @ X),
                  linop(lambda X: X.T @ Ggram @ J0 + J0.T @ Ggram @ X)])
dim0 = nullspace(Ltan).shape[0]
print(f"  step 0 (no GU data): orthogonal J's form a FAMILY; tangent dimension at J0 = {dim0}")
check("step 0: family dimension = 20 = dim O(6,4) - dim U(3,2) = 45 - 25", dim0 == 20, f"dim {dim0}")

# ---- step 1 (+ trace/scale direction): J must commute with the G-orthogonal projector onto span(eta)
P1 = np.outer(v_eta, v_eta @ Ggram) / Geta
check("P1 is a projector, G-self-adjoint", np.linalg.norm(P1 @ P1 - P1) < 1e-12
      and np.linalg.norm(P1.T @ Ggram - Ggram @ P1) < 1e-12)
com1 = commutant_basis([P1])
print(f"  step 1: commutant of P1 has dim {len(com1)} (= 1^2 + 9^2 = 82 expected)")
check("commutant(P1) dim = 82", len(com1) == 82)
best1, J1 = scan(Ggram, Bas=com1, nstart=30, seed=21, label="step 1: J in commutant(P1)")
# exact certificate: any J commuting with P1 restricts to the 1-dim range of P1 -> a real scalar c
# with c^2 = -1 (impossible); the 9-dim kernel is odd-dimensional -> det(J9^2) = det(-I9) = -1 < 0
# but det(J9^2) = det(J9)^2 >= 0 (impossible).  Both blocks obstruct: floor >= 2 for the J^2 part.
check("step 1: EMPTY -- residual floor >= 2 (exact: 1-dim block >=1, 9-dim odd block >=1)",
      best1 > 2 - 1e-6, f"floor {best1:.6f} (predicted >= 2)")
print("    (exact argument: [J,P1]=0 restricts J to the 1-dim trace line, where J^2=-1 needs a real")
print("     scalar c with c^2=-1; and on the 9-dim complement det(J^2)=det(-I9)=-1 but det(J)^2>=0.)")

# CONTROL: rank-2 projector onto a G-POSITIVE 2-plane -> complement has signature (4,4); J exists.
u1 = C[:, 0]; u2 = C[:, 1]                    # two G-orthonormal G-positive directions
P2 = np.outer(u1, u1 @ Ggram) + np.outer(u2, u2 @ Ggram)
assert np.linalg.norm(P2 @ P2 - P2) < 1e-10
com2c = commutant_basis([P2])
bestc, _ = scan(Ggram, Bas=com2c, nstart=10, seed=22, label="CONTROL: rank-2 G-definite projector")
check("CONTROL: rank-2 definite projector -> scan FINDS J (empty results are not optimizer theater)",
      bestc < 1e-12, f"{bestc:.3e}")

# ---- step 2 (+ base-vs-vertical split): N/A at this level
print("  step 2: base-vs-vertical split -- N/A on the 10-dim fiber: the 4+10 split lives on T(Y14),")
print("          and V10 here IS the vertical summand. Recorded via the (9,5) assembly remark above.")

# ---- step 3 (+ SO(3,1) isotropy): commutant of the induced so(3,1) action
com3 = commutant_basis(L6)
print(f"  step 3: commutant of so(3,1) on V10 has dim {len(com3)} (expected 2: V10 = 9 (+) 1, both")
print(f"          real-type irreducible, multiplicity-free -> commutant = R P9 (+) R P1)")
check("commutant(so(3,1)) dim = 2", len(com3) == 2)
# verify the commutant is exactly span{I, P1} (equivalently span{P9, P1})
span_IP = np.vstack([I10.ravel(), P1.ravel()])
for cB in com3:
    resid = cB.ravel() - span_IP.T @ np.linalg.lstsq(span_IP.T, cB.ravel(), rcond=None)[0]
    check("commutant element lies in span{I, P1} (i.e., a P9 + b P1)",
          np.linalg.norm(resid) < 1e-9, f"resid {np.linalg.norm(resid):.1e}")
# exact floor over the commutant for the J^2 part alone: ||(aP9+bP1)^2 + I||_F^2 = 9(a^2+1)^2+(b^2+1)^2 >= 10
P9 = I10 - P1
aa = np.linspace(-3, 3, 601)
grid = min(9 * (a * a + 1) ** 2 + (b * b + 1) ** 2 for a in aa for b in aa)  # exact min 10 at a=b=0
print(f"  step 3: exact J^2-floor over the commutant = 10 (grid check: {grid:.6f} at a=b=0)")
best3, _ = scan(Ggram, Bas=[P9, P1], nstart=10, seed=23, label="step 3: J in commutant(so(3,1))")
check("step 3: EMPTY -- joint residual floor >= 10 (exact formula floor 10 for J^2 alone)",
      best3 > 10 - 1e-6, f"floor {best3:.6f}")

# cumulative steps 1+3 (P1 already lies in the step-3 commutant's stabilized split; intersection = step 3)
com13 = commutant_basis(L6 + [P1])
check("cumulative (trace + so(3,1)): commutant dim still 2 (P1 adds nothing new)", len(com13) == 2)

# ---- step 4 (+ SU(2)+ family action, where it acts on the REAL fiber)
# Hodge star on Lambda^2(R^{1,3}): *^2 = -I  => the self-dual/anti-self-dual split is COMPLEX in
# Lorentzian signature, so SU(2)+ acts on the real V10 only through its SO(3) rotation image.
PAIRS2 = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
def levi(i, j, k, l):
    perm = [i, j, k, l]
    if len(set(perm)) < 4:
        return 0
    sgn, arr = 1, perm[:]
    for a in range(4):
        for b in range(a + 1, 4):
            if arr[a] > arr[b]:
                arr[a], arr[b] = arr[b], arr[a]; sgn = -sgn
    return sgn
def hodge(inv_metric):
    """(*F)_{mn} = (1/2) eps_{mnab} g^{ar} g^{bs} F_{rs}; on the basis 2-form f^{(rs)} (r<s) this is
    eps(m,n,a,b) g^{ar} g^{bs} summed over a,b (the 1/2 is eaten by the antisymmetrized basis)."""
    Hs = np.zeros((6, 6))
    for A, (m, n) in enumerate(PAIRS2):
        for Bb, (r, s) in enumerate(PAIRS2):
            Hs[A, Bb] = sum(levi(m, n, a, b) * inv_metric[a, r] * inv_metric[b, s]
                            for a in range(4) for b in range(4))
    return Hs
Hlor, Heuc = hodge(np.linalg.inv(eta)), hodge(np.eye(4))
check("Hodge-* on Lambda^2: Lorentzian *^2 = -I (SD/ASD split is complex; SU(2)+ not real here)",
      np.linalg.norm(Hlor @ Hlor + np.eye(6)) < 1e-10)
check("Hodge-* CONTROL: Euclidean *^2 = +I (machinery discriminates)",
      np.linalg.norm(Heuc @ Heuc - np.eye(6)) < 1e-10)

Lrot = [rho(M6[i]) for i in (3, 4, 5)]        # spatial rotations (1,2),(1,3),(2,3)
com4 = commutant_basis(Lrot)
print(f"  step 4: commutant of the SO(3) rotation image has dim {len(com4)} "
      f"(V10 = 1+1+3+5 under SO(3): 2^2+1+1 = 6 expected)")
check("commutant(SO(3)) dim = 6", len(com4) == 6)
best4, _ = scan(Ggram, Bas=com4, nstart=30, seed=24, label="step 4 standalone: J in commutant(SO(3))")
# J^2-floor: the odd real-type isotypics (3-dim and 5-dim, multiplicity 1) force scalars there:
# >= 3 + 5 = 8; the 2-dim trivial isotypic has G-signature (1,1) so orthogonality obstructs it too.
check("step 4 standalone: EMPTY -- floor >= 8 (odd isotypics 3 and 5 force real scalars)",
      best4 > 8 - 1e-6, f"floor {best4:.6f} (J^2-alone floor 8)")
# the 2-dim SO(3)-trivial isotypic span{h_tt, h_spatial-trace}: G-signature there is (1,1) --
# both odd, so by the Section-A theorem even this even-dim block admits no orthogonal J
w1c, w2c = coords(np.diag([1.0, 0, 0, 0])), coords(np.diag([0, 1.0, 1.0, 1.0]))
G2 = np.array([[a @ Ggram @ b for b in (w1c, w2c)] for a in (w1c, w2c)])
sig2 = signature(G2)
print(f"  step 4: G restricted to the 2-dim SO(3)-trivial isotypic has signature "
      f"(+{sig2[0]}, -{sig2[1]}) -- (1,1), both odd, so it too refuses an orthogonal J")
check("2-dim trivial isotypic G-signature is (1,1)", sig2 == (1, 1, 0), str(sig2))
com134 = commutant_basis(L6 + [P1] + Lrot)
check("cumulative (1+3+4): commutant dim still 2; scan floor unchanged (rotations lie inside so(3,1))",
      len(com134) == 2)

# CONTROL: the so(2) generated by J0 itself -- its commutant contains J0, scan must find it
comJ = commutant_basis([J0])
bestJctl, _ = scan(Ggram, Bas=comJ, nstart=8, seed=25, label="CONTROL: commutant of so(2)_J0")
check("CONTROL: commutant of J0's own so(2) -> scan finds an orthogonal J (~0)",
      bestJctl < 1e-12, f"{bestJctl:.3e}")

print()
print("  CUMULATIVE SCAN SUMMARY")
print("  step 0  no constraint             FAMILY   dim 20")
print("  step 1  + trace/scale direction   EMPTY    (floor {:.3f} >= 2, exact parity argument)".format(best1))
print("  step 2  + base-vs-vertical        N/A      (lives on T(Y14); (3,1)+(6,4)=(9,5) recorded)")
print("  step 3  + SO(3,1) isotropy        EMPTY    (commutant dim 2; exact floor 10; measured {:.3f})".format(best3))
print("  step 4  + SU(2)+ (via SO(3))      EMPTY    (standalone dim 6, floor {:.3f} >= 8; cumulative dim 2)".format(best4))
print("  every named datum ALONE already empties the scan; no step ever returns CANONICAL.")

# additional exact remark: invariant subspaces under so(3,1) are only {0, trace(1), traceless(9), V10}
# (commutant dim 2 certifies irreducibility + multiplicity-freeness), so there is also NO invariant
# 6-dim subspace: the direct so(4,2) (+) so(2,2) vector-split route is equally non-canonical.
print("  remark: invariant subspaces are only 0/1/9/10-dim => no invariant (4,2)-signature 6-plane")
print("          exists either; the direct so(4,2)+so(2,2) split route is equally non-canonical.")

# ----------------------------------------------------------------------------------------------
# SECTION C -- the chain (contingent / informational: the scan returned EMPTY, not CANONICAL)
# ----------------------------------------------------------------------------------------------
print("=" * 98)
print("SECTION C: the chain u(3,2) -> u(1)+u(2,2) -> su(2,2) ~ so(4,2), at matrix level (informational)")
print("=" * 98)

# centralizer of J0 inside so(Ggram) = u(3,2)
LopA = np.vstack([linop(lambda X: X.T @ Ggram + Ggram @ X),
                  linop(lambda X: X @ J0 - J0 @ X)])
cent = nullspace(LopA)
print(f"  dim centralizer of J0 in so(6,4) = {cent.shape[0]}  (dim u(3,2) = 25)")
check("centralizer(J0) in so(6,4) has dim 25 = dim u(3,2) [and H-signature (3,2) measured above]",
      cent.shape[0] == 25)
check("dim so(6,4) = 45 (consistency)", nullspace(linop(lambda X: X.T @ Ggram + Ggram @ X)).shape[0] == 45)

# stabilizer of a G-positive complex line span_R{u, J0 u} inside u(3,2)
u = C[:, 0]                                    # G(u,u) = +1
Ju = J0 @ u
plane = np.vstack([u, Ju])
# G-orthogonal projector onto the plane (plane is G-positive-definite 2-dim)
Gp = plane @ Ggram @ plane.T
Pplane = plane.T @ np.linalg.inv(Gp) @ (plane @ Ggram)
Qc = I10 - Pplane                              # projector onto the G-orthocomplement
rowsS = []
for k in range(cent.shape[0]):
    A = cent[k].reshape(10, 10)
    rowsS.append(np.concatenate([(Qc @ A @ u), (Qc @ A @ Ju)]))
# combos t with (sum_k t_k A_k) preserving the line: null space of the (20 x 25) coefficient matrix
coefM = np.array(rowsS).T                      # 20 constraints x 25 basis elements
stab_dim = nullspace(coefM).shape[0]
print(f"  dim stabilizer of a G-positive complex line inside u(3,2) = {stab_dim}  (dim u(1)+u(2,2) = 17)")
check("stabilizer of positive complex line: dim 17 = 1 + 16 = dim(u(1) (+) u(2,2))", stab_dim == 17)

# su(2,2) vs so(4,2): dim, rank, Killing signature at matrix level
def su22_basis():
    h = np.diag([1.0, 1.0, -1.0, -1.0]).astype(complex)
    rows = []
    for idx in range(32):                      # 16 complex entries -> 32 real params
        X = np.zeros((4, 4), dtype=complex)
        X.flat[idx // 2] = (1.0 if idx % 2 == 0 else 1j)
        Cc = X.conj().T @ h + h @ X
        rows.append(np.concatenate([Cc.real.ravel(), Cc.imag.ravel(),
                                    [np.trace(X).real, np.trace(X).imag]]))
    # rows[k] = constraint(e_k); constraint(sum t_k e_k) = t @ rows -> null space of rows^T (34x32)
    ns = nullspace(np.array(rows).T)
    mats = []
    for v in ns:
        X = np.zeros((4, 4), dtype=complex)
        for idx in range(32):
            X.flat[idx // 2] += v[idx] * (1.0 if idx % 2 == 0 else 1j)
        mats.append(X)
    return mats

def so42_basis():
    g6 = np.diag([1.0, 1.0, 1.0, 1.0, -1.0, -1.0])
    rows = []
    for idx in range(36):
        Y = np.zeros((6, 6)); Y.flat[idx] = 1.0
        rows.append((Y.T @ g6 + g6 @ Y).ravel())
    ns = nullspace(np.array(rows).T)
    return [v.reshape(6, 6) for v in ns]

def lie_invariants(mats, is_complex, label):
    n = len(mats)
    flat = np.array([np.concatenate([m.real.ravel(), m.imag.ravel()]) if is_complex
                     else m.ravel() for m in mats])
    Q, _ = np.linalg.qr(flat.T)
    coords_of = lambda M: Q.T @ (np.concatenate([M.real.ravel(), M.imag.ravel()]) if is_complex
                                 else M.ravel())
    basis_c = [coords_of(m) for m in mats]
    Bc = np.array(basis_c).T                   # coords of basis in orthonormal frame
    Binv = np.linalg.pinv(Bc)
    ads = []
    for i in range(n):
        cols = []
        for jx in range(n):
            br = mats[i] @ mats[jx] - mats[jx] @ mats[i]
            cols.append(Binv @ coords_of(br))
        ads.append(np.array(cols).T)
    K = np.array([[np.trace(ads[i] @ ads[jx]) for jx in range(n)] for i in range(n)])
    sig = signature(K, tol=1e-6 * max(1.0, np.max(np.abs(K))))
    tvec = rng_global.normal(size=n)
    adX = sum(t * a for t, a in zip(tvec, ads))
    sv = np.linalg.svd(adX, compute_uv=False)
    rank_alg = int(np.sum(sv < 1e-8 * max(1.0, sv[0])))
    print(f"  {label}: dim {n}, rank (generic centralizer dim) {rank_alg}, "
          f"Killing signature (+{sig[0]}, -{sig[1]}, 0:{sig[2]})")
    return n, rank_alg, sig

su_m = su22_basis()
so_m = so42_basis()
d1, r1_, s1 = lie_invariants(su_m, True, "su(2,2)")
d2, r2_, s2 = lie_invariants(so_m, False, "so(4,2)")
check("su(2,2) and so(4,2): dim 15 = 15", d1 == 15 and d2 == 15, f"{d1},{d2}")
check("su(2,2) and so(4,2): rank 3 = 3", r1_ == 3 and r2_ == 3, f"{r1_},{r2_}")
check("su(2,2) and so(4,2): Killing signatures match (8,7) = (8,7)",
      s1 == (8, 7, 0) and s2 == (8, 7, 0), f"{s1},{s2}")

# ----------------------------------------------------------------------------------------------
# SECTION D -- verdict
# ----------------------------------------------------------------------------------------------
print("=" * 98)
print("SECTION D: VERDICT (pre-registered downgrade rule, route V3 part d)")
print("=" * 98)
print("""  (a) THEOREM: orthogonal complex structure on R^{p,q} iff p,q both even. (6,4): constructed.
      (7,3): obstructed (proof in doc; 40-start numerical falsification floor printed above).
      The from-memory flag on the even-parity criterion is CLEARED.
  (b) The commutant scan never returns CANONICAL. Step 0 is a 20-dim FAMILY; imposing GU's FIRST
      named fiber datum (the trace/scale direction) already returns EMPTY, and so does each other
      named datum standalone (so(3,1) isotropy: exact floor 10; SO(3) rotation image of SU(2)+:
      floor >= 8). There is NO GU-native J: not canonical, not even a family.
  (c) The chain so(6,4) > u(3,2) > u(1)+u(2,2) > su(2,2) ~ so(4,2) is VERIFIED as abstract Lie
      theory at matrix level -- but it hangs off a J that GU's own fiber data refuses.
  (d) Pre-registered rule fires on the EMPTY branch: the conformal attachment via a canonical J
      is dead at the fiber level. T1' reports NEGATIVE -- and STRONGER than the family-downgrade:
      any J is not merely one unforced choice among a 20-dim family, it is INCOMPATIBLE with the
      fiber's own trace split and isotropy. 'Conformal is GU-native' is refuted at this level;
      the surviving reading is 'conformal is an import that breaks GU's fiber decomposition'.""")

print()
if FAIL:
    print(f"RESULT: {len(FAIL)} CHECK(S) FAILED: {FAIL}")
    sys.exit(1)
print("RESULT: ALL CHECKS PASS (exit 0)")
sys.exit(0)
