import GUFormalization.Status
import GUFormalization.K3IndexArithmetic
import GUFormalization.W2Polynomial
import GUFormalization.LocatedNotForcedLegs
import GUFormalization.ResidualSelection
import GUFormalization.R4TwoArena
import GUFormalization.CoflipCore
import GUFormalization.CoflipAbstract
