#!/usr/bin/env python3
"""Fail-closed scope audit for the K77 Dirac--de Rham/super-IG rebase."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "lab/process/k77-wave2-dirac-derham-superig-rebase.json"
REPORT = ROOT / "explorations/k77-wave2-dirac-derham-superig-rebase-2026-08-04.md"
REVIEW = ROOT / "lab/process/hostile-reviews/2026-08-04-k77-wave2-dirac-derham-superig-rebase-review.md"
CAMPAIGN = ROOT / "lab/process/k77-post-b2-next-eight-wave-campaign.json"
CURRENT = ROOT / "lab/process/k77-wave2-global-draft916-krein-preboundary.json"


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique_object)


def normalized(path: Path) -> str:
    return " ".join(path.read_text(encoding="utf-8").lower().split())


def main() -> None:
    registry = load_json(REGISTRY)
    campaign = load_json(CAMPAIGN)
    current = load_json(CURRENT)
    report = normalized(REPORT)
    review = normalized(REVIEW)

    assert registry["gate_status"] == "PARTIAL_DIRAC_DERHAM_SYMBOL_BUILT__SOURCE_SELECTED_ACTION_AND_DOMAIN_OPEN"
    assert len(registry["layer0_objects"]) == 5
    assert registry["source_collision"]["cyclic_two_connection_completion"] == "SOURCE_UNRELEASED"
    assert registry["source_collision"]["full_odd_action_and_odd_Ward_requirement"] == "SOURCE_CORRECTS_TO_NOT_REQUIRED_FOR_GU"

    operator = registry["operator"]
    assert operator["domain"] == "OMEGA1_S_PLUS_OMEGA0_S"
    assert operator["codomain"] == "OMEGA13_S_PLUS_OMEGA14_S"
    assert operator["southeast"] == "ZERO_SOURCE_STATED"
    assert operator["global_selected_operator"] == "OPEN"

    fixture = registry["exact_fixture"]
    assert fixture["matrix_dimension"] == 1920
    assert fixture["positive_nonnull_rank"] == fixture["negative_nonnull_rank"] == 1920
    assert fixture["null_rank"] == 1024
    assert fixture["null_kernel_dimension"] == 896
    assert fixture["checks"] == {"source": 11, "type": 14, "exact": 20, "planted": 7, "total": 52}

    placement = registry["variational_placement"]
    assert placement["bare_middle_B_selfadjoint"] is False
    assert placement["bare_middle_B_skew"] is False
    assert placement["exact_draft_identity"] == "OPEN"
    assert placement["global_hodge_krein_boundary_domain"] == "OPEN"

    rebase = registry["superig_rebase"]
    assert "ODD_MODULE" in rebase["required"]
    assert "FULL_ODD_ACTION_SYMMETRY" in rebase["not_source_required"]
    assert rebase["conditional_reduced_algebra"] == "gl(64,R)"
    assert rebase["full_source_group_identification"] == "OPEN"
    assert rebase["third_lane"] == "NOT_PROMOTED"

    assert registry["curt_family_disposition"]["three_physical_chiral_generations"] == "NOT_DERIVED"
    assert registry["external_datum"] == {"P1": "UNUSED", "P2": "UNUSED", "P3": "UNUSED"}
    assert all(value is False for value in registry["status_boundary"].values())

    wave2 = campaign["waves"][1]
    assert wave2["status"] == current["gate_status"]
    assert "SOURCE_TYPED_0_1_13_14_CHAIN" in wave2["emitted"]
    assert "ODD_ACTION_WARD_REQUIREMENT_FORMALLY_REBASED" in wave2["emitted"]
    assert campaign["frontier"]["next_wave"] == 2
    assert campaign["frontier"]["next_required_build"] == "ACTUAL_DRAFT916_K77_BLOCKWISE_ADJOINT_DESCENT_AND_COMMON_CONNECTION_VARIATION"
    assert current["built_now"]["formal_adjoint"].startswith("EXACT_GENERAL_PRIMALIZED_FIRST_ORDER_TEMPLATE")
    assert current["campaign_disposition"]["wave2"] == "PARTIAL"

    for token in (
        "five nearby objects",
        "phi o d_a",
        "rank `1024`, kernel `896`",
        "curt jaimungal's complete 30-step iceberg",
        "conditional completion generated by the action burden",
        "the previous wave-2 gate demanded a full odd action",
        "wave 2 remains partial",
        "p1/p2/p3 use",
    ):
        assert token in report, f"missing report token: {token}"

    for token in (
        "pass_with_material_scope_repairs__gate_partial",
        "summary no longer outruns the artifact",
        "artifact defends a superseded object",
        "rank-1024 minor",
        "middle block is neither self- nor skew-adjoint",
        "analytic/global promotion is forbidden",
    ):
        assert token in review, f"missing review token: {token}"

    print("k77_wave2_dirac_derham_superig_rebase_scope_audit: PASS")
    print("  five-object Layer-0 split, exact K77 symbol, conditional action, super-IG rebase, and held-out wall preserved")


if __name__ == "__main__":
    main()
