import Mathlib

set_option autoImplicit false

/-!
# Co-flip core (CH-REC / blockbuster P1–P2, finite form)

**Hardening swing H2 (gap G-A4), 2026-07-19.** Lean formalization of the minimal finite
core of the co-flip result:

* **P1 (co-flip / zero-import diagonal).** In the zero-extra-import class the payload
  flip `E` flips the physical-sector G-sign and the record-accumulation direction
  *together*, and every zero-import operation acts *diagonally* on the pair
  (sector, direction) — both fixed or both flipped. No zero-import decoupling exists.
* **P2 (split-costs-one).** Every operation that splits the pair (flips exactly one)
  pays the record-law sign bit: it carries import cost exactly one additional ℤ/2, and
  factors as the paid flip `M` composed with a zero-import operation.

Design source: `explorations/channel-swing-CH-REC-2026-07-19.md` §1–2 and the runnable
probe `tests/channel-swings/ch_rec_coflip_probe.py`; P1/P2 statements as tabulated in
`explorations/blockbuster-p3-one-bit-dossier-2026-07-19.md` §2.

## Architecture (what is derived vs. what is presented)

**Part A — the finite Krein toy.** A signature (1,1) Krein space over ℚ (pairs of
rationals) with the covariant-relabel gauge `rho`, fundamental symmetry `Jmap`,
orientation projector `proj`, sector charge `charge`, and the record register
`register`. Here the observable content is *derived*, not stipulated:

* `charge_nonneg` / `sector_definite`: the sector charge is a square, and the selected
  subspace is form-definite with sign `eps` — in **both** gauges (the sector observable
  is the transmitted orientation, gauge-independently).
* `register_eq_sum` / `register_direction` / `direction_unique`: on any trajectory with
  positive total charge, the register's final sign is `mu * eps`, and that sign is
  unique. The quantification is over *arbitrary* nonnegative-charge trajectories, so it
  covers both time directions and any grading-preserving Krein-unitary dynamics at
  once — time-reversal inertness (dossier P3) is a corollary of the register shape,
  not an extra axiom.
* `relabel_charge_invariant`: the full covariant relabel (gauge move) is invisible to
  the charge; `fundamental_symmetry_gate` / `partial_relabel_rejected`: the transported
  `J` passes the positivity gate exactly in the matched presentation — the probe's
  partial-relabel attack is rejected, formally.
* `vacuum_charge_zero` / `vacuum_unwitnessed`: the vacuum carries zero charge and an
  orientation-independent (identically zero) register trajectory — the finite shadow of
  "one absence seen twice" (dossier P10).

**Part B — the operation group and the theorems.** The operation inventory is the
finite group `Op ≅ (ℤ/2)⁴`, presented multiplicatively as `ℤˣ × ℤˣ × ℤˣ × ℤˣ` with
generators `E` (payload flip), `M` (record-law sign insert), `T` (dynamics reversal),
`Rl` (covariant relabel), acting on configurations (a `MulAction`, proven). The
observables `sector c = c.eps` and `dir c = c.mu * c.eps` are *justified* by Part A
(`sector_spec`, `dir_spec`, `dir_unique`) rather than free-standing definitions. Main
theorems: `coflip`, `zeroImport_diagonal`, `splits_iff`, `no_zeroImport_split`,
`split_costs_one`, `split_factorization`, `one_bit_accounting`.

## Admissibility (explicit; H1 alignment)

An *admissible operation* in this file is an element of the group generated by
`{E, M, T, Rl}` — proven to be all of `Op` (`inventory_generates`). A *zero-import*
operation is one whose record-law component is trivial (`zeroImport g : g.m = 1`),
proven to be exactly the subgroup generated by `{E, T, Rl}`, i.e. the kernel of the
record-law character (`zeroImport_iff_mem_ker`, `zeroImport_iff_generated`).

Alignment with H1 (`explorations/hardening-h1-exhaustiveness-2026-07-19.md`, written
in parallel with this swing): H1's admissibility quantifier is strictly weaker —
arbitrary partial maps between admissible configurations of the general-(p,q)
envelope class — and its Theorems A/B derive diagonality from the rigidity lemmas
L1/L2 alone. This file formalizes (a) the (1,1) instance of L1/L2 fully derived
(`sector_definite`, `charge_nonneg`, `register_direction`), (b) the operation-group
presentation of Theorems A/B (`zeroImport_diagonal`, `splits_iff`,
`one_bit_accounting`), (c) H1's split-parity identity `sigma·d = mu`
(`split_parity`), and (d) the charge action of H1's benign miss F, the total form
flip (`total_flip_charge`). The general-(p,q) abstract-class Lean lift of L0–L2 +
Theorems A/B (H1 §7 item 4) is the named remaining step for full G-A4 closure.
Exhaustiveness for the *full GU construction* (cohomological grade, G-A2) is **not**
claimed here.

## Scope boundary

As everywhere in this Lean layer: Lean checks the finite kernel only. That GU's actual
W229 record law is a member of the class (typing constraint T3 / membership audit P9),
and everything physical, stays in Markdown/Python surfaces and enters nowhere here.
No `sorry`, no new `axiom` declarations (mathlib's standard axioms only).
-/

namespace GUFormalization
namespace CoflipCore

/- ===================================================================== -/
/-  Sign values: ℤˣ = {1, -1} is the multiplicative presentation of ℤ/2   -/
/- ===================================================================== -/

/-- Rational value of a sign `s : ℤˣ` (so signs can multiply rational data). -/
def sv (s : ℤˣ) : ℚ := ((s : ℤ) : ℚ)

theorem sv_one : sv 1 = 1 := by simp [sv]

theorem sv_neg_one : sv (-1) = -1 := by simp [sv]

theorem sv_mul (s t : ℤˣ) : sv (s * t) = sv s * sv t := by simp [sv]

theorem sv_sq (s : ℤˣ) : sv s * sv s = 1 := by
  rw [← sv_mul, Int.units_mul_self, sv_one]

/-- No sign equals its own negation (the two anchors are genuinely distinct). -/
theorem units_ne_neg_self (s : ℤˣ) : ¬ s = -s := by
  rcases Int.units_eq_one_or s with h | h <;> subst h <;> intro hh
  · have h2 : (1 : ℤ) = -1 := by simpa using congrArg Units.val hh
    omega
  · have h2 : (-1 : ℤ) = 1 := by simpa using congrArg Units.val hh
    omega

theorem units_one_ne_neg_one : ¬ ((1 : ℤˣ) = -1) := units_ne_neg_self 1

theorem units_neg_one_ne_one : ¬ ((-1 : ℤˣ) = 1) := fun h =>
  units_ne_neg_self 1 h.symm

/-- Flip cancellation: `a * s = -s ↔ a = -1`. -/
theorem flip_iff (a s : ℤˣ) : a * s = -s ↔ a = -1 := by
  constructor
  · intro h
    have h2 : a * s * s = -s * s := by rw [h]
    rwa [mul_assoc, Int.units_mul_self, mul_one, neg_mul, Int.units_mul_self] at h2
  · rintro rfl
    exact neg_one_mul s

/-- Fix cancellation: `a * s = s ↔ a = 1`. -/
theorem fix_iff (a s : ℤˣ) : a * s = s ↔ a = 1 := by
  constructor
  · intro h
    have h2 : a * s = 1 * s := by rw [h, one_mul]
    exact mul_right_cancel h2
  · rintro rfl
    exact one_mul s

/- ===================================================================== -/
/-  Part A — the finite (1,1) Krein toy over ℚ                            -/
/- ===================================================================== -/

/-- The signature (1,1) Krein toy space: pairs of rationals.
    (The probe's (2,2) instance adds nontrivial block dynamics; the co-flip core needs
    only the sign structure, and dynamics is abstracted by quantifying over arbitrary
    nonnegative-charge trajectories below.) -/
abbrev K := ℚ × ℚ

/-- Krein form in gauge `rho` (`rho = 1` the standard presentation, `rho = -1` the
    fully transported covariant relabel, `G ↦ Sᵀ G S = -G` under the swap). -/
def form (rho : ℤˣ) (v w : K) : ℚ := sv rho * (v.1 * w.1 - v.2 * w.2)

/-- Fundamental symmetry in gauge `rho` (`J ↦ S J S = -J` under the swap). -/
def Jmap (rho : ℤˣ) (v : K) : K := (sv rho * v.1, -(sv rho) * v.2)

/-- The covariant relabel on states (the block swap of the probe, at (1,1) scale). -/
def swapK (v : K) : K := (v.2, v.1)

/-- Orientation projector `P_eps = (I + eps·J_rho)/2` in gauge `rho`. -/
def proj (rho eps : ℤˣ) (v : K) : K :=
  ((1 + sv eps * sv rho) / 2 * v.1, (1 - sv eps * sv rho) / 2 * v.2)

/-- Sector charge `q = eps·⟨P_eps ψ, P_eps ψ⟩` — the probe's `q_of`. -/
def charge (rho eps : ℤˣ) (v : K) : ℚ :=
  sv eps * form rho (proj rho eps v) (proj rho eps v)

/-- **Structure lemma** for the projector and charge: in every gauge, the projector
    selects one coordinate line and the charge is the square of the retained
    coordinate. This is the derivation that makes everything downstream honest. -/
theorem charge_spec (rho eps : ℤˣ) (v : K) :
    (eps = rho ∧ proj rho eps v = (v.1, 0) ∧ charge rho eps v = v.1 * v.1) ∨
    (eps = -rho ∧ proj rho eps v = (0, v.2) ∧ charge rho eps v = v.2 * v.2) := by
  rcases Int.units_eq_one_or eps with he | he <;> rcases Int.units_eq_one_or rho with hr | hr <;>
    subst he <;> subst hr
  · exact Or.inl ⟨rfl,
      by simp only [proj, sv_one, Prod.mk.injEq]; exact ⟨by ring, by ring⟩,
      by simp only [charge, form, proj, sv_one]; ring⟩
  · exact Or.inr ⟨(neg_neg (1 : ℤˣ)).symm,
      by simp only [proj, sv_one, sv_neg_one, Prod.mk.injEq]; exact ⟨by ring, by ring⟩,
      by simp only [charge, form, proj, sv_one, sv_neg_one]; ring⟩
  · exact Or.inr ⟨rfl,
      by simp only [proj, sv_one, sv_neg_one, Prod.mk.injEq]; exact ⟨by ring, by ring⟩,
      by simp only [charge, form, proj, sv_one, sv_neg_one]; ring⟩
  · exact Or.inl ⟨rfl,
      by simp only [proj, sv_neg_one, Prod.mk.injEq]; exact ⟨by ring, by ring⟩,
      by simp only [charge, form, proj, sv_neg_one]; ring⟩

/-- The sector charge is nonnegative in every configuration (class constraint of C_0:
    the record current's magnitude is sourced by physical content). -/
theorem charge_nonneg (rho eps : ℤˣ) (v : K) : 0 ≤ charge rho eps v := by
  rcases charge_spec rho eps v with ⟨_, _, h⟩ | ⟨_, _, h⟩ <;> rw [h] <;>
    exact mul_self_nonneg _

/-- **Sector definiteness (the sector observable is `eps`).** Any nonzero vector of the
    selected subspace has strictly positive charge, i.e. the physical form
    `eps·⟨·,·⟩` is positive definite on `ran P_eps` — in both gauges. The G-sign of the
    selected sector is therefore the transmitted orientation, gauge-independently. -/
theorem sector_definite (rho eps : ℤˣ) (v : K) (hv : proj rho eps v ≠ 0) :
    0 < charge rho eps v := by
  rcases charge_spec rho eps v with ⟨_, hp, h⟩ | ⟨_, hp, h⟩ <;> rw [h]
  · have h1 : v.1 ≠ 0 := by
      intro h0
      exact hv (by simp [hp, h0])
    exact mul_self_pos.mpr h1
  · have h2 : v.2 ≠ 0 := by
      intro h0
      exact hv (by simp [hp, h0])
    exact mul_self_pos.mpr h2

/-- **Gauge move is invisible.** The full covariant relabel (transporting form,
    fundamental symmetry, and state together) leaves the sector charge unchanged:
    the anchor exchange is gauge, the payload flip is physical. -/
theorem relabel_charge_invariant (rho eps : ℤˣ) (v : K) :
    charge (-rho) eps (swapK v) = charge rho eps v := by
  rcases Int.units_eq_one_or eps with he | he <;> rcases Int.units_eq_one_or rho with hr | hr <;>
    subst he <;> subst hr <;>
    simp only [charge, form, proj, swapK, neg_neg, sv_one, sv_neg_one] <;> ring

/-- **Total form flip (H1's benign miss F).** Flipping the form and the fundamental
    symmetry together — WITHOUT transporting the state — stays admissible (the gate
    passes in every gauge, `fundamental_symmetry_gate` below) and exchanges the
    charge with the mirror-sector charge: `q ∘ F = q(−eps)`. Since the signed
    observables (`sector_definite`'s sign, `register_direction`'s sign) never
    reference the gauge, the observable pair is F-inert: the anchor exchange is
    gauge, exhibited at (1,1) scale. -/
theorem total_flip_charge (rho eps : ℤˣ) (v : K) :
    charge (-rho) eps v = charge rho (-eps) v := by
  rcases Int.units_eq_one_or eps with he | he <;> rcases Int.units_eq_one_or rho with hr | hr <;>
    subst he <;> subst hr <;>
    simp only [charge, form, proj, neg_neg, sv_one, sv_neg_one] <;> ring

/-- **Fundamental-symmetry gate, pass direction.** In the matched presentation the
    form composed with `J` is positive definite (this is what makes `J` a fundamental
    symmetry — the probe's admissibility gate). -/
theorem fundamental_symmetry_gate (rho : ℤˣ) (v : K) (hv : v ≠ 0) :
    0 < form rho v (Jmap rho v) := by
  have hcomp : form rho v (Jmap rho v) = v.1 * v.1 + v.2 * v.2 := by
    rcases Int.units_eq_one_or rho with hr | hr <;> subst hr <;>
      simp only [form, Jmap, sv_one, sv_neg_one] <;> ring
  have h1 : v.1 ≠ 0 ∨ v.2 ≠ 0 := by
    rcases eq_or_ne v.1 0 with hz1 | hz1
    · rcases eq_or_ne v.2 0 with hz2 | hz2
      · exact absurd (Prod.ext hz1 hz2) hv
      · exact Or.inr hz2
    · exact Or.inl hz1
  rw [hcomp]
  rcases h1 with h | h
  · have hp := mul_self_pos.mpr h
    have hn := mul_self_nonneg v.2
    linarith
  · have hp := mul_self_pos.mpr h
    have hn := mul_self_nonneg v.1
    linarith

/-- **Fundamental-symmetry gate, reject direction.** The partial-relabel attack
    (flipping `J` without transporting the form) fails the gate: the mixed pairing is
    not positive definite. The relabel cannot be used to split the observable pair. -/
theorem partial_relabel_rejected :
    ∃ v : K, v ≠ 0 ∧ form 1 v (Jmap (-1) v) < 0 := by
  refine ⟨(1, 0), ?_, ?_⟩
  · intro h
    have h1 : (1 : ℚ) = 0 := congrArg Prod.fst h
    norm_num at h1
  · simp only [form, Jmap, sv_one, sv_neg_one]
    norm_num

/-- Vacuum charge vanishes (W229 lineage: `Psi = 0 → J = 0`). -/
theorem vacuum_charge_zero (rho eps : ℤˣ) : charge rho eps (0, 0) = 0 := by
  rcases charge_spec rho eps (0, 0) with ⟨_, _, h⟩ | ⟨_, _, h⟩ <;> rw [h] <;> norm_num

/-- The unit state has strictly positive charge in every gauge and orientation —
    the standing witness state used for the end-to-end instances below. -/
theorem unit_state_charge_pos (rho eps : ℤˣ) : 0 < charge rho eps (1, 1) := by
  rcases charge_spec rho eps (1, 1) with ⟨_, _, h⟩ | ⟨_, _, h⟩ <;> rw [h] <;> norm_num

/- --------------------------------------------------------------------- -/
/-  The record register                                                   -/
/- --------------------------------------------------------------------- -/

/-- Record register driven by a charge trajectory: `N += mu * eps * q` per step
    (the probe's `record_register`). `mu ≠ 1` is one underived ℤ/2 import. -/
def register (mu eps : ℤˣ) : List ℚ → ℚ
  | [] => 0
  | q :: qs => sv mu * sv eps * q + register mu eps qs

/-- Closed form: the register is `mu * eps` times the total accumulated charge. -/
theorem register_eq_sum (mu eps : ℤˣ) (qs : List ℚ) :
    register mu eps qs = sv mu * sv eps * qs.sum := by
  induction qs with
  | nil => simp [register]
  | cons q qs ih =>
      simp only [register, List.sum_cons, ih]
      ring

/-- **Record direction.** On any trajectory with positive total charge the register's
    final value has sign `mu * eps`. The trajectory is *arbitrary*: this single
    statement covers forward and reversed dynamics and any grading-preserving
    Krein-unitary at once, which is why time reversal is inert (dossier P3) — the
    arrow lives in the record law plus the orientation, not in the propagator. -/
theorem register_direction (mu eps : ℤˣ) (qs : List ℚ) (h : 0 < qs.sum) :
    0 < sv (mu * eps) * register mu eps qs := by
  rw [register_eq_sum, sv_mul]
  have h2 : sv mu * sv eps * (sv mu * sv eps * qs.sum) = qs.sum := by
    calc sv mu * sv eps * (sv mu * sv eps * qs.sum)
        = (sv mu * sv mu) * ((sv eps * sv eps) * qs.sum) := by ring
      _ = qs.sum := by rw [sv_sq, sv_sq, one_mul, one_mul]
  rw [h2]
  exact h

/-- **Direction uniqueness.** A nonvanishing register value determines its sign
    uniquely — so `dir` below is a genuine observable, not a convention. -/
theorem direction_unique {u w : ℤˣ} {x : ℚ} (hu : 0 < sv u * x) (hw : 0 < sv w * x) :
    u = w := by
  rcases Int.units_eq_one_or u with h1 | h1 <;> rcases Int.units_eq_one_or w with h2 | h2 <;>
    subst h1 <;> subst h2
  · rfl
  · exfalso
    rw [sv_one, one_mul] at hu
    rw [sv_neg_one, neg_one_mul] at hw
    linarith
  · exfalso
    rw [sv_neg_one, neg_one_mul] at hu
    rw [sv_one, one_mul] at hw
    linarith
  · rfl

/-- **Vacuum is unwitnessed (dossier P10, finite shadow).** On an all-zero charge
    trajectory the register vanishes identically and is independent of both the
    record-law sign and the orientation: the two anchors are operationally exactly
    degenerate at the vacuum — one absence, seen from either presentation. -/
theorem vacuum_unwitnessed (mu eps mu' eps' : ℤˣ) (qs : List ℚ)
    (h : ∀ q ∈ qs, q = 0) :
    register mu eps qs = 0 ∧ register mu eps qs = register mu' eps' qs := by
  have h0 : qs.sum = 0 := List.sum_eq_zero h
  constructor
  · rw [register_eq_sum, h0, mul_zero]
  · rw [register_eq_sum, register_eq_sum, h0, mul_zero, mul_zero]

/- ===================================================================== -/
/-  Part B — the operation group and the co-flip theorems                 -/
/- ===================================================================== -/

/-- The operation inventory: the finite abelian group `(ℤ/2)⁴`, multiplicatively
    presented. Coordinates: payload flip (E), record-law sign insert (M), dynamics
    reversal (T), covariant relabel (Rl). -/
abbrev Op := ℤˣ × ℤˣ × ℤˣ × ℤˣ

/-- Payload-flip component. -/
def Op.e (g : Op) : ℤˣ := g.1

/-- Record-law sign-insert component (the *paid* coordinate). -/
def Op.m (g : Op) : ℤˣ := g.2.1

/-- Dynamics-reversal component. -/
def Op.t (g : Op) : ℤˣ := g.2.2.1

/-- Covariant-relabel component. -/
def Op.r (g : Op) : ℤˣ := g.2.2.2

/-- Generator E: flip the transmitted orientation (zero import — it is the payload). -/
def E : Op := (-1, 1, 1, 1)

/-- Generator M: record-law sign insert (ONE ℤ/2 import — `mu` is underived). -/
def M : Op := (1, -1, 1, 1)

/-- Generator T: dynamics reversal (zero import). -/
def T : Op := (1, 1, -1, 1)

/-- Generator Rl: full covariant relabel (zero import — a gauge move). -/
def Rl : Op := (1, 1, 1, -1)

/-- Every operation is an involution: the inventory is an elementary abelian 2-group. -/
theorem op_mul_self (g : Op) : g * g = 1 := by
  obtain ⟨a, b, c, d⟩ := g
  simp [Prod.mk_mul_mk, Prod.mk_eq_one, Int.units_mul_self]

/-- A configuration of the finite class: transmitted orientation, record-law sign
    datum, dynamics direction, relabel gauge. `mu ≠ 1` is one underived ℤ/2 import. -/
structure Cfg where
  eps : ℤˣ
  mu : ℤˣ
  tdir : ℤˣ
  gauge : ℤˣ

/-- The group action on configurations: componentwise sign flips. -/
def act (g : Op) (c : Cfg) : Cfg :=
  ⟨g.e * c.eps, g.m * c.mu, g.t * c.tdir, g.r * c.gauge⟩

theorem act_one (c : Cfg) : act 1 c = c := by
  cases c
  simp [act, Op.e, Op.m, Op.t, Op.r]

theorem act_mul (g h : Op) (c : Cfg) : act (g * h) c = act g (act h c) := by
  cases c
  simp [act, Op.e, Op.m, Op.t, Op.r, mul_assoc]

instance : SMul Op Cfg := ⟨act⟩

/-- The inventory acts on configurations as a (finite) group action. -/
instance : MulAction Op Cfg where
  one_smul := act_one
  mul_smul := act_mul

/- --------------------------------------------------------------------- -/
/-  Observables (justified by Part A, not stipulated)                     -/
/- --------------------------------------------------------------------- -/

/-- Sector observable: the G-sign of the selected physical subspace.
    Justified by `sector_spec` below (= `sector_definite` of Part A). -/
def sector (c : Cfg) : ℤˣ := c.eps

/-- Direction observable: the record-accumulation direction.
    Justified by `dir_spec`/`dir_unique` below (= `register_direction` +
    `direction_unique` of Part A). -/
def dir (c : Cfg) : ℤˣ := c.mu * c.eps

/-- Import cost of a configuration: one underived ℤ/2 iff the record-law sign datum
    is engaged (the probe's `imports` counter). -/
def importCost (c : Cfg) : ℕ := if c.mu = 1 then 0 else 1

/-- Zero-import operation: the record-law component is untouched. -/
def zeroImport (g : Op) : Prop := g.m = 1

/-- The sector observable is what Part A says it is: on any nonzero vector of the
    subspace selected in the configuration's own gauge, the form has sign
    `sector c`. -/
theorem sector_spec (c : Cfg) (v : K) (hv : proj c.gauge c.eps v ≠ 0) :
    0 < sv (sector c) * form c.gauge (proj c.gauge c.eps v) (proj c.gauge c.eps v) := by
  have h := sector_definite c.gauge c.eps v hv
  simpa only [charge, sector] using h

/-- The direction observable is what Part A says it is: on any positive-total-charge
    trajectory, the register's sign is `dir c`. -/
theorem dir_spec (c : Cfg) (qs : List ℚ) (h : 0 < qs.sum) :
    0 < sv (dir c) * register c.mu c.eps qs :=
  register_direction c.mu c.eps qs h

/-- And it is the *unique* sign with that property (so `dir` is forced, not chosen). -/
theorem dir_unique (c : Cfg) {qs : List ℚ} (h : 0 < qs.sum) {u : ℤˣ}
    (hu : 0 < sv u * register c.mu c.eps qs) : u = dir c :=
  direction_unique hu (dir_spec c qs h)

/-- **Split parity (H1 alignment).** The product of the two observables is the
    record-law sign datum: `sector · dir = mu`. The import bit is itself an
    observable — H1's `sigma·d = mu`: the pair (sector, direction) is a faithful
    copy of the discrete data (payload bit, import bit). -/
theorem split_parity (c : Cfg) : sector c * dir c = c.mu := by
  simp only [sector, dir]
  calc c.eps * (c.mu * c.eps) = c.mu * (c.eps * c.eps) := by
        rw [mul_comm c.eps (c.mu * c.eps), mul_assoc]
    _ = c.mu := by rw [Int.units_mul_self, mul_one]

/-- Witness restored (probe check): on an import-free configuration with physical
    content, the record direction *is* the transmitted orientation. -/
theorem witness_restored (c : Cfg) (hmu : c.mu = 1) (qs : List ℚ) (h : 0 < qs.sum) :
    0 < sv c.eps * register c.mu c.eps qs := by
  have hd := dir_spec c qs h
  rw [hmu]
  simp only [dir, hmu, one_mul] at hd
  exact hd

/- --------------------------------------------------------------------- -/
/-  Action on the observable pair                                         -/
/- --------------------------------------------------------------------- -/

theorem sector_act (g : Op) (c : Cfg) : sector (act g c) = g.e * sector c := rfl

theorem dir_act (g : Op) (c : Cfg) : dir (act g c) = (g.m * g.e) * dir c := by
  simp only [dir, act]
  exact mul_mul_mul_comm g.m c.mu g.e c.eps

theorem sector_flip_iff (g : Op) (c : Cfg) :
    sector (act g c) = -sector c ↔ g.e = -1 := by
  rw [sector_act]
  exact flip_iff g.e (sector c)

theorem dir_flip_iff (g : Op) (c : Cfg) :
    dir (act g c) = -dir c ↔ g.m * g.e = -1 := by
  rw [dir_act]
  exact flip_iff (g.m * g.e) (dir c)

/- --------------------------------------------------------------------- -/
/-  THEOREM 1 (dossier P1, forward): the co-flip                          -/
/- --------------------------------------------------------------------- -/

/-- **Co-flip.** Flipping the transmitted orientation flips the physical-sector
    G-sign AND the record-accumulation direction, together, in every configuration. -/
theorem coflip (c : Cfg) : sector (act E c) = -sector c ∧ dir (act E c) = -dir c := by
  constructor
  · simp [sector, act, E, Op.e]
  · simp [dir, act, E, Op.e, Op.m]

/- --------------------------------------------------------------------- -/
/-  THEOREM 2 (dossier P1, converse): zero-import operations are diagonal -/
/- --------------------------------------------------------------------- -/

/-- **Zero-import diagonal.** Every zero-import operation acts diagonally on the
    observable pair (sector, direction): both fixed or both flipped. No zero-cost
    decoupling exists in the inventory — the H-REC kill does not fire. -/
theorem zeroImport_diagonal (g : Op) (hg : zeroImport g) (c : Cfg) :
    (sector (act g c) = sector c ∧ dir (act g c) = dir c) ∨
    (sector (act g c) = -sector c ∧ dir (act g c) = -dir c) := by
  have hm : g.m = 1 := hg
  rcases Int.units_eq_one_or g.e with h | h
  · left
    constructor
    · rw [sector_act, h, one_mul]
    · rw [dir_act, hm, h, one_mul, one_mul]
  · right
    constructor
    · rw [sector_act, h, neg_one_mul]
    · rw [dir_act, hm, h, one_mul, neg_one_mul]

/-- Time reversal is inert: it changes neither sector nor direction (dossier P3;
    the register-level reason is `register_direction`'s quantification over
    arbitrary trajectories). -/
theorem timeReversal_inert (c : Cfg) :
    sector (act T c) = sector c ∧ dir (act T c) = dir c := by
  constructor
  · simp [sector, act, T, Op.e]
  · simp [dir, act, T, Op.e, Op.m]

/-- The covariant relabel is inert: a gauge move, invisible to the pair (the
    charge-level reason is `relabel_charge_invariant`). -/
theorem relabel_inert (c : Cfg) :
    sector (act Rl c) = sector c ∧ dir (act Rl c) = dir c := by
  constructor
  · simp [sector, act, Rl, Op.e]
  · simp [dir, act, Rl, Op.e, Op.m]

/-- Sharp form of P3: a zero-import operation that flips the record direction must
    flip the sector too (any zero-import arrow reversal drags the sector). -/
theorem zeroImport_arrow_flip_forces_sector_flip (g : Op) (hg : zeroImport g)
    (c : Cfg) (h : dir (act g c) = -dir c) : sector (act g c) = -sector c := by
  have hm : g.m = 1 := hg
  have he : g.m * g.e = -1 := (dir_flip_iff g c).mp h
  rw [hm, one_mul] at he
  exact (sector_flip_iff g c).mpr he

/- --------------------------------------------------------------------- -/
/-  THEOREM 3 (dossier P2): split-costs-one                               -/
/- --------------------------------------------------------------------- -/

/-- `g` splits the pair at `c`: it flips exactly one of (sector, direction). -/
def splits (g : Op) (c : Cfg) : Prop :=
  Xor (sector (act g c) = -sector c) (dir (act g c) = -dir c)

/-- **Split characterization.** An operation splits the pair iff it engages the
    record-law sign insert — independently of the configuration. -/
theorem splits_iff (g : Op) (c : Cfg) : splits g c ↔ g.m = -1 := by
  simp only [splits, Xor, sector_flip_iff, dir_flip_iff]
  rcases Int.units_eq_one_or g.e with h | h <;>
    rcases Int.units_eq_one_or g.m with h2 | h2 <;>
      rw [h, h2] <;>
        simp [units_one_ne_neg_one, units_neg_one_ne_one]

/-- **No zero-import split** (the kill did not fire, as a theorem). -/
theorem no_zeroImport_split (g : Op) (c : Cfg) (hg : zeroImport g) : ¬ splits g c := by
  intro h
  have hm : g.m = 1 := hg
  have h2 := (splits_iff g c).mp h
  rw [hm] at h2
  exact units_one_ne_neg_one h2

/-- **Split costs exactly one.** Acting on an import-free configuration, any
    splitting operation produces a configuration carrying exactly one underived
    ℤ/2 import: decoupling the arrow from the Krein sign costs precisely one
    additional payload bit. -/
theorem split_costs_one (g : Op) (c : Cfg) (hc : importCost c = 0) (hs : splits g c) :
    importCost (act g c) = 1 := by
  have hm : g.m = -1 := (splits_iff g c).mp hs
  have hcmu : c.mu = 1 := by
    by_contra h
    unfold importCost at hc
    rw [if_neg h] at hc
    exact one_ne_zero hc
  have hact : (act g c).mu = -1 := by
    show g.m * c.mu = -1
    rw [hm, hcmu, mul_one]
  unfold importCost
  rw [hact, if_neg units_neg_one_ne_one]

/-- The record-law sign insert `M` itself is the canonical splitter: direction flips,
    sector holds (the probe's `mu-import-detected` control). -/
theorem M_splits (c : Cfg) :
    splits M c ∧ sector (act M c) = sector c ∧ dir (act M c) = -dir c := by
  refine ⟨(splits_iff M c).mpr rfl, ?_, ?_⟩
  · simp [sector, act, M, Op.e]
  · simp [dir, act, M, Op.e, Op.m]

/-- **Factorization.** Every splitting operation is the paid flip `M` composed with a
    zero-import operation: the second ℤ/2 is exactly one bit, always the same bit. -/
theorem split_factorization (g : Op) (c : Cfg) (hs : splits g c) :
    ∃ g0 : Op, zeroImport g0 ∧ g = M * g0 := by
  have hm : g.m = -1 := (splits_iff g c).mp hs
  refine ⟨M * g, ?_, ?_⟩
  · show (M * g).m = 1
    have hcomp : (M * g).m = M.m * g.m := rfl
    rw [hcomp, hm]
    simp [M, Op.m]
  · rw [← mul_assoc, op_mul_self M, one_mul]

/-- **The one-bit accounting theorem (finite core).** For every operation in the
    inventory group and every configuration: zero-import ⇔ diagonal (no split);
    splitting ⇔ paying the record-law bit; and every splitter factors as the paid
    flip composed with a zero-import operation. Decoupling (sector, direction)
    requires one additional ℤ/2 datum — the N → 5 boundary, exact. -/
theorem one_bit_accounting (g : Op) (c : Cfg) :
    (zeroImport g ↔ ¬ splits g c) ∧
    (splits g c ↔ g.m = -1) ∧
    (splits g c → ∃ g0 : Op, zeroImport g0 ∧ g = M * g0) := by
  refine ⟨⟨fun h => no_zeroImport_split g c h, fun h => ?_⟩,
    splits_iff g c, fun h => split_factorization g c h⟩
  rcases Int.units_eq_one_or g.m with h1 | h1
  · exact h1
  · exact absurd ((splits_iff g c).mpr h1) h

/- --------------------------------------------------------------------- -/
/-  Admissibility: the inventory as a generated group                     -/
/- --------------------------------------------------------------------- -/

/-- The record-law character `Op →* ℤˣ` (projection to the paid coordinate). -/
def recordChar : Op →* ℤˣ :=
  (MonoidHom.fst ℤˣ (ℤˣ × ℤˣ)).comp (MonoidHom.snd ℤˣ (ℤˣ × ℤˣ × ℤˣ))

/-- Zero-import operations are exactly the kernel of the record-law character
    (in particular they form a subgroup). -/
theorem zeroImport_iff_mem_ker (g : Op) : zeroImport g ↔ g ∈ recordChar.ker := by
  rw [MonoidHom.mem_ker]
  exact Iff.rfl

theorem zeroImport_E : zeroImport E := rfl
theorem zeroImport_T : zeroImport T := rfl
theorem zeroImport_Rl : zeroImport Rl := rfl

theorem not_zeroImport_M : ¬ zeroImport M := fun h => units_neg_one_ne_one h

/-- Zero-import operations are exactly the subgroup generated by {E, T, Rl}. This is
    the explicit admissibility definition of this file (H1-alignment anchor): an
    admissible zero-import operation is a composite of the payload flip, the dynamics
    reversal, and the covariant relabel. -/
theorem zeroImport_iff_generated (g : Op) :
    zeroImport g ↔ g ∈ Subgroup.closure ({E, T, Rl} : Set Op) := by
  constructor
  · intro hg
    obtain ⟨a, b, c, d⟩ := g
    have hb : b = 1 := hg
    subst hb
    have hdec : ((a, 1, c, d) : Op) =
        ((a, 1, 1, 1) : Op) * ((1, 1, c, 1) : Op) * ((1, 1, 1, d) : Op) := by
      simp [Prod.mk_mul_mk]
    rw [hdec]
    have hE : ∀ x : ℤˣ, ((x, 1, 1, 1) : Op) ∈ Subgroup.closure ({E, T, Rl} : Set Op) := by
      intro x
      rcases Int.units_eq_one_or x with h | h <;> subst h
      · exact one_mem _
      · exact Subgroup.subset_closure (Set.mem_insert_iff.mpr (Or.inl rfl))
    have hT : ∀ x : ℤˣ, ((1, 1, x, 1) : Op) ∈ Subgroup.closure ({E, T, Rl} : Set Op) := by
      intro x
      rcases Int.units_eq_one_or x with h | h <;> subst h
      · exact one_mem _
      · exact Subgroup.subset_closure
          (Set.mem_insert_iff.mpr (Or.inr (Set.mem_insert_iff.mpr (Or.inl rfl))))
    have hR : ∀ x : ℤˣ, ((1, 1, 1, x) : Op) ∈ Subgroup.closure ({E, T, Rl} : Set Op) := by
      intro x
      rcases Int.units_eq_one_or x with h | h <;> subst h
      · exact one_mem _
      · exact Subgroup.subset_closure
          (Set.mem_insert_iff.mpr (Or.inr (Set.mem_insert_iff.mpr
            (Or.inr (Set.mem_singleton_iff.mpr rfl)))))
    exact mul_mem (mul_mem (hE a) (hT c)) (hR d)
  · intro hg
    rw [zeroImport_iff_mem_ker]
    have hle : Subgroup.closure ({E, T, Rl} : Set Op) ≤ recordChar.ker := by
      rw [Subgroup.closure_le]
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl | rfl <;> rw [SetLike.mem_coe, MonoidHom.mem_ker] <;> rfl
    exact hle hg

/-- The four named generators generate the whole inventory group: the enumerated
    inventory {E, M, T, Rl} is complete *for this presentation*. (Exhaustiveness for
    the full GU construction — dossier G-A1/G-A2 — is NOT claimed.) -/
theorem inventory_generates (g : Op) :
    g ∈ Subgroup.closure ({E, M, T, Rl} : Set Op) := by
  obtain ⟨a, b, c, d⟩ := g
  have hdec : ((a, b, c, d) : Op) =
      ((a, 1, 1, 1) : Op) * ((1, b, 1, 1) : Op) * ((1, 1, c, 1) : Op) *
        ((1, 1, 1, d) : Op) := by
    simp [Prod.mk_mul_mk]
  rw [hdec]
  have hE : ∀ x : ℤˣ, ((x, 1, 1, 1) : Op) ∈ Subgroup.closure ({E, M, T, Rl} : Set Op) := by
    intro x
    rcases Int.units_eq_one_or x with h | h <;> subst h
    · exact one_mem _
    · exact Subgroup.subset_closure (Set.mem_insert_iff.mpr (Or.inl rfl))
  have hM : ∀ x : ℤˣ, ((1, x, 1, 1) : Op) ∈ Subgroup.closure ({E, M, T, Rl} : Set Op) := by
    intro x
    rcases Int.units_eq_one_or x with h | h <;> subst h
    · exact one_mem _
    · exact Subgroup.subset_closure
        (Set.mem_insert_iff.mpr (Or.inr (Set.mem_insert_iff.mpr (Or.inl rfl))))
  have hT : ∀ x : ℤˣ, ((1, 1, x, 1) : Op) ∈ Subgroup.closure ({E, M, T, Rl} : Set Op) := by
    intro x
    rcases Int.units_eq_one_or x with h | h <;> subst h
    · exact one_mem _
    · exact Subgroup.subset_closure
        (Set.mem_insert_iff.mpr (Or.inr (Set.mem_insert_iff.mpr
          (Or.inr (Set.mem_insert_iff.mpr (Or.inl rfl))))))
  have hR : ∀ x : ℤˣ, ((1, 1, 1, x) : Op) ∈ Subgroup.closure ({E, M, T, Rl} : Set Op) := by
    intro x
    rcases Int.units_eq_one_or x with h | h <;> subst h
    · exact one_mem _
    · exact Subgroup.subset_closure
        (Set.mem_insert_iff.mpr (Or.inr (Set.mem_insert_iff.mpr
          (Or.inr (Set.mem_insert_iff.mpr (Or.inr (Set.mem_singleton_iff.mpr rfl)))))))
  exact mul_mem (mul_mem (mul_mem (hE a) (hM b)) (hT c)) (hR d)

/- --------------------------------------------------------------------- -/
/-  End-to-end concrete instances (Part A driving Part B)                 -/
/- --------------------------------------------------------------------- -/

/-- On the unit state's one-step trajectory — with the charge computed from the
    concrete Krein toy in the configuration's own gauge — every configuration's
    register realizes its direction observable. -/
theorem concrete_direction (c : Cfg) :
    0 < sv (dir c) * register c.mu c.eps [charge c.gauge c.eps (1, 1)] := by
  apply dir_spec
  simpa using unit_state_charge_pos c.gauge c.eps

/-- End-to-end co-flip instance: the payload flip flips direction and sector, and the
    flipped configuration's register (on the concrete unit-state trajectory, in its
    own gauge) realizes the flipped direction. Nothing here is stipulated: the charge
    comes from the (1,1) Krein toy and the direction from the register theorem. -/
theorem concrete_coflip (c : Cfg) :
    dir (act E c) = -dir c ∧ sector (act E c) = -sector c ∧
      0 < sv (dir (act E c)) *
        register (act E c).mu (act E c).eps
          [charge (act E c).gauge (act E c).eps (1, 1)] :=
  ⟨(coflip c).2, (coflip c).1, concrete_direction (act E c)⟩

end CoflipCore
end GUFormalization
