import GUFormalization.GroupActionFixedPoints
import GUFormalization.GroupActionCoproducts
import GUFormalization.EquivariantInternalHom
import GUFormalization.GroupActionChangeOfGroups
import GUFormalization.GroupActionInduction
import GUFormalization.GroupActionInductionCoherence
import GUFormalization.GroupActionMackey

/-!
# Axiom receipt for the group-action fixed-point classification

This module is part of the default Lean target, so routine `lake build`
replays the theorem-family receipt. The commands are informational: they
report the exact axioms on which each exported theorem depends.
-/

open GUFormalization.GroupActionFixedPoints
open GUFormalization.EquivariantInternalHom
open GUFormalization.GroupActionChangeOfGroups
open GUFormalization.GroupActionInduction
open GUFormalization.GroupActionInductionCoherence
open GUFormalization.GroupActionMackey

#print axioms mem_commonFixedPoints_iff
#print axioms pointwiseInvariant_iff_range_subset
#print axioms pointwiseInvariant_iff_values_mem
#print axioms invariantValuationEquivFixedPointValuation
#print axioms natCard_invariantValuation
#print axioms natCard_invariantValuation_eq_zero_iff
#print axioms natCard_invariantValuation_eq_one_of_isEmpty
#print axioms regularEquivariantMapEquivValue
#print axioms existsUnique_regularEquivariantMap_eval
#print axioms natCard_regularEquivariantMap
#print axioms equivariantMapEquivStabilizerFixedValue
#print axioms natCard_equivariantMap
#print axioms nonempty_equivariantMap_iff_stabilizerFixedValue
#print axioms equivariantMapEquivOfDomainEquiv
#print axioms natCard_equivariantMap_eq_of_domainEquiv
#print axioms nonempty_equivariantMap_iff_of_domainEquiv
#print axioms equivariantMapEquivOfCodomainEquiv
#print axioms natCard_equivariantMap_eq_of_codomainEquiv
#print axioms nonempty_equivariantMap_iff_of_codomainEquiv
#print axioms equivariantMap_domainEquiv_codomainEquiv_commute
#print axioms equivariantMapEquivPi
#print axioms natCard_equivariantMap_pi
#print axioms nonempty_equivariantMap_pi_iff
#print axioms fixedPointValueEquivOfCodomainEquiv
#print axioms stabilizerFixedValueEquivOfCodomainEquiv
#print axioms natCard_fixedPointValue_eq_of_codomainEquiv
#print axioms natCard_stabilizerFixedValue_eq_of_codomainEquiv
#print axioms fixedPointValueEquivPi
#print axioms stabilizerFixedValueEquivPi
#print axioms natCard_fixedPointValue_pi
#print axioms natCard_stabilizerFixedValue_pi
#print axioms nonempty_fixedPointValue_pi_iff
#print axioms nonempty_stabilizerFixedValue_pi_iff
#print axioms equivariantMapEquivSigma
#print axioms natCard_equivariantMap_sigma
#print axioms nonempty_equivariantMap_sigma_iff
#print axioms internalHomMulAction
#print axioms internalHomFixedPointEquivEquivariantMap
#print axioms equivariantMapCurry
#print axioms restrictedMulAction
#print axioms restrictEquivariantMap
#print axioms equivariantMapEquivRestricted_of_surjective
#print axioms fixedPointValueEquivRestricted_of_surjective
#print axioms natCard_equivariantMap_eq_restricted_of_surjective
#print axioms nonempty_equivariantMap_iff_restricted_of_surjective
#print axioms CoinducedCarrier
#print axioms coinducedMulAction
#print axioms restrictionCoinductionEquiv
#print axioms natCard_restriction_eq_coinduction
#print axioms nonempty_restriction_iff_coinduction
#print axioms inductionPairMulAction
#print axioms InducedCarrier
#print axioms inducedMulAction
#print axioms inducedMk_mul_phi
#print axioms inductionRestrictionEquiv
#print axioms natCard_induction_eq_restriction
#print axioms nonempty_induction_iff_restriction
#print axioms inductionIdentityEquiv
#print axioms inductionIdentityEquiv_equivariant
#print axioms inductionCompositionEquiv
#print axioms inductionCompositionEquiv_equivariant
#print axioms doubleCosetMulAction
#print axioms restrictedInducedPointOrbitEquivDoubleCoset
#print axioms restrictedInducedPoint_stabilizer_iff
#print axioms stabilizer_restrictedInducedPoint_eq_transportedIntersection
#print axioms transportedIntersectionToH
#print axioms transportedIntersectionToH_spec
#print axioms mackeySummandToRestrictedInduced
#print axioms mackeySummandToRestrictedInduced_injective
#print axioms mem_mackeySummandImage_iff
#print axioms mackeySummandEquivImage
#print axioms mackeySummandEquivImage_equivariant
#print axioms orbitIndexMapOfEquivariantEquiv
#print axioms orbitIndexEquivOfDomainEquiv
#print axioms orbitIndexEquivOfDomainEquiv_mk
#print axioms natCard_orbitIndex_eq_of_domainEquiv
#print axioms equivariantMapEquivOrbitStabilizerFixedSection
#print axioms natCard_equivariantMap_orbitProduct
#print axioms nonempty_equivariantMap_iff_forall_orbit_stabilizerFixedValue
#print axioms stabilizerFixedValueEquiv_of_fixedSets_eq
#print axioms equivariantMapEquivOrbitValuation_of_fixedSets_eq
#print axioms natCard_equivariantMap_of_fixedSets_eq
#print axioms nonempty_equivariantMap_iff_stabilizerFixedValue_of_fixedSets_eq
#print axioms stabilizerFixedValueEquiv_smul
#print axioms natCard_stabilizerFixedValue_smul
#print axioms stabilizerFixedValueEquivValue_of_isCancelSMul
#print axioms equivariantMapEquivOrbitValuation_of_isCancelSMul
#print axioms natCard_equivariantMap_of_isCancelSMul
#print axioms nonempty_equivariantMap_iff_nonempty_of_isCancelSMul
#print axioms stabilizerFixedValueEquivValue_of_trivial
#print axioms equivariantMapEquivOrbitValuation_of_trivial
#print axioms natCard_equivariantMap_of_trivial
#print axioms nonempty_equivariantMap_iff_nonempty_of_trivial
#print axioms stabilizerFixedValues_regular_one
#print axioms exists_pointwiseInvariant_iff_commonFixedPoints_nonempty
#print axioms commonFixedPoints_eq_empty_of_fixpointFreeElement
#print axioms no_pointwiseInvariant_of_commonFixedPoints_eq_empty
#print axioms no_pointwiseInvariant_iff_commonFixedPoints_eq_empty
#print axioms no_pointwiseInvariant_of_fixpointFreeElement
