import GUFormalization.GroupActionBurnsideBisetCoend
import Mathlib.GroupTheory.FreeAbelianGroup

/-!
# Additive coend presentation for Burnside restriction correspondences

The all-middle set quotient is upgraded here to the additive presentation
appropriate to the additive Burnside-span hom groups.  We take the free
abelian group on all composable pairs and quotient by the subgroup generated
by left additivity, right additivity, and arbitrary-middle balance.  Every
biadditive balanced evaluator factors uniquely through the resulting additive
group.

This is an additive-group-valued coend presentation for the supplied
restriction-correspondence data.  It is not a biset bicategory,
ambidexterity theorem, Mackey 2-functor, source action, or physical model.
-/

set_option autoImplicit false

namespace GUFormalization
namespace GroupActionBurnsideAdditiveCoend

noncomputable section

open CategoryTheory
open GroupActionBurnside
open GroupActionBurnsideSpanCategory
open GroupActionBurnsideSpanRestriction
open GroupActionBurnsideSpanCorrespondence
open GroupActionBurnsideSpanCorrespondenceComposition
open GroupActionBurnsideBisetCoend

universe u v

variable {H K L : Type u} [Group H] [Group K] [Group L]

/-- The three relation families required for an additive coend: additivity in
each correspondence variable and dinatural balance through every intermediate
morphism. -/
inductive AdditiveCoendRelation (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) :
    FreeAbelianGroup (AllMiddlePair phi psi A C) → Prop
  | left_add (B : AdditiveBurnsideSpanObject K)
      (x x' : RestrictionCorrespondence phi A B)
      (y : RestrictionCorrespondence psi B C) :
      AdditiveCoendRelation phi psi A C
        (FreeAbelianGroup.of ⟨B, x + x', y⟩ -
          FreeAbelianGroup.of ⟨B, x, y⟩ -
          FreeAbelianGroup.of ⟨B, x', y⟩)
  | right_add (B : AdditiveBurnsideSpanObject K)
      (x : RestrictionCorrespondence phi A B)
      (y y' : RestrictionCorrespondence psi B C) :
      AdditiveCoendRelation phi psi A C
        (FreeAbelianGroup.of ⟨B, x, y + y'⟩ -
          FreeAbelianGroup.of ⟨B, x, y⟩ -
          FreeAbelianGroup.of ⟨B, x, y'⟩)
  | balance (B B' : AdditiveBurnsideSpanObject K)
      (x : RestrictionCorrespondence phi A B) (k : B ⟶ B')
      (y : RestrictionCorrespondence psi B' C) :
      AdditiveCoendRelation phi psi A C
        (FreeAbelianGroup.of ⟨B', rightAction phi k x, y⟩ -
          FreeAbelianGroup.of ⟨B, x, leftAction psi k y⟩)

/-- The subgroup generated by the additive and balance relations. -/
def additiveCoendRelations (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) :
    AddSubgroup (FreeAbelianGroup (AllMiddlePair phi psi A C)) :=
  AddSubgroup.closure {z | AdditiveCoendRelation phi psi A C z}

/-- The additive balanced coend presentation. -/
abbrev AdditiveBalancedCoend (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) :=
  FreeAbelianGroup (AllMiddlePair phi psi A C) ⧸
    additiveCoendRelations phi psi A C

/-- The canonical generator represented by one composable pair. -/
def coendGenerator (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    (p : AllMiddlePair phi psi A C) :
    AdditiveBalancedCoend phi psi A C :=
  QuotientAddGroup.mk' (additiveCoendRelations phi psi A C)
    (FreeAbelianGroup.of p)

/-- A target-valued evaluator that is additive in both correspondence
variables and balanced across arbitrary intermediate morphisms. -/
structure AdditiveBalancedEvaluator (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L)
    (Z : Type v) [AddCommGroup Z] where
  eval : AllMiddlePair phi psi A C → Z
  left_add : ∀ (B : AdditiveBurnsideSpanObject K)
    (x x' : RestrictionCorrespondence phi A B)
    (y : RestrictionCorrespondence psi B C),
    eval ⟨B, x + x', y⟩ = eval ⟨B, x, y⟩ + eval ⟨B, x', y⟩
  right_add : ∀ (B : AdditiveBurnsideSpanObject K)
    (x : RestrictionCorrespondence phi A B)
    (y y' : RestrictionCorrespondence psi B C),
    eval ⟨B, x, y + y'⟩ = eval ⟨B, x, y⟩ + eval ⟨B, x, y'⟩
  balance : ∀ (B B' : AdditiveBurnsideSpanObject K)
    (x : RestrictionCorrespondence phi A B) (k : B ⟶ B')
    (y : RestrictionCorrespondence psi B' C),
    eval ⟨B', rightAction phi k x, y⟩ =
      eval ⟨B, x, leftAction psi k y⟩

/-- Extend an evaluator additively to the free abelian group. -/
def AdditiveBalancedEvaluator.freeLift
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    {Z : Type v} [AddCommGroup Z]
    (E : AdditiveBalancedEvaluator phi psi A C Z) :
    FreeAbelianGroup (AllMiddlePair phi psi A C) →+ Z :=
  FreeAbelianGroup.lift E.eval

theorem AdditiveBalancedEvaluator.relation_killed
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    {Z : Type v} [AddCommGroup Z]
    (E : AdditiveBalancedEvaluator phi psi A C Z)
    {z : FreeAbelianGroup (AllMiddlePair phi psi A C)}
    (hz : AdditiveCoendRelation phi psi A C z) :
    E.freeLift phi psi z = 0 := by
  cases hz with
  | left_add B x x' y => simp [AdditiveBalancedEvaluator.freeLift, E.left_add]
  | right_add B x y y' => simp [AdditiveBalancedEvaluator.freeLift, E.right_add]
  | balance B B' x k y => simp [AdditiveBalancedEvaluator.freeLift, E.balance]

theorem AdditiveBalancedEvaluator.relations_le_kernel
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    {Z : Type v} [AddCommGroup Z]
    (E : AdditiveBalancedEvaluator phi psi A C Z) :
    additiveCoendRelations phi psi A C ≤ (E.freeLift phi psi).ker := by
  rw [additiveCoendRelations, AddSubgroup.closure_le]
  intro z hz
  change E.freeLift phi psi z = 0
  exact E.relation_killed phi psi hz

/-- Every biadditive balanced evaluator descends to an additive homomorphism
out of the additive coend. -/
def AdditiveBalancedEvaluator.descend
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    {Z : Type v} [AddCommGroup Z]
    (E : AdditiveBalancedEvaluator phi psi A C Z) :
    AdditiveBalancedCoend phi psi A C →+ Z :=
  QuotientAddGroup.lift (additiveCoendRelations phi psi A C)
    (E.freeLift phi psi) (E.relations_le_kernel phi psi)

@[simp]
theorem AdditiveBalancedEvaluator.descend_generator
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    {Z : Type v} [AddCommGroup Z]
    (E : AdditiveBalancedEvaluator phi psi A C Z)
    (p : AllMiddlePair phi psi A C) :
    E.descend phi psi (coendGenerator phi psi p) = E.eval p := by
  simp [AdditiveBalancedEvaluator.descend, coendGenerator,
    AdditiveBalancedEvaluator.freeLift]

/-- Actual restriction-correspondence composition is a biadditive balanced
evaluator. -/
def compositionEvaluator
    (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) :
    AdditiveBalancedEvaluator phi psi A C
      (IteratedRestrictionCorrespondence phi psi A C) where
  eval := fun p => compose phi psi p.first p.second
  left_add := fun _ x x' y => compose_add_left phi psi x x' y
  right_add := fun _ x y y' => compose_add_right phi psi x y y'
  balance := fun _ _ x k y => compose_middle_balance phi psi x k y

/-- Restriction-correspondence composition therefore descends as an additive
homomorphism from the additive coend. -/
def additiveBalancedCompose
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L} :
    AdditiveBalancedCoend phi psi A C →+
      IteratedRestrictionCorrespondence phi psi A C :=
  (compositionEvaluator phi psi A C).descend phi psi

@[simp]
theorem additiveBalancedCompose_generator
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    (p : AllMiddlePair phi psi A C) :
    additiveBalancedCompose phi psi (coendGenerator phi psi p) =
      compose phi psi p.first p.second := by
  exact (compositionEvaluator phi psi A C).descend_generator phi psi p

/-- The additive factorization is unique: agreement on all pair-generators
determines the homomorphism from the additive coend. -/
theorem AdditiveBalancedEvaluator.descend_unique
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    {Z : Type v} [AddCommGroup Z]
    (E : AdditiveBalancedEvaluator phi psi A C Z)
    (f : AdditiveBalancedCoend phi psi A C →+ Z)
    (h : ∀ p : AllMiddlePair phi psi A C,
      f (coendGenerator phi psi p) = E.eval p) :
    f = E.descend phi psi := by
  apply AddMonoidHom.ext
  intro q
  induction q using QuotientAddGroup.induction_on with
  | H a =>
      have hfree :
          f.comp (QuotientAddGroup.mk' (additiveCoendRelations phi psi A C)) =
            E.freeLift phi psi := by
        apply FreeAbelianGroup.lift_ext
        intro p
        simpa [coendGenerator, AdditiveBalancedEvaluator.freeLift] using h p
      simpa [AdditiveBalancedEvaluator.descend] using
        DFunLike.congr_fun hfree a

end

end GroupActionBurnsideAdditiveCoend
end GUFormalization
