import GUFormalization.GroupActionMackeyLinearization
import Mathlib.RepresentationTheory.Intertwining

/-!
# Permutation-representation form of the canonical Mackey decomposition

The free-module lift of the canonical Mackey carrier is more than an isolated
linear equivalence.  Linearizing each supplied set action gives a genuine
permutation representation, and the canonical Mackey equivalence is an
equivalence of those `K`-representations.  Over a commutative semiring it is
therefore also an isomorphism of modules over the group algebra `R[K]`.

The construction still begins with supplied set actions.  It does not build an
additive Mackey functor on physical representations, identify a source-native
action, or select any coupling or observable.
-/

namespace GUFormalization
namespace GroupActionMackeyRepresentations

open GroupActionFixedPoints GroupActionInduction GroupActionMackey
  GroupActionMackeyLinearization
open scoped MonoidAlgebra

universe u v w

variable {G : Type u} [Group G]
variable (R : Type w) [Semiring R]

/-- Linearizing a supplied action on a basis type gives its free permutation
representation. -/
noncomputable def freePermutationRepresentation (K : Type u) [Group K]
    (X : Type v) [MulAction K X] : Representation R K (FreeModule R X) where
  toFun k := linearizeMap R fun x => k • x
  map_one' := by
    ext x r
    simp [linearizeMap]
  map_mul' k l := by
    ext x r
    simp [linearizeMap, mul_smul]

@[simp]
theorem freePermutationRepresentation_single (K : Type u) [Group K]
    (X : Type v) [MulAction K X] (k : K) (x : X) (r : R) :
    freePermutationRepresentation R K X k (Finsupp.single x r) =
      Finsupp.single (k • x) r := by
  simp [freePermutationRepresentation, linearizeMap]

/-- The permutation representation on the canonical, representative-free
Mackey coproduct. -/
noncomputable def canonicalMackeyPermutationRepresentation
    (K H : Subgroup G) {B : Type v} [MulAction H B] :
    Representation R K
      (FreeModule R (CanonicalMackeyCoproductCarrier K H B)) := by
  letI : MulAction K (CanonicalMackeyCoproductCarrier K H B) :=
    canonicalMackeyCoproductMulAction K H B
  exact freePermutationRepresentation R K
    (CanonicalMackeyCoproductCarrier K H B)

/-- The permutation representation on the restricted induced carrier. -/
noncomputable def restrictedInducedPermutationRepresentation
    (K H : Subgroup G) {B : Type v} [MulAction H B] :
    Representation R K (FreeModule R (SubgroupInducedCarrier H B)) := by
  letI : MulAction K (SubgroupInducedCarrier H B) :=
    restrictedSubgroupInducedMulAction K H B
  exact freePermutationRepresentation R K (SubgroupInducedCarrier H B)

/-- The canonical Mackey free-module equivalence is an equivalence of the
permutation representations generated by the two supplied `K`-sets. -/
noncomputable def canonicalMackeyPermutationRepresentationEquiv
    (K H : Subgroup G) {B : Type v} [MulAction H B] :
    (canonicalMackeyPermutationRepresentation R K H (B := B)).Equiv
      (restrictedInducedPermutationRepresentation R K H (B := B)) :=
  Representation.Equiv.mk (canonicalMackeyFreeLinearEquiv R K H) fun k => by
    change
      (canonicalMackeyFreeLinearEquiv R K H).toLinearMap.comp
          (linearizeMap R fun x : CanonicalMackeyCoproductCarrier K H B =>
            @SMul.smul K (CanonicalMackeyCoproductCarrier K H B)
              (canonicalMackeyCoproductMulAction K H B).toSMul k x) =
        (linearizeMap R fun x : SubgroupInducedCarrier H B =>
            @SMul.smul K (SubgroupInducedCarrier H B)
              (restrictedSubgroupInducedMulAction K H B).toSMul k x).comp
          (canonicalMackeyFreeLinearEquiv R K H).toLinearMap
    exact canonicalMackeyFreeLinearEquiv_equivariant R K H k

@[simp]
theorem canonicalMackeyPermutationRepresentationEquiv_single
    (K H : Subgroup G) {B : Type v} [MulAction H B]
    (x : CanonicalMackeyCoproductCarrier K H B) (r : R) :
    canonicalMackeyPermutationRepresentationEquiv R K H
        (Finsupp.single x r) =
      Finsupp.single
        (canonicalMackeyCoproductEquivRestrictedInduced K H x) r := by
  simp [canonicalMackeyPermutationRepresentationEquiv]

/-- Over a commutative semiring, the representation equivalence is exactly an
isomorphism of modules over the group algebra `R[K]`. -/
noncomputable def canonicalMackeyGroupAlgebraLinearEquiv
    (R : Type w) [CommSemiring R] (K H : Subgroup G)
    {B : Type v} [MulAction H B] :
    (canonicalMackeyPermutationRepresentation R K H (B := B)).asModule ≃ₗ[R[K]]
      (restrictedInducedPermutationRepresentation R K H (B := B)).asModule := by
  let phi := canonicalMackeyPermutationRepresentationEquiv R K H (B := B)
  exact LinearEquiv.ofBijective
    (Representation.IntertwiningMap.equivLinearMapAsModule _ _
      phi.toIntertwiningMap)
    phi.bijective

@[simp]
theorem canonicalMackeyGroupAlgebraLinearEquiv_apply
    (R : Type w) [CommSemiring R] (K H : Subgroup G)
    {B : Type v} [MulAction H B]
    (x : (canonicalMackeyPermutationRepresentation R K H (B := B)).asModule) :
    canonicalMackeyGroupAlgebraLinearEquiv R K H x =
      canonicalMackeyFreeLinearEquiv R K H x := by
  rfl

end GroupActionMackeyRepresentations
end GUFormalization
