import GUFormalization.GroupActionBurnsideSpanCorrespondenceComposition

/-!
# Balanced quotients for Burnside restriction correspondences

For homomorphisms `H -> K -> L`, restriction correspondences carry the two
actions needed for the usual coend balance relation. This file proves the
fixed-middle quotient and then ranges over all intermediate additive
Burnside-span objects and morphisms. The all-middle quotient has the expected
set-valued factorization and uniqueness property for every balanced evaluator.
Three-stage composition is coherent.

This is not a biset bicategory, an additive/category-valued coend,
ambidexterity, a Mackey 2-functor, or a physical/source realization.
-/

set_option autoImplicit false

namespace GUFormalization
namespace GroupActionBurnsideBisetCoend

noncomputable section

open CategoryTheory
open GroupActionBurnside
open GroupActionBurnsideSpanCategory
open GroupActionBurnsideSpanRestriction
open GroupActionBurnsideSpanCorrespondence
open GroupActionBurnsideSpanCorrespondenceComposition

universe u

variable {H K L M : Type u} [Group H] [Group K] [Group L] [Group M]

/-- The defining balance law at the intermediate `K`-object: acting on the
right of the first correspondence is the same after composition as acting on
the left of the second correspondence. -/
theorem compose_middle_balance (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B B' : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    (x : RestrictionCorrespondence phi A B)
    (k : B ⟶ B')
    (y : RestrictionCorrespondence psi B' C) :
    compose phi psi (rightAction phi k x) y =
      compose phi psi x (leftAction psi k y) := by
  change (x ≫ (restrictionFunctor phi).map k) ≫
      (restrictionFunctor phi).map y =
    x ≫ (restrictionFunctor phi).map (k ≫ y)
  rw [(restrictionFunctor phi).map_comp]
  exact Category.assoc x ((restrictionFunctor phi).map k)
    ((restrictionFunctor phi).map y)

/-- A pair of restriction correspondences with one fixed intermediate
`K`-object. -/
structure FixedMiddlePair (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (B : AdditiveBurnsideSpanObject K)
    (C : AdditiveBurnsideSpanObject L) where
  first : RestrictionCorrespondence phi A B
  second : RestrictionCorrespondence psi B C

/-- One generating middle-action move.  Its equivalence closure is the
fixed-intermediate analogue of the balance quotient in biset/coend
composition. -/
inductive MiddleMove (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (B : AdditiveBurnsideSpanObject K)
    (C : AdditiveBurnsideSpanObject L) :
    FixedMiddlePair phi psi A B C → FixedMiddlePair phi psi A B C → Prop
  | balance (x : RestrictionCorrespondence phi A B) (k : B ⟶ B)
      (y : RestrictionCorrespondence psi B C) :
      MiddleMove phi psi A B C
        ⟨rightAction phi k x, y⟩
        ⟨x, leftAction psi k y⟩

/-- Composition is constant on the equivalence relation generated by the
middle-action moves. -/
theorem compose_eq_of_eqvGen (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {p q : FixedMiddlePair phi psi A B C}
    (h : Relation.EqvGen (MiddleMove phi psi A B C) p q) :
    compose phi psi p.first p.second =
      compose phi psi q.first q.second := by
  induction h with
  | rel p q hpq =>
      cases hpq with
      | balance x k y => exact compose_middle_balance phi psi x k y
  | refl => rfl
  | symm p q _ ih => exact ih.symm
  | trans p q r _ _ hpq hqr => exact hpq.trans hqr

/-- The quotient generated by the genuine intermediate endomorphism balance
moves, with the intermediate object held fixed. -/
abbrev FixedMiddleBalancedQuotient (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (B : AdditiveBurnsideSpanObject K)
    (C : AdditiveBurnsideSpanObject L) :=
  Quotient (Relation.EqvGen.setoid (MiddleMove phi psi A B C))

/-- Restriction-correspondence composition descends to the fixed-middle
balanced quotient. -/
def balancedCompose (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L} :
    FixedMiddleBalancedQuotient phi psi A B C →
      IteratedRestrictionCorrespondence phi psi A C :=
  Quotient.lift
    (fun p => compose phi psi p.first p.second)
    (fun _ _ h => compose_eq_of_eqvGen phi psi h)

@[simp]
theorem balancedCompose_mk (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    (p : FixedMiddlePair phi psi A B C) :
    balancedCompose phi psi (Quotient.mk _ p) =
      compose phi psi p.first p.second := rfl

/-! ## The all-intermediate-object coend presentation -/

/-- A composable pair whose intermediate additive Burnside-span object is
part of the data rather than fixed in advance. -/
structure AllMiddlePair (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) where
  middle : AdditiveBurnsideSpanObject K
  first : RestrictionCorrespondence phi A middle
  second : RestrictionCorrespondence psi middle C

/-- The coend balance move across an arbitrary morphism between two possibly
different intermediate objects. -/
inductive AllMiddleMove (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) :
    AllMiddlePair phi psi A C → AllMiddlePair phi psi A C → Prop
  | balance (B B' : AdditiveBurnsideSpanObject K)
      (x : RestrictionCorrespondence phi A B) (k : B ⟶ B')
      (y : RestrictionCorrespondence psi B' C) :
      AllMiddleMove phi psi A C
        ⟨B', rightAction phi k x, y⟩
        ⟨B, x, leftAction psi k y⟩

/-- Composition is constant on the equivalence relation generated by every
all-middle balance move. -/
theorem compose_eq_of_allMiddle_eqvGen (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    {p q : AllMiddlePair phi psi A C}
    (h : Relation.EqvGen (AllMiddleMove phi psi A C) p q) :
    compose phi psi p.first p.second =
      compose phi psi q.first q.second := by
  induction h with
  | rel p q hpq =>
      cases hpq with
      | balance B B' x k y => exact compose_middle_balance phi psi x k y
  | refl => rfl
  | symm p q _ ih => exact ih.symm
  | trans p q r _ _ hpq hqr => exact hpq.trans hqr

/-- The all-intermediate-object balanced quotient. -/
abbrev AllMiddleBalancedQuotient (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) :=
  Quotient (Relation.EqvGen.setoid (AllMiddleMove phi psi A C))

/-- Restriction-correspondence composition descends across arbitrary changes
of intermediate object. -/
def allMiddleBalancedCompose (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L} :
    AllMiddleBalancedQuotient phi psi A C →
      IteratedRestrictionCorrespondence phi psi A C :=
  Quotient.lift
    (fun p => compose phi psi p.first p.second)
    (fun _ _ h => compose_eq_of_allMiddle_eqvGen phi psi h)

@[simp]
theorem allMiddleBalancedCompose_mk (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L}
    (p : AllMiddlePair phi psi A C) :
    allMiddleBalancedCompose phi psi (Quotient.mk _ p) =
      compose phi psi p.first p.second := rfl

/-- A set-valued evaluator on composable pairs together with the exact
dinaturality/balance equation required for coend descent. -/
structure BalancedEvaluator (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (C : AdditiveBurnsideSpanObject L) (Z : Sort*) where
  eval : AllMiddlePair phi psi A C → Z
  balance : ∀ (B B' : AdditiveBurnsideSpanObject K)
    (x : RestrictionCorrespondence phi A B) (k : B ⟶ B')
    (y : RestrictionCorrespondence psi B' C),
    eval ⟨B', rightAction phi k x, y⟩ =
      eval ⟨B, x, leftAction psi k y⟩

theorem BalancedEvaluator.eq_of_eqvGen
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L} {Z : Sort*}
    (E : BalancedEvaluator phi psi A C Z)
    {p q : AllMiddlePair phi psi A C}
    (h : Relation.EqvGen (AllMiddleMove phi psi A C) p q) :
    E.eval p = E.eval q := by
  induction h with
  | rel p q hpq =>
      cases hpq with
      | balance B B' x k y => exact E.balance B B' x k y
  | refl => rfl
  | symm p q _ ih => exact ih.symm
  | trans p q r _ _ hpq hqr => exact hpq.trans hqr

/-- Every balanced evaluator factors through the all-middle quotient. -/
def BalancedEvaluator.descend
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L} {Z : Sort*}
    (E : BalancedEvaluator phi psi A C Z) :
    AllMiddleBalancedQuotient phi psi A C → Z :=
  Quotient.lift E.eval (fun _ _ h => E.eq_of_eqvGen phi psi h)

@[simp]
theorem BalancedEvaluator.descend_mk
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L} {Z : Sort*}
    (E : BalancedEvaluator phi psi A C Z)
    (p : AllMiddlePair phi psi A C) :
    E.descend phi psi (Quotient.mk _ p) = E.eval p := rfl

/-- The factorization is unique: agreeing on every representative determines
the map out of the all-middle quotient. -/
theorem BalancedEvaluator.descend_unique
    (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {C : AdditiveBurnsideSpanObject L} {Z : Sort*}
    (E : BalancedEvaluator phi psi A C Z)
    (f : AllMiddleBalancedQuotient phi psi A C → Z)
    (h : ∀ p : AllMiddlePair phi psi A C,
      f (Quotient.mk _ p) = E.eval p) :
    f = E.descend phi psi := by
  funext q
  induction q using Quotient.inductionOn with
  | _ p => exact h p

/-- The common target for three composable restriction correspondences. -/
abbrev TripleIteratedRestrictionCorrespondence
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    (A : AdditiveBurnsideSpanObject H)
    (D : AdditiveBurnsideSpanObject M) :=
  A ⟶ (restrictionFunctor phi).obj
    ((restrictionFunctor psi).obj ((restrictionFunctor chi).obj D))

/-- First compose at `K`, then append the twice-restricted third
correspondence. -/
def composeLeftAssociated
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {D : AdditiveBurnsideSpanObject M}
    (x : RestrictionCorrespondence phi A B)
    (y : RestrictionCorrespondence psi B C)
    (z : RestrictionCorrespondence chi C D) :
    TripleIteratedRestrictionCorrespondence phi psi chi A D :=
  compose phi psi x y ≫
    (restrictionFunctor phi).map ((restrictionFunctor psi).map z)

/-- First compose at `L`, then restrict that composite and append it to the
first correspondence. -/
def composeRightAssociated
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {D : AdditiveBurnsideSpanObject M}
    (x : RestrictionCorrespondence phi A B)
    (y : RestrictionCorrespondence psi B C)
    (z : RestrictionCorrespondence chi C D) :
    TripleIteratedRestrictionCorrespondence phi psi chi A D :=
  x ≫ (restrictionFunctor phi).map (compose psi chi y z)

/-- Three-stage restriction-correspondence composition is associative after
the canonical functorial expansion inside the same iterated-restriction
target. -/
theorem compose_associativity_coherence
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {D : AdditiveBurnsideSpanObject M}
    (x : RestrictionCorrespondence phi A B)
    (y : RestrictionCorrespondence psi B C)
    (z : RestrictionCorrespondence chi C D) :
    composeLeftAssociated phi psi chi x y z =
      composeRightAssociated phi psi chi x y z := by
  unfold composeLeftAssociated composeRightAssociated compose
  rw [(restrictionFunctor phi).map_comp]
  exact Category.assoc x ((restrictionFunctor phi).map y)
    ((restrictionFunctor phi).map ((restrictionFunctor psi).map z))

end

end GroupActionBurnsideBisetCoend
end GUFormalization
