import GUFormalization.GroupActionBurnsideSpanCorrespondenceComposition

/-!
# A fixed-middle balanced quotient for Burnside restriction correspondences

For homomorphisms `H -> K -> L`, restriction correspondences carry the two
actions needed for the usual coend balance relation.  This file proves the
defining middle-action equation, forms the equivalence closure generated by
that equation for one fixed intermediate `K`-object, and descends composition
to the resulting quotient.  It also proves the three-stage associativity
coherence inside iterated categorical restriction.

The quotient here has a fixed intermediate object.  It is therefore a
finite-supplied-action, biset-shaped discriminator, not a construction of the
full coend over all intermediate objects, not a coend universal property, and
not a Mackey 2-functor.
-/

set_option autoImplicit false

namespace GUFormalization
namespace GroupActionBurnsideBisetCoend

noncomputable section

open CategoryTheory
open GroupActionBurnside
open GroupActionBurnsideSpanCategory
open GroupActionBurnsideSpanRestriction
open GroupActionBurnsideSpanCorrespondence
open GroupActionBurnsideSpanCorrespondenceComposition

universe u

variable {H K L M : Type u} [Group H] [Group K] [Group L] [Group M]

/-- The defining balance law at the intermediate `K`-object: acting on the
right of the first correspondence is the same after composition as acting on
the left of the second correspondence. -/
theorem compose_middle_balance (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    (x : RestrictionCorrespondence phi A B)
    (k : B ⟶ B)
    (y : RestrictionCorrespondence psi B C) :
    compose phi psi (rightAction phi k x) y =
      compose phi psi x (leftAction psi k y) := by
  change (x ≫ (restrictionFunctor phi).map k) ≫
      (restrictionFunctor phi).map y =
    x ≫ (restrictionFunctor phi).map (k ≫ y)
  rw [(restrictionFunctor phi).map_comp]
  exact Category.assoc x ((restrictionFunctor phi).map k)
    ((restrictionFunctor phi).map y)

/-- A pair of restriction correspondences with one fixed intermediate
`K`-object. -/
structure FixedMiddlePair (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (B : AdditiveBurnsideSpanObject K)
    (C : AdditiveBurnsideSpanObject L) where
  first : RestrictionCorrespondence phi A B
  second : RestrictionCorrespondence psi B C

/-- One generating middle-action move.  Its equivalence closure is the
fixed-intermediate analogue of the balance quotient in biset/coend
composition. -/
inductive MiddleMove (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (B : AdditiveBurnsideSpanObject K)
    (C : AdditiveBurnsideSpanObject L) :
    FixedMiddlePair phi psi A B C → FixedMiddlePair phi psi A B C → Prop
  | balance (x : RestrictionCorrespondence phi A B) (k : B ⟶ B)
      (y : RestrictionCorrespondence psi B C) :
      MiddleMove phi psi A B C
        ⟨rightAction phi k x, y⟩
        ⟨x, leftAction psi k y⟩

/-- Composition is constant on the equivalence relation generated by the
middle-action moves. -/
theorem compose_eq_of_eqvGen (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {p q : FixedMiddlePair phi psi A B C}
    (h : Relation.EqvGen (MiddleMove phi psi A B C) p q) :
    compose phi psi p.first p.second =
      compose phi psi q.first q.second := by
  induction h with
  | rel p q hpq =>
      cases hpq with
      | balance x k y => exact compose_middle_balance phi psi x k y
  | refl => rfl
  | symm p q _ ih => exact ih.symm
  | trans p q r _ _ hpq hqr => exact hpq.trans hqr

/-- The quotient generated by the genuine intermediate endomorphism balance
moves, with the intermediate object held fixed. -/
abbrev FixedMiddleBalancedQuotient (phi : H →* K) (psi : K →* L)
    (A : AdditiveBurnsideSpanObject H)
    (B : AdditiveBurnsideSpanObject K)
    (C : AdditiveBurnsideSpanObject L) :=
  Quotient (Relation.EqvGen.setoid (MiddleMove phi psi A B C))

/-- Restriction-correspondence composition descends to the fixed-middle
balanced quotient. -/
def balancedCompose (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L} :
    FixedMiddleBalancedQuotient phi psi A B C →
      IteratedRestrictionCorrespondence phi psi A C :=
  Quotient.lift
    (fun p => compose phi psi p.first p.second)
    (fun _ _ h => compose_eq_of_eqvGen phi psi h)

@[simp]
theorem balancedCompose_mk (phi : H →* K) (psi : K →* L)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    (p : FixedMiddlePair phi psi A B C) :
    balancedCompose phi psi (Quotient.mk _ p) =
      compose phi psi p.first p.second := rfl

/-- The common target for three composable restriction correspondences. -/
abbrev TripleIteratedRestrictionCorrespondence
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    (A : AdditiveBurnsideSpanObject H)
    (D : AdditiveBurnsideSpanObject M) :=
  A ⟶ (restrictionFunctor phi).obj
    ((restrictionFunctor psi).obj ((restrictionFunctor chi).obj D))

/-- First compose at `K`, then append the twice-restricted third
correspondence. -/
def composeLeftAssociated
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {D : AdditiveBurnsideSpanObject M}
    (x : RestrictionCorrespondence phi A B)
    (y : RestrictionCorrespondence psi B C)
    (z : RestrictionCorrespondence chi C D) :
    TripleIteratedRestrictionCorrespondence phi psi chi A D :=
  compose phi psi x y ≫
    (restrictionFunctor phi).map ((restrictionFunctor psi).map z)

/-- First compose at `L`, then restrict that composite and append it to the
first correspondence. -/
def composeRightAssociated
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {D : AdditiveBurnsideSpanObject M}
    (x : RestrictionCorrespondence phi A B)
    (y : RestrictionCorrespondence psi B C)
    (z : RestrictionCorrespondence chi C D) :
    TripleIteratedRestrictionCorrespondence phi psi chi A D :=
  x ≫ (restrictionFunctor phi).map (compose psi chi y z)

/-- Three-stage restriction-correspondence composition is associative after
the canonical functorial expansion inside the same iterated-restriction
target. -/
theorem compose_associativity_coherence
    (phi : H →* K) (psi : K →* L) (chi : L →* M)
    {A : AdditiveBurnsideSpanObject H}
    {B : AdditiveBurnsideSpanObject K}
    {C : AdditiveBurnsideSpanObject L}
    {D : AdditiveBurnsideSpanObject M}
    (x : RestrictionCorrespondence phi A B)
    (y : RestrictionCorrespondence psi B C)
    (z : RestrictionCorrespondence chi C D) :
    composeLeftAssociated phi psi chi x y z =
      composeRightAssociated phi psi chi x y z := by
  unfold composeLeftAssociated composeRightAssociated compose
  rw [(restrictionFunctor phi).map_comp]
  exact Category.assoc x ((restrictionFunctor phi).map y)
    ((restrictionFunctor phi).map ((restrictionFunctor psi).map z))

end

end GroupActionBurnsideBisetCoend
end GUFormalization
